- lib/model.js
- test/integration/model/bulk-create.test.js
fix #9947 
In the case of processing that is not bulk, we use rawAttribute, so we should do the same in this case.
https://github.com/sequelize/sequelize/blob/master/lib/model.js#L3627
> fix(model): validate virtual attribute (#9947)

- lib/errors/index.js
- test/integration/error.test.js
- test/unit/errors.test.js
`BaseError` expects to receive `message`, but the `options` object is being passed. 
It leads to this:
```
SequelizeOptimisticLockError: [object Object]
```
With the fix the error looks like:
```
SequelizeOptimisticLockError: Attempting to update a stale model instance: Customers
```
> fix OptimistickLockError message

- lib/model.js
- test/integration/model/scope/associations.test.js
- test/unit/model/include.test.js
- test/unit/model/scope.test.js
Confirming options after foreign key is added.
See issue: #6245
> Scopes with foreign key

- lib/data-types.js
- lib/dialects/postgres/connection-manager.js
- lib/dialects/postgres/data-types.js
- test/integration/dialects/postgres/connection-manager.test.js
- test/integration/dialects/postgres/range.test.js
Related to issue #9863. This pull request makes postgres `DataTypes` OID agnostic, all OID information is contained in `ConnectionManager`. They are refreshed automatically.
I've added some tests but I didn't run them. I will wait for this pull request to run them on travis.
EDIT: Autodetection of Ranges dropped, reasons in #9863
> feat(postgres): dyanmic oids(#9863)

- lib/dialects/abstract/query-generator.js
- test/integration/model/attributes.test.js
- test/unit/dialects/mysql/query-generator.test.js
> fix(query): correct-quote-identifiers(#9964)

- lib/dialects/mssql/query-generator.js
- lib/dialects/postgres/query-generator.js
- test/unit/dialects/mssql/query-generator.test.js
- test/unit/dialects/postgres/query-generator.test.js
- test/unit/sql/add-column.test.js
Resolves #4386 
More specifically https://github.com/sequelize/sequelize/issues/4386#issuecomment-433015711
This adds on the work @theRichu started around adding an ability to add a comment while using `addColumn` API.
Initial PR can be found here
https://github.com/sequelize/sequelize/pull/10076
> fix(query-generator): fix addColumn create comment

- lib/dialects/abstract/query-generator.js
fixed an issue when passing limit/offset inside of a subquery
- [ x ] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [ - ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ - ] Have you added new tests to prevent regressions?
- [ - ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ x ] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?
When executing a query like the following, the offset value would not get passed to the UNION ALL Generated query.
```js …
```
> fix(query-generator): adding offset in unioned queries

- docs/associations.md
Maybe this checklist does not apply to the change.
_Probably, wrong property was being used in the docs example. This PR fixes this typo._
Looks like the last example should define `association` rather then `model` in this case.
Using `model` the error happens:
```bash
Error: Unable to connect to the database TypeError: self._expandAttributes is not a function
at Function._conformOptions (<...>/node_modules/sequelize/lib/model.js:198:12)
at Function._conformInclude (<...>/node_modules/sequelize/lib/model.js:264:12)
at options.include.options.include.map.include (<...>/node_modules/sequelize/lib/model.js:213:59)
at Array.map (<anonymous>)
at Function._conformOptions (<...>/node_modules/sequelize/lib/model.js:213:39)
at new Model …
```
> docs: typo in associations.md

- lib/associations/belongs-to-many.js
- lib/associations/belongs-to.js
- lib/associations/has-many.js
- lib/associations/has-one.js
- lib/associations/mixin.js
- test/integration/associations/belongs-to-many.test.js
- test/integration/associations/belongs-to.test.js
- test/integration/associations/has-many.test.js
- test/integration/associations/has-one.test.js
fix #9928 
Since conditions are different for each relation, I tried using polymorphism.
> fix(association): enable eager load with include all(#9928)

- lib/sequelize.js
- test/integration/sequelize.test.js
Fixes https://github.com/sequelize/sequelize/issues/10144
Fixes https://github.com/sequelize/sequelize/issues/1207
> fix(sync): throw when no models defined

- docs/migrations.md
Added an example of a more advanced migration skeleton
> docs(migrations): added advanced skeleton example

- docs/migrations.md
Instead of directly calling the CLI from node_modules, you should use NPX that comes with NPM from v5.2.
> docs(migrations): Simplify CLI Call

- .esdoc.json
- docs/data-types.md
- docs/models-definition.md
- docs/querying.md
Issue #10114. I propose to document how to add custom data types. In this pull request I illustrate only how to add postgres data types.
> feat(documentation): explain custom/new postgres data types

- lib/model.js
While testing with CockroachDB as backend database, I encountered a strange situation where the version number used by Sequelize for optimistic locking is (correctly) stored as INT in the table, but is incremented as string, and ends up becoming "1111...". Eventually the version number becomes too large to fit an integer. The exact same code does not show the issue when using MySQL or SQLite as backend store.
This fix ensures that the version number is incremented as a number. It merely makes the existing desired behaviour explicit and should not change the behaviour for backends where it is already working correctly.
I am not sure about how I would go about adding tests for this - more research would be needed to see whether this …
> fix(model): prevent version number from being interpreted as string

- package.json
Fixes issue #10090 - Similar to PR #10127, but targeting master instead of v4
> docs: fix favicon

- lib/model.js
- test/integration/model/update.test.js
Fixes https://github.com/sequelize/sequelize/issues/7101
> fix(update): skips update when nothing to update

- docs/models-usage.md
- lib/associations/belongs-to-many.js
- lib/associations/has-many.js
- lib/associations/has-one.js
- lib/dialects/abstract/query-generator.js
- lib/dialects/mssql/connection-manager.js
- lib/dialects/mysql/connection-manager.js
- lib/model.js
- lib/sequelize.js
- test/integration/associations/belongs-to-many.test.js
- test/integration/data-types.test.js
- test/integration/dialects/mariadb/associations.test.js
- test/integration/dialects/mariadb/errors.test.js
- test/integration/dialects/mysql/associations.test.js
- test/integration/dialects/mysql/connector-manager.test.js
- test/integration/dialects/postgres/associations.test.js
- test/integration/include/schema.test.js
- test/integration/instance.test.js
- test/integration/instance/values.test.js
- test/integration/model.test.js
- test/integration/model/bulk-create.test.js
- test/integration/model/create.test.js
- test/integration/model/findAll/separate.test.js
- test/integration/model/scope/find.test.js
- test/integration/query-interface.test.js
- test/integration/sequelize.test.js
- test/integration/utils.test.js
- test/unit/associations/has-many.test.js
Fixes #10275 I think
This is another small scale cleanup PR.
- Replace some loops with `Object.assign`
- Replace all usage of `spread` with native array spread
- Use object literals in various places
- Avoid aliasing of `this`
> chore: cleanup

- lib/dialects/abstract/query-generator.js
> (comments): Fix typo

- test/unit/model/validation.test.js
The file [test/unit/model/validation.test.js](https://github.com/sequelize/sequelize/blob/9c0f0414623805136a24fc584d634b3a132e8211/test/unit/model/validation.test.js) contains among other things two `describe` blocks, one of them called ["custom validation functions"](https://github.com/sequelize/sequelize/blob/9c0f0414623805136a24fc584d634b3a132e8211/test/unit/model/validation.test.js#L460) and the other called ["custom validation functions returning promises"](https://github.com/sequelize/sequelize/blob/9c0f0414623805136a24fc584d634b3a132e8211/test/unit/model/validation.test.js#L547). Both test very similar things, and by their names one would expect that only the latter returns promises, but both do. I think this is probably a …
> test(validation): throw instead of promise.reject

- docs/scopes.md
- package.json
- test/integration/model/scope/merge.test.js
The PR #9735 solved the issue #9087 very nicely. I was thinking that it deserved more tests, to help preventing regressions, and also deserved one section of the tutorial docs to be better explained.
This way, in this PR I have added a strong test to prevent regressions, and also some extra documentation.
> Docs and more tests for #9087

- lib/instance.js
- test/unit/instance/changed.test.js
- test/unit/instance/set.test.js
Ports over two instance fixes for v3:
1. Corrects `setDataValue` to not set `changed` when updating from null to null (port of #9347)
2. Uses the custom setter value for comparing if the original value has changed (port of #8389)
Thanks to the authors of these original PRs!
> Instance Fixes for v3

- lib/model.js
- test/integration/model.test.js
I was testing some scenarios and noticed that when:
1. Have a model with `paranoid: true` set
2. Have `beforeUpdate` hook defined in the model
3. Use the static `<Model>.update` method with `individualHooks: true`
The hook does not get called and therefore update statement is not executed. After a bit of investigation, I found the root cause - the `paranoid` option was not propagated to the select statement.
As it was quite straightforward change, I decided to give it a go and created PR directly :)
> fix(model/update): propagate paranoid to individualHooks query

- docs/usage.md
Fixes the broken link to options on **Basic Usage -> Dialects -> Mysql**.
This was reported on #9664
> docs(usage): fix broken link on Basic Usage

- lib/model.js
- types/lib/model.d.ts
- types/lib/sequelize.d.ts
This is just a very minor typo fix.
(By the way, I'm surprised that I had to change it in three places! I am not very familiar with TypeScript though, so I have no clue if there is or should be a better way, so no problem)
> docs(model): fix typo

- docs/hooks.md
- lib/sequelize.js
- types/lib/sequelize.d.ts
- types/test/sequelize.ts
Adds documentation for the `beforeConnect()` and `afterConnect()` hooks, API documentation for providing global hook definitions when constructing a Sequelize instance, and the corresponding TypeScript types.
Additionally, this corrects the TypeScript types to make `operatorsAliases` an _optional_ configuration property (which was discovered when writing tests for the new types).
> docs(hooks): add documentation for connection hooks

- lib/dialects/postgres/connection-manager.js
- lib/sequelize.js
- test/integration/dialects/postgres/connection-manager.test.js
For some reason, Sequelize sets `client_min_messages` to `warning` when connecting to Postgres. This was introduced in https://github.com/sequelize/sequelize/pull/3041 with the only justification being "There is a new `SET` that increases the message level to `warning` (up from `notice`) since the upgraded pg client is now capable of bubbling these messages." 
`pg` does indeed allow you to [register an event when the server returns a message](https://node-postgres.com/api/client#client-on-39-notice-39-notice-string-gt-void-gt-void), but it doesn't follow that Sequelize needs to override the default `client_min_messages`. 
Furthermore, this behavior accidentally became coupled to the `keepDefaultTimezone` setting in https://github.com/sequelize/sequelize/commit/95a5c0d86dbdd32133a3dcb64659e …
> feat(postgres): allow customizing client_min_messages

- test/integration/include.test.js
- types/lib/model.d.ts
> feat(types): enabled string association

- .eslintrc.json
- lib/data-types.js
- package.json
- test/integration/data-types.test.js
This adds support for Number types that aren't represented as actual Javascript Number instances. For example, [BigInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt) (new in Node 10), [Decimal.js](https://github.com/MikeMcl/decimal.js/), etc. Anything with a `.toString` should work.
Fixes #10491
Fixes #10491
> feat(types): handle Numbers passed as Objects

- docs/upgrade-to-v5.md
- docs/usage.md
- lib/associations/mixin.js
- lib/dialects/mssql/connection-manager.js
- lib/model.js
- lib/query-interface.js
- package.json
- scripts/appveyor-setup.ps1
- test/config/config.js
- test/config/options.js
- test/integration/sequelize.test.js
Breaking change, support `tedious@6` format for `dialectOptions`
> feat: update to tedious@6.0.0

- lib/sequelize.js
- test/integration/sequelize.test.js
Fixes #10453 , Now `options` and `sql` are only prepared once, retry logic only deals with obtaining connection and querying SQL prepared in first step.
> fix(query): don't prepare options & sql for every retry

- docs/legacy.md
The N:M example was using `hasMany` calls instead of `belongsToMany`.
I also used the opportunity to make minor tweaks in formatting and text.
> docs(legacy): fix N:M example

- types/lib/model.d.ts
- types/lib/query-interface.d.ts
- types/lib/sequelize.d.ts
- types/test/connection.ts
- types/test/sequelize.ts
See title
fixes #10506
@sushantdhiman can you clarify if you can specify BOTH the query `type` AND `model`?
It seems that when model is specified it implicitly uses `SELECT` but what if `type` is specified?
> fix(types): allow specifying additional options for db.query and add missing retry

- lib/associations/belongs-to-many.js
- lib/associations/has-many.js
- test/integration/associations/belongs-to-many.test.js
- test/integration/associations/has-many.test.js
> fix(association): use empty select for hasAssociation

- lib/dialects/sqlite/query-generator.js
- test/unit/sql/delete.test.js
Follow-up to #5356 adding support for SQLite.
`npm run test-sqlite` passes and I also tested the generated SQL against my DB
I believe current docs suffice?
> feat(sqlite/query-generator): support restart identity in SQLite

- lib/utils/classToInvokable.js
Script:
```js
'use strict';
class A {
constructor(a, b) {
this.rng = Math.random();
this.a = a;
this.b = b;
}
}
A.a = 1;
A.b = 2;
function classToInvokable(Class) {
return new Proxy(Class, {
apply(Target, thisArg, args) {
return new Target(...args);
},
// NEW
construct(Target, args) {
return new Target(...args);
},
get(target, p) {
return target[p];
}
});
}
const B = classToInvokable(A);
console.log(new A(1, 2), new B, new B(1, 2), B(1, 2));
console.time('class');
for (let i = 0;i<0xFFFFF;++i) {
const a = new A();
}
console.timeEnd('class');
console.time('proxy new');
for (let i = 0;i<0xFFFFF;++i) {
const b = new B();
}
console.timeEnd('proxy new');
console.time('proxy invoke');
for (let i = 0;i<0xFFFFF;++i) {
const b = B();
} …
```
> fix(util): improve performance of classToInvokable

- .travis.yml
- CONTACT.md
- README.md
- docs/ROUTER
- docs/index.md
- docs/usage.md
This PR covers all changes related to v5 release, these are mostly documentation updates. Full changelog is available [here](https://github.com/sequelize/sequelize/blob/master/docs/upgrade-to-v5.md)
> v5 release

- lib/hooks.js
- lib/model.js
- test/unit/hooks.test.js
- types/lib/hooks.d.ts
- types/lib/model.d.ts
- types/lib/sequelize.d.ts
- types/test/sequelize.ts
Related: https://github.com/sequelize/sequelize/issues/10542
This prevents various hooks from being added to `Model` that are only available on `Sequelize` instances.
There are some issues with the typings `Model.addHook('beforeConnect')` will not error but `Model.beforeConnect` will, I'm unsure on how to fix this in an elegant way as there's nothing like `static interfaces` in TypeScript.
This is _technically_ a breaking change as attempting to call these methods will now error, while previously these hooks would silently fail.
> fix(hooks): do not expose unsupported hooks on models

- README.md
- docs/getting-started.md
- docs/index.md
I've reworked the getting-started docs, improving explanations, simplifying some other things, adding more examples and adding more links, hopefully making it easier for new Sequelize users to grasp the basics.
This PR also has some changes for README.md and the index.md from docs, making both more similar to each other. I've also added more nice badges and replaced the badge provider to [badgen.net](https://badgen.net) which I've grown to like a lot - it's fast and reliable.
----------
**NOTE:** I've been wanting to help with a major rework of the sequelize tutorials for a while now, I finally had the time to make some changes, but I will probably be opening more PRs in the future to improve the rest of the tutorials/guides. IMO, they look a bit outdated and disorganized. But I am short …
> Improve basic getting-started docs

- lib/dialects/mariadb/connection-manager.js
- lib/dialects/mssql/connection-manager.js
- lib/dialects/mysql/connection-manager.js
- lib/dialects/postgres/connection-manager.js
Fixes https://github.com/sequelize/sequelize/issues/10556
It seems default ports were never used by pool because connection manager keep a cloned copy of config. Now we assign default port before initializing connection manager
> fix(connection-manager): correctly assign default port

- lib/deferrable.js
- lib/dialects/postgres/connection-manager.js
- lib/model.js
- lib/sequelize.js
- lib/utils.js
- test/unit/dialects/mariadb/query-generator.test.js
- test/unit/dialects/mssql/query-generator.test.js
- test/unit/dialects/mysql/query-generator.test.js
- test/unit/dialects/postgres/query-generator.test.js
- test/unit/dialects/sqlite/query-generator.test.js
Basically #10553 but without the forEach changes.
> chore: optimize a few code paths

- lib/dialects/abstract/query-generator.js
- lib/dialects/mariadb/data-types.js
- lib/dialects/mysql/data-types.js
- test/integration/operators.test.js
Fixes #10602
Apparently the `operation` parameter was never set anywhere, it's time for a type checker.....
> fix(query-interface): incorrect regex escape with json querying

- lib/dialects/abstract/query-generator.js
- lib/dialects/abstract/query.js
- lib/sequelize.js
- lib/utils/deprecations.js
- lib/utils/logger.js
- package.json
- test/integration/sequelize.test.js
- test/unit/utils.test.js
- types/lib/utils/logger.d.ts
Removes `depd` in favour of `util.deprecate`.
I am unsure if this should be considered breaking since `.deprecate` was more internal.
Pro:
- Centralised place for deprecations
- Deprecation codes
- Less dependencies
Contra:
- API slightly different but `depd` was never *officially* in the docs
> chore: use native deprecations

- lib/data-types.js
Small typo fix to the `DataType.ARRAY` autodoc comment
> Remove extra tick mark and period in Array autodoc comment

- lib/model.js
- test/integration/associations/has-many.test.js
#10484 Allow to create nested instances of models with custom getters/setters on a foreign key.
> fix(associations): symmetric getters/setters on FK

- types/lib/query-interface.d.ts
- types/test/query-interface.ts
`QueryInterface`'s `addConstraint` allows a `transaction` as part of its options.
Currently the TS definition for `addConstraint` is a *union* type of:
```
public addConstraint(
...
options?: AddConstraintOptions | QueryInterfaceOptions
): Promise<void>;
```
When using a `transaction` in options, this results in a TS error of:
```
Argument of type '{ type: "foreign key"; references: { table: string; field: string; }; transaction: Transaction; onDelete: string; onUpdate: string; }' is not assignable to parameter of type 'QueryInterfaceOptions | AddUniqueConstraintOptions | AddDefaultConstraintOptions | AddCheckConstraintOptions | AddPrimaryKeyConstraintOptions | AddForeignKeyConstraintOptions'.
Object literal may only specify known properties, and 'transaction' does not exist in type …
```
> Intersect addConstraint options instead of union

- types/lib/sequelize.d.ts
The return type of Sequelize.prototype.close is currently `void`, but it should be `Promise<void>` instead. Under the hood, it calls [connectionManager.close](https://github.com/sequelize/sequelize/blob/master/lib/sequelize.js#L1131), which returns a [Promise](https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/connection-manager.js#L110). Therefore Sequelize.prototype.close returns a Promise itself.
> fix(types): change Sequelize.prototype.close type

- lib/data-types.js
- test/integration/data-types.test.js
This regressed in #10492
Fixes #10600
Fixes #10633
Bring back support for passing booleans into `TINYINT` fields.
> fix(mysql): boolean TINYINT support

- lib/data-types.js
This change will store the options of `ARRAY` in the class. I stumbled across this when I tried to extend the `ARRAY` type and the options were not set.
> fix: store options in array

- lib/associations/belongs-to-many.js
Just fixed the typo on `lib\associations\belongs-to-many.js`
> docs: fix typo on belongs-to-many.js

- lib/data-types.js
- test/integration/data-types.test.js
Backports #10644 to v4. Since the original feature that broke this was backported to v4, it's only fair to backport the fix too. 
Fixes #10600
> fix(mysql): backport boolean TINYINT support to v4

- types/index.d.ts
Remove `export * from './lib/model';` exported twice in `./types`
> Remove type lib/model double export

- docs/getting-started.md
The docs currently say Models are defined with `Model.init` but not where to import this `Model` from.
> Clarify where to get Model from

- types/lib/associations/has-many.d.ts
- types/lib/associations/has-one.d.ts
- types/lib/query-interface.d.ts
- types/test/e2e/docs-example.ts
- [ X] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [ X] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ X] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?
add missing `sourceKey` option in `HasOneOptions` association type definition
> fix(typings): add missing sourceKey option in HasOneOptions association type 

- lib/sequelize.js
- types/lib/sequelize.d.ts
Since `sequelize.define` has started to be called "legacy" and `Model.init` has been preferred, and since the current implementation of `sequelize.define` simply calls `Model.init` internally, I think this minor change in the docs is desirable.
Question: I've added an `@link` to the `.js` documentation but I left it as plain-text in the `.d.ts` documentation, because I didn't see any other `@link` on the `.d.ts` files. Should I have done something different? Also please see #10673.
> docs(sequelize): update constructor define docs

- README.md
Adding a few more things to the README to give important information more quickly to newcomers. I think the README should be a place where a quick glance should pass a lot of information, especially for people who don't know the project.
> docs(readme): make it easier for newcomers

- docs/getting-started.md
- docs/index.md
- docs/models-definition.md
- docs/typescript.md
Improves a bit the tutorials:
* Quick start script now works (changed `Model` to `Sequelize.Model`)
* A few other clarifications, link updates and minor formatting changes
> docs: tutorial improvements

- types/lib/query-interface.d.ts
- types/test/connection.ts
The `bind` property described in the [docs](http://docs.sequelizejs.com/manual/raw-queries.html#bind-parameter) was missing in the type definitions.
> fix(types): add basic support for `bind` in Sequelize.query() method

- docs/associations.md
- docs/getting-started.md
- docs/index.md
- docs/instances.md
- docs/legacy.md
- docs/models-definition.md
- docs/models-usage.md
- docs/scopes.md
- docs/typescript.md
Fixes https://github.com/sequelize/sequelize/issues/10682
Closes https://github.com/sequelize/sequelize/pull/10683
> docs: use modelName with init for proper include alias

- lib/dialects/postgres/query.js
- test/unit/sql/insert.test.js
Postgres doesn't support null characters in strings. This has generally been handled via https://github.com/sequelize/sequelize/blob/master/lib/sql-string.js#L75. However with Sequelize 5 using bind parameters for insert and update, the replacement of null characters no longer happens. This PR adds replacement of null characters in case of bind parameters being used.
I have added tests, but have not been able to run them across the other database. I think it should pass though, otherwise I would appreciate help getting them fixed.
> fix(bind): add escsape of null character for postgres bind parameters

- lib/dialects/mariadb/connection-manager.js
- test/integration/timezone.test.js
Mariadb doesn't support named timezones. Previous workaround missed `connectionConfig.timezone`. It didn't show on online tests, because they use UTC.
> fix(mariadb): named timezone connection bug

- docs/typescript.md
- types/test/e2e/docs-example.ts
This changes two occurrences of `associtations` (note the extra `t`).
I figure if this isn't corrected, this typo will slowly seep into the
various implementations (like end-users like myself) who are copying and
pasting examples from the documentation into their own projects. 😄
> docs(typescript): correct misspelling of `associations`

- lib/sql-string.js
- lib/utils/logger.js
Provides a configurable `logger.inspector` that will format non-string JS elements in logs and errors. This will be useful for configuring how binded parameters are logged, once that functionality is merged into sequelize.
Related to issues #10284 #10285
> feat(log): configurable inspector

- types/lib/model.d.ts
- types/test/where.ts
At present, using the regexp operator when calling the where function produces a typescript error. As an abbreviated example, the following...
```
where('name', {
[Op.regexp]: '^[s|a|m]'
})
```
would produce the error...
`Argument of type '{ [Op.regexp]: string; }' is not assignable to parameter of type 'LogicType'.`
However, when casted to an any type, it produces a valid SQL query.
Therefore, I have updated WhereOperators to support regexp, notRegexp, iRegexp and notIRegexp operators.
> fix(types): add regex operators to WhereOperators

- docs/upgrade-to-v5.md
Resolves #10744 by changing incorrectly formatted code block from `json` to `javascript`.
> docs: correctly format code block

- lib/dialects/abstract/connection-manager.js
- lib/dialects/postgres/connection-manager.js
1. This enable sequelize to set `standard_conforming_strings = on` whenever they are disabled regardless of postgres version. This fixes a security issue.
2. It saves one extra query for postgres version per connection, which is available with `parameterStatus` as `server_version`
> fix(postgres): check and enable standard conforming strings when required

- lib/associations/helpers.js
- test/integration/associations/belongs-to.test.js
- test/integration/include/findOne.test.js
or with composite pk
fix foreign key with a targetkey on table without pk or with composite pk
fix 3 tests which where false positive => a foreign key must target a pk or a column with unique constraint
> fix(associations): fix foreign key with a targetkey on table without pk

- lib/dialects/mssql/query-generator.js
- test/integration/dialects/mssql/regressions.test.js
Closes https://github.com/sequelize/sequelize/issues/10425.
Backports https://github.com/sequelize/sequelize/commit/0cbb7b9f54fa385b233dbbef69c346c3fc369145 to v4.
Tests fail, but seems related to connection issues to the remote database. (have no local MSSQL DB to test):
```
1) [MSSQL] BelongsToMany
getAssociations
supports transactions:
Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (test/integration/associations/belongs-to-many.test.js)
2) "after each" hook for "supports transactions":
Error: Expected 0 running queries. 1 queries still running in [MSSQL] BelongsToMany getAssociations supports transactions
at Object.verifyNoRunningQueries …
```
> fix(query-generator): subquery handling

- types/lib/model.d.ts
`FindOptions` is missing most query options like `useMaster` etc.
According to @mickhansen https://github.com/sequelize/sequelize/issues/3977#issuecomment-428841057 all query options are being passed on, that's why we can directly extend `FindOptions` with `QueryOptions`.
> fix(types): extend FindOptions with QueryOptions

- lib/dialects/mssql/query-generator.js
- lib/dialects/postgres/query-generator.js
- lib/query-interface.js
- test/integration/query-interface/changeColumn.test.js
Solves #10720 
Adds ability to use `changeColumn` to alter comments. It wasn't implemented initially. Works for all dialects except sqlite.
> feat(comments): allow altering comments

- docs/scopes.md
Solves #10742 
Trying to clarify that `options.attributes.exclude` is always going to be preserved no matter how many scopes are applied.
@sushantdhiman if I wasn't clear enough let me know and I'll fix it up.
> feat(docs): attributes key merging

- lib/model.js
- test/integration/model/attributes/types.test.js
Fix virtual attributes used in includes to be returned by `get` after the model is loaded https://github.com/sequelize/sequelize/issues/10552
`originalAttributes` wasn't being set before calling `Utils.mapFinderOptions` like it is in other places
> fix(model): handle virtual attributes in includes

- lib/model.js
- test/integration/instance.test.js
Solves #10714 
Handling `deleted_at` being `undefined` if not defaulted when model is created.
> fix(instance): isSoftDelete true after creating

- lib/dialects/mssql/query.js
- test/integration/dialects/mssql/regressions.test.js
MSSQL got support for varchar lengths in #9896 but if the length is `MAX` in the database the length === `-1`
This PR will check for that case and change the length to `MAX`
> fix(describeTable): MAX string length for mssql

- types/lib/model.d.ts
- types/test/where.ts
Solves #10789 
Adding `Literal` as an option for most of Operators
> feat(types): adding Literal type to Operators

- types/lib/model.d.ts
- types/test/model.ts
Solves #10811 
Adding missing fields to `ModelIndexesOptions`
> feat(types): add using & operator index interface

- types/lib/model.d.ts
- types/test/upsert.ts
Added correct return type to `upsert` when `{ returning: true }`
> feat(types): adding upsert with returning: true

- types/lib/model.d.ts
- types/test/usage.ts
Add missing `validate` option to `create` as mentioned here: http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-create
> fix(types): add validate to CreateOptions

- lib/model.js
Fixes #10856
I am unsure how to test this correctly, @PatrickGeyer can you please confirm that adding the `having` resolves the issue?
> fix(querying): prevent `having` clause from cascading

- types/lib/model.d.ts
- types/lib/query-interface.d.ts
- types/test/models/User.ts
- types/test/query-interface.ts
I looked up all the values that are used and valid and cleaned up the index types a bit. Also merged with the query interface to have a consistent interface (as they both call addIndexQuery anyways)
> fix(typings): use correct set of allowed options for addIndex

- docs/models-definition.md
Copy-pasting an example into your code would make it crash. This is obvious typo mistake.
> Docs: fixed typo in the model definition example

- .esdoc.json
- docs/css/style.css
- docs/plugins/group-data-types.js
This PR groups every data type from the API reference menu into one section.
This is closely related to #10686. I personally prefer that solution, but I tried to follow [this comment](https://github.com/sequelize/sequelize/pull/10686#issuecomment-479338407). My solution only changes the menu, but the Reference Summary remains cluttered.
> docs(data-types): separate nav menu

- docs/scopes.md
Adds a `where` clause to the SQL example provided in the **Scopes** documentation under **Merging**, which showcases merging the **Project** `deleted` scope with the **Project** `activeUsers` scope.
> docs(scopes): fix sql example for merging deleted projects and projects with active users

- lib/dialects/abstract/query-generator.js
- lib/model.js
- lib/query-interface.js
Add index operator option for API Documentation.
Operator option is used here : https://github.com/sequelize/sequelize/blob/5f9d5907425ae1d86b402133718d007a52f2b39e/lib/dialects/abstract/query-generator.js#L577
> docs: add index operator option

- docs/migrations.md
- [-] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [-] Have you added new tests to prevent regressions?
Just a minor fix in the migrations docs where the command used ot be `npx sequelize` witch no longer works and should be caned to "npx sequelize-cli". This should help users and prevent them from having to google for the solution
> docs(migrataions): use npx sequelize-cli when migrating

- types/lib/sequelize.d.ts
Added missing types to SyncOptions.
> fix(types): add missing types to SyncOptions

- types/lib/sequelize.d.ts
Thought it was removed, but it's still there. Just not documented.
Workaround until this is merged `await sequelize.sync({ alter: true } as SyncOptions);`
> Undocumented alter option in SyncOptions

- lib/model.js
- types/lib/model.d.ts
- types/lib/sequelize.d.ts
Fix issue #10925, correct the documentation and type definition of Model.findByPk()
findByPk takes the same option as findAll, except the `where` option in the implementation, so we should correct the document and type definition
> docs(findbypk): fix document and type definition

- docs/associations.md
The headline was 'Advance concepts' instead of 'Advanced concepts'
> Fixed typo in Association documentation

- docs/typescript.md
Fix errors in typescript docs example.
When running `sequelize.sync()` using the typescript documentation I had the following issues:
1.
```
Cannot find module '../../lib/associations'
```
the change I made is to update the import import from `../../lib/associations` to `sequelize`.
2.
```
UnhandledPromiseRejectionWarning: SequelizeDatabaseError: column "name" of relation "users" does not exist
```
The `Address` should be in it's own table by the looks of it so I changed the table from `users` to `address`.
These two fixes mean the example runs fine against the latest postgres image https://hub.docker.com/_/postgres (11.3)
> docs: fix Typescript example import and table name

- types/lib/hooks.d.ts
- types/lib/model.d.ts
- types/lib/sequelize.d.ts
- types/test/hooks.ts
It is not obvious from types that `afterFind` hook can be fired with `null` as first argument (instead of model instance or instances). So this PR adds `null` explicitly.
> fix(types): add null to afterFind hook

- docs/models-definition.md
Replace `method: 'BTREE'` with `using: 'BTREE'` in `docs/models-definition.html#indexes`.
Tested locally with `queryInterface.addIndex()` and `sequelize.sync()`.
> Fix incorrect option name in docs/model-definition

- .gitignore
Is there a reason why this pattern should still be ignored?
See https://github.com/sequelize/sequelize/issues/11107
> Remove `test*.js` from `.gitignore`

- docs/models-usage.md
- lib/model.js
I spent a few days this week pounding my head against the wall wondering why when I would run any of the `Model.find*Create()` functions, whatever I was putting into the `where` options parameter, it was getting inserted into the database. 
From reading the docs and also assuming that `where` is only used for the "WHERE" query generation, I finally dug into the source code of sequelize and realized my issue. 
I thought it would be helpful for others to realize when they use any of these functions that the `where` option will be used in the create query.
> docs: add note for find*create functions

- lib/dialects/abstract/query-generator.js
Our production app has been experiencing memory leaks in sequelize that seem to be happening in lodash templates. It appears some other users are also experiencing this issue here #9276. It was thought that #10047 would resolve the issue but that PR still left some lodash template usages in the query generator. This PR removes the last calls to lodash templates.
I have tried to create a small sample case to reproduce the memory leak and have not been able to. However this change seems to resolve this issue in production for us.
> refactor(query-generation): remove lodash string templates

- docs/hooks.md
- lib/dialects/abstract/connection-manager.js
- lib/hooks.js
- lib/sequelize.js
- test/unit/connection-manager.test.js
- test/unit/hooks.test.js
- types/lib/hooks.d.ts
- types/lib/sequelize.d.ts
Add hooks that run before and after disconnecting a connection:
- `beforeDisconnect`
- `afterDisconnect`
> disconnect hooks

- docs/models-definition.md
Found in tutorial section of documentation. Specifically, models-definition.
> docs: Typo and grammar fix

- types/lib/model.d.ts
- types/lib/sequelize.d.ts
- types/test/model.ts
This is allowable for Aliases, according to docs and lack of errors when attempting.
See Types: [options.include](http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-findAll)
I tried to follow what this person did at https://github.com/sequelize/sequelize/pull/10804 as far as tests go, but, TBH I didn't look into how these typedef tests work.
This just adds `string` as a possible type for `Includeable` as is allowed for Aliases.
> fix(types): add string to Includeable

- types/lib/model.d.ts
- types/test/include.ts
Relax type `order` checking in queries, because we can have multiple nester models and or strings etc. I'm not sure we can do better than this.
Closes https://github.com/sequelize/sequelize/issues/10780
> fix(types): relax order typing

- lib/model.js
- lib/utils.js
- test/unit/model/scope.test.js
Model was previously altering the original scopes when merging them for queries.
This happened because [Model._mergeFunction](https://github.com/sequelize/sequelize/blob/b6c9117f279d3df19565797ae3fc1be0a1a5eda9/lib/model.js#L793) was in some cases returning references to attributes of the original scope objects instead of cloning them (see [line 811](https://github.com/sequelize/sequelize/blob/b6c9117f279d3df19565797ae3fc1be0a1a5eda9/lib/model.js#L811)).
Also added a new test to prevent this problem from happening again.
Closes #10696
Tried to clone the object with both [Utils.cloneDeep](https://github.com/sequelize/sequelize/blob/b6c9117f279d3df19565797ae3fc1be0a1a5eda9/lib/utils.js#L126) and Lodash's `_.cloneDeep`, but both …
> fix(model): don't alter original scopes when combining them

- docs/migrations.md
The seed instructions in the docs fail as they don't pass validation.
This fix adds the createdAt and updatedAt fields to the seed data.
Skipped template as per contribution instructions.
> Migrations doc seed have timestamp

- lib/dialects/mariadb/query.js
- lib/dialects/mysql/query.js
- lib/query-interface.js
- lib/sequelize.js
- test/integration/dialects/mysql/errors.test.js
- test/integration/transaction.test.js
When MySQL or MariaDB encounter a deadlock, [the default behavior](https://dev.mysql.com/doc/refman/5.7/en/innodb-deadlock-detection.html) is to roll back the active transaction (having roughly the same effect as manually issuing the `ROLLBACK;` command). 
Currently, Sequelize does not apply any special handling to these errors.  If a query yields a deadlock error, all future queries against that "transaction" will actually be run against the default context.  This can have potentially destructive implications, as those subsequent queries cannot be rolled back.
This PR adds some code to mark any deadlocked transactions as though they've been rolled-back.  This prevents Sequelize from running any further queries against these …
> fix(mysql): deadlocks indicate a rollback

- docs/dialects.md
I removed broken link for old options page.
> docs(dialect): remove broken link

- lib/dialects/mssql/query.js
- test/integration/dialects/mssql/regressions.test.js
Add length to `CHAR` and `NCHAR` fields in MSSQL's `describeTable` function.
> fix(describetable): support string length for char in mssql

- .github/stale.yml
<s>Fix probot-stale config after I renamed some labels.</s>
EDIT: I think temporarily disabling is better, once the new labels are settled we can activate it again.
> chore(probot-stale): temporarily disable

- README.md
Mention the existence of [sequelize-cockroachdb](https://github.com/cockroachdb/sequelize-cockroachdb).
> docs(README): mention sequelize-cockroachdb

- lib/dialects/abstract/query-generator.js
- test/integration/model/searchPath.test.js
Should close issue #10875 
Disable `bindParam` in `updateQuery` when `searchPath` is used. Similar to how [insertQuery](https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/query-generator.js#L168) handles `searchPath`
> fix(search_path): disable bindParam in updateQuery

- lib/dialects/mssql/query.js
- test/integration/dialects/mssql/regressions.test.js
Pull request to address issue #11245 . This change fixes issue in mssql dialect allowing to save a number bigger than 2147483647 into a column with BIGINT type.
> fix(mssql): save number bigger than 2147483647

- lib/dialects/postgres/query-interface.js
- test/integration/dialects/postgres/dao.test.js
- test/integration/query-interface/createTable.test.js
*I am sorry, I wasn't able to run `npm run test` or `npm run test-DIALECT` on my local machine, nor did I added any new tests or even followed 'commit message conventions'. My bad.*
*I tested this solution locally on two arrays with various values, all got me right results. I also tested it on my local postgres database on real project, which also worked just fine.*
**Please, feel free to help me make this Pull Request look good and be merged**
---
Fixes #11053
The following is an attempt to explain how my solution works:
General idea is to use already existing values of enum type as a reference for new values. Previous (and currently active) version has some flaws, like referring non-existent values and some sort of 'race …
> Fix: postgresql's ensureEnums (#11053)

- lib/sequelize.js
- types/lib/sequelize.d.ts
I noticed a typo (`posibility` was written instead of `possibility`) and instead of just fixing it I thought of rewriting the sentence a bit.
> docs: fix minor typo

- lib/associations/has-many.js
- lib/model.js
- lib/query-interface.js
When we do many `findAll` calls, with complex options (many includes, many specific attributes etc), `deepCopy` consumes a lot of CPU. I removed some of these calls, and replaced them with a shallow copy (using `Object.assign`) when the function does not alter deep attributes.
> perf: remove unnecessary cloneDeep calls

- lib/dialects/postgres/query-generator.js
- lib/query-interface.js
- test/integration/dialects/postgres/query-interface.test.js
Allow the use of variables in plpgsql functions for issue https://github.com/sequelize/sequelize/issues/9708
Add a parameter to `createFunction` that takes an array of variables to be declared
> feat(postgres):  add function variables for postgres

- lib/model.js
As the missing include error comes up in async code, it can be hard to trace the caller and source of the issue.
Propose adding the name of the model that the association cannot be found on so as to give more context for debugging.
> docs(association): Name model that association is missing from

- types/lib/model.d.ts
- types/test/model.ts
Currently, if I try to initialize `getterMethods` or `setterMethods` while initializing a model in a TypeScript project, TS does not infer the correct type for `this` inside of those methods (and does not allow `this` to be easily casted to the correct type):
```ts
import { Association, HasOne, Model, Sequelize, DataTypes } from 'sequelize';
class MyModel extends Model {
public num!: number;
}
MyModel.init({}, {
sequelize,
tableName: 'my_model',
getterMethods: {
multiply: function() {
return this.num * 2; // <-- ERROR
}
}
});
```
> fix(types): use correct `this` value when initializing getterMethods

- types/lib/sequelize.d.ts
- types/test/sequelize.ts
Currently, looking up model classes via the `sequelize.models` interface does not yield an object with a usable type signature (for reasons that I admittedly do not entirely understand).
Static functions such as `findAll` and `belongsTo` do not work on the values pulled off of `sequelize.models`, presumably because these methods use the `ModelCtor` "hack" to infer the correct return type.
```ts
class Model1 extends Model {}
const M1 = sequelize.models.model1;
m1.findAll({});  // <-- ERROR
/**
The 'this' context of type 'typeof Model' is not assignable to method's 'this' of type 'ModelCtor<Model<unknown, unknown>>'.
Type 'typeof Model' is not assignable to type 'new () => Model<unknown, unknown>'.
Cannot assign an abstract …
```
> fix(types): return a usable type when using the sequelize.models lookup

- lib/model.js
- test/integration/model/count.test.js
> fix(count): fix null count with includes

- README.md
- SECURITY.md
> docs(security): add responsible disclosure policy

- lib/model.js
- test/integration/model/bulk-create.test.js
- test/integration/model/bulk-create/include.test.js
- types/lib/model.d.ts
Closes #3277.
This PR makes `bulkInsert` capable of handling associations. It uses the `include` option, just like other model methods.
It requires only 1 insert statement for each association model. E.g. 100 instances with 100 children and 100 grandchildren are created in 3 insert statements.
> feat: support include option in bulkInsert

- docs/associations.md
- lib/associations/belongs-to-many.js
- lib/dialects/abstract/query-generator.js
- test/integration/associations/belongs-to-many.test.js
- test/integration/dialects/postgres/query-interface.test.js
- test/unit/associations/belongs-to-many.test.js
- types/lib/associations/belongs-to-many.d.ts
> Feature: source/target keys in belongsToMany associations

- lib/dialects/abstract/query-generator.js
- lib/dialects/mariadb/query-generator.js
- lib/dialects/mysql/query-generator.js
- lib/dialects/sqlite/query-generator.js
- test/integration/model/json.test.js
- test/unit/sql/json.test.js
- test/unit/sql/where.test.js
This fixes a security issue with `sequelize.json()`, some old code was still used for formatting sub paths for json queries when used with `sequelize.json()` function helper
Example of attack vector
```js
return User.findAll({
where: this.sequelize.json("data.id')) AS DECIMAL) = 1 DELETE YOLO INJECTIONS; -- ", 1)
});
```
> refactor: use common path extraction for mysql/mariadb/sqlite

- lib/dialects/mysql/query-generator.js
- test/integration/model/json.test.js
- test/unit/sql/json.test.js
- test/unit/sql/where.test.js
Fixes https://github.com/sequelize/sequelize/issues/11202
Backport https://github.com/sequelize/sequelize/pull/11089
Backport https://github.com/sequelize/sequelize/pull/11329
> fix(mysql): json path security issues

- docs/querying.md
- types/lib/operators.d.ts
Adds a description to the operators. Previously, you had to look only in the documentation.
Before:
After:
> docs(types): Add explanatory comments to operators

- types/lib/sequelize.d.ts
Updated comment in  `sequelize.d.ts` since `Sequelize` constructor's `operatorsAliases` option is deprecated. Please let me know if comment's grammar is awkward.
> docs(types): update comment for options.operatorsAliases

- lib/dialects/abstract/query-generator.js
- test/integration/model/scope/find.test.js
Resolves issue described in #11316. When compiling list of attributes to be included as part of SQL query the initial list is cleaned up from virtual column and then updated with column aliases. Before this change only column aliases worked correctly. Pull request doesn't include new test but there is a change to test/integration/model/scope/find.test.js file that adds a virtual column to `DefaultScopeExclude` model that has scope with `attributes` config already defined.
I think the test case `should work when included with default scope` works to prevent regression here.
> fix(query-generator): handle virtual column on associations with scopes

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/documentational-issue.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/other_issue.md
I have made some changes to the issue templates and added a 'other' issue template for issues that don't fit into the other categories. I think it is a good idea to have this 'other' issue template because users can open generic issues anyway, so it is better if they have at least a general template to follow to help us.
I think this will help us a lot to triage issues!
> chore(.github): improve issue templates

- lib/dialects/mariadb/query.js
- lib/dialects/mssql/query.js
- lib/dialects/mysql/query.js
- lib/dialects/postgres/query.js
- lib/errors/database-error.js
- test/integration/error.test.js
- types/lib/errors.d.ts
Added a new property name 'parameters' on the DatabaseError class.
It's purpose is to hold the array of parameters for the sql query that's already defined on the error so that the complete sql query could be reconstructed based on the information offered by the error.
The issue solved by this PR is the absence of the complete information about an sql query that triggers an error. For example, if an error is thrown with the message 'invalid input syntax for integer: "220.00000000000003"' for a table with multiple integer columns, it is impossible to figure out, from the contents of the error, the exact column in which the query attempted to insert the value. With this change it should be possible to match the the value and the column using the index of the value in the newly added …
> feat(database-error): add 'parameters' property

- lib/dialects/abstract/query-generator.js
- lib/dialects/sqlite/index.js
- lib/model.js
- test/unit/dialects/sqlite/query-generator.test.js
- test/unit/sql/insert.test.js
- types/lib/model.d.ts
SQLite supports upsert from version 3.24.0 (see [docs](https://www.sqlite.org/lang_UPSERT.html)). Theses changes allow the SQLite dialect using the:
`INSERT ... ON CONFLICT DO UPDATE`
This feature allow to use the option updateOnDuplicate with SQLite like database.
This is my first attempt at a PR on a project like this, please advise on how I can improve my submission, thank you.
> Add support for `ON CONFLICT DO UPDATE` on SQLite 3

- lib/model.js
- types/lib/model.d.ts
This was added in #9197 but not added to the docs for `findAll`.
Document the `skipLocked` option for `findAll`.
> docs(model): document skipLocked

- lib/dialects/abstract/query-generator.js
- lib/dialects/postgres/query-generator.js
- lib/model.js
- test/integration/dialects/postgres/associations.test.js
Relations and Indexes created from models that have set a schema are not properly prefixed with the schema. This patch solves this.
In several cases, the schema prefix was not applied for generated indexes and related tables. This PR fixes this.
Fixes #11276.
> fix(postgres): schema for index and relations

- docs/dialects.md
Options in tedious have to be nested in additional objects underneath the dialectOptions. While this could be inferred from the tedious documentation, it is in contrast to the other dialects and might confuse others - at least it confused me :)
Perhaps it's better to be more explicit about it.
> Explain options handling in tedious

- lib/model.js
- test/integration/model/bulk-create.test.js
Reopened accidentally closed PR: https://github.com/sequelize/sequelize/pull/11433
This pull request fixes the following issue:
https://github.com/sequelize/sequelize/issues/11432
When performing `bulkCreate` with `updateOnDuplicate` using Postgres dialect, the generated query has bad column names. The query has the Javascript model's field names instead of the column names.
> fix(bulkcreate): use correct PK column names in updateOnDuplicate

- docs/models-usage.md
Included one space between the value and curly brackets
> docs: Keeping consistency around the spacing inside of curly brackets

- lib/dialects/mssql/query-generator.js
- lib/dialects/mysql/query-generator.js
- test/integration/query-interface.test.js
- test/unit/dialects/mssql/query-generator.test.js
Closes #11438
Filter tables by 'BASE TABLE' in `MSSQLQueryGenerator.showTablesQuery`.
Added tests.
> fix(mssql): filter tables only in mssql+mysql showTablesQuery

- types/lib/model.d.ts
- types/test/model.ts
added support for multiple primary key attributes in sequelize/types/lib/model.d.ts
closes #11392
> feat: added support for multiple primary key attributes

- lib/query-interface.js
Not yet, I looked into it, and it looks like the bulkDelete take a generic(?) QueryOptions object.
This issue adds missing documentation, thus closes #11473
> Added already existing options for bulkDelete to the documentation

- docs/manual/data-types.md
Fix `DataTypes` link at the top of the [manual](https://sequelize.org/master/manual/data-types.html)
> docs: fix data-types link

- lib/dialects/abstract/query.js
- test/integration/sequelize.test.js
Fixes https://github.com/sequelize/sequelize/issues/11458 - the `fieldMap` code now checks that `name` is different from `field` before reassigning the value of `field` in the query result to `name` and deleting `field`. A test is included.
> Do not omit field when same field/name in fieldMap

- docs/manual/upgrade-to-v5.md
Documentation-only change.
These were previously being rendered as `mailto:` links via esdoc (which uses marked's autolink rendering); see https://sequelize.org/master/manual/upgrade-to-v5.html. 
There are some [suggestions](https://gist.github.com/alexpeattie/4729247) about how one might disable or avoid autolinking but in this case the package identifiers are in backticks, producing weird behaviour similar to https://github.com/markedjs/marked/issues/1327.  Assuming the fix for this latter issue worked to solve this issue, then a dependency upgrade of `marked` within `esdoc` might solve the problem, but there are [maintenance issues](https://github.com/esdoc/esdoc/pull/543) there preventing updates or merges.
Until that point, this is a workaround to avoiding the weird `mailto:` links …
> fix(docs): fix package id links in docs

- .github/ISSUE_TEMPLATE/bug_report.md
Including the suggestion to use https://github.com/papb/sequelize-sscce in the bug report issue template!
> chore(.github): update bug report template

- test/unit/sql/where.test.js
- types/lib/model.d.ts
- types/test/where.ts
Types for string and number arrays are missing for `Op.contains` & `Op.contained` operator.
> fix(types): allow string and number arrays for contains operator

- types/lib/model.d.ts
- types/test/where.ts
`where` clauses that contain Buffer values (querying binary fields) fail Typescript validation due to a missing type declaration. Example:
```js
Foo.findOne({
where: { bar: Buffer.alloc(0) },
});
```
This PR adds the missing Buffer type to the `WhereValue` type definition.
I ran `npm run test-typings`
> fix(types): add Buffer to WhereValue type

- types/lib/model.d.ts
- types/test/where.ts
`where` clauses that contain arrays of Buffers (querying binary fields) fail Typescript validation due to a missing type declaration. Example:
```js
Foo.findOne({
where: { bar: [Buffer.alloc(0)] },
});
```
Buffer support was just added in https://github.com/sequelize/sequelize/pull/11499. This PR adds support for arrays of Buffers to the `WhereValue` type definition.
I ran `npm run test-typings`
> fix(types): add array of Buffers to WhereValue type

- docs/manual/models-usage.md
- lib/dialects/abstract/index.js
- lib/dialects/abstract/query-generator.js
- lib/dialects/sqlite/index.js
- lib/model.js
- test/integration/include.test.js
- test/integration/model/count.test.js
- test/unit/sql/generateJoin.test.js
- test/unit/sql/select.test.js
- types/lib/model.d.ts
Add ability to specify a right join for associations
Addresses #4187, should we reopen it?
`test/integration/model/count.test.js` was changed due to the linter. I can revert it if you would like.
> feat(model): add `options.include[].right` option

- lib/dialects/postgres/query-generator.js
- test/unit/dialects/postgres/query-generator.test.js
Fixes #11523
Postgres' upsert query generator replaces the first `RETURNING *` it finds on the insert and update query, so if the data being added has that string, it replaces it (so it replaces the wrong `RETURNING *`) changing the input data and messing with the the final query.
This PR updates the replace method to use a regex with a negative lookahead so it only chooses the last `RETURNING *` in the query.
> fix(postgres): update upsert regex to match the last `RETURNING *`

- lib/dialects/abstract/query-generator.js
- lib/dialects/mssql/query-generator.js
- lib/dialects/postgres/query-generator.js
- lib/model.js
- test/integration/model.test.js
- test/integration/model/bulk-create.test.js
- test/integration/model/create.test.js
- test/unit/sql/insert.test.js
- test/unit/sql/update.test.js
If an underlying table has columns that don't exist in the model, when using `returning: true` the instance will be created with these extra attributes. This change alters this behavior to only return the fields defined in the model, provided a model definition is passed.
Note: this is a breaking change since the option `returning: true` will no longer create
attributes on the instance that are not defined in the model.
The old default behavior can be used by:
```diff
- returning: true
+ returning: ['*']
```
> feat(postgres): change returning option to only return model attributes

- lib/associations/belongs-to-many.js
- test/integration/associations/belongs-to-many.test.js
> fix(associations): allow binary key for belongs-to-many

- .eslintrc.json
- docs/manual/transactions.md
- lib/sequelize.js
- package.json
- test/integration/cls.test.js
- test/unit/model/find-or-create.test.js
- types/lib/sequelize.d.ts
> feat: support cls-hooked / tests

- docs/manual/hooks.md
Close #11600 
Add information that beforeBulkCreate/afterBulkCreate hooks will run
> doc(hook): add info about belongsToMany

- types/lib/query-interface.d.ts
- types/test/query-interface.ts
(npm run test-typings, actaully)
as described in #11027, many of the QueryInterface methods accept something like `string | { tableName: string, schema: string }` as the first argument. however, they are accepting tableName with string type only. So I added interface and type so that they could get arguments other than string.
> fix: fix type of methods in query-interface

- types/lib/model.d.ts
This is just an update to typescript model declaration that fixes "beforeDestroy" callback type.
> More precise beforeDestroy type

- types/lib/sequelize.d.ts
- types/test/sequelize.ts
Add `getDatabaseName` function type in `Sequelize` class type. Closes #11431
> fix(typings): Add getDatabaseName type

- types/lib/model.d.ts
- types/test/where.ts
Add `Date` type in `WhereValue`. Closes #11381
> fix(typings): Add Date type to WhereValue 

- types/lib/model.d.ts
- types/test/include.ts
Typings were missing previously.
Add `nested` to typings `Includeable`.
> fix(typings): add missing nested to Includeable

- lib/dialects/abstract/query-generator.js
- package.json
- test/integration/instance/save.test.js
- test/integration/model/create.test.js
- test/unit/dialects/abstract/query-generator.test.js
https://github.com/sequelize/sequelize/issues/11533
- changed the abstract query generator handleSequelizeMethod to escape dollar ($) in argument
> fix: escape dollarsign in sequelize.fn related to issue 11533

- types/lib/model.d.ts
- types/lib/transaction.d.ts
- types/test/transaction.ts
As stated in the sequelize docs (https://sequelize.org/master/class/lib/transaction.js~Transaction.html#static-get-LOCK), when performing find operations, a lock property can be passed, and that can be either `true` or `false` or also a lock level obtained from the actual instance, i.e. `t1.LOCK.UPDATE`, which ends up being a string.
The TypeScript types were failing when trying to pass a boolean value to `lock` or when trying to access `t1.LOCK...` on a transaction instance.
This PR adds those missing types.
Link to existing issue: https://github.com/sequelize/sequelize/issues/11178#issuecomment-547014408
> fix(types): add missing transaction typescript types (v6-beta)

- types/lib/model.d.ts
- types/lib/transaction.d.ts
- types/test/transaction.ts
As stated in the sequelize docs (https://sequelize.org/master/class/lib/transaction.js~Transaction.html#static-get-LOCK), when performing find operations, a lock property can be passed, and that can be either `true` or `false` or also a lock level obtained from the actual instance, i.e. `t1.LOCK.UPDATE`, which ends up being a string.
The TypeScript types were failing when trying to pass a boolean value to `lock` or when trying to access `t1.LOCK...` on a transaction instance.
This PR adds those missing types.
Link to existing issue: https://github.com/sequelize/sequelize/issues/11178#issuecomment-547014408
Link to v6-beta PR: https://github.com/sequelize/sequelize/pull/11620
> fix(types): add missing transaction typescript types (v5)

- types/lib/model.d.ts
- types/test/model.ts
This will update the field `IncludeOptions.include` type so that it now supports `Includeable | Includeable[]`. This change also affects other interfaces which were updated accordingly.
Closes #11376
> fix(types): add Includeable to IncludeOptions.include type

- docs/manual/migrations.md
This pull request just fixes a very little syntax error in the documentation.
> fix syntax error in docs.

- CONTRIBUTING.md
- lib/model.js
- test/integration/associations/belongs-to-many.test.js
- types/lib/model.d.ts
- types/test/model.ts
This will add `as` property to the `IncludeThroughOptions` definition.
Closes #11185
> fix(types): include 'as' in IncludeThroughOptions definition

- docs/manual/transactions.md
Subsections of "Concurrent/Partial transactions" in transactions.md 
should be "WITH CLS enabled" instead of "WITHOUT CLS enabled".
See comment in the code below section header
> docs(transaction): fix typo

- types/lib/model.d.ts
- types/test/model.ts
This will add `paranoid` to the `UpdateOptions` interface. Closes #11200
> fix(types): add paranoid to UpdateOptions interface

- types/lib/model.d.ts
- types/test/model.ts
Added typings for `this` on getters and setters in attribute definitions.
> fix(types): specified `this` for getters and setters in fields

- types/lib/query-interface.d.ts
- types/test/query-interface.ts
> docs(sequelize): typing of upsert interface to match code (#11673)

- lib/model.js
- test/integration/model/bulk-create.test.js
- `npm run test-postgres` fails... with 3 unrelated failures ([details](https://gist.github.com/huned/401bd7781f7092a69fa925dd0b9ce4c7)) that occur both before and after my commit to fix #11665 
- N/A ~~[ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?~~
- N/A ~~[ ] Did you update the typescript typings accordingly (if applicable)?~~
Closes #11665
> fix(model): generate ON CONFLICT ... DO UPDATE correctly

- types/lib/query-interface.d.ts
This PR fixes the [https://github.com/sequelize/sequelize/issues/11567](https://github.com/sequelize/sequelize/issues/11567) issue.
> fix(typings): added 'fieldMaps' to QueryOptions typings

- lib/model.js
- lib/sequelize.js
- test/integration/model/sync.test.js
- types/lib/sequelize.d.ts
This is a less impactful version of a PR from last year (#9732 #9731). This feature implements the ability for the `alter` option to take an object for further configuration of the alter process during `sequelize.sync()`. Inside of the object the developer then can decide whether to allow drop statements or not using the `drop` option.
To give a small example why this feature is useful: I'm currently developing an app that can be extended by plugins. These plugins should have the ability to extend existing database models. I found out about the `alter` option in sync but it is currently not suitable for me since the end-user would instantly lose data if a plugin would not load correctly or would get removed by the user. 
Usage of …
> feat(sync): allow to bypass drop statements when sync with alter enabled

- lib/dialects/mssql/query.js
Fixes https://github.com/sequelize/sequelize/issues/11695.
> fix(mssql): optimize formatError RegEx

- types/lib/hooks.d.ts
The `hooks.d.ts` file is missing the restore hooks (`beforeRestore`, `afterRestore` and so on). This PR adds missing restore hook definitions to the `hooks.d.ts` file.
> feat(typescript): add 'restore' hooks to types

- lib/query-interface.js
- types/lib/query-interface.d.ts
- Add missing getForeignKeyReferencesForTable type
- Add comments for getForeignKeysForTables method. There are no comments in the code so that there are no documentations in the QueryInterface API Reference:  https://sequelize.org/v5/class/lib/query-interface.js~QueryInterface.html#instance-method-getForeignKeysForTables
> fix(types): add getForeignKeyReferencesForTable type

- lib/model.js
- test/integration/model/findAll.test.js
- n/a Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- n/a Did you update the typescript typings accordingly (if applicable)?
Properly injects dependent virtual attributes on included model. Closes #10930
> fix(model): injectDependentVirtualAttrs on included models

- docs/manual/migrations.md
Fixes #11758
This PR fixes a code example in the documentation under:
**Advance Topics** -> **Migration Skeleton** -> "The next is an example of a migration that has uses async/await where you create an unique index on a new column:"
https://sequelize.org/master/manual/migrations.html#migration-skeleton
> docs(*): corrects async/await example that uses transactions

- docs/manual/upgrade-to-v6.md
Fat arrow could mean arrow function and thus could be confusing. Changing it to comment. The exact formatting is copied from upgrade-to-v5.md.
> docs(upgrade-to-v6): remove confusing fat arrow in snippet

- docs/manual/core-concepts/raw-queries.md
As observed by @louy2 in [this comment](https://github.com/sequelize/sequelize/pull/2990#issuecomment-565863631), this part of the docs is incorrect.
In my opinion it can simply be removed.
> docs(raw-queries): remove outdated info

- docs/manual/other-topics/dialect-specific-things.md
Creating this pull request to add an example to the MSSQL section for domain authentication. It took me a while to figure out how to do so in Sequelize when it was working in pure Tedious. The line in the docs, shown below, is what caused the confusion. Due to the statement, I had thought that ***all*** MSSQL specific configuration settings had to be in `options` under `dialectOptions`. Maybe the text can be changed, but I've added an example nonetheless.
> Please note: `tedious@^6.0.0` requires you to nest MSSQL specific options inside an additional `options`-object inside the `dialectOptions`-object.
> Added MSSQL domain auth example.

- docs/manual-groups.json
The [models-definition](https://sequelize.org/master/manual/models-definition.html) page of the manuals is currently a 404, this was an oversight by me, the fix is this one-liner...
> docs(manuals): fix missing models-definition page

- docs/manual/other-topics/optimistic-locking.md
The manual on optimistic locking was missing from the left menu because apparently ESDoc only renders those for manuals with a single `#` at the top level
> docs(optimistic-locking): fix missing manual

- docs/esdoc-config.js
- docs/manual-utils.js
This is a refactor of the code that generates the manuals, which includes a few assertions in order to prevent mistakes like #11850 from ever happening again.
> refactor(docs): catch some mistakes

- lib/dialects/abstract/query-generator.js
- lib/model.js
- lib/query-interface.js
- test/integration/model/increment.test.js
- test/unit/dialects/mariadb/query-generator.test.js
- test/unit/dialects/mssql/query-generator.test.js
- test/unit/dialects/mysql/query-generator.test.js
- test/unit/dialects/postgres/query-generator.test.js
- test/unit/dialects/sqlite/query-generator.test.js
Fixes #10719
Fixes #10411
Fixes #9572
[Inspired](https://github.com/sequelize/sequelize/pull/11676#issuecomment-576415470) by #11676, thanks @mhio and @ALiangLiang.
> fix(increment): broken queries

- docs/manual/core-concepts/assocs.md
Fixed typo from Playes to Player
> Fixed typo from Playes to Player

- types/lib/sequelize.d.ts
- types/test/where.ts
In the types of the where function, in the comparator parameter a symbol is added as type, this solves problems when using the constant Op the function where
Example of the problem i had:
```typescript 
import { Op } from 'sequelize';
Sequelize.where(
 Sequelize.fn('LOWER', Sequelize.col('email')),
 Op.like, // error Argument of type 'unique symbol' is not assignable to parameter of type 'string'.ts
 Sequelize.fn('LOWER', email + '%'),
)
```
Closes #11241
> fix(typings): `comparator` arg of `Sequelize.where`

- package.json
We already hide the links to source from our docs:
https://github.com/sequelize/sequelize/blob/9d3be832838b3db2326cdbac60d670118b4112ec/docs/css/style.css#L58-L61
However we still generate them and deploy them. For example:
https://sequelize.org/master/file/lib/query-interface.js.html
There is no way to navigate to the above link using the interface in the docs, but if you press F12 you will figure out that link.
We should save deployment space and not deploy those at all, since they're hidden anyway...
> build(docs): save space

- docs/manual/core-concepts/model-querying-basics.md
Added two commas to a sentence to allow it to be clearer. Reference: https://data.grammarbook.com/blog/commas/commas-part-10/ (Rule #2)
Edited a sentence adding and thus surrounding with two commas a 'for example' expression
> Added some commas

- docs/manual/core-concepts/assocs.md
This PR contains simple fixes of typos in assocs manual - `Foo` and `Bar` was switched by mistake.
> docs(manual): fix typos in assocs manual

- types/lib/sequelize.d.ts
- types/test/sequelize.ts
Closes #11595
- https://github.com/sequelize/sequelize/pull/11929
> Support `{ plain: true }` in typescript typings for sequelize.query

- lib/dialects/abstract/index.js
- lib/dialects/abstract/query-generator.js
- lib/dialects/postgres/index.js
- test/unit/sql/index.test.js
- types/lib/query-interface.d.ts
> feat(index): improve to support multiple fields with operator

- lib/model.js
- test/integration/model/count.test.js
Add code to count() to cause it to create valid SQL when distinct=true and col is unspecified or `"*"`. Otherwise the SQL generated is `COUNT(DISTINCT(*))`, which is invalid. Issues referenced below were already closed, but the issue hadn't actually been fixed, and it _keeps coming up_.
Closes: #11894, #2713, #6404, #6418, #7344
Add code to count() to cause it to create valid SQL when distinct=true and col is unspecified or "*". Otherwise the SQL generated is COUNT(DISTINCT(*)), which is invalid. Issues referenced below were already closed, but the issue hadn't actually been fixed, and it keeps coming up.
#11893 was this PR against v5. This PR is against master.
Notes:
**Tests:** Tested against Postgres 11 only. There are failures, but they seem to be failures in `master`, not in anything …
> fix(model): count() code generation for distinct rows

- lib/query-interface.js
This change related exclusively to the documentation
> docs: improve query-interface removeIndex indexNameOrAttributes @param

- lib/model.js
- test/integration/model/bulk-create.test.js
I noticed that my original PR #11163 to support `updateOnDuplicate` for Postgres (and subsequent community updates since then) isn't working with composite unique keys. This fixes that, I think.
This bug appears to have been raised in issues #11569 and #11534, and maybe #11665?
I think PR #11611 is supposed to fix this? But it looks like it also adds additional functionality (`upsertIndex` and `upsertKeys` options on `bulkCreate()`), and has not been merged yet.
I added 2 tests as well: one for composite `primaryKey` bulkCreates, and one for composite `unique` bulkCreates. All Postgres tests appear to be passing.
> fix(model): updateOnDuplicate handles composite keys now

- package.json
No functional effect of this change. The missing entry prevents installation of the module from Git.
> File list fix

- lib/dialects/mssql/query-generator.js
sys.extended_properties.value is a column of type sql_variant. If used with msnodesqlv8, the driver will crash when executing this query without casting the sql_variant to nvarchar.
The issue is only relevant if a model is synced with `{alter: true}` option. In this case, the Application will just exit without any error. The "real" error is probably in the c++ driver of msnodesqlv8, since I was not able to debug it any further. However, I was able to isolate the query which is causing the bug. Running the same query without sequelize causes the same problem. I started modifying the query and found it that it is related to the extended_properties value column. Casting it to NVARCHAR solves the issue.
This is a really small fix. I …
> fix(mssql): cast sql_variant in query generator

- lib/dialects/mssql/query.js
- test/unit/dialects/mssql/query.test.js
When we set type options of float for mssql, existing code blindly set it to precision 30, scale 15.
This could cause an issue with a large float value e.g. 43069.0122916667.
see issue https://github.com/tediousjs/tedious/issues/1058
and https://github.com/sequelize/sequelize/issues/11959
to minimize the impact of the issue, we should at least set the scale correctly.
> fix(mssql): set correct scale for float

- lib/dialects/abstract/query-generator.js
- lib/dialects/postgres/query.js
- test/integration/dialects/postgres/query.test.js
Proposal to make the `minifyAliases` option also alias includes that go over the 63 POSTGRES character limit.
Closes https://github.com/sequelize/sequelize/issues/11937
> feat(postgres): minify include aliases over limit

- types/lib/model.d.ts
- types/lib/query-interface.d.ts
- types/test/query-interface.ts
Add `null` as allowed parameter to `insert` on `queryInterface` and adjust return type of `bulkInsert` to include `number` as it can be one.
> fix(query-interface): allow passing null for query interface insert

- types/lib/model.d.ts
- types/test/where.ts
Added `Fn` to the type union to allow performing `model.findOne({ where: fn(...) })` which is currently supported by sequelize.
> fix(typings): fn is assigning to where

- lib/sequelize.js
- test/unit/configuration.test.js
Allow the query string `host` value to override the host value from the
uri. The host query string is used to specify domain socket paths which
cannot be specified in host part of a uri.
I've found a few references online (including #695) which indicate that the `host` query string value should work for domain sockets. However, upon review of the code and tests, this functionality may have been lost.
Related: https://github.com/sequelize/cli/issues/695
> feat(sequelize): handle query string host value

- lib/query-interface.js
- test/integration/data-types.test.js
- test/integration/dialects/postgres/dao.test.js
- test/integration/dialects/sqlite/dao.test.js
- test/integration/include/paranoid.test.js
- test/integration/model/scope/associations.test.js
- test/integration/sequelize.test.js
I may have missed one or two cases of `.get('stringLiteral')`.  ~~I haven't checked for `.get(identifier)`...~~ Okay, I didn't find any instances of `.get(identifier)` being in a bluebird promise chain
> refactor: replace bluebird .get

- lib/query-interface.js
- types/lib/query-interface.d.ts
Fixes the definition of `getForeignKeysForTables` in TS.
This change can also apply to v5. Is it ok to merge to master?
PS: I don't think any of the above is needed, right? I couldn't even run `DIALECT=sqlite npm run test` successfully.
> fix(types): fixed getForeignKeysForTables argument definition

- docs/manual/core-concepts/model-instances.md
_PR only contains changes to documentation_
Shouldn't this be 'jane' instead of 'user' when calling the increment method to increment the age of the 'jane' instance by 2 ?
> variable 'jane' instead of 'user'

- lib/dialects/abstract/connection-manager.js
- lib/sequelize.js
- types/lib/sequelize.d.ts
Expose the recently added `maxUses` pool config option (https://github.com/sequelize/sequelize-pool/pull/18).
I followed the instructions given in #12057, with the additional step of updating the `PoolOptions` type definition.
Thank you for all your help!
> feat(pool): Expose the recently added maxUses pool config option

- lib/dialects/mssql/query.js
- test/integration/dialects/mssql/regressions.test.js
Hi @sushantdhiman 
I reopen an PR to merge to master tree simply.
#12024 
This is issue is similar with #11121
> 
> sequelize@^5.21.5
> tedious@8.2.0
The sample code is following
```js
var Company= sequelize.define('tm_company', {
"COMPANY_GUID": {
"type": Sequelize.STRING(36)",  "allowNull": false, "primaryKey": true, "defaultValue": Sequelize.UUIDV1},
"ENCRYPT_ALL": { "type": Sequelize.BOOLEAN, "allowNull": false, "defaultValue": false },
"MORE_INFO": { "type": Sequelize.TEXT, "allowNull": true}
});
Company.sync().then(() => {
Company.create({});
})
```
The db query exception: 
> SequelizeDatabaseError: Conversion failed when converting the nvarchar value 'false' to data type smallint.     at Query.formatError …
> fix(mssql) insert record failure because of BOOLEAN column type

- .travis.yml
Replaced [giorgos/takis](https://hub.docker.com/r/giorgos/takis) with [wilder/dockerize](https://hub.docker.com/r/jwilder/dockerize). Better interface and logs
resolves #12103
> refactor(ci): improve database wait script

- types/lib/model.d.ts
Resolves #12112 
Correct the return type of Model.init from `void` to `Model` to match to the return type defined in the API reference (which is the correct one).
> docs(types): correct Model.init return type

- lib/model.js
- test/integration/include/separate.test.js
- test/unit/model/include.test.js
Resolves https://github.com/sequelize/sequelize/issues/12141
As stated in issue, I believe "separate" queries are being negatively impacted if their "parent" is required, even if that parent is not part of the current query.
The generated SQL expects the parent to be generating a literal subquery (wrapped in parentheses) but due to the nature of "separate" queries, that isn't actually happening.
This change fixes things locally for me.
~I don't believe this portion of code is currently covered by unit-tests, and I'm not entirely sure where to start on a higher level integration test...~
Added unit test
> fix: Separate queries are not subQueries

- .travis.yml
- CONTRIBUTING.md
- appveyor.yml
- package-lock.json
Use package-lock for installs.
I also ran the `dedupe command` prior to this.
This will:
- Speed up installs.
- Allow reproducable builds.
Side effects:
Apparently `Out-File` emits BOM with utf8 encoding which breaks `npm ci` so I removed it, `pg-native` isn't installed by default so that was a noop and skipping `sqlite3` doesn't bring much of a benefit either.
> ci(install): use package lock for install

- lib/model.js
Found this while messing around in code base.
Wrote no test due to high complexity of function, plus nothing seems to be failing as a result...
> fix(model): fix unchained promise in association logic in bulkCreate

- types/lib/model.d.ts
- types/test/where.ts
Allows `Op.between` to process data ranges.
> fix(types): make between operator accept date ranges

- docs/manual/other-topics/upgrade-to-v6.md
- lib/sequelize.js
- test/integration/sequelize.test.js
Closes https://github.com/sequelize/sequelize/issues/11739
> refactor: remove sequelize.import helper

- lib/dialects/mssql/connection-manager.js
- test/unit/dialects/mssql/connection-manager.test.js
Call `connect` after creating `tedious` connection if required.
Fixes #12181
> Fix tedious connect deprecation

- docs/manual/advanced-association-concepts/association-scopes.md
Simple documentation fix, wrong scope name.
Closes #12198
> fix(docs): fix scope name on association scope

- lib/model.js
- test/unit/model/scope.test.js
Closes https://github.com/sequelize/sequelize/issues/12172
> fix(scope): don't modify original scope definition

- lib/model.js
Fixes https://github.com/sequelize/sequelize/issues/12189
> fix(sync): pass options to all query methods

- lib/model.js
- test/integration/instance/reload.test.js
Fixes https://github.com/sequelize/sequelize/issues/12046
Now `reload` ignores `options.where`
> fix(model.reload): ignore options.where and always use this.where()

- lib/associations/belongs-to-many.js
- lib/associations/has-many.js
- lib/dialects/postgres/query-interface.js
- lib/dialects/sqlite/query-interface.js
- lib/instance-validator.js
- lib/model.js
- lib/query-interface.js
- lib/sequelize.js
- lib/utils.js
- test/integration/dialects/abstract/connection-manager.test.js
- test/unit/model/destroy.test.js
- test/unit/model/update.test.js
This replaces (almost) all `_.clone` calls with object spreading (there was 1 array clone).
Turns out `_.clone` is around least an order of magnitude slower compared to native object spreading!
Consider this (rather naive) performance test:
```js
'use strict';
const { clone } = require('lodash');
const data = {
a: 1,
b: 2,
c: 3,
d: 4,
e: 5
};
let out;
console.time('clone');
for (let i = 0; i < 0xffffff; i++) {
data[Math.floor(Math.random() * 10)] = Math.random(); //avoid opt
out = clone(data);
}
console.timeEnd('clone');
console.time('spread');
for (let i = 0; i < 0xffffff; i++) {
data[Math.floor(Math.random() * 10)] = Math.random(); //avoid opt
out = { ...data };
}
console.timeEnd('spread');
console.log(out); // avoid opt
```
The …
> refactor: replace lodash clone with object spread

- lib/associations/belongs-to-many.js
- lib/associations/belongs-to.js
- lib/associations/has-many.js
- lib/associations/has-one.js
- lib/dialects/abstract/query-generator.js
- lib/dialects/postgres/query-generator.js
- lib/dialects/sqlite/query-generator.js
- lib/instance-validator.js
- lib/model.js
- lib/sequelize.js
Replaces most instances of `_.defaults` with object spreading.
- _.defaults has somewhat of a high mental overhead as you have to go from last to first argument to understand the object assignment, especially complicated when used with nested spreading and/or Object.assign.
- object spread is a bit faster (~10% in my tests).
- less memory/gc pressure due to less intermediate object creation.
> refactor: replace lodash defaults with object spread

- docs/manual/other-topics/resources.md
I have written this library to solve the problem of having a very natural API.
It has very fast role permissions based Authorization resolution.
Role permission map is stored in cache which makes permission resolution fast.
please check if out and merge this if you guys like it. It would be big help in making it better.
https://github.com/lotivo/sequelize-acl/
> add SequelizeGuard library into acl category in documentation/resources

- docs/manual/other-topics/typescript.md
Simple documentation fix.
Closes #12081
> Doc: remove unnecessary comment on typescript

- lib/dialects/sqlite/query-generator.js
- test/unit/dialects/sqlite/query-generator.test.js
- [V] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [V] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [V] Have you added new tests to prevent regressions?
- [V] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?
Fixes https://github.com/sequelize/sequelize/issues/12194
> Fix multiple primary keys results in syntax error (duplicate "NOT NULL")

- lib/dialects/abstract/query.js
- test/integration/sequelize.test.js
> fix(query) Do not bind character with $ on the middle

- lib/associations/belongs-to-many.js
- test/integration/associations/belongs-to-many.test.js
Fixes https://github.com/sequelize/sequelize/issues/6790
> feat(belongs-to-many): get/has/count for paranoid join table

- lib/associations/helpers.js
- lib/dialects/mssql/query-generator.js
- lib/dialects/mysql/query-generator.js
- lib/utils.js
- test/integration/dialects/mssql/regressions.test.js
Fixes an general issue with association, improper merging of newly generated attributes was overriding schema based `toString` fn with `Object.isString`
Closes #10125
> fix(associations): ensure correct schema on all generated attributes

- lib/dialects/postgres/query-generator.js
- test/integration/query-interface.test.js
> fix(postgres): addColumn support ARRAY(ENUM)

- lib/dialects/abstract/query-generator.js
- lib/dialects/abstract/query-interface.js
- lib/dialects/mssql/query.js
- lib/instance-validator.js
- lib/model.js
- test/unit/sql/update.test.js
~This is a breaking change for MSSQL. MSSQL lacks ability to return `affectedRows` for update operation without `OUTPUT INSERTED.*` statement. As this PR fixes that behavior, we are not automatically injecting that statement.~
~So MSSQL users if need `affectedRows` count from `update`, will need to call it with `returning: true`~
Supports disabling `OUTPUT INSERTED.*` with `returning: false`
Closes #11203
Fixes #11304
Fixes #11201
> fix(mssql): no default returning in update

- lib/associations/base.js
- lib/model.js
Closes https://github.com/sequelize/sequelize/issues/10104
> fix: remove custom inspect

- docs/manual/other-topics/query-interface.md
Links to `queryInterface` API reference are broken in docs since #12217
Closes #12270
> docs(query-interface): fix broken links

- lib/dialects/mssql/query.js
- lib/dialects/postgres/query.js
> fix: add missing sql and parameters properties to some query errors

- lib/associations/belongs-to-many.js
- lib/model.js
- lib/sequelize.js
- lib/transaction.js
- types/lib/model.d.ts
- types/lib/query-interface.d.ts
- types/lib/sequelize.d.ts
- types/lib/transaction.d.ts
- types/test/connection.ts
- types/test/e2e/docs-example.ts
- types/test/query-interface.ts
- types/test/sequelize.ts
- types/test/upsert.ts
- types/test/where.ts
#9552 # Pull Request check-list
Update js docs and ts to use async await.
Improved `describeTable` typings while at it.
> docs: asyncify

- lib/dialects/abstract/index.js
- lib/dialects/abstract/query-generator.js
- lib/dialects/abstract/query-interface.js
- lib/dialects/mariadb/query.js
- lib/dialects/mssql/query-interface.js
- lib/dialects/mssql/query.js
- lib/dialects/mysql/query-generator.js
- lib/dialects/mysql/query-interface.js
- lib/dialects/mysql/query.js
- lib/dialects/postgres/query-generator.js
- lib/dialects/postgres/query-interface.js
- lib/dialects/postgres/query.js
- lib/dialects/sqlite/query-generator.js
- lib/dialects/sqlite/query.js
- lib/model.js
- test/config/config.js
- test/integration/model/upsert.test.js
- test/unit/dialects/postgres/query-generator.test.js
- types/lib/model.d.ts
- types/test/upsert.ts
Closes https://github.com/sequelize/sequelize/pull/11246
Fixes https://github.com/sequelize/sequelize/issues/4132
Fixes https://github.com/sequelize/sequelize/issues/12051
Fixes https://github.com/sequelize/sequelize/issues/9629
Fixes https://github.com/sequelize/sequelize/issues/9216
> feat(postgres): native upsert

- lib/dialects/mssql/query-generator.js
- lib/dialects/mysql/query-generator.js
- lib/dialects/postgres/query-generator.js
Rename / remove some internal methods
> refactor: cleanup query generators

- lib/model.js
- test/integration/include/findAll.test.js
```js
Project.belongsToMany(User, { through : 'UserProject' })
User.belongsToMany(Project, { through : 'UserProject' })
User.findAll({
include : [
{
model : Project,
through : {
attributes : [] // the option is fixed by this change
}
}
]
})
```
This PR is a port of the https://github.com/sequelize/sequelize/pull/12020 to master branch.
> fix(model): check attributes specified for included through model

- types/lib/model.d.ts
Association ordering is preferred in docs, but not allowed from typescript.
> fix(types): add Association into OrderItem type

- lib/dialects/abstract/query-generator.js
- test/unit/sql/group.test.js
Fixes: https://github.com/sequelize/sequelize/issues/12315
> Do not generate GROUP BY clause if options.group is empty

- types/lib/model.d.ts
- types/test/model.ts
This PR includes some typings needed to provide clarification in regards to the usage of `findOrCreate` functionality, thus the `FindOrCreateOptions` interface has been altered to include the `fields` string array to whitelist which fields should be persisted as explained in https://github.com/sequelize/sequelize/issues/12325 . Tests are not passing, as well as in master upstream.
> fix: add missing fields to 'FindOrCreateType'

- lib/dialects/mssql/query.js
- lib/dialects/postgres/query.js
- lib/model.js
- test/integration/model.test.js
This close #12164.
I was debugging and realize, the [SSCE](https://github.com/papb/sequelize-sscce/pull/72) examples is passing truncate as an option. Therefore truncate on the database does not show affected rows so we can't return the value, thus I found the Postgres NaN in these cases.
- I changed the doc adding info about it when use truncate will no show rows affected only on Sqlite do this.
- Fixed Postgres rowCount when queryResult.rowCount isn't returning 
- Fixed MSsql  when data is empty return 0 on isBulkDeleteQuery
> fix(model destroy): Return 0 when options is truncate. 

- lib/dialects/mssql/query-generator.js
- test/unit/sql/offset-limit.test.js
(https://github.com/sequelize/sequelize/issues/10472)
It is a small fix for the mssql dialect when using the FETCH and OFFSET clauses since these must be used together with the ORDER BY clause and when sending an `options.order` like a empty array, the ORDER BY clause is not applyed and throw the error
> fix(mssql): solving issue 10472

- types/lib/model.d.ts
- types/test/model.ts
I'm bringing #11648 into v5.
Added typings for `this` on getters and setters in attribute definitions.
> fix(types): specified 'this' for getters and setters in fields

- lib/dialects/mssql/query.js
- lib/dialects/mysql/query.js
- test/integration/cls.test.js
Using promise.then instead of custom handler function for processing run query results for mysql dialect.
It change fix losing CLS context for mysql logging custom function in case of `benchmark: true` #12317
MR for v5: #12318
> fix(logger): use promise.then for processing query results(mysql)

- types/lib/sequelize.d.ts
- [ X ] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [ X ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ X ] Have you added new tests to prevent regressions?
- [ X ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ X ] Did you update the typescript typings accordingly (if applicable)?
- [ X ] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?
This adds the clientMinMessages to the Options interface for postgres specific configuration …
> feat(types): add clientMinMessages to Options interface

- types/lib/sequelize.d.ts
- [ x Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?
Closes #12376
> fix(types): transactinType in Options

- lib/dialects/postgres/query-generator.js
- test/unit/dialects/postgres/query-generator.test.js
_This bug affects **v5** for sure, I haven't checked for **v6** but I'm pretty sure it also applies to it._
When you have a PostgreSQL table containing a user-defined enum, if the last value of this enum contains multiple words, using a `describeTable()` on it will generate an array with a trailing quote due to a bad parsing of the result data. It works well in other cases (as long as the enum doesn't end with a multi-word value).
Consider this schema:
```sql
CREATE TYPE my_enum AS ENUM ('foo', 'bar', 'foo bar');
CREATE TABLE my_table (
foo my_enum
);
```
Sequelize uses `array_agg(pg_catalog.pg_enum.enumlabel)` to fetch the enum values, before passing it to `QueryGenerator.fromArray()` to parse it. In this case it will send the …
> fix(postgres): parse enums correctly when describing a table

- lib/sequelize.js
- test/integration/configuration.test.js
- test/unit/configuration.test.js
This commit allows complex object to be passed as option in the URI connection string. For example it's now possibile to do something like:
```
const sequelize = new Sequelize('mssql://user:password@server.database.windows.net/database?options={"encrypt":true}&anotherOption=1');
```
so that it will be possible to correctly connect to an Azure SQL database, as encryption is required
> allow options to be a JSON object

- lib/dialects/postgres/query-generator.js
- test/unit/dialects/postgres/query-generator.test.js
This PR is a cherry-pick of #12409, as the bug exists in v5 and v6!
When you have a PostgreSQL table containing a user-defined enum, if the last value of this enum contains multiple words, using a `describeTable()` on it will generate an array with a trailing quote due to a bad parsing of the result data. It works well in other cases (as long as the enum doesn't end with a multi-word value).
Consider this schema:
```sql
CREATE TYPE my_enum AS ENUM ('foo', 'bar', 'foo bar');
CREATE TABLE my_table (
foo my_enum
);
```
Sequelize uses `array_agg(pg_catalog.pg_enum.enumlabel)` to fetch the enum values, before passing it to `QueryGenerator.fromArray()` to parse it. In this case it will send the string `{foo,bar,"foo bar"}`, and the …
> v5: fix(postgres): parse enums correctly when describing a table

- .travis.yml
- lib/sequelize.js
- test/unit/configuration.test.js
Backported to V5. This commit allows complex object to be passed as option in the URI connection string. For example it's now possibile to do something like:
```
const sequelize = new Sequelize('mssql://user:password@server.database.windows.net/database?options={"encrypt":true}&anotherOption=1');
```
so that it will be possible to correctly connect to an Azure SQL database, as encryption is required
> V5: allow options to be a JSON object

- lib/dialects/mssql/query.js
- test/integration/model/update.test.js
- types/lib/model.d.ts
Fix for the MSSQL dialect to return changed records when using bulkUpdate with `returning: true`
- bulkUpdate will now return the updates if options.returning is true.
- Fix documentation for model.update
This is in relation to #12410 as requested
> fix(mssql): returning data for bulkUpdate

- lib/dialects/abstract/query-generator.js
- lib/dialects/mssql/query.js
- test/integration/model/update.test.js
- types/lib/model.d.ts
Fix MSSQL returning values for bulkUpdate
The issue creates a major performance hit for v5 - as bulkUpdates right now does not work correctly and requires to run another query to get the model data - which is returning already in the update itself.
- bulkUpdate will now return the updates if options.returning is true.
- updateQuery removed redundant setting check
- Fix documentation for model.update
> fix (mssql): bulkUpdate returning values

- types/lib/model.d.ts
Telling the `ModelAttributeColumnOptions` interface property `references` to accept strings as well.
This feature is actually implemented into sequelize, as can be seen in the [documentation](https://sequelize.org/master/class/lib/model.js~Model.html) you need to search for `attributes.column.references`.
> fix(types): Updated Types to match JavaScript implementation

- lib/dialects/mssql/query.js
- test/integration/model/create.test.js
- test/integration/model/upsert.test.js
When using the MSSQL dialect, running Insert or Upsert operations, the mssql dialect is ignoring the values returned by OUTPUT INSERTED.* which can also include defaults values populated by the database or fields being updated by various triggers.
> fix(mssql): insert and upsert operations do not return all fields

- lib/dialects/mssql/query.js
- test/integration/model/create.test.js
- test/integration/model/upsert.test.js
When using the MSSQL dialect, running Insert or Upsert operations, the mssql dialect is ignoring the values returned by OUTPUT INSERTED.* which can also include defaults values populated by the database or fields being updated by various triggers.
This is the sister to PR #21433 and solves the issue for Sequelize v5 as well
> fix(mssql): insert and upsert operations do not return all fields (v5)

- docs/manual/other-topics/typescript.md
Fixes error when you try to compile the example:
```
TS2304: Cannot find name 'ProjectCreationAttributes'.
```
> docs: fix error in the name of interface

- lib/dialects/sqlite/query-generator.js
- lib/dialects/sqlite/query-interface.js
- test/integration/model.test.js
- test/integration/model/sync.test.js
- test/integration/query-interface/changeColumn.test.js
- test/unit/dialects/sqlite/query-generator.test.js
Fixes #7078 
For the sqlite dialect, I added an additional query for describeTable to get the constraints for the columns via showIndexes. I also added a new test for this behavior, and updated existing tests to reflect the new behavior. Currently, this only fixes unique constraints.
I'm intentionally making this a draft until we can fix the foreign key thing because I don't know how those work, and so we can put this fix in v5 as well.
I'm also not really sure if the changes I made to the tests are valid
> fix(sqlite): describeTable now returns unique constraint and references

- docs/manual/core-concepts/assocs.md
The documentation under the `Associations` says that instead of a string
we can use a model directly but in the example still a string was used.
> docs: fix typo in the associations docs

- lib/dialects/sqlite/query-generator.js
- lib/dialects/sqlite/query-interface.js
- lib/query-interface.js
- test/integration/model.test.js
- test/integration/model/sync.test.js
- test/integration/query-interface/changeColumn.test.js
- test/unit/dialects/sqlite/query-generator.test.js
Fixes #7078 for v5
This is a back port for the fix I made in #12420.
> fix(sqlite): describeTable now returns unique and references (v5)

- types/lib/model.d.ts
Fixes the TypeScript typing of the SaveOptions and InstanceUpdateOptions to include the hooks option (as is documented). Fixes #12441.
> fix(types): update SaveOptions type to include Hookable (#12441)

- src/dialects/abstract/query-generator.js
- src/dialects/abstract/query-interface.js
- test/unit/sql/add-constraint.test.js
Only in the query interface.  Extensive support for composite keys is the subject of #311; this is merely one step in the right direction.
- [yep] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [yep] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [yep] Have you added new tests to prevent regressions?
- [yep] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [can't] Did you update the typescript typings accordingly (if applicable)?
- [yep] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?
Added support for defining …
> feat(query-interface): add support for defining composite foreign keys

- src/dialects/mssql/query-generator.js
- test/unit/dialects/mssql/query-generator.test.js
properly determines if a value used in a filter clause for upsert is relevant. currently there is a bug where it treats "falsey" values as not being specified, making it impossible to use something like a default value of `0` in a unique key and then filter by that value. 
closes https://github.com/sequelize/sequelize/issues/11902
closes https://github.com/sequelize/sequelize/issues/11684
> fix(mssql): upsert query with falsey values

- lib/dialects/mssql/query-generator.js
- test/unit/dialects/mssql/query-generator.test.js
cherry-pick of #12453 
properly determines if a value used in a filter clause for upsert is relevant. currently there is a bug where it treats "falsey" values as not being specified, making it impossible to use something like a default value of `0` in a unique key and then filter by that value. 
closes https://github.com/sequelize/sequelize/issues/11902
closes https://github.com/sequelize/sequelize/issues/11684
> fix(mssql): upsert query with falsey values (#12453)

- docs/manual/other-topics/typescript.md
- types/lib/model.d.ts
- types/test/typescriptDocs/ModelInit.ts
The current way to define a module in a functional way with Typescript works like this:
```ts
const Note: ModelCtor<
Model<
NoteAttributes, 
NoteCreationAttributes
>
> = sequelize.define(
...
);
```
However this approach is a bit much to write, and with the `ModelDefined` type it could be reduced to:
```ts
const Note: ModelDefined<
NoteAttributes, 
NoteCreationAttributes
> = sequelize.define(
...
);
```
It's just added syntactic sugar, that simplifies things.
Also there is no reference to `ModelCtor` nor a functional way with Typescript in the docs.
So another change is, I've added an example for defining models in a functional way in Typescript.
> feat(types): Add ModelDefined type as syntactic sugar

- src/utils.js
Closes #12358
Lodash throws an error when calling _.isNative if core-js has been loaded because some of its shims can interfere with lodash's ability to accurate determine if a particular function is a native function or not.  Using the _baseIsNative module directly bypasses the core-js check in lodash without requiring a custom implementation if the native function detection.
I didn't add any new unit test to validate that an error isn't thrown when core-js shims are loaded because I wasn't sure if you wanted an extra dev dependency for that.  I also wasn't sure since Mocha doesn't isolate each test file to a separate process if you wanted the core-js loaded for all tests since that could in theory mask some other problem when …
> fix: use lodash _baseIsNative directly instead of _.isNative (#12358)

- src/dialects/mariadb/query.js
- src/model.js
- test/integration/instance.test.js
- test/unit/model/upsert.test.js
I'm having problems on upsert returned instances. Doing a `.save()` on an instance right after an upsert returns validation error because it tries to insert instead of updating. I think I tracked this error to having `isNewRecord` as `true` on that returned instance. I tried fixing it by setting it to false on `upsert` method but failed on other tests.
> fix(upsert): sets isNewRecord to false when upserting

- lib/dialects/mariadb/query.js
- lib/model.js
- test/integration/instance.test.js
- test/unit/model/upsert.test.js
> fix(upsert): set isNewRecord to false when upserting (#12447)

- package.json
same as https://github.com/sequelize/sequelize/pull/12484 but for the `master` branch
> fix: mark database drivers as optional peer dependencies

- lib/model.js
- test/integration/model.test.js
This is a cherry-pick from #12580 targeting the `v6` branch, so that a fix can land in v6.
> fix(model): handle `true` timestamp fields correctly (#12580)

- docs/manual/other-topics/hooks.md
URL changed to "v6", this is a continuation of #12669 - which was branched of master instead of v6
> Update documentation - hooks.md - fixed URL

- docs/manual/other-topics/transactions.md
**await** keyword doesn't work inside a function if the function is not defined using **async** keyword
Added **async** keyword to the anonymous function
> Fix function definition for await keyword usage

- lib/dialects/mariadb/query.js
- lib/sequelize.js
- lib/transaction.js
- test/integration/transaction.test.js
Closes #11571
This change makes deadlocked queries release the MariaDB/MySQL connection and does a redundant rollback. These ensure that subsequent queries work properly.
While running sequelize in production for a collaborative document editor, we found that deadlocks on MariaDB would sometimes cause other queries to stall. After debugging, we realized that this is because MySQL/MariaDB has custom deadlock handling in Sequelize.
1. Because InnoDB (MariaDB/MySQL engine) automatically rolls back one query in the case of deadlocks, sequelize marks the `transaction.finished = 'rollback'` in the `run` function of [query.js](https://github.com/sequelize/sequelize/blob/4097aaa/src/dialects/mariadb/query.js#L54)
2. In `transaction()` of …
> fix(mysql, mariadb): release connection on deadlocks

- docs/manual/core-concepts/model-basics.md
- docs/manual/core-concepts/model-querying-basics.md
- lib/data-types.js
- lib/dialects/abstract/query-generator/operators.js
- lib/dialects/postgres/data-types.js
- lib/dialects/postgres/index.js
- lib/operators.js
- test/integration/data-types.test.js
- test/integration/model/create.test.js
- test/integration/model/findOne.test.js
- test/unit/sql/where.test.js
This is PR #12631 rebased on top of the new `main` branch.
> feat(tsvector): TSVECTOR support

- lib/dialects/mariadb/query.js
- lib/dialects/mysql/query.js
Make the codes in `lib/dialects/mariadb/query.js` and `lib/dialects/mysql/query.js` more similar.
Also adds a debug message to MySQL.
> refactor(query): similar code for mysql and mariadb

- lib/data-types.js
The following changes update the link of an obsolete resource that is the `GeoJSON` link in `data-types.js` file. The old resource is from 2008 and the new one is from 2016. @papb please leave a review.
> This PR is a rework of #12937

- types/lib/model.d.ts
- types/test/transaction.ts
When using TypeScript with `strictNullChecks` enabled, we cannot pass `null` to `transaction`, but this is actually allowed and used to execute in a non-transaction context when in an auto-transaction block.
Closes #13092.
I wish for this change to also be backported to v5. How do I go about doing that?
> fix(types): Allow transaction to be null in Transactionable interface (#13092).

- types/lib/query-interface.d.ts
Fix the capitalization of the `queryGenerator` property
https://github.com/sequelize/sequelize/blob/6388507ebd916efe6adf3e6a94a4c5ce235dee2a/lib/dialects/abstract/query-interface.js#L16
> fix(types): decapitalize queryGenerator property

- types/lib/model.d.ts
- types/test/update.ts
Allow to use an array of columns for the `returning` option
Closes https://github.com/sequelize/sequelize/issues/13070
> fix(types): allow `(keyof TAttributes)[]` in `UpdateOptions.returning`

- lib/dialects/abstract/query-generator.js
- test/unit/sql/where.test.js
Fix handling of Op.between / Op.notBetween when using Sequelize.where
Closes #13040
> fix(queryGenerator): use AND for not/between

- lib/model.js
- test/integration/model/bulk-create.test.js
Supersedes #12516
Also addresses https://github.com/sequelize/sequelize/pull/11984/files#r414863957 via refactor
> fix(bulk-create): `ON CONFLICT` with unique index

- docs/manual/core-concepts/model-querying-basics.md
just found a typo in model-querying-basics at the "Examples with Op.not" section.
> docs(model-querying-basics.md): Fix a typo in the docs

- docs/manual/core-concepts/model-querying-basics.md
Documentation only change:
The generated SQL joins the two NOT clauses with an AND, which is what I would've expected.
> docs(model-querying-basics.md): change OR to AND

- types/lib/model.d.ts
- types/test/model.ts
The init method returns the model class itself, rather than an instance.
Generic parameters had to be tweaked to correctly automatically use the models types, rather than Model<any, any>
> fix(typings): model init returns model class, not instance

- types/lib/model.d.ts
- types/test/upsert.ts
Update returning to match other methods like bulkCreate: https://github.com/sequelize/sequelize/blob/main/types/lib/model.d.ts#L772
Test was updated with attributes to enforce valid values, rather than `any`
> fix(typings): returning can specify column names

- types/lib/model.d.ts
- types/lib/query-interface.d.ts
- types/test/query-interface.ts
Allow `schema` option with table name for queryInterface
Support already exists for all methods except [removeIndex](https://github.com/sequelize/sequelize/pull/13222)
Admittedly "support" to my knowledge is primarily postgres
> fix(typings): allow schema for queryInterface methods

- docs/manual/advanced-association-concepts/eager-loading.md
I'm not sure if most of the items above are applicable for this change.
There's a currently an extra parenthesis in the `eager loading` page:
This is caused due to the link having its own parenthesis: `https://en.wikipedia.org/wiki/Join_(SQL)` that breaks the markdown parsing.
Escaping those parenthesis (`https://en.wikipedia.org/wiki/Join_\(SQL\)`) should already fix it.
> Escape trailing parenthesis at eager loading doc page

- types/lib/transaction.d.ts
- types/test/models/User.ts
This change makes `Transactionable` compatible with `TransactionOptions`. Having both compatible allows for much cleaner code like this:
```javascript
async afterDestroy(instance: Model, options: InstanceDestroyOptions) {
return sequelize.transaction(options, async (transaction) => {
```
This piece of code was working before but broke on #13093. We can either merge this change or revert that PR to make these interfaces compatible but I think allowing `null` (merging this PR) is the way to go because it better represents the reality of this library.
> fix(typings): makes Transactionable compatible with TransactionOptions

- lib/sequelize.js
This is just a one liner to change a static `this` to the actuall class `Sequelize`. The reason behind this is somewhat out of the scope of the Sequelize project, but [when working with sequelize-typescript, `this` is interpretted as the sequelize-typescript class and trying to make cls work is impossible without a workaround](https://github.com/RobinBuschmann/sequelize-typescript/issues/1083). 
I understand if you consider the responsability for fixing this lies on the sequelize-typescript repo, but being such a simple change that it's pretty much the same, I think it's worth it. Besides, I think it's less ambiguous that way, and actually fits better with the comment above.
This is my frist contribution, so any feedback is …
> Change static this to class reference

- lib/model.js
Resolves the problem we've had with the documentation not being built. Replaces the incorrect esdocs syntax. Fixes #13612
> fix(docs): using incorrect esdocs syntax

- lib/model.js
- types/lib/model.d.ts
- types/test/model.ts
This will add `paranoid` property to the `IncludeThroughOptions` definition.
Closes #12848
> fix(types): include 'paranoid' in IncludeThroughOptions definition

- types/lib/hooks.d.ts
- types/lib/query.d.ts
- types/test/hooks.ts
Adds typed definitions for AbstractQuery and before/afterQuery lifecycle events
Closes #11441
> feat(definitions): Adds AbstractQuery and before/afterQuery hook definitions

- types/lib/data-types.d.ts
https://github.com/sequelize/sequelize/blob/7e43212f6f12db8afa3e5ceb9ef5502919effbcc/lib/data-types.js#L1073
`TEXT` class could be invoked as a static function, which has two types of params. This PR is trying to keep the definition and behavior consistent.
> fix(types): DataType.TEXT overloading definition

- types/lib/model.d.ts
- types/test/model.ts
_This is a continuation of the closed PR of https://github.com/sequelize/sequelize/pull/13044_
This PR introduces a more precise type to the `.toJSON()` function. Default it returns the given interface of a Sequelize model and allows to also pass along derived models that can be used to force an expected state. For example, that can be used to simulate the type after a specific sequelize `.find()`. 
This acts as an alternative to the `.toJSON() as <x>` notation, where using this generic type parameter restricts the type to only derived model types.
> fix(types): add specifc tojson type in model.d.ts

- .github/workflows/stale.yml
Look like some important PRs is staled and closed, so I'm adding `days-before-pr-close: -1` to avoid PRs being closed without assignees or contributors permission.
> chore(build): never close PRs

- .github/workflows/stale.yml
@fncolon @sdepold just a suggestion for the labels to be exempt as mentioned in #13648 
This does require maintainers/issue reviewers to add type labels to all still occurring issues and regularly update them.
> chore(stale): exempt issues with type label

- types/lib/associations/belongs-to-many.d.ts
- types/lib/associations/belongs-to.d.ts
- types/lib/associations/has-many.d.ts
- types/lib/associations/has-one.d.ts
- types/test/models/UserGroup.ts
Fixes https://github.com/sequelize/sequelize/issues/13000
This change restricts the typing on creating via association to the attributes of said model.
> fix: typing on creation within an association

- lib/dialects/postgres/connection-manager.js
- lib/sequelize.js
- package.json
- test/integration/dialects/postgres/connection-manager.test.js
- test/integration/sequelize.test.js
I don't think docs are needed
This commit uses the pg_connection_string package to parse the
connection string if the dialect is postgresql. This is helpful because
it automatically handles reading SSL certs that are specified in the
connection string.
As part of this, support was added for the `options` URL parameter,
which allows arbitrary session variables to be configured in the
connection string.
fixes https://github.com/sequelize/sequelize/issues/13672
None
> feat(postgresql): easier SSL config and options param support

- lib/dialects/abstract/query-generator.js
- lib/model.js
- test/unit/sql/select.test.js
The select query raises ambiguity errors when I join two tables that have the same attribute/column names which contain a dot(".") in them.
This PR fixes it by provides a new option; 
`options.dotnotation = true`
> feat: option for attributes having dotnotation

- types/lib/sequelize.d.ts
- types/test/sequelize.ts
https://github.com/sequelize/sequelize/blob/51bc05ae806ee11d36764bdafb4e4645d00e93be/lib/sequelize.js#L1257-L1264
These methods are not only static member of Sequelize. So I made this PR and trying to keep the definition and behavior consistent.
> fix(types): add instance member declaration

- docs/manual-groups.json
> hotfix(docs): add aws-lamda route

- types/lib/model.d.ts
- types/test/model.ts
_Closes #13683_
This PR makes sure we still allow for the old behavior where we allow any `object` type to be returned for the `.toJSON()` function, but also allows adding the custom type. This allows for backwards compatibility.
> fix(types): allow override json function with custom return type

- .github/workflows/ci.yml
This PR adds a check to generate the docs. Locally I ran `yarn docs` on https://github.com/sequelize/sequelize/pull/12642 and it failed. So this should prevent us from merging it in the future.
Fixes https://github.com/sequelize/meetings/issues/10
> ci(docs): add doc generation to checks

- package.json
The file is not called requireHook anymore, but registerEsbuild. Thanks to @AllAwesome497 for figuring it out
> test: fix mocha

- test/unit/errors.test.js
The remaining checks that fail for postgres and sqlite are due to https://github.com/sequelize/sequelize/pull/13594 
The one test that failed on MySQL 8 can be ignored, that one happens quite often and we are not yet sure why
@slickmb we had an issue that the tests in the checks were not actually running. This is fixed now and we noticed some failing tests for your PR on postgres and sqlite. Any idea on how to solve them?
> test: fix failing stack trace test

- lib/dialects/abstract/query-generator.js
- lib/dialects/mssql/query-generator.js
- lib/dialects/mssql/query.js
- lib/dialects/mysql/query-interface.js
- lib/dialects/postgres/query.js
- lib/model.js
- test/integration/model/upsert.test.js
- fix(upsert): fall back to DO NOTHING if no update key values provided (#13594)
- fix: remove erroneous .length in _.isEmpty
This reapplies the original fall back to DO NOTHING commit, but with an additional fix for the broken unit tests.
> fix(upsert): fall back to DO NOTHING if no update key values provided

- types/lib/model.d.ts
- types/test/where.ts
Added type `Col` for whereOperators: eq, lt, lte, gt, gte. Closes: #13701
> fix(types): add Col to where Ops

- lib/dialects/mariadb/data-types.js
- lib/dialects/mysql/data-types.js
unnecessary warning when getting data with DATE dataTypes attributes.
> fix(data-types): unnecessary warning when getting data with DATE dataTypes

- lib/data-types.js
A minor fix in the examples for GeoJson format
closes: #13671
> fix(example): fix coordinates format as per GeoJson

- .gitignore
- docs/manual/other-topics/dialect-specific-things.md
- lib/dialects/postgres/connection-manager.js
- lib/sequelize.js
- test/integration/associations/scope.test.js
- test/integration/dialects/postgres/connection-manager.test.js
- types/lib/sequelize.d.ts
Please make sure to review and check all of these items:
Move `clientMinMessages` out of general option for decouple dialect purpose.
> refactor(postgres): move `clientMinMessages` from general to pg options

- lib/dialects/postgres/connection-manager.js
- types/lib/sequelize.d.ts
Follow-up to #13720.
It will render warnings when the option is used and point out the deprecation.
> docs(postgres): warn about deprecated clientMinMessage option

- .github/workflows/ci.yml
- README.md
- build.js
- docs/index.md
- package.json
This PR is dropping support for Node 10. Should we go straight to the latest LTS version of Node 12 or is any version >= 12 fine?
> ci(node): drop support for node 10

- docs/esdoc-config.js
- esdoc-ts.js
Adds partial support for TS files in generated docs.  This isn't the ideal solution but it unhides TS files from docs for now.
In #13569 I forgot to add support for generated docs, so TS files were being omitted from documentation.
Properly support TS docs (eg function overloading, inferring types from type annotations), possibly switch to an alternate tool for generated tooling.  
Unsure how the current theme will be translated or if it even will at all; its missing support for some TS features like function overloading which is better shown by tools and themes built around TS.
> docs(typescript): add plugin to parse TS files

- lib/dialects/sqlite/query.js
- package.json
- yarn.lock
As per https://github.com/sequelize/umzug/pull/529 we move to vscode's version of sqlite3 which does not have the node-gyp version with a vulnerable tar dependency; https://github.com/mapbox/node-sqlite3/issues/1493#issuecomment-978912655
> build(sqlite): update node-sqlite3 without tar vulnerability

- types/index.d.ts
- types/lib/model.d.ts
- [n/a] Have you added new tests to prevent regressions?
- [n/a] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
Replacement PR of https://github.com/sequelize/sequelize/pull/13796
Attempt to fix https://github.com/sequelize/sequelize/issues/13791
There was an issue in PR https://github.com/sequelize/sequelize/pull/13731 where `Op` was exported using `export =` but was imported using `import Op from './operator'` which is not compatible (source https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require).
This is a simple fix that changes the imports back to `import Op = require('./lib/operators')` syntax.
This one does not include any lint correction …
> fix: fix invalid ts import style of lib/operators

- package.json
- test/registerEsbuild.js
- test/unit/deep-exports.test.js
- test/unit/dialects/abstract/query.test.js
- test/unit/dialects/mssql/query.test.js
- test/unit/dialects/mysql/query.test.js
- test/unit/dialects/snowflake/query.test.js
- [N/A] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [N/A] Did you update the typescript typings accordingly (if applicable)?
Fixes https://github.com/sequelize/sequelize/issues/13787
The issue was that once `exports` is defined in package.json, node uses it as the source of truth for all valid exports of a package.
I've configured `exports` to replicate how the imports worked in v6.  
I also had to remove the alias in `registerEsbuild.js` as it was redundant with `exports`.  
It also matches reality better as the tests use the same export definition as the published build. :)
I recommend changing the export declaration for V7, see below
---
In v7, we could change the export …
> fix: allow deep imports

- package.json
- yarn.lock
Earlier versions of retry-as-promised rely on the package any-promise which depends on a global `window` object. This change makes Sequelize a bit easier to use on node environments, especially with server side rendering like next.js
> meta(deps): Update retry-as-promised to 5.0.0

- lib/dialects/postgres/data-types.js
- test/integration/dialects/postgres/dao.test.js
Closes #13804
This change is also realated with #13204 PR #13210. It not caused by it but the source of both bugs is the same, improper handling of ARRAY[ENUM] on postgres. In this scenario is only when we are using schemas.
> fix(13804): use schema for ARRAY(ENUM) type name

- lib/operators.ts
- types/index.d.ts
- types/lib/model.d.ts
- [n/a] Have you added new tests to prevent regressions?
- [n/a] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
Closes #13791
Fix turned out more complicated than previously thought (https://github.com/sequelize/sequelize/pull/13797)
Current solution is definitely a hack to please both TypeScript and Node.
I think the TypeScript migration is going to keep breaking things due to how `esbuild` transpiles ESM. I've opened an issue regarding this as the decision will impact this PR https://github.com/sequelize/sequelize/issues/13806
> Fix TS support for operators.ts

- lib/dialects/abstract/query-generator.js
- lib/dialects/abstract/query-interface.js
- lib/utils/class-to-invokable.ts
- test/unit/dialects/abstract/query-interface.test.ts
- types/lib/query-interface.d.ts
- types/test/query-interface.ts
In some version of v6, the queryInterface apparently lost `quoteIdentifier` and `quoteIdentifiers` which is hindering people to update to v6 (https://github.com/sequelize/sequelize/issues/12627). Interestingly, the types haven't been updated accordingly. So there is a certain discrepancy. This PR is recovering the methods.
> Bring back quoteIdentifier(s) to queryInterface to ease migration to v6

- .github/workflows/ci.yml
The notification flow can be triggered by sending a dispatch event to API including the release's ID. This change will automatically send such and event at the end of the release process.
> ci(release): dispatch custom event to trigger notifications

- lib/dialects/mssql/async-queue.ts
Fix unable to start mysql docker in test due to circular reference
Why this happen? Because on this line, it attempts to export an Error that's outside `errors` dir and this outside AsyncQueueError has circular reference to `errors/index.ts`
https://github.com/sequelize/sequelize/blob/8cdce6aeb32b09e4bc1359250efcfacc6742501f/lib/errors/index.ts#L36
It's a bit weird to me that `errors/index.ts` attempts to expose an Error that's outside this dir, maybe it shouldn't do it in the first place but removing it will be a breaking change so I'll not change it in this PR. Taking it out requires a different discussion.
Node: v14.18.1
run the follow command
```
npm run start-mysql 
```
and received the following error
```
class …
```
> fix(mssql/async-queue): fix unable to start mysql due to circular ref

- .github/workflows/ci.yml
Currently we run checks twice if the branch for the PR is in the sequelize repo. This would reduce the checks to be done on all Pull Requests and the pushes to the main/v6/v7 branches.
When a Pull Request has a new commit it will still run the checks.
> build(ci): only run on pushes to main/v6/v7

- package.json
v6 and v7 have been publishing updated versions to the default `latest` tag and this should correct that.
Documentation: https://semantic-release.gitbook.io/semantic-release/usage/workflow-configuration#channel
Evidence:
```
$ npm dist-tag ls sequelize
latest: 6.12.4
v4: 4.44.4
v5: 5.22.5
```
This means that anyone installing with `npm i sequelize@latest` will get alpha and beta versions (e.g., `7.0.0-alpha.3`) when they just happen to be the latest published versions.
> fix: semantic-release should not push beta or alpha to default channel

- .github/workflows/ci.yml
Introduces extra stages to the GitHub Actions CI workflow. Should limit the time needed to check on PRs that are obviously failing (like we had with the esbuild)
One thing that's not clear from the picture is that the test-mysql-mariadb is not dependent on docs, docs goes directly to release as you can see here; https://github.com/sequelize/sequelize/actions/runs/1637499004
> build(ci): add extra stages to ci checks

- lib/dialects/mssql/connection-manager.js
- [√] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [√] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [√] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)?
fix sequelize pool doesn't take effect in dialect "mssql"
please refer issue https://github.com/sequelize/sequelize/issues/13865 for detail info
> fix(dialect): sequelize pool doesn't take effect in dialect "mssql" with new tedious version v13.1.0

- types/lib/model.d.ts
- types/test/count.ts
- [n/a] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
Closes #13871
Current typings state that count with grouping returns an object `{ [columnName: count] }` when in reality something like this:
returns this:
An array where each entry is an object with column -> column value of the group, plus a `count` property.
`count.test.js` backs this, so it's only a typing issue.
---
I also noticed `Model.count({ group: ['count'] })` is going to return a broken result. I've added it to my [future improvements list](https://gist.github.com/ephys/50a6a05be7322c64645be716fea6186a).
> fix(model): fix count with grouping typing

- types/lib/associations/has-many.d.ts
- types/test/e2e/docs-example.ts
- types/test/models/UserGroup.ts
- types/test/typescriptDocs/ModelInit.ts
When using `HasManyCreateAssociationMixin `, and similar methods, Sequelize automatically sets the FK value using the source key from the source model, as well as attributes used in the scope, so the `create*` mtheods shouldn't allow to specify these values.
I couldn't think of an automatic way to do this so i added new generic options, but i made them optionals to keep it backwards compatible (though i'm not super convinced the FK generic should be optional).
Didn't do it for all the association types because i wanted to get some feedback first, to make sure this approach makes sense.
Related to https://github.com/sequelize/sequelize/pull/13685/files#r777743536
> fix(types): omit FK and scope keys in HasManyCreateAssociationMixin

- LICENSE
License notice contributors when it's likely to be authors or "The Team Name"
as this part from MIT LICENSE mentioning too:
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
***AUTHORS*** OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
also optionally we can add AUTHORS.md file to list all the authors (contributors) in Sequelize or change it to Team Name instead (which is Sequelize Organization or Sequelize).
> docs(license): change contributors to authors

- lib/dialects/abstract/query.js
- lib/utils.js
- package.json
- test/integration/sequelize/query.test.js
- test/unit/dialects/abstract/query.test.js
- [n/a] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [n/a] Did you update the typescript typings accordingly (if applicable)?
Closes https://github.com/sequelize/sequelize/issues/13724
There is an issue where `AbstractQuery#_logQuery` crashes when it receives a `bigint` and `logQueryParameters` is true due to `JSON.stringify` being unable to stringify bigints (related to https://github.com/tc39/proposal-bigint/issues/24).
> fix _logQuery crashing when logging bigints

- lib/dialects/abstract/query-interface.js
- lib/dialects/mssql/connection-manager.js
- lib/dialects/postgres/query-generator.js
- test/unit/dialects/postgres/query-generator.test.js
This is a follow up to the [feature request](https://github.com/sequelize/sequelize/issues/13901).
On `removeIndex` it now extends the `options` object
to take in a new attribute, `concurrently`, which
will ensure that the the SQL statement being run
includes `DROP INDEX CONCURRENTLY`...
Having this is nice so developers can use the ORM settings
when dropping an index, safely, instead of having to write
raw SQL.
`concurrently` is a supported attribute on addIndex
Closes https://github.com/sequelize/sequelize/issues/13901
> feat(postgres): drop indices concurrently in Postgres

- docs/manual/core-concepts/assocs.md
This address #11847 partially at least - I'm not sure where else it should be documented.
> docs: `joinTableAttributes` in `belongsToMany` mixin

- types/lib/sequelize.d.ts
Fix missing `<M>` association in `ModelOptions` argument in `Sequelize.define`method
Closes #13906
> fix(sequelize.d) fix type of `options` arg in `Sequelize.define` method

- lib/sequelize.js
- test/integration/sequelize.test.js
Add mariadb support in Sequelize.set function
https://github.com/sequelize/sequelize/issues/13920
> feat(mariadb): add mariadb support in Sequelize.set function

- package.json
- yarn.lock
~We should be able to remove this within a week or so. Not entirely sure why there are so many changes to yarn.lock but I removed the version in main and the node_modules folder and reinstalled everything~
~https://snyk.io/blog/open-source-npm-packages-colors-faker/~
EDIT: it seems that by updating the yarn.lock file we already got the versions of dependencies that pin colors so that's the only thing needed. We might want to look into why there are so many changes for the file even with renovate. Maybe we can find a way to automatically update the entire yarn.lock file every week or so since we use it in a locked state for our CI
> build(deps): update yarn.lock file

- docs/manual/core-concepts/model-querying-finders.md
- package.json
- types/lib/model.d.ts
- types/test/model-count.ts
- types/test/model.ts
> fix(model.d): fix type for `count` and `findAndCountAll`

- types/lib/data-types.d.ts
- types/lib/query-interface.d.ts
- types/test/data-types.ts
- types/test/query-interface.ts
This is a very small PR to improve the typings to `bulkInsert` and the `JSON`/`JSONB` data types.
**Motivation:** I have a typescript seeders file that is seeding some JSONB columns in a postgres database. The seed file uses `queryInterface.bulkInsert` to insert a bunch of rows read from a file. But since `queryInterface` does not know the model column types, it does know to convert a few specific columns to JSONB. It was suggested in https://github.com/sequelize/sequelize/issues/8310#issuecomment-430287656 to pass `attributes` as a 4th arg to `bulkInsert`. But the existing types for `attributes` seems to be incorrect. (Additionally I discovered `new Sequelize.JSONB()` was throwing a "not constructable" type error.)
*PS: I'm …
> fix(types): fix QueryInterface#bulkInsert attribute arg type

- .husky/commit-msg
- package.json
Per #13952, If we fail a commit message, we basically throw it away, which is
frustrating if the commit message was more than trivial, which good
commit messages often are.
Instead, offer the developer a command to recover and re-edit their
commit message.
> fix: don't discard commit message on lint fail

- .github/workflows/ci.yml
- docs/manual/other-topics/typescript.md
- [no, the opposite actually] Have you added new tests to prevent regressions?
- [n/a] Did you update the typescript typings accordingly (if applicable)?
- [n/a] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
Follow-up to https://github.com/sequelize/meetings/issues/6#issuecomment-1013081721
This PR drops support for TypeScript < 4.1 and documents our TS support policy.
This release should cause a SemVer MINOR bump.
> feat(types): drop TypeScript < 4.1

- docs/manual/other-topics/upgrade-to-v7.md
I did not realize #13951 was a breaking change. https://github.com/sequelize/sequelize/issues/14003 reported breakage following that change.
PR https://github.com/sequelize/sequelize/pull/14004 rolls back the change in v6.
We're keeping the change in v7, and this PR documents the change in `upgrade-to-v7.md`.
> docs: document breaking change from #13951

- .github/workflows/ci.yml
CI PR to stop the CI from testing PRs targetting v6 twice.
This is going to trigger a release. I don't know if the release will be aborted since the only change is tagged a build.
> build(ci): don't run tests twice on v6 PRs

- test/unit/sql/where.test.js
- types/lib/model.d.ts
- types/lib/sequelize.d.ts
- types/test/connection.ts
- types/test/findOne.ts
- types/test/infer-attributes.ts
- types/test/models/UserGroup.ts
- types/test/sequelize.ts
- types/test/where.ts
This PR backports to v6:
- https://github.com/sequelize/sequelize/pull/13983
- https://github.com/sequelize/sequelize/pull/13990
- https://github.com/sequelize/sequelize/pull/14018
This PR should not be squashed, for proper changelog generation. I've kept the commits clean :)
> backport TS PRs to V6

- .github/workflows/stale.yml
It's just a stupid label, doesn't serve a purpose in my opinion.
> ci: ignore PRs for stale action

- src/sequelize.js
- test/unit/sequelize.test.ts
Alternative PR  to https://github.com/sequelize/sequelize/pull/14071 that fixes the path to package.json in v6 & adds a unit test for it
> fix: correct path to `package.json` in Sequelize.version

- docs/ROUTER.txt
- docs/css/style.css
- docs/esdoc-config.js
- docs/manual/core-concepts/assocs.md
- docs/manual/core-concepts/getting-started.md
- docs/manual/core-concepts/model-basics.md
- docs/manual/core-concepts/model-instances.md
- docs/manual/core-concepts/model-querying-basics.md
- docs/manual/core-concepts/raw-queries.md
- docs/manual/other-topics/aws-lambda.md
- docs/manual/other-topics/connection-pool.md
- docs/manual/other-topics/hooks.md
- docs/manual/other-topics/indexes.md
- docs/manual/other-topics/query-interface.md
- docs/manual/other-topics/scopes.md
- docs/transforms/group-data-types.js
Cherry picks https://github.com/sequelize/sequelize/pull/14094 in v6
Fixes https://github.com/sequelize/sequelize/issues/14083 too
> build: generate jsdoc from src instead of lib (v6)

- src/dialects/postgres/query.js
I have tested against local PostgreSQL database with pg-native plugin enabled.
Fixes https://github.com/sequelize/sequelize/issues/14086
> fix(postgres): correctly re-acquire connection while using pg-native

- src/sequelize.d.ts
Type adjustments according **'replication'** option.
I am trying do setup *replication* option asynchronous using for it hook [beforeConnect](https://sequelize.org/master/manual/hooks.html). According types definition hook receive as parameter [Config](https://github.com/sequelize/sequelize/blob/main/src/sequelize.d.ts#L690). As You can see there is no *replication* defined for [Config Interface](https://github.com/sequelize/sequelize/blob/main/src/sequelize.d.ts#L148), which is wrong.
As result in typescript project, when we try define replication  asynchronous in hook
```javascript
const myReplicationConfig = {...};
new Sequelize({
...defautlOptions
hooks: {
beforeConnect: (config: DeepWriteable<Config>) => {
// ts error here >>>
// Type 'false | ReplicationOptions' is not assignable to …
```
> fix(types): update 'replication' option property

- docs/manual/other-topics/dialect-specific-things.md
Fixes #14056 by clarifying that pg@>=8.2.x needs to be used with Node 14 as mentioned in the documentation linked. I removed the minimum version for now but that can return if we also know our CI policy for that (like if we want to run tests on pg@7 as well or not)
> docs(postgres): clarify pg version for Node >=14

- package.json
This should fix the publishing error we got on v7
> meta: set access to public for publishing

- src/dialects/abstract/query-interface.d.ts
- test/types/query-interface.ts
Corresponding JavaScript file [query-interface.js](https://github.com/sequelize/sequelize/blob/main/src/dialects/abstract/query-interface.js#L808) doesn't require model attribute to be passed. Instead it is passed inside `options`.
> fix(types): drop excess argument for upsert

- src/model.d.ts
Needed to use this type but it wasn't exported. And since the rest of the types are, it feels like it would be more consistent to also export this one
> fix(types): export `GroupedCountResultItem` interface

- src/utils.d.ts
- test/types/create.ts
PR https://github.com/sequelize/sequelize/pull/13909 introduced a change where creation attributes that accept `undefined` were also as being `optional` in typings.
The way this change was implemented is incompatible with TS unions and broke with the following example https://github.com/sequelize/sequelize/issues/14129
closes https://github.com/sequelize/sequelize/issues/14129
I'm bringing this change in v6 only for backward compatibility. I will bring a different solution in v7, see https://github.com/sequelize/sequelize/pull/14091#issuecomment-1046227092 for more
> fix(types): support union in CreationAttributes

- .github/workflows/ci.yml
Proposal PR to disable running the CI on main.
As all changes on `main` are done through PRs, we already know the the main branch passes the CI. 
Nothing is released from the main branch either.
Disabling the CI on the main branch would reduce how many actions are being run concurrently and allow PRs to run faster.
I may be missing something so feel free to reject this PR
> ci: disable CI on main

- .github/workflows/auto-remove-awaiting-response-label.yml
This PR aborts the 'remove awaiting response' action before its environment is set up if the issue/pr doesn't have the label the CI tries to remove.
I'm not sure how to test this without merging it
> ci: skip 'rm awaiting response' if label is absent

- src/model.d.ts
- src/model.js
- test/integration/model/scope/destroy.test.js
- test/integration/model/scope/find.test.js
- test/integration/model/scope/findAndCountAll.test.js
- test/integration/model/scope/update.test.js
- test/support.js
- test/unit/model/include.test.js
- test/unit/model/scope.test.js
Issues related:
- https://github.com/sequelize/sequelize/issues/11588
- https://github.com/sequelize/sequelize/issues/10873
Pull request that tried to solve these issues:
- https://github.com/sequelize/sequelize/pull/11805
This pr adds the following elements:
- A way to merge scopes with where clauses using the `AND` operator instead of overwriting it with the last value. It supports merging attributes, `[Op.and]` and `[Op.or]`. 
- The flag `mergeWhereScopesWithAndOperator` to enable this behavior for a model or all the models.
Examples:
```js
// Attributes merging
// Scope 1
whereAttributeIs1: {
where: {
field: 1,
},
},
// Scope 2
whereAttributeIs2: {
where: {
field: 2,
},
}
// Current behavior (without mergeWhereScopesWithAndOperator)
myModel.scope('whereAttributeIs1', …
```
> feat: merge scope where conditions using the and operator

- .github/workflows/ci.yml
- docs/manual/other-topics/typescript.md
TypeScript 4.2 has been out for a little over a year now.
Based on our policy that offers one year of support for a given TypeScript version, we can now stop testing against TypeScript 4.1 & 4.2.
We now only officially support TypeScript 4.4, 4.5, and 4.6
> feat: stop testing against TypeScript < 4.4

- test/integration/data-types.test.js
- test/integration/error.test.js
- test/integration/model.test.js
- test/integration/pool.test.js
- test/integration/query-interface.test.js
- test/integration/sequelize/query.test.js
Signed-off-by: Mark Irish <mirish@ibm.com>
Fixes https://github.com/sequelize/sequelize/issues/14196
I wasn't sure if this should only apply to current instances where multiple dialects are checked, or if single dialects should be checked as well (more function overhead, but future-proof changes?)
> refactor: convert multiple dialect checks to use Array.includes

- src/model.d.ts
- src/model.js
- test/support.js
- test/unit/model/scope.test.js
This pr is meant for the v6 of Sequelize. It has been motivated by this pr:
- https://github.com/sequelize/sequelize/pull/14110
This pr introduces the following elements:
- A way to merge scopes with where clauses using the `AND` operator instead of overwriting it with the last value.
- The flag `whereMergeStrategy` to choose between the `and` strategy and the `overwrite` one.
> feat(scopes): add whereScopeStrategy to merge where scopes with Op.and

- docs/manual/other-topics/scopes.md
This pr updates the manual documentation when merging multiple where scopes with the flag `whereMergeStrategy` set to `and`. 
The described changes have been made in:
- https://github.com/sequelize/sequelize/pull/14152
Note: For the v7 documentation, please refer to the following pr that updates the documentation on the same behavior:
- https://github.com/sequelize/sequelize/pull/14202
> docs: document scope whereMergeStrategy option

- docs/manual/other-topics/scopes.md
- docs/manual/other-topics/upgrade-to-v7.md
This pr updates the manual documentation when merging multiple where scopes. 
The described changes have been made in:
- https://github.com/sequelize/sequelize/pull/14152
Note: For the v6 documentation, please refer to the following pr that updates the documentation on the same behavior:
- https://github.com/sequelize/sequelize/pull/14201
> docs(scopes): update manual documentation on where scope merging

- docs/manual/other-topics/migrations.md
Update field to **type** instead of **indicesType** since it was renamed since v5  as it says here on issue _[#10831](https://github.com/sequelize/sequelize/issues/10831) Sequelize v5 renames addIndex(... { indicesType: ...}) to addIndex(... { type: ...})_
> docs: update renamed field

- test/unit/sql/data-types.test.js
This PR is related to documentation PR https://github.com/sequelize/website/pull/11
It adds a small set of DataType unit tests that were previously missing.
They're still lacking but cleaning up the DataTypes is something that can be done in a future PR (unless someone wants to take up the torch).
> test: add unit tests for every datatype

- .eslintrc.js
This PR makes our eslint config accept the [`@typeParam`](https://typedoc.org/guides/doccomments/#%40typeparam-%3Cparam-name%3E-or-%40template-%3Cparam-name%3E) and [`@internal`](https://www.typescriptlang.org/tsconfig/stripInternal.html) tags valid in typedoc
This PR is part of a series of PR that reduce the size of https://github.com/sequelize/sequelize/pull/14280
> build: accept `@typeParam` and `@internal` tags in  typedoc

- test/integration/sequelize/query.test.js
I noticed in #14284 that a test failed because it was returning UniqueConstraintError instead of DatabaseError. Then I tested the others in that group as well and they all return what they also do for other dialects. So that was probably fixed in a later stage of the db2 PR.
> test(db2): remove db2-specific expectations

- docs/transforms/header-customization.js
Fixes this comment https://github.com/sequelize/website/issues/43#issuecomment-1086796681
This PR replaces the dead 'API Reference' link with `<a href="/docs/v6/intro/" data-ice="manualHeaderLink" class="api-reference-link">Guides</a>`
> docs: fix dead link in API reference

- .github/workflows/ci.yml
- test/integration/transaction.test.js
Same PR as https://github.com/sequelize/sequelize/pull/14314, but for v7
With one difference: CI tests are now run against latest mariadb 10.5 again
> test: disable deadlock test for mariadb 10.5.15

- docs.sh
- package.json
- src/model.js
This PR modifies model.js to use syntax compatible with esdoc. This brings the Model api reference page back.
It also ensures the `docs` script fails if it's unable to parse a file again
Related to https://github.com/sequelize/website/issues/43
> docs: restore Model api reference & make fail on error

- src/dialects/abstract/query-generator.js
- src/index.d.ts
- src/index.mjs
- src/model.js
- src/sequelize.js
- src/utils/model-utils.ts
- test/unit/utils/model-utils.test.ts
This PR adds two new utility methods:
- `isModelStatic`: returns true if the value is a subclass (not instance) of model
- `isSameInitialModel`: returns true if two models are variants of the same model
Both were initially created for https://github.com/sequelize/sequelize/pull/14280, but this PR also refactors the existing codebase to use them where it makes sense
> feat: add `isModelStatic`, `isSameInitialModel`

- src/model.d.ts
- src/model.js
- test/integration/model/schema.test.js
- test/support.d.ts
- test/unit/model/schema.test.ts
- test/unit/model/scope.test.ts
As a follow up to https://github.com/sequelize/sequelize/pull/14337. While we're renaming `Model.schema` to `Model.withSchema`, we might as well simplify its API. I changed it from:
```typescript
MyModel.schema('public');
MyModel.schema('public', /* schema delimiter */ '.');
MyModel.schema('public', { schemaDelimiter: '.' });
```
to
```typescript
MyModel.withSchema('public');
MyModel.withSchema({ schema: 'public', schemaDelimiter: '.' });
```
Not a breaking change because `.schema` keeps its old API and `.withSchema` hasn't been released yet
> feat: simplify withSchema API

- ENGINE.md
- README.md
This PR removes the Supported Database table from ENGINE.md, redirecting the user to https://sequelize.org/releases/ instead, to deduplicate the information that we have to maintain :)
> docs: redirect engines.md to our website

- .github/workflows/stale.yml
This exempts the RFC labels from being marked as stale.
> meta(stale): exempt RFC issues

- renovate.json
Renovate uses `chore` by default which we do not allow in the commit message conventions. As mentioned by @ephys in #14392
> build(renovate): make Renovate use build commit scope

- test/integration/instance.test.js
- test/integration/model/upsert.test.js
#14390 is currently failing due to https://github.com/sinonjs/fake-timers/pull/426
This should solve it. I did update the `Model upsert works when two separate uniqueKeys are passed` test to remove the timing check since that is not part of what is being tested.
As a future refactor we should look into the usage of fakeTimers and see if they are not used too often
> test: remove additional fake timer

- .github/workflows/ci.yml
This PR makes sure PRs only run one workflow at a time by cancelling the previous workflow if a new commit is added.
This doesn't impact doing multiple pushes to the v7 branch, only PRs are impacted.
I also removed the mention of the v6 branch in the workflow triggers, as the configuration present in the v6 branch is used instead.
> ci: cancel old run on new push in PRs

- docs.sh
- src/utils.js
Closes https://github.com/sequelize/sequelize/issues/14509
This PR fixes the [JSDoc comment](https://github.com/sequelize/sequelize/pull/14472#discussion_r873211094) that causes esdoc to crash.
I also updated `docs.sh` to ensure such an error would cause the script to exit with a non-zero code. I can't guarantee it will catch every future esdoc crash, but it will catch this one if it happens again.
> build: fix esdoc

- test/integration/transaction.test.js
See https://github.com/sequelize/sequelize/issues/14174 for context.
We already disabled this [deadlock test for MariaDB 10.5.15](https://github.com/sequelize/sequelize/pull/14315), but the exact same issue now occurs with MySQL 8.0.29.
This PR disables the deadlock test altogether (it only ran for MariaDB, MySQL). 
While it is unfortunate that we have not managed to understand why the deadlock did not occur anymore, this test is blocking the whole CI and we have looked into it extensively.
This PR targets v6.
> test: disable mysql/mariadb deadlock test

- src/utils/sql.ts
- test/unit/utils/sql.test.js
Closes: https://github.com/sequelize/sequelize/issues/14517
Other bug report: https://github.com/sequelize/sequelize/pull/14472#issuecomment-1129661928
This PR fixes the replacement parser to replace them in the following two queries:
```sql
-- replacements were not transformed in arrays
SELECT * FROM users WHERE id = ARRAY[:id]::int[];
SELECT * FROM users WHERE id = ARRAY[?]::int[];
```
```sql
-- replacements were not transformed if followed by ';'
SELECT * FROM users WHERE id = :id;
SELECT * FROM users WHERE id = ?;
```
> fix: accept replacements in `ARRAY[]` & followed by `;`

- .github/workflows/ci.yml
- src/sequelize.d.ts
- src/sequelize.js
- src/utils/url.ts
- test/unit/configuration.test.ts
SQLite's unit tests were missing from the CI.
This PR enables these unit tests & fixes a (unreleased) regression introduced in https://github.com/sequelize/sequelize/pull/14501
> ci: enable sqlite unit tests

- src/utils/sql.ts
- test/unit/utils/sql.test.ts
Ports https://github.com/sequelize/sequelize/pull/14518 to v7.
`$bind` parameters can be followed by `;` but, unlike `:replacements` cannot be used inside of an array literal.
With this PR, these are all processed correctly:
```sql
SELECT * FROM users WHERE id = ARRAY[:id]::int[];
SELECT * FROM users WHERE id = ARRAY[?]::int[];
SELECT * FROM users WHERE id = :id;
SELECT * FROM users WHERE id = ?;
SELECT * FROM users WHERE id = $bind;
```
> fix: expand where `$bind` & `:replacements` can be used

- src/dialects/abstract/connection-manager.d.ts
- src/dialects/abstract/connection-manager.js
- src/sequelize.js
- src/transaction.js
- test/integration/sequelize.transaction.test.js
This is an attempt at fixing https://github.com/sequelize/sequelize/issues/10858. I don't know if it'll completely fix it, so in doubt I'm not closing that issue.
If an error occurred during a transaction commit or rollback (such as a network error), Sequelize would call `transaction.cleanup()`, which released the connection to the pool.
The problem is that if an error occurred, we cannot guarantee that the transaction did actually commit or roll back. It may still be active. Releasing the connection to the pool does not kill the connection, and it will end up used by other queries - unknowingly running in another transaction.
This PR changes that by taking the drastic approach of killing the connection if an error occurred during `COMMIT TRANSACTION` or `ROLLBACK TRANSACTION`.
> fix: kill connection on commit/rollback error

- test/integration/dialects/postgres/dao.test.js
- User.sync(), which references the schema, was executed before the schema exists
- add an `await` before the schema is created to enforce sequencing/synchronocity
Subtle style change:
- remove word 'even' from test description
Addresses only PostgreSQL-portion of issue #14161
> fix(postgres-test): insert record with enums array into schema (#14161)

- src/model.d.ts
Fixes a link directive so that it correctly displays as it currently does not link to the correct attribute.
> docs: fix typedoc link to `Sequelize#define`

- src/dialects/abstract/index.ts
- src/dialects/abstract/query-interface.js
- src/dialects/db2/index.js
- src/dialects/db2/query-generator.js
- src/dialects/db2/query-interface.js
- src/dialects/mssql/index.js
- src/dialects/mssql/query-generator.js
- src/dialects/mssql/query-interface.js
- src/dialects/postgres/query-generator.js
- src/dialects/sqlite/query-generator.js
- src/model.d.ts
- src/model.js
- src/utils/string.ts
- test/integration/associations/belongs-to-many.test.js
- test/integration/associations/has-many.test.js
- test/integration/dialects/mariadb/dao-factory.test.js
- test/integration/dialects/mysql/dao-factory.test.js
- test/integration/model.test.js
- test/integration/model/sync.test.js
- test/integration/query-interface.test.js
- test/integration/query-interface/createTable.test.js
- test/integration/query-interface/removeColumn.test.js
- test/unit/associations/belongs-to-many.test.ts
- test/unit/dialects/db2/query-generator.test.js
- test/unit/dialects/sqlite/query-generator.test.js
- test/unit/model/indexes.test.js
- test/unit/sql/index.test.js
Closes https://github.com/sequelize/sequelize/issues/12889
This PR fixes the following bugs:
- DB2 forced columns that had a unique index to be non-null, this has been removed (you still need to make your column non-null, but we don't silently make that happen).
- When defining an index through the `indexes` option on a model, then calling `sync()`, the dialect would *modify* the model to mark all attributes that are part of the index as unique. (DB2 only)
- Calling `sync({ alter: true })` with an attribute that has `unique: true` set would generate a query such as `ALTER TABLE users ALTER COLUMN emails SET VARCHAR UNIQUE`. DB2 and MSSQL do not allow `UNIQUE` to be specified there. This has been changed to use a separate `CREATE INDEX` query.
- SQLite supports specifying an index name …
> feat: fix multiple bugs related to `sync()` and indexes. Add `Model.getIndexes()`

- src/model.js
- test/unit/model/find-one.test.js
Remove conditional logic for adding `LIMIT 1` to `findOne` queries. Instead, always add it.
* Foreign keys should be used to ensure data integrity, and should not impact query performance.
* It's unclear how omitting `LIMIT 1` benefits any query that should return a single result.
* Models are imperfect representations of schema, making unnecessarily assumptions about their correctness can lead to severe issues.
* see #14548
> feat: Always add LIMIT 1 to `findOne` queries

- src/dialects/abstract/query-generator.js
- src/dialects/postgres/query-generator.js
- test/unit/dialects/postgres/query-generator.test.js
- test/unit/sql/add-column.test.js
- test/unit/sql/remove-column.test.js
This has already been merged into `main` https://github.com/sequelize/sequelize/pull/14634
This is an attempt at fixing a bug where the Postgres Query Generator does not respect a custom schema name if it is provided.
https://github.com/sequelize/cli/issues/284#issuecomment-573351082 on https://github.com/sequelize/cli/issues/284 describes the problem in detail.
> fix(postgres): use schema set in sequelize config by default

- src/data-types.d.ts
[The actual file(data-types.js)](https://github.com/sequelize/sequelize/blob/main/src/data-types.js#L585
) says JSON type available for MySQL, Postgres, and SQLite. But the `d.ts` file says JSON is only available in Postgres.
Is this too tiny problem to open PR?
> docs: fix comment in data-types.d.ts

- src/dialects/abstract/query-generator.js
- test/integration/instance/save.test.js
- test/integration/model/create.test.js
- test/unit/dialects/abstract/query-generator.test.js
Fixes improper escaping of multiple dollar signs in strings sent to `sequelize.fn` as detailed in https://github.com/sequelize/sequelize/issues/14601. Also removes some trailing whitespace, since my editor did it automatically 🤷
> fix: multiple $ in `fn` args now properly escaped

- CONTACT.md
In order to react to pressing concerns swiftly, we are swapping the contacts with the core team only
> meta: add core team members to the contacts list

- src/utils/sql.ts
- test/unit/utils/sql.test.ts
This PR is a follow up to https://github.com/sequelize/sequelize/pull/14700 which added support for postgres' E-prefixed strings.
That support now also considers lowercase "e" as a valid prefix for e-prefixed strings
> fix(postgres): treat lowercase e as valid e-string prefix

- src/dialects/postgres/connection-manager.js
This is the corresponding v7 / `main` PR for https://github.com/sequelize/sequelize/pull/14731
Please see that PR for a discussion of the issue.  (tl;dr; There appears to be a brief window immediately after connecting to a Postgres database during which Sequelize may crash if the connection fails.  This change should close that window.)
> fix(postgres): attach postgres error-handler earlier in lifecycle

- src/dialects/postgres/connection-manager.js
We recently observed a crash due to an unhandled `Connection terminated unexpectedly` exception originating from the `pg` library.  As best as I've been able to tell, this _shouldn't_ be possible, and I've had difficulty reproducing it.  
However, upon reading through the current implementation of the Postgres connection-manager, I noticed that we don't immediately attach an error-handler to the `pg` connection.  
Based off of my reading of this code, it actually seems reasonably possible that an error emitted during either of the setup queries could trigger a hard crash.  Moving the error-handler to an earlier phase of the connection's lifecycle should, in theory, make this a bit safer, and guard against any errors that are …
> fix(postgres): prevent crash if postgres connection fails immediately (v6)

- src/dialects/abstract/query.d.ts
- src/dialects/abstract/query.js
- src/dialects/db2/query.js
- src/sequelize.js
- test/integration/sequelize/query.test.js
Accept `queryLabel` as query option (open to alternate names, like `loggingLabel` or just `label`). Extremely useful for labeling queries when query logging is turned on. For example, when I have query logging turned on and I hit an endpoint in one of my applications, a dozen or more queries may show up in the logs. This allows me to provide a name/label so I can quickly jump to the code that produced a given query.
> feat: Accept queryLabel query option for logging.

- src/sequelize.d.ts
- src/sequelize.js
- test/types/connection.ts
- test/types/sequelize.ts
Sequelize passes on all retry options to `retry-as-promised` but the `RetryOptions` type was missing some properties ([reference](https://github.com/mickhansen/retry-as-promised#configuration)). This PR adds the missing properties and updates the necessary documentation.
> fix(types): add missing properties to RetryOptions

- package.json
- yarn.lock
Fixes #14952
The breaking change in v6 of retry-as-promised should not affect sequelize.
> meta: update retry-as-promised

- src/sequelize.d.ts
Target patch releases of #14991
> fix(types): missing type for oracle dialect in v6

- .github/workflows/ci.yml
- src/hooks.d.ts
- src/model.d.ts
- yarn.lock
Sequelize typings are affected in a few places by a TypeScript 4.8 breaking change (https://devblogs.microsoft.com/typescript/announcing-typescript-4-8/#unconstrained-generics-no-longer-assignable-to).
This PR addresses #14934.
> feat(types): add typescript 4.8 compatibility

- src/hooks.d.ts
- test/types/hooks.ts
> fix(types): add missing model hooks types

- .github/workflows/ci.yml
- package.json
- src/hooks.d.ts
- src/model.d.ts
- src/utils/object.ts
- src/utils/sql.ts
- test/support.ts
- yarn.lock
Sequelize typings are affected in a few places by a TypeScript 4.8 breaking change (https://devblogs.microsoft.com/typescript/announcing-typescript-4-8/#unconstrained-generics-no-longer-assignable-to).
The PR brings changes from https://github.com/sequelize/sequelize/pull/14990 (which closes #14934) to `main` branch.
> fix(types): add TypeScript 4.8 compatibility

- renovate.json
Yes, I've tried the scope thing multiple times now but I haven't tried this so hopefully it will work.
I've added the oldest docker-compose files to the ignorePaths so renovate won't update those.
Future PR will add renovate to v6, just like some other CI changes that we've done on main already.
> meta: ignore dependency updates on oldest Docker and use `meta` type

- renovate.json
Delete extra `:`, this is very soft, we missed it
Closes #15025
> meta: renovate typo on ignorePaths

- src/dialects/abstract/query-generator.js
- test/integration/dialects/postgres/query.test.js
Fix for new issue raised at https://github.com/sequelize/sequelize/issues/14723.
Essentially, we weren't pushing the order direction when pushing the alias for the sub-query field. This PR adds logic to do so, as well as tests for ascending/descending subquery ordering with aliases.
> fix(postgres): add custom order direction to subQuery ordering with minified alias

- src/dialects/abstract/query-generator.js
- test/integration/dialects/postgres/query.test.js
As discussed with @evanrittenhouse , this backports #15046 to v6.
> fix(postgres): add custom order direction to subQuery ordering with minified alias (v6)

- renovate.json
For some reason `:semanticCommitTypeAll(meta)` is only for all dependency update PRs, not the lockfile update PR. I hope including both of them will finally work.
> meta: fix commit type for lockfile update PRs

- src/dialects/abstract/index.ts
- src/dialects/db2/query-generator.js
- src/dialects/snowflake/index.js
- src/model.js
- src/utils/dialect.ts
- test/unit/utils.test.js
Part of the PRs split from #14505
I couldn't really find why snowflake doesn't support milliseconds or that it was just an oversight but we can't do integration tests so I'm not risking it.
> meta: make `Utils.now()` and `Utils.toDefaultValue()` accept a dialect

- src/dialects/mariadb/query.js
- test/integration/json.test.js
This PR ports #14800 to `main` and unblocks #14505
> fix(mariadb): do not automatically parse JSON fields

- CONTRIBUTING.md
Corrected `yarn` commands in contributions guidelines pertaining to running databases in Docker (for the purpose of testing). Updated commands now run either the `-oldest` or `-latest` version of a database, with version indicated.
Related to #14737
Closes #15078
> docs: update instructions for running databases in Docker

- src/dialects/snowflake/query-generator.js
- test/unit/dialects/snowflake/query-generator.test.js
**This is an additional PR to merge fix from https://github.com/sequelize/sequelize/pull/14930 (already merged into v7) into v6 branch**
Starting from version 6.20.0 a new method `tableExistsQuery` is introduced and used by the  sequelize`sync` method. Unfortunately this method is implemented in all dialects except snowflake. This causes `snowflake` dialect basically unusable. This PR fixes the issue by adding the implementation of `tableExistsQuery` in snowlake dialect.
> feat(snowflake): Add support for `QueryGenerator#tableExistsQuery`

- src/dialects/sqlite/index.js
This issue was first mentioned by #14965 , SQLite now supports `RIGHT JOIN`s https://www.sqlite.org/releaselog/3_39_3.html. This PR enables RIGHT JOIN support for SQLite.
Closes #14965
> feat(sqlite): enable `RIGHT JOIN` capability for sqlite

- renovate.json
This should theoretically enable automatic merges of renovate PRs. In the main branch protection rules, I have also configured this now. 
I think that might work?
> meta: automatically merge renovate PRs

- renovate.json
Renovate tries to rebase merge its PRs, which we don't allow. This PR changes its configuration to squash & merge instead
Well, turns out this is not strictly needed (https://github.com/sequelize/sequelize/pull/15104), but still good to have as otherwise renovates tries all possible merge options until one works
> meta: make renovate merge using squash

- package.json
Imports of things like 'sequelize/types/hooks' (which is used by sequelize-typescript) is broken when using Typescript's "nodenext" or "node16" module resolution strategies. One could update the imports to 'sequelize/lib/hooks', but doing so breaks the default Typescript module resolution. So projects like sequelize-typescript can't easily make that change.
**Currently anyone using the newer module resolution strategies along with sequelize-typescript have no upgrade path to a version of sequelize without the vulnerability mentioned in #14519** 
This is a different approach to #14719.
Instead of adding hooks to the exports in index.d.ts, we can just add a  "/types/" alias to the exports in package.json. Doing so allows imports of 'sequelize/types/hooks' to properly resolve using both …
> fix(types): expose legacy "types" folder in export alias

- src/model.d.ts
This is the same PR as #15134, but for v6
Closes https://github.com/sequelize/sequelize/issues/15133
> fix(types): fix TS 4.9 excessive depth error on `InferAttributes` (v6)

- CONTACT.md
- CONTRIBUTING.md
- README.md
As discussed, we have to get rid of Heroku and hence swap the invite links with the direct Slack powered feature.
> meta: replace slack links

- CONTRIBUTING.md
- README.md
As discussed, we have to get rid of Heroku and hence swap the invite links with the direct Slack powered feature.
> meta: swap Slack links (v6)

- src/dialects/abstract/query-interface.js
- test/unit/model/update.test.js
This is the same changes from pr #15231
> fix: remove options.model overwrite on bulkUpdate

- test/chai-extensions.d.ts
- test/support.ts
- test/unit/model/include.test.js
- test/unit/model/scope.test.ts
- test/unit/utils.test.js
While working on unblocking #15250 I noticed that our own implementation of deepEqual was not needed anymore so this PR removes that and uses chai's own deep.equal
> meta: remove own deep.equal

- src/dialects/abstract/query-interface.js
- src/dialects/mariadb/query-generator.js
- src/dialects/mssql/query-generator.js
- test/unit/query-generator/add-column-query.test.ts
- test/unit/query-generator/remove-column-query.test.ts
Reported in #14928 
MariaDB seems to support both `DROP COLUMN IF EXISTS` and `ADD COLUMN IF NOT EXISTS` therefore support for it is supposed to be added.
MSSQL also seems to support `DROP COLUMN IF EXISTS` however there seems to be no support for `ADD COLUMN IF NOT EXISTS`. There are possible workarounds.
Closes #14928
Closes #11774
> feat: add support for add/drop column IF [NOT] EXISTS for `mssql` and `mariadb`

- src/dialects/postgres/query.js
- test/integration/dialects/postgres/query.test.js
Merge ff43e8d32d8069f4071df2ca57931c74f6556a2e from main:
The `query_timeout` feature of the `pg` package helps handle stuck TCP connections more quickly and gracefully by implementing a client-side timeout:
https://github.com/brianc/node-postgres/issues/1713
Sequelize started passing this dialect-specific option through to `pg` here:
https://github.com/sequelize/sequelize/pull/13258
I believe we also want to invalidate the connection when a client-side timeout occurs. We shouldn't try to reuse the stuck connection because...it's stuck.
This PR updates the error handling code so that the connection is invalidated if the error matches the one thrown from here:
https://github.com/brianc/node-postgres/blob/5538df6b446f4b4f921947b460fe38acb897e579/packages/pg/lib/client.js#L529
> fix(postgres): invalidate connection after client-side timeout

- .github/workflows/ci.yml
- package.json
- src/dialects/abstract/data-types-utils.ts
- yarn.lock
Now TS 4.9 is out we need to add that to our CI. We also drop support for TS 4.5 per our version policy since it has been out for a year.
> fix: support TS 4.9 and drop support TS 4.5

- README.md
Lets remove CI badge, this is somehow a mistake.
CI badge was checking all the PRs from the CI action: https://github.com/sequelize/sequelize/actions/workflows/ci.yml so instead of success it will always show `failing`
The correct way is to replace it by https://github.com/sequelize/sequelize/actions/workflows/notify.yml but the badge was looking like this after https://github.com/sequelize/sequelize/workflows/Notify%20release%20channels/badge.svg so I think we can remove it instead
> meta: remove CI badge

- CONTRIBUTING.md
- dev/postgres/latest/docker-compose.yml
- dev/postgres/oldest/docker-compose.yml
- src/dialects/postgres/index.ts
- test/integration/sequelize.test.js
This PR removes the support for postgres 10, which is now EOL. It also changes the latest version we test on to postgres 15, but we had to disable a test in order to do that. A TODO has been added reflecting what needs to be done to fix this.
> meta: update postgres support to 11-15

- src/dialects/oracle/connection-manager.js
The Oracle dialect had the maxRows value hardcoded to 1000 so select queries returned only the first 1000 rows unless the user set the maxRows option. Fixing this would fetch all the rows from the table instead.
Fix to the issue raised in https://stackoverflow.com/questions/74357044/sequelize-have-a-limit-of-return-1000-rows-of-my-table-oracle-connection
> fix(oracle): remove hardcoded maxRows value

- src/dialects/postgres/connection-manager.js
please see https://github.com/sequelize/sequelize/issues/15345.
Please see linked issue.
> feat(postgres): add support for lock_timeout

- src/dialects/abstract/query-generator.js
- test/unit/query-generator/get-where-conditions.test.ts
Currently, setting the `where` option to an unsupported value makes it use `1=1` as the where condition. With this change, it will throw instead. The former doesn't make sense and is a security risk.
> fix: throw if `where` receives an invalid value

- src/dialects/abstract/index.ts
- src/dialects/abstract/query-generator.d.ts
- src/dialects/abstract/query-generator.js
- src/dialects/abstract/query-interface.d.ts
- src/dialects/mssql/index.ts
- src/dialects/postgres/index.ts
- src/model.d.ts
- src/utils/deprecations.ts
- test/integration/data-types/methods.test.ts
- test/integration/instance/decrement.test.js
- test/integration/instance/increment.test.js
- test/integration/model.test.js
- test/integration/model/bulk-create.test.js
- test/integration/model/update.test.js
- test/integration/sequelize.test.js
- test/unit/dialects/db2/query-generator.test.js
- test/unit/dialects/mariadb/query-generator.test.js
- test/unit/dialects/mysql/query-generator.test.js
- test/unit/dialects/postgres/query-generator.test.js
- test/unit/dialects/snowflake/query-generator.test.js
- test/unit/dialects/sqlite/query-generator.test.js
- test/unit/query-generator/insert-query.test.ts
- test/unit/query-generator/select-query.test.ts
- test/unit/sql/insert.test.js
- test/unit/sql/select.test.js
- test/unit/sql/update.test.js
This removes a security vulnerability we have where attributes would not be escaped if they included `(` and `)`, or where equal to `*`, and were split if they included the character `.`
Users must always use `literal` or `col` to inline something without escaping.
The special syntax is still available when using `col`. We'll need to provide something like [`identifier()`](https://github.com/sequelize/sequelize/issues/14299) that only escapes, and thoroughly document `col`.
The following
```ts
User.findAll({
attributes: [
'*',
'a.*',
['count(id)', 'count']
]
});
```
used to return this:
```sql
SELECT *, "a".*, count(id) AS "count" FROM "users"
```
now it returns this:
```sql
SELECT "*", "a.*", "count(id)" AS "count" FROM "users"
```
The previous behavior can be restored by writing this …
> fix: always escape string attributes

- package.json
- src/sequelize.d.ts
- src/sequelize.js
- yarn.lock
I have corrected the types in the underlying `retry-as-promised` library so they can now be re-exported by sequelize to get the proper type for `retry`.
See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63267 for details.
> feat(types): use retry-as-promised types for retry options to match documentation

- src/data-types.js
- src/dialects/abstract/query-generator.js
- src/dialects/db2/query.js
- src/dialects/mssql/connection-manager.js
- src/dialects/mssql/query.js
- src/dialects/oracle/data-types.js
- src/dialects/oracle/query.js
- src/dialects/sqlite/query.js
- src/model.d.ts
- src/model.js
- src/sql-string.js
- test/integration/data-types.test.js
- test/integration/model/findOne.test.js
- test/unit/dialects/mssql/query.test.js
- test/unit/sql/select.test.js
this PR backports #14485 to v6 branch with some exceptions regarding original PR [changes](https://github.com/sequelize/sequelize/pull/14485/files)
* src/dialects/mssql/query.js L93-L98 because the `paramType` object changed
* test/integration/sequelize/query.test.js because changes tests that are not related to BigInt support
* test/registerEsbuild.js because increases the node version
* test/unit/query-generator/select-query.test.ts because does not exists in v6
the other changes have been applied.
> feat: add support for bigints (backport of #14485)

- src/dialects/abstract/query-generator-typescript.ts
- src/dialects/abstract/query-interface.d.ts
- src/dialects/db2/query-generator-typescript.ts
- src/dialects/db2/query-generator.js
- src/dialects/ibmi/query-generator-typescript.ts
- src/dialects/ibmi/query-generator.js
- src/dialects/mariadb/query-generator-typescript.ts
- src/dialects/mariadb/query-generator.js
- src/dialects/mssql/query-generator-typescript.ts
- src/dialects/mssql/query-generator.js
- src/dialects/mysql/query-generator-typescript.ts
- src/dialects/mysql/query-generator.js
- src/dialects/postgres/query-generator-typescript.ts
- src/dialects/postgres/query-generator.js
- src/dialects/snowflake/query-generator-typescript.ts
- src/dialects/snowflake/query-generator.js
- src/dialects/sqlite/query-generator-typescript.ts
- src/dialects/sqlite/query-generator.js
- src/utils/check.ts
- test/types/query-interface.ts
- test/unit/dialects/db2/query-generator.test.js
- test/unit/dialects/mariadb/query-generator.test.js
- test/unit/dialects/mssql/query-generator.test.js
- test/unit/dialects/mysql/query-generator.test.js
- test/unit/dialects/postgres/query-generator.test.js
- test/unit/query-generator/remove-index-query.test.ts
- test/unit/sql/index.test.js
Update the methods used to quote the indexes and table to match the [Microsoft SQL Server docs](https://learn.microsoft.com/en-us/sql/t-sql/statements/drop-index-transact-sql?view=sql-server-ver16).
> fix: migrate removeIndexQuery to TypeScript

- test/integration/data-types/data-types.test.ts
- test/unit/sql/where.test.ts
This very small PR adds two tests to cover behaviors that were fixed in v7 but were reported as being an issue in v6 in https://github.com/sequelize/sequelize/issues/15463. This should help prevent future regressions.
> meta: add DateTime tests

- src/index.mjs
- src/sequelize.js
Fix the export/typing issues pointed out in [this comment](https://github.com/sequelize/sequelize/pull/15339#discussion_r1045288006).
Definitely a hacky solution, so if there's no better one I'd like to revisit this later. I'm not super familiar with our import/export system and how typings interact across the codebase, so any feedback is welcome
> fix: align `QueryInterface` type export with value exports

- src/dialects/mssql/query-interface.js
- test/integration/dialects/mssql/regressions.test.js
- test/unit/query-interface/bulk-insert.test.ts
Force a transaction to be used if we're attempting to insert more than 1,000 rows in a single `bulkInsert`. This allows us to safely rollback everything in case it fails.
This fixes https://github.com/sequelize/sequelize/issues/15426.
> fix(mssql): force transactions if attempting to insert more than 1,000 rows

- src/model.js
- src/utils/deprecations.ts
- test/registerEsbuild.js
- test/unit/decorators/attribute.test.ts
- test/unit/decorators/table.test.ts
- test/unit/instance/changed.test.ts
- test/unit/model/get-attributes.test.ts
- test/unit/model/init.test.ts
- test/unit/model/overwriting-builtins.test.ts
- test/unit/query-interface/delete.test.ts
- test/unit/query-interface/update.test.ts
- test/unit/utils/model-utils.test.ts
Almost Closes https://github.com/sequelize/sequelize/issues/14300, will need to backport to v6
This PR fixes https://github.com/sequelize/sequelize/issues/14300, all details are in the diff & linked issue :)
> feat: unshadow model attributes

- package.json
As of now, the version mentioned as latest on NPM is [alpha-10](https://www.npmjs.com/package/@sequelize/core) which is not really wanted. This should become the latest alpha so people start using that sooner. This PR fixes that.
> meta: publish new v7 alphas as 'latest'

- packages/core/src/dialects/db2/query.js
- packages/core/src/dialects/ibmi/query.js
- packages/core/src/dialects/mariadb/query.js
- packages/core/src/dialects/mssql/query.js
- packages/core/src/dialects/mysql/query.js
- packages/core/src/dialects/postgres/query.js
- packages/core/src/dialects/sqlite/query.js
- packages/core/src/errors/base-error.ts
- packages/core/src/errors/database-error.ts
- packages/core/src/errors/database/exclusion-constraint-error.ts
- packages/core/src/errors/database/foreign-key-constraint-error.ts
- packages/core/src/errors/database/timeout-error.ts
- packages/core/src/errors/database/unknown-constraint-error.ts
- packages/core/src/errors/validation-error.ts
- packages/core/src/errors/validation/unique-constraint-error.ts
Fixes https://github.com/sequelize/sequelize/issues/14807
Closes https://github.com/sequelize/sequelize/pull/15348
This PR removes the stack trace modification introduced in #13347. Instead, I've rewritten the necessary Query implementations to use an async flow that is compatible with native async stack traces. Resulting in the clean stacktraces posted here: https://github.com/sequelize/sequelize/pull/15555#issuecomment-1383136934
I think this can be backported to v6 too, there shouldn't be any breaking change (apart from the use of private methods which may not supported in node 10)
> feat: rollback workaround #13347, improve stack traces using async stack traces instead

- packages/core/package.json
Prior to the monorepo prepare work run husky install & then build
Prepare only exists in the root package.json file therefore I have updated this to just build.
> meta: prepare doesn't exist in the workspace context

- packages/validator-js/package.json
Tiny change: PR aligns the validator package with the core package by making typedoc use the source code instead of the built files for its doc generation
> meta: generate `@sequelize/validator.js` docs using /src instead of /lib

- .github/workflows/auto-add-pending-approval.yml
Currently people can still make blank issues through the GitHub API or going to https://github.com/sequelize/sequelize/issues/new Having blank issues disabled only makes them not showing up by default, but it doesn't remove the ability to create blank issues. This is by design so we need a workaround to still add the pending-approval label to newly created issues. It seems that the issue template config does not have such an option so we're using a GitHub Action as per https://docs.github.com/en/actions/managing-issues-and-pull-requests/adding-labels-to-issues
> meta: automatically add pending-approval to new issues

- packages/core/src/model.d.ts
- packages/core/src/utils/object.ts
- packages/core/test/unit/model/schema.test.ts
- packages/core/test/unit/model/scope.test.ts
This PR reduces the amount of times that we disable the `import/order` lint rule to 1. One thing I am not sure of is the changes I made to the withSchema/schema typings. I included `null` in there since we have a test for that case, but maybe we would like to remove that functionality and use a different method to remove the custom scope?
I didn't fix the last one since that would be more work to be done properly.
> meta: reduce disabling import/order lint rule

- packages/core/src/model-definition.ts
- packages/core/test/unit/model/init.test.ts
Closes https://github.com/sequelize/sequelize/issues/11734. Registering the same model twice is not supported. [Repository mode](https://github.com/sequelize/sequelize/issues/15389) can eventually add support for this in the future
> fix: throw an error if the user tries to register the same model twice

- packages/core/test/integration/sequelize.test.js
This is now possible with the bugfixes in pg 8.9.0
> meta: test on postgres >12 that a password of null fails

- .github/workflows/stale.yml
This PR pins actions/stale to the newest release instead of the main branch.
The only action we're using now that's not pinned to a release are `sequelize/proxy-release-to-open-collective` (in notify) `sdepold/github-action-get-latest-release` (in ci for release step) but we both control those so I think that's not an issue
> meta: pin actions/stale to release

- package.json
- yarn.lock
moment-timezone 0.5.34 has a major listed vulnerability that is patched in 0.5.35. Updating the minimum version of moment-timezone used by sequelize to be the patched version. More details on the vulnerability here: https://github.com/moment/moment-timezone/commit/7915ac567ab19700e44ad6b5d8ef0b85e48a9e75
> fix: update moment-timezone version for vulnerability

- src/dialects/abstract/query-generator.js
- test/unit/sql/get-where-conditions.test.js
Backport of https://github.com/sequelize/sequelize/pull/15375 to resolve CVE-2023-22579 and CVE-2023-22580
> fix: throw if `where` receives an invalid value (v6)

- src/dialects/abstract/query-generator.js
- test/unit/sql/get-where-conditions.test.js
This PR fixes a regression introduced by https://github.com/sequelize/sequelize/pull/15699 where "undefined" became an invalid value in `where`. This PR treats undefined the same as if the where property was missing
Closes #15702
> fix: accept & ignore "undefined" as a value in where

- src/dialects/abstract/query-generator.js
- src/sequelize.d.ts
- src/sequelize.js
- src/utils/deprecations.ts
- test/integration/sequelize.test.js
- test/unit/dialects/db2/query-generator.test.js
- test/unit/dialects/mariadb/query-generator.test.js
- test/unit/dialects/mysql/query-generator.test.js
- test/unit/dialects/postgres/query-generator.test.js
- test/unit/dialects/snowflake/query-generator.test.js
- test/unit/dialects/sqlite/query-generator.test.js
- test/unit/sql/select.test.js
The goal of this PR is to fix CVE-2023-22578 in Sequelize 6 ([thread](https://github.com/sequelize/sequelize/discussions/15694))
Unlike in v7 where we [always escape all non-literal attributes](https://github.com/sequelize/sequelize/pull/15374), in v6 using parentheses in an attribute will throw an error by default. This is deliberate to warn users that relied on this feature that the behavior changed.
Users then have 3 options:
- Wrap the attribute in a `literal()` call. This will make Sequelize treat it as raw SQL.
- Set the `attributeBehavior` sequelize option to `"escape"` to make Sequelize escape the attribute, like in Sequelize v7. We highly recommend this option.
- Set the `attributeBehavior` sequelize option to `"unsafe-legacy"` to make Sequelize escape the attribute, like in …
> feat: throw an error if attribute includes parentheses (fixes CVE-2023-22578)

- src/dialects/postgres/query-generator.js
- test/unit/sql/create-schema.test.js
Fixes #15651. This patch backports a part of #14999 to Sequelize v6 to quote schema identifiers in PostgreSQL `createSchema()` and `dropSchema()`.
(none)
> fix(postgres): Escape identifier in createSchema and dropSchema

- packages/core/src/utils/sql.ts
- packages/core/test/unit/utils/sql.test.ts
Fixes an issue reported here: https://github.com/sequelize/sequelize/issues/15301#issuecomment-1322151016
Basically unnamed `$$` quoted strings were ending too quickly. The parser considered the string to be delimited like this:
```sql
SELECT $$ id $$
--     ^ start of string
--      ^ end of string
```
instead of this:
```sql
SELECT $$ id $$
--     ^ start of string
--           ^ end of string
```
> fix: fix unnamed dollar string detection (v7)

- packages/core/src/associations/belongs-to.ts
- packages/core/src/associations/has-many.ts
- packages/core/src/associations/has-one.ts
- packages/core/test/unit/associations/belongs-to.test.ts
Closes #15625
This comment explains the issue: https://github.com/sequelize/sequelize/issues/15625#issuecomment-1408092528
I've also updated `HasOneCreateAssociationMixin` to align it with `HasManyCreateAssociationMixin`. Something I noticed while writing the association documentation
> fix: prevent BelongsTo's inverse association from itself creating a BelongsTo (#15625)

- .github/workflows/authors.yml
This should fix the Renovate warning. For some reason it didn't pick up the `v1` tag anymore but updating it to the latest patch release should be enough.
> meta: fix tag for action in authors workflow

- packages/core/src/decorators/legacy/attribute-utils.ts
- packages/core/src/decorators/legacy/built-in-attributes.ts
- packages/core/src/decorators/legacy/decorator-utils.ts
- packages/core/src/decorators/legacy/index.mjs
- packages/core/src/decorators/legacy/index.ts
- packages/core/src/decorators/legacy/validation.ts
- packages/core/test/unit/decorators/built-in-attributes.test.ts
This PR adds the 3 timestamp attribute decorators, `@CreatedAt`, `@UpdatedAt`, `@DeletedAt`, as well as the `@Version` decorator
They're used to control which attribute will be used at the timestamp and version attributes
> feat: add timestamp & version attributes

- packages/core/src/dialects/abstract/data-types.ts
Hopefully unblocks #15799 by restricting the precision option to `number | undefined`
> fix: restrict precision option in DATE and TIME to number

- src/dialects/abstract/index.d.ts
- src/dialects/abstract/index.js
- src/dialects/abstract/query-generator.js
- src/dialects/postgres/index.js
- src/dialects/sqlite/index.js
- src/model.d.ts
- test/integration/model/upsert.test.js
- test/types/upsert.ts
- test/unit/sql/insert.test.js
Adds an option to set the where clause in the `ON CONFLICT` part of postgres/sqlite upserts.  Backport of #13411.
> feat(postgres, sqlite): add conflictWhere option to upsert (v6)

- src/model.js
- test/integration/cls.test.js
> fix: cls transaction hook

- src/model.d.ts
- src/model.js
- test/integration/model/bulk-create.test.js
- test/types/bulk-create.ts
- test/unit/model/bulk-create.test.js
Adds the conflictAttributes option to Model.bulkCreate.  Backport of #13419
> feat(postgres, sqlite): allow override of conflict keys for bulkCreate (v6)

- packages/core/src/transaction.ts
- packages/core/test/integration/transaction.test.js
This PR replaces PR https://github.com/sequelize/sequelize/pull/13038
Closes https://github.com/sequelize/sequelize/pull/13038
This PR adds two new transaction hooks:
- `afterRollback`: called when a transaction is rolled back
- `afterTransaction`: called when a transaction is either committed or rolled back (the `finally` of transactions)
- Document these two methods in our transaction guide
> feat: add `Transaction#afterRollback`, `Transaction#afterTransaction`

- src/dialects/db2/query.js
Since DB2 is showing that it passes even when erroring and we haven't fixed the failing tests on v6 yet, this slipped past our radar. `node:util` is not supported for Node 10
> meta(db2): remove node:util

- packages/core/src/dialects/abstract/data-types.ts
- packages/core/src/dialects/mysql/data-types.ts
- packages/core/src/sql-string.ts
- packages/core/test/integration/instance/update.test.js
- packages/core/test/unit/sql/insert.test.js
- packages/core/test/unit/sql/where.test.ts
This PR is an updated version of PR https://github.com/sequelize/sequelize/pull/13145
Looks like the bug was fixed, so I only added a regression test
Closes https://github.com/sequelize/sequelize/pull/13145
Closes https://github.com/sequelize/sequelize/issues/12717
> fix(mysql): don't print milliseconds if date precision is 0

- packages/core/src/dialects/postgres/connection-manager.ts
Ports https://github.com/sequelize/sequelize/pull/14119 to v7
> feat(postgres): support connectionTimeoutMillis dialectOption

- src/dialects/abstract/query-generator.js
- src/model.d.ts
- test/integration/model/bulk-create.test.js
- test/unit/sql/insert.test.js
Adds a conflictWhere option to Model.bulkCreate in postgres & sqlite which controls the clause in the `ON CONFLICT` part of the query.  Backport of #13420.
> feat(postgres, sqlite): add conflictWhere option to Model.bulkCreate (v6)

- CONTACT.md
- CONTRIBUTING.md
- README.md
Update Slack invitation link with a generic and cloudflare controlled one.
> meta: update Slack invitation link

- packages/core/src/dialects/abstract/connection-manager.ts
- packages/core/src/model-internals.ts
- packages/core/src/model.d.ts
- packages/core/src/model.js
- packages/core/src/sequelize-typescript.ts
- packages/core/src/sequelize.d.ts
- packages/core/src/sequelize.js
- packages/core/test/integration/sequelize.test.js
- packages/core/test/integration/sequelize/set-session-variables.test.ts
- packages/core/test/integration/sequelize/with-connection.test.ts
Closes https://github.com/sequelize/sequelize/issues/15388
This PR implements `sequelize.withConnection`. It's a method you can call to reserve a connection and use it multiple times before releasing it back to the pool.
This is useful in dialects that support session variables & session options.
It is now possible to specify on which connection a query must run by using the `connection` option. This option is mutually exclusive with the `transaction` option.
```ts
sequelize.withConnection(async (connection) => {
await sequelize.query('SET SESSION group_concat_max_len = 10485760;', { connection });
await User.findAll({ connection });
});
```
This `connection` option takes precedence over CLS transactions. Unlike transactions, the connection reserved by `withConnection` is not (currently) …
> feat: add `sequelize.withConnection`, rename `sequelize.set` to `sequelize.setSessionVariables`

- .github/workflows/ci.yml
We added support to TypeScript 5.0 already, but didn't add it to the CI. This also means we drop testing for TS 4.6 support, I'll open a PR for the docs as well
> meta: add TypeScript 5.0 type testing to CI

- .github/workflows/ci.yml
I've noticed that some dependency updates are failing to install other versions of TypeScript, and a quick Google search leaves me to think we should not add TypeScript on both the root level and on the workspace level. There should no harm in adding TypeScript to the root level here since it will not be added to the archive used for the other checks.
I hope that this fixes that.
One occurance of this; https://github.com/sequelize/sequelize/actions/runs/4590964565
Two errors that happened on that run, highlighting that it might not be directly related to the dependency being updated;
`error An unexpected error occurred: "expected workspace package to exist for \"eslint-utils\"".`
`error An unexpected error occurred: "expected workspace package to exist for \"typedoc\"".`
> meta: install TypeScript at root level for test-typings CI

- packages/core/src/dialects/sqlite/connection-manager.ts
On Windows, using fs.mkdir() on the root directory even with recursion will result in an error
https://nodejs.org/dist/latest-v16.x/docs/api/fs.html#fsmkdirpath-options-callback
Fixes #14555
> fix(sqlite): don't use mkdirp if the file already exists

- src/dialects/postgres/connection-manager.js
We recently observed multiple crashes due to an unhandled "server conn crashed?" exception originating from the pg library. As best as I've been able to tell, this shouldn't be possible and should have been fixed in this previous PR : https://github.com/sequelize/sequelize/pull/14731
I think that an error might be able to slip up during the connection without the error listener being properly attached or that error can be fired multiple times and is only handled once.
My fix is to attach the listener before trying to connect to the database. Also I change back the .once handler to a .on (this was changed in the PR 14731) to be able to catch multiple errors.
> fix(postgres): prevent crash if postgres connection emit multiple errors

- packages/core/package.json
- yarn.lock
`pg-hstore` used to be lazily loaded if DataTypes.HSTORE is used. This was changed in the DataTypes PR for the following reasons:
- It's a pain to import using `require` with TypeScript
- In an indeterminate future, we'll fully migrate to ESM. Dynamic imports will be done with `import()`, which is asynchronous
This means that if you use `pg`, you must always install pg-hstore. `pg-hstore` is a tiny library, so we might as well install it by default.
Once we move dialects to their own packages, we'll move this dependency to the `@sequelize/postgresql` package
> feat: move pg-hstore to prod dependencies

- packages/core/package.json
- packages/validator-js/package.json
I moved `types` condition to the front. `package.json#exports` are **order-sensitive** - they are always matched from the top to the bottom. When a match is found then it should be used and no further matching should occur. 
Right now, the current setup works in TypeScript but it's considered a bug and it should not be relied upon, see the thread and the comment [here](https://github.com/microsoft/TypeScript/issues/50762#issuecomment-1528318260). For that reason, I would like to fix all popular packages that misconfigured their `exports` this way so the bug can be fixed in TypeScript.
Note that some of your entrypoints were already using this more correct order (see [those](https://github.com/sequelize/sequelize/blob/e83ff36c3c55c2aee12188861d1cf26720017277/packages/core/package.json#L28-L …
> meta: move `types` condition to the front

- src/dialects/abstract/query-generator.js
A fix was added to support minification of aliases to avoid character limits for PostgreSQL queries, but it did not account for through joins. I've abstracted the aliasing function and used it in both join generator functions.
> fix(postgres): adds support for minifying through join aliases

- package.json
- packages/core/package.json
- packages/core/src/data-types.ts
- packages/core/src/dialects/abstract/data-types.ts
- packages/core/src/dialects/abstract/index.ts
- packages/core/src/dialects/abstract/query.js
- packages/core/src/dialects/mssql/data-types.db.ts
- packages/core/src/dialects/mysql/data-types.db.ts
- packages/core/src/dialects/postgres/data-types-db.ts
- packages/core/src/errors/validation-error.ts
- packages/core/src/index.d.ts
- packages/core/src/instance-validator.d.ts
- packages/core/src/model.d.ts
- packages/core/typedoc.json
- packages/validator-js/package.json
- packages/validator-js/typedoc.json
- typedoc.base.json
- typedoc.js
- yarn.lock
TypeDoc 0.24 is out, which supports monorepos.
This means all modules will be properly listed in our API definition now:
URLs changed, we will need to update the documentation to align with this update
> meta: update typedoc

- .github/workflows/ci.yml
This PR makes our branch validation pipeline run on merge queue branches. This would allow us to enable the merge queue if we want to.
> meta: support merge queue in CI

- packages/core/src/associations/belongs-to.ts
- packages/core/test/integration/associations/has-one.test.js
- packages/core/test/unit/associations/belongs-to.test.ts
Closes #15895
Fairly straightforward fix. Instead of inferring the singular form, use the one that was already provided in the configuration of the association, or the model
> fix: use singular association name to generate FK

- dev/mariadb/latest/docker-compose.yml
One test is very flaky for 11.0 and it needs further debugging and possibly is a bug within MariaDB itself. See https://github.com/sequelize/sequelize/pull/16147#issuecomment-1598349038
Since this impacts our CI quite a lot I would suggest going back to the previous 'major' version
Update; I created this all from mobile, and the GitHub app does not give me the PR template
> meta(mariadb): test for 10.11 instead of 11.0

- renovate.json
Seems that this is needed to let Renovate use the merge queues, as per https://docs.renovatebot.com/key-concepts/automerge/
> meta: enable platformAutomerge in renovate

- dev/mariadb/latest/docker-compose.yml
- packages/core/test/integration/model/findAll/groupedLimit.test.js
This PR fixes a flaky test. Users with ID 4 and 7 have the same absolute age, so the sort order was undetermined.
I added the primary key as a secondary sort order to fix this issue. This seems to have fixed the issue: It failed 9 times out of 10 before, and has not failed since. Tested with MariaDB 11.
> meta: fix mariadb flaky test

- packages/core/src/index.d.ts
- packages/core/src/sequelize-typescript.ts
- packages/core/src/sequelize.d.ts
- packages/core/src/sequelize.js
- packages/core/src/transaction.ts
- packages/core/test/integration/sequelize/transaction.test.ts
This is a tiny PR to fix an issue I noticed while writing the new transaction documentation. The new transaction options included CLS in their name but they had nothing to do with CLS, they're related to managed transactions with or without CLS.
> fix: rename `clsTransactionNestMode` ➡️ `defaultTransactionNestMode`; `ClsTransactionOptions` ➡️ `ManagedTransactionOptions`

- packages/core/test/integration/pool.test.ts
- packages/core/test/integration/transaction.test.js
These two tests are flaky and I hope that with a longer delay they fail less often. I'll keep a look out for failing CI checks in the coming weeks to see if these return
> meta: increase delay for flaky tests

- packages/core/src/dialects/sqlite/query-generator-typescript.ts
- packages/core/src/dialects/sqlite/query-generator.js
- packages/core/src/dialects/sqlite/query-interface.d.ts
- packages/core/src/dialects/sqlite/query-interface.js
- packages/core/test/unit/query-generator/drop-foreign-key-query.test.ts
- packages/core/test/unit/query-generator/remove-column-query.test.ts
This PR splits SQLite from MySQL dialect so all methods are unique to each dialect.
Also, this PR remove support for some unsupported SQLite methods.
> feat(sqlite): split SQLite from MySQL

- packages/core/src/dialects/mariadb/data-types.db.ts
- packages/core/src/dialects/mariadb/data-types.ts
- packages/core/src/dialects/mariadb/index.ts
- packages/core/src/dialects/mariadb/query-generator-typescript.ts
- packages/core/src/dialects/mariadb/query-generator.d.ts
- packages/core/src/dialects/mariadb/query-generator.js
- packages/core/src/dialects/mysql/data-types.db.ts
- packages/core/test/unit/data-types/uuid.test.ts
This PR splits MariaDB from MySQL dialect so all methods are unique to each dialect.
> feat(mariadb): split MariaDB from MySQL

- SECURITY.md
NPM seems to have removed all resources to report a vulnerability. Not sure why they did this, but the link on this page is dead now.
> docs: remove NPM disclosure link

- .github/workflows/ci.yml
- build-packages.mjs
- packages/core/package.json
When I recently forked the repo, while attempting to run `npm run build` command in order to build the package, the build didn't run on my Windows machine.
The reasons turned out to be:
* `fast-glob` package [not recognizing](https://github.com/mrmlnc/fast-glob/issues/237) backslashes.
* The `build` script not specifying the executable to run the `.mjs` file with.
After applying the changes in this PR, the build process has finished without errors.
> fix: build on windows machines

- dev/mysql/latest/start.sh
It's not really fixing it, but hopefully this additional time prevents us from not able to connect even though the Docker container is healthy. If this causes `mysql latest` to not fail anymore we can look into a better solution to detect the database is ready for connections.
> meta(mysql): sleep 5 seconds before trying to connect

- .github/workflows/stale.yml
It's the holiday period so we might not respond on time. We'll temporarily disable the stale bot and re-activate it again later
> meta: temp disable stale bot

- packages/core/src/associations/belongs-to-many.ts
- packages/core/src/model.d.ts
- packages/core/test/integration/json.test.ts
- packages/core/test/types/find-all.ts
- packages/core/test/types/find-one.ts
- packages/core/test/unit/query-generator/select-query.test.ts
Updates the attributes typing for find queries so that model attributes can be selected/suggested by IDE's.
> feat(types): restrict attributes typing

- packages/core/src/dialects/abstract/query-generator-typescript.ts
- packages/core/src/dialects/abstract/query-interface-typescript.ts
- packages/core/src/dialects/abstract/query-interface.d.ts
- packages/core/src/dialects/abstract/query-interface.js
- packages/core/src/dialects/db2/query-generator-typescript.ts
- packages/core/src/dialects/db2/query-generator.js
- packages/core/src/dialects/ibmi/query-generator-typescript.ts
- packages/core/src/dialects/mariadb/query-generator.js
- packages/core/src/dialects/mssql/query-generator.js
- packages/core/src/dialects/mysql/query-generator.js
- packages/core/src/dialects/postgres/query-generator.js
- packages/core/src/dialects/snowflake/query-generator.js
- packages/core/src/dialects/sqlite/query-generator-typescript.ts
- packages/core/src/dialects/sqlite/query-generator.js
- packages/core/src/model.js
- packages/core/test/integration/query-interface/table-exists.test.ts
- packages/core/test/unit/dialects/snowflake/query-generator.test.js
- packages/core/test/unit/query-generator/table-exists-query.test.ts
Migrates `tableExists` and `tableExistsQuery` to typescript.
For some reason the foreign key check in the `alter` method for the `Model` class needed to have the tableCatalog condition updated so that it only checks the value is its returned by the `getForeignKeyReferencesForTable` query.
> feat: migrate tableExists to typescript

- packages/core/src/dialects/ibmi/index.ts
- packages/core/src/dialects/snowflake/index.ts
- packages/core/test/unit/model/define.test.ts
- yarn.lock
This PR marks IBMi and Snowflake as experimental. Configuring Sequelize for one of these dialects will render a warning. This change is done due to insufficient means of running our integration tests against a publicly available instance of either of the dialects and a respective inability of verifying code changes.
Render warning when ibmi or snowflake dialect is loaded:
```
import {Sequelize}from './packages/core';
const s = new Sequelize({dialect: 'ibmi'})
```
-->
```
The IBMi dialect is experimental and usage is at your own risk. Its development is exclusively community-driven and not officially supported by the maintainers.
```
> docs(ibmi,snowflake): Mark IBMi and Snowflake as experimental

- packages/core/src/utils/sql.ts
- packages/core/test/unit/utils/sql.test.ts
Hi! I'm working on upgrading from Sequelize 6 to the latest Sequelize 7 alpha in an application. One of the things I've run into is that bind parameters can no longer go inside array literals, for example:
```js
await sequelize.query('SELECT array[$1, $2]', {
type: 'SELECT',
bind: [123, 456],
});
```
As of 7.0.0-alpha.12 this stopped working, and I tracked it down to #14447. It does appear to be an intentional change, since it even added a test for that case: https://github.com/sequelize/sequelize/blob/b3f853e5c2199c33dffe3a988b71a4ac5f14dc22/packages/core/test/unit/utils/sql.test.ts#L91-L98
The application does rely on being able to build array literals like that in quite a few places, so I'll have to say that there are some good use cases for this syntax, and that it feels a bit too …
> fix: allow bind parameters in array literal

- .github/workflows/authors.yml
Since it runs once a week I kinda forgot about this. Apparently GitHub wants `dist/index.js` of the action to be included but it's not shipped. This fixes it but I'm not sure renovate will easily pick up updates to the action. But last release was November 2022 so it doesn't get that many updates.
> meta: fix update-authors CI

- package.json
- packages/core/src/expression-builders/attribute.ts
- packages/core/src/expression-builders/identifier.ts
- packages/core/src/expression-builders/json-path.ts
- packages/core/src/expression-builders/json.ts
- packages/core/src/expression-builders/list.ts
- packages/core/src/index.d.ts
- yarn.lock
This PR fixed the typedoc `@link` tag module resolutions. 
This also unblocks #16412 
Nothing
> meta: fixed typedoc 0.25 @link issues

- packages/core/src/utils/deprecations.ts
When using an unsupported database engine the warning printed links to the now removed ENGINE.md file instead of the https://sequelize.org/releases/ page. This was missed when ENGINE.md was removed in in #14380.
> fix: outaded link on unsupported engines warning

- .github/workflows/ci.yml
- package.json
- yarn.lock
- [] Did you update the typescript typings accordingly (if applicable)?
This PR fixes the issue with caching breaking in the CI when different machines run CI tasks.
> meta: update ci artifact

- packages/core/src/decorators/legacy/associations.ts
- packages/core/test/unit/decorators/associations.test.ts
This PR:
- Forbids specifying the `as` option at the root of association decorators, because it will be ignored in favor of using the name of the property being decorated
- Loosens the typing of the `@BelongsTo` decorator, due to it being incompatible with inheritable models
> fix: improve association decorators

- packages/core/src/associations/base.ts
- packages/core/src/associations/belongs-to-many.ts
- packages/core/src/associations/has-many.ts
- packages/core/src/dialects/abstract/query-generator-typescript.ts
- packages/core/src/dialects/abstract/query-interface-typescript.ts
- packages/core/src/dialects/sqlite/query-generator-typescript.ts
- packages/core/src/dialects/sqlite/query-interface.js
- packages/core/src/utils/check.ts
- packages/core/src/utils/types.ts
- packages/core/test/integration/associations/belongs-to-many-mixins.test.ts
- packages/core/test/integration/associations/has-many-mixins.test.ts
This PR adds the possibility of using any iterable (instead of only arrays) in addX, setX, hasX, and removeX hasMany and belongsToMany association methods.
This means that it will now be possible to write the following:
```ts
const books = new Set([1, 2, 3]);
await user.addBooks(books);
```
Whereas before you add to convert the set to an array first
---
The changes done in query-generator & query-interface are misc small issues that were not caught during previous reviews
> feat: support iterables in association methods

- .github/workflows/ci.yml
- build-packages.mjs
- packages/core/package.json
- packages/core/test/unit/utils/utils.test.ts
- test/register-esbuild.js
Node 16 is [EOL since September 11th, 2023](https://nodejs.org/en/blog/announcements/nodejs16-eol). With this PR we're dropping support for Node 16 in our CI.
> feat: drop Node 16 support

- packages/core/src/decorators/shared/model.ts
- packages/core/src/model-definition.ts
- packages/core/test/unit/decorators/table.test.ts
Edge case we discovered while updating Sequelize in a production app: Using decorators to define an index on a model that inherits from another model causes a crash during the merging of options, due to the index option being undefined instead of being absent altogether
> fix: fix crash when defining index on child model with decorators

- packages/core/src/dialects/abstract/query-generator-typescript.ts
- packages/core/src/dialects/abstract/query-generator.d.ts
- packages/core/src/dialects/abstract/query-generator.js
- packages/core/src/dialects/abstract/query-generator.types.ts
- packages/core/src/dialects/abstract/query-interface-typescript.ts
- packages/core/src/dialects/abstract/query-interface.d.ts
- packages/core/src/dialects/abstract/query-interface.js
- packages/core/src/dialects/abstract/query-interface.types.ts
- packages/core/src/dialects/mssql/query-generator-typescript.ts
- packages/core/src/dialects/mssql/query-generator.js
- packages/core/src/dialects/postgres/query-generator-typescript.ts
- packages/core/src/dialects/postgres/query-generator.js
- packages/core/src/dialects/snowflake/query-generator-typescript.ts
- packages/core/src/dialects/snowflake/query-generator.js
- packages/core/test/integration/query-interface/create-drop-list-database.test.ts
- packages/core/test/integration/support.ts
- packages/core/test/unit/query-generator/create-database-query.test.ts
- packages/core/test/unit/query-generator/drop-database-query.test.ts
- packages/core/test/unit/query-generator/list-databases-query.test.ts
Migrate the following methods to typescript:
- `createDatabase` and `createDatabaseQuery`
- `dropDatabase` and `dropDatabaseQuery`
- `listDatabases` and `listDatabasesQuery`
Also updated the test `clearDatabaseInternal` function to support removing test databases.
> feat: migrate database queries to typescript

- packages/core/src/associations/belongs-to-many.ts
- packages/core/test/unit/associations/belongs-to-many.test.ts
This PR adds configuration options to BelongsToMany associations to customize the name of intermediary associations (the ones going from/to the through model).
> feat: support customizing through associations

- nx.json
Currently changing the `.mocharc.jsonc` file causes the cache of the build to differ therefore rebuilding the entire project.
This PR works to exclude any non-build dependencies so that the build cache is not impacted by test/dev changes.
> meta: update build cache dependency exclusions

- src/model.js
Added missing docs of property `conflictAttributes` to v6 API Reference. Solves #16572.
> docs: add missing conflictAttributes to bulkCreate

- README.md
Fixed wrong Typescript documentation link for the Read.me file. Solves #16586
> docs: update typescript link to an existing documentation

- packages/core/src/dialects/abstract/index.ts
- packages/core/src/dialects/abstract/query-generator-typescript.ts
- packages/core/src/dialects/abstract/query-generator.d.ts
- packages/core/src/dialects/abstract/query-generator.js
- packages/core/src/dialects/abstract/query-generator.types.ts
- packages/core/src/dialects/abstract/query-interface-typescript.ts
- packages/core/src/dialects/abstract/query-interface.d.ts
- packages/core/src/dialects/abstract/query-interface.js
- packages/core/src/dialects/abstract/query-interface.types.ts
- packages/core/src/dialects/db2/index.ts
- packages/core/src/dialects/db2/query-generator-typescript.ts
- packages/core/src/dialects/db2/query-generator.js
- packages/core/src/dialects/ibmi/index.ts
- packages/core/src/dialects/ibmi/query-generator-typescript.ts
- packages/core/src/dialects/ibmi/query-generator.js
- packages/core/src/dialects/mssql/index.ts
- packages/core/src/dialects/mssql/query-generator-typescript.ts
- packages/core/src/dialects/mssql/query-generator.js
- packages/core/src/dialects/postgres/index.ts
- packages/core/src/dialects/postgres/query-generator-typescript.ts
- packages/core/test/integration/query-interface.test.js
- packages/core/test/integration/query-interface/rename-table.test.ts
- packages/core/test/unit/query-generator/rename-table-query.test.ts
This PR migrates `renameTable` and `renameTableQuery` methods to typescript.
I have included a `changeSchema` option which has to be set in order to move a table from one schema to another if this is supported by the dialect.
> feat: migrate renameTable to typescript

- packages/core/src/expression-builders/where.ts
Updated TypeError error message in regards to the documentation link for Custom Operators. 
Before this change the error message was providing the home page of the Sequelize documentation https://sequelize.org/ instead of the actual Custom Operators documentation link https://sequelize.org/docs/v7/querying/operators/#custom-operators.
Solves #16595.
> docs: provide custom operators documentation link

- packages/core/src/dialects/db2/connection-manager.ts
Fixes issue #16583
See ['ibm_db' API Documentation](https://github.com/ibmdb/node-ibm_db/blob/master/APIDocumentation.md), search for `Secure Database Connection using SSL/TSL`:
```bash
connStr = "DATABASE=database;HOSTNAME=hostname;PORT=port;Security=SSL;SSLServerCertificate=<cert.arm_file_path>;PROTOCOL=TCPIP;UID=username;PWD=passwd;";
```
The SSL related keyword should be `Security` (not `SECURITY`) with a value of `SSL` (string, not boolean).
> fix(db2): change SSL related keyword and value in connection-manager.ts

- src/dialects/oracle/index.js
- test/integration/model/json.test.js
- test/integration/transaction.test.js
The issue is raised [here](https://github.com/sequelize/sequelize/issues/16606)
- Enabled skipLocked, forShare, lockOuterJoinFailure, lock properties for Oracle dialect. 
-  Oracle does not have shared locks on individual table rows, `FOR UPDATE` is what i found closest to 
` forShare` dialect support .
- `FOR UPDATE` cant be used in sql's along with these :
-  ORDER BY 
-  FETCH NEXT 1 ROWS ( creates a inline view, ...)
It results in error
`ORA-02014: cannot select FOR UPDATE from view with DISTINCT, GROUP BY, etc. `
We can instead generate a subquery like this to avoid error , but it's not equivalent and is not correct all the time and might cause issues. 
`SELECT "id", "username", "awesome", "createdAt", "updatedAt" FROM "users"  "user" WHERE  rowid in (select rowid from "users" "user" …
> feat(oracle): add support for lock

- src/dialects/oracle/query-generator.js
- test/unit/sql/add-column.test.js
This PR is to allow default values and not null condition for `BOOLEAN` and `ENUM`.
While adding columns, the options `defaultValue` and `allowNull` have no impact.
Example:
```
queryInterface.addColumn('menu_uploads', 'displayable', {
type: Sequelize.DataTypes.BOOLEAN(),
defaultValue: true,
allowNull: false
});
```
SQL expected: `ALTER TABLE "menu_uploads" ADD "displayable" CHAR(1) DEFAULT 1 NOT NULL CHECK ("displayable" IN('1',  '0'))`
> fix(oracle): add missing default and not null condition to addColumn

- src/dialects/oracle/query-generator.js
- test/unit/sql/add-constraint.test.js
Oracle doesn't support "ON UPDATE" actions in constraints and it throws an error if defined. It also doesn't support "ON DELETE NO ACTION".
The PR modifies `addConstraintQuery` method to avoid errors.
> fix(oracle): clean constraints

- .gitignore
When developping fixes on main, nx created its cache in a `.nx`  directory that was not ignored.
> meta: ignore .nx cache

- CONTRIBUTING.md
Having `nx` as a dependency when using `lerna` causes issues as there are different versions of the same packages.
The reason for `nx` as a dependency was only to reset the cache during the CI so in this case, we can leverage `yarn dlx` and run the same command.
> meta: update contributing doc

- packages/core/src/dialects/abstract/query.js
- packages/core/test/unit/dialects/abstract/query.test.js
> fix: sort keys by depth in groupJoinData

- packages/core/test/integration/query-interface/add-show-remove-constraint.test.ts
This PR is linked to #16770 on v6.
On v6, the equivalent function to retrieve constraints on a table did not correctly filter on schema name. I added tests on v7 to ensure filtering is correctly done also on schema name.
It seems to be the case, so we don't need to port the fix on v7. But maybe these tests would be useful to avoid future regressions on this subject.
> meta: add tests to verify that showConstraints filters on schema

- packages/core/src/sequelize.d.ts
- packages/core/src/sequelize.js
- packages/core/test/unit/query-interface/bulk-delete.test.ts
- packages/core/test/unit/query-interface/bulk-update.test.ts
- packages/core/test/unit/query-interface/decrement.test.ts
- packages/core/test/unit/query-interface/delete.test.ts
- packages/core/test/unit/query-interface/drop-table.test.ts
- packages/core/test/unit/query-interface/increment.test.ts
- packages/core/test/unit/query-interface/insert.test.ts
- packages/core/test/unit/query-interface/raw-select.test.ts
- packages/core/test/unit/query-interface/select.test.ts
- packages/core/test/unit/query-interface/update.test.ts
- packages/core/test/unit/query-interface/upsert.test.ts
- packages/core/test/unit/sequelize.test.ts
This PR adds support for using the `sql` tag in `sequelize.query`, like was already described in our documentation: https://sequelize.org/docs/v7/querying/raw-queries/#sequelizequery
Closes https://github.com/sequelize/website/issues/634
> feat: add support for `sql` tag & functions in `sequelize.query`

- packages/core/src/dialects/abstract/data-types-utils.ts
- packages/core/src/model.d.ts
- packages/core/test/unit/data-types/arrays.test.ts
- packages/core/test/unit/data-types/decimal-numbers.test.ts
- packages/core/test/unit/data-types/geography.test.ts
- packages/core/test/unit/data-types/geometry.test.ts
- packages/core/test/unit/data-types/integers.test.ts
- packages/core/test/unit/data-types/misc-data-types.test.ts
- packages/core/test/unit/data-types/string-types.test.ts
- packages/core/test/unit/data-types/temporal-types.test.ts
Resolves the additional remark in https://github.com/sequelize/sequelize/issues/11039#issuecomment-1770198478
> fix: correct link to data types docs

- packages/core/src/dialects/snowflake/query-generator-typescript.ts
- packages/core/src/dialects/snowflake/query-generator.js
- packages/core/test/unit/query-generator/create-database-query.test.ts
- packages/core/test/unit/query-generator/create-table-query.test.ts
Snowflake does not explicitly support collation in the same way as some other databases.
Like it shows in [create table syntax](https://docs.snowflake.com/en/sql-reference/sql/create-table#syntax)
And in [collation specification](https://docs.snowflake.com/en/sql-reference/collation#label-collation-specification)
This fix removes the unsupported options for Snowflake
> fix: remove unsupported options for snowflake

- .github/workflows/ci.yml
- .husky/pre-commit
- package.json
- packages/core/src/dialects/abstract/query-generator-typescript.ts
- packages/core/src/dialects/abstract/where-sql-builder.ts
- packages/core/src/utils/check.ts
In line with our support policy this PR drops testing on TS 4.9. A workaround for isPlainObject typing is removed since it was fixed in TS 4.9. We also update husky on the side.
> feat: drop support TS 4.9

- packages/core/src/dialects/abstract/where-sql-builder.ts
- packages/core/test/unit/sql/where.test.ts
> fix: fix `NOT` operator sometimes producing incorrect queries

- .github/workflows/ci.yml
- renovate.json
The goal of this PR is to make renovate use `automergeType: branch`, which only opens a PR if the CI failed on the `renovate/x` branch, and is otherwise merged immediately.
This should massively reduce the spam caused by renovate
> meta: make renovate only open a PR if the CI check failed

- src/model.d.ts
In the type definition file, the return of SaveOptions was omitted. 
https://github.com/sequelize/sequelize/blob/cb8ea88c9aa37b14c908fd34dff1afc603de2ea7/src/model.d.ts#L1284-L1307
They are present in the actual code.
https://github.com/sequelize/sequelize/blob/cb8ea88c9aa37b14c908fd34dff1afc603de2ea7/src/model.js#L4016-L4022
This pull request adds the missing `returning`.
There was no problem with the v7 codes.
> fix(types): Add definition of returning in SaveOptions as it was missing.

- .github/CODEOWNERS
- .husky/pre-commit
- package.json
The lint-staged config had issues with running on every type of files
eslint:
prettier:
This updated config only runs eslint on JS/TS files, and makes prettier ignore any file it doesn't have a parser for
I also updated the codeowner based on https://github.com/sequelize/sequelize/pull/17095#issuecomment-1953041371
> meta: fix codeowners & lint-staged

- package.json
- yarn.lock
Nx version `18.1.0` was accidentally published. Reverting to actual `latest` version of Nx, which is `18.0.6`.
> fix: revert nx version to 18.0.6

- .github/workflows/autoupdate.yml
- renovate.json
Renovate auto-updates their PRs themselves. By doing it ourselves, we block their process and the PR remains open indefinitely.
This PR applies the label "no-autoupdate" to renovate PRs, and excludes PRs with this label from being automatically updated
In order to test this, I'll only enable automerge on this PR once it is outdated.
> meta: exclude renovate from auto-update

- .github/workflows/autoupdate.yml
- .github/workflows/ci.yml
Follow-up PR to solve this issue: https://github.com/sequelize/sequelize/pull/17174#issuecomment-2003747324
I created a GitHub App that belongs to the Sequelize org, this GitHub app will handle auto-updating PRs and pushing the release commit, instead of my account
The bot can be seen in the settings of our org for those who have access: https://github.com/organizations/sequelize/settings/apps
- Enable auto-merge once this PR is outdated. The update commit should come from the Sequelize Bot instead of my account.
- Delete the PAT from our secrets & from my account
> meta: replace PAT with Sequelize Bot (GitHub App)

- packages/core/src/dialects/abstract/index.ts
- packages/core/src/dialects/abstract/query-generator-typescript.ts
- packages/core/src/dialects/mssql/index.ts
- packages/core/src/dialects/mssql/query-generator-typescript.ts
- packages/core/src/dialects/snowflake/index.ts
- packages/core/src/dialects/sqlite/index.ts
- packages/core/src/dialects/sqlite/query-generator-typescript.ts
- packages/postgres/src/dialect.ts
This is another change split from #17063.
This PR fixes the supported options for delete to make them match what the dialects actually support plus a few other misc changes.
> fix: update bulkDeleteQuery supported options

- .github/workflows/ci.yml
- tsconfig.json
- [] Have you added new tests to prevent regressions?
Add `"experimentalDecorators": true` to the root tsconfig so that the `sscce.ts` file can be run.
> meta: add experimentalDecorators support for sscce

- .github/workflows/ci.yml
- packages/core/package.json
- packages/core/src/dialects/snowflake/query-generator.d.ts
- packages/core/src/sequelize.internals.ts
- packages/core/test/unit/dialects/snowflake/query-generator.test.js
- packages/core/test/unit/dialects/snowflake/query.test.js
- packages/snowflake/.eslintrc.js
- packages/snowflake/package.json
- packages/snowflake/src/_internal/data-types-overrides.ts
- packages/snowflake/src/connection-manager.ts
- packages/snowflake/src/dialect.ts
- packages/snowflake/src/index.mjs
- packages/snowflake/src/index.ts
- packages/snowflake/src/query-generator-typescript.internal.ts
- packages/snowflake/src/query-generator.d.ts
- packages/snowflake/src/query-generator.internal.ts
- packages/snowflake/src/query-generator.js
- packages/snowflake/src/query-interface.ts
- packages/snowflake/src/query.d.ts
- packages/snowflake/src/query.js
- packages/snowflake/tsconfig.json
- packages/snowflake/typedoc.json
- test/esm-named-exports.test.js
- yarn.lock
Related issue: #13722
Related PR: #17190 
This PR moves the Snowflake Dialect to the `@sequelize/snowflake` package.
- This package pre-installs the necessary snowflake-specific dependency `snowflake`. Users won't need to install the additional packages anymore. This gives us control over which version we support.
- Unlike the postgres package, this package does not have unit tests yet. Once we add those, the script should be added to the package package.json and CI.
- Instead of installing `snowflake-sdk` users need to install `@sequelize/snowflake`.
> feat(snowflake)!: move snowflake to the `@sequelize/snowflake` package

- src/sequelize.js
- src/transaction.d.ts
- src/transaction.js
Closes Sequelize/website#562.
Adds to documentation and types the previously not documented option `readOnly` of the transaction constructor.
None.
> fix: add `readOnly` to the transaction options types and docs

- .eslintrc.js
- .github/workflows/pr-title.yml
- .prettierignore
- CONTRIBUTING.md
- packages/cli/.gitignore
- packages/cli/package.json
- packages/cli/src/_internal/config.ts
- packages/cli/src/api/generate-seed.ts
- packages/cli/src/commands/seed/generate.test.ts
- packages/cli/src/commands/seed/generate.ts
- packages/cli/static/skeletons/seed.cjs
- packages/cli/static/skeletons/seed.mjs
- packages/cli/static/skeletons/seed.ts
This PR adds the command `seed generate` to the CLI. This command can generate the seed in 4 formats; `sql`, `typescript` (with `import`), `cjs` or `esm`.
This command acts the same way as `migration generate`, added in #17195 
I also updated the pr-title Action and CONTRIBUTING docs to reflect that we allow all packages as scopes.
> feat(cli): add `seed generate` command

- .github/workflows/autoupdate.yml
This PR adds an action that adds the `conflicted` label whenever a PR has conflicts, and removes it once a PR does not.
That label can then be used to exclude PRs that have conflicts, such as on the PR dashboards I use to know which PR I should review next:
- To Review: https://github.com/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+review-requested%3A%40me+-reviewed-by%3A%40me+sort%3Acreated-asc+-author%3A%40me+-label%3Aconflicted
- To Re-review: https://github.com/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+user-review-requested%3A%40me+reviewed-by%3A%40me+sort%3Acreated-asc+-label%3Aconflicted
This action is actually our own action: https://github.com/sequelize/pr-auto-update-and-handle-conflicts. That action was tested in dry-run in that repository: …
> meta: add label when a PR is in conflict

- packages/core/src/expression-builders/association-path.ts
- packages/core/src/expression-builders/attribute.ts
- packages/core/src/expression-builders/base-sql-expression.ts
- packages/core/src/expression-builders/cast.ts
- packages/core/src/expression-builders/col.ts
- packages/core/src/expression-builders/fn.ts
- packages/core/src/expression-builders/identifier.ts
- packages/core/src/expression-builders/json-path.ts
- packages/core/src/expression-builders/list.ts
- packages/core/src/expression-builders/literal.ts
- packages/core/src/expression-builders/value.ts
- packages/core/src/expression-builders/where.ts
- packages/core/test/types/sequelize.ts
This PR is split from #17063 and makes `BaseSqlExpression` and its extended classes unique.
This is required to be able to set options to restrict its values to `BaseSqlExpression`'s.
`BaseSqlExpression` is now a unique class.
> fix: make `BaseSqlExpression` a unique class

- src/dialects/postgres/query-interface.js
- test/integration/sequelize/drop.test.js
- test/unit/dialects/postgres/query-generator.test.js
> fix(postgres): use schema for foreign key constrains of a table

- packages/core/src/abstract-dialect/dialect.ts
- packages/core/src/abstract-dialect/query-generator-typescript.ts
- packages/core/src/abstract-dialect/query-generator.d.ts
- packages/core/src/abstract-dialect/query-interface-typescript.ts
- packages/core/src/sequelize-typescript.ts
- packages/db2/src/dialect.ts
- packages/mariadb/src/dialect.ts
- packages/mysql/src/dialect.ts
This PR sets the Sequelize dialect type for the `queryGenerator` and `queryInterface`.
Currently the sequelize instance in the `queryGenerator` and `queryInterface` uses the `AbstractDialect` which mean accessing the `sequelize.options` from inside these classes does not return the correct typed values.
> fix: set sequelize dialect type in query generator and interface

- dev/mssql/latest/docker-compose.yml
- dev/mssql/latest/start.sh
- dev/wait-until-healthy.sh
- packages/core/test/unit/dialects/mssql/connection-manager.test.ts
- packages/mssql/src/connection-manager.ts
- [ x ] Have you added new tests to prevent regressions?
- [ x ] Did you update the typescript typings accordingly (if applicable)?
- [ x ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ x ] Does the name of your PR follow [our conventions](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md#6-commit-your-modifications)?
Remove the hardcoded default port as this throws an error when specified with `instanceName` and doesn't throw an error when it's excluded as 1433 is the default port
> fix(mssql): add ability to use instanceName in connection-manager config

- .github/workflows/ci.yml
As per https://github.com/actions/runner-images/issues/10649, ubuntu server 24.04 does not support running MSSQL 2017
> meta(mssql): use ubuntu-20.04 for tests on 2017

- packages/core/package.json
This makes sure that the new alpha versions are published on the latest tag and used by people. This is similar to how we publish the other packages (like the dialect ones)
> meta: remove alpha tag from core package

- packages/mariadb/src/query.js
Fixes [https://github.com/sequelize/sequelize/security/code-scanning/75](https://github.com/sequelize/sequelize/security/code-scanning/75)
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
> fix(mariadb): fix inefficient regular expression in error message

- packages/core/src/decorators/legacy/attribute.ts
- packages/core/src/decorators/shared/model.ts
- packages/core/test/unit/decorators/attribute.test.ts
Adds the ability to specify the position of inherited attributes in models.
The current behaviour is that all inherited attributes are added after the models' own attributes.
With this PR, you can now choose to use this behaviour or specify for the inherited attributes to appear before the models' own attributes.
> feat: respect position of inherited attributes

- packages/mssql/package.json
- packages/mssql/src/_internal/connection-options.ts
- yarn.lock
Fixes the build error for MSSQL in #17267
MSSQL `textsize` connection option accepts number not string.
> fix(mssql): update mssql to v18.6.1

- .github/workflows/ci.yml
- dev/mariadb/10.3/start.sh
- dev/mariadb/10.3/stop.sh
- dev/mssql/2019/docker-compose.yml
- dev/mssql/2019/start.sh
- dev/mssql/2019/stop.sh
- dev/mysql/5.7/start.sh
- dev/mysql/5.7/stop.sh
- dev/mysql/8.0/start.sh
- dev/mysql/8.0/stop.sh
- dev/oracle/18-slim/start.sh
- dev/oracle/18-slim/stop.sh
- dev/oracle/23-slim/start.sh
- dev/oracle/23-slim/stop.sh
- dev/postgres/10/start.sh
- dev/postgres/10/stop.sh
- src/dialects/postgres/connection-manager.js
- src/sql-string.js
- test/unit/sql/where.test.js
This adds input validation as a workaround to prevent SQL injection using `TO_TIMESTAMP` or `TO_DATE`. It's not pretty, but it should do the trick while we fix it properly in v7 where the internals should be more suitable. This fix is the least intrusive.
> fix(oracle): validate input with TO_TIMESTAMP_TZ and TO_DATE

- packages/mariadb/package.json
- packages/mariadb/src/_internal/connection-options.ts
- yarn.lock
Closes #17502
MariaDB uses `queryTimeout` instead of `timeout` in connection options.
> fix(mariadb): update mariadb to v3.3.2

- packages/core/src/model.js
- packages/core/test/integration/model/update.test.ts
- packages/core/test/integration/model/upsert.test.js
- packages/core/test/unit/query-generator/arithmetic-query.test.ts
- packages/core/test/unit/query-generator/insert-query.test.ts
- packages/core/test/unit/query-interface/decrement.test.ts
- packages/core/test/unit/query-interface/increment.test.ts
- packages/core/test/unit/query-interface/insert.test.ts
- packages/core/test/unit/query-interface/update.test.ts
- packages/core/test/unit/sql/insert.test.js
- packages/core/test/unit/sql/update.test.js
- packages/core/test/unit/sql/where.test.ts
- packages/db2/src/query-interface.js
- packages/db2/src/query.js
- packages/ibmi/src/query.js
- packages/mssql/src/query.js
- packages/postgres/src/query.js
- packages/sqlite3/src/dialect.ts
- packages/sqlite3/src/query-generator.js
- packages/sqlite3/src/query.js
This is another change split from #16988.
This PR unifies the way data from the database is mapped to a Model instance for inserts, updates and upserts.
SQLite now supports returning database values from inserts, updates and upserts.
> fix: unify returning queries 

- src/dialects/abstract/query-generator.js
In MySQL strings can equal 0 so this protects against a type casting attack.
> fix: cast numbers in DataTypes.STRING to strings

- packages/core/src/model-definition.ts
- packages/core/src/model.d.ts
Closes #17569.
This change is only around the type annotations, so it should not cause any runtime regressions. I'd be happy to add some type-level tests but I'm not really sure how to pull that off in a reasonable way.
Improves the type declaration for model validation functions. Currently the declaration forces validation functions to return a `boolean` even though that value is never used.
This should not be a breaking change - except on the type level and only in case the original (faulty) types are already being followed.
> fix(core): Improve type declaration for model validation functions

- nx.json
The `tasksRunnerOptions` has been deprecated. Custom task runners will no longer be supported in Nx 21
> fix: remove deprecated tasksRunnerOptions

- packages/core/src/model.d.ts
This change is only around the type annotations, so it should not cause any runtime regressions. I'd be happy to add some type-level tests but I'm not really sure how to pull that off in a reasonable way.
This is a small follow-up on https://github.com/sequelize/sequelize/pull/17586 where the `this` argument for the model validation functions is typed as `M` (an instance of the model class itself), but in reality it does not necessarily have all the model fields available. Using `CreationAttributes<M>` seems like a reasonable choice that is both practical and does not promise too much.
This should not be a breaking change - except on the type level and only in case the code relies on fields on `this` that may not really be there.
> fix(core): Further improve type declaration for model validation functions

- packages/core/src/model-definition.ts
- packages/core/src/model.d.ts
This change is only around the type annotations, so it should not cause any runtime regressions. I'd be happy to add some type-level tests but I'm not really sure how to pull that off in a reasonable way.
This is yet another small follow-up on https://github.com/sequelize/sequelize/pull/17586 and https://github.com/sequelize/sequelize/pull/17686. I rushed a bit too much towards a fix for the issues we were seeing in our code base and overdid the weakening of the type for the the `this` argument in model validation functions. Specifically, the type now in the `main` branch disallows model method calls on the object that is being validated - but such calls work just fine.
This PR contains two changes:
1. It strengthens the type from `CreationAttributes<M>` to a type that also includes all …
> fix(core): Adjust model validator types yet again

- packages/core/test/integration/query-interface/createTable.test.js
- packages/postgres/src/query-interface.js
`ensureEnums` prepares a query per enum and puts them in a results array, in-enum-column-order. It can look like this:
```
results =[
{
enum_name: 'enum_SomeTable_someEnum',
enum_value: '{value1,value2,value3}'
},
null,
{
enum_name: 'enum_SomeTable_someEnumb',
enum_value: '{value1,value2,value3}'
},
null
]
```
However, the index that increments through the enum results array is only happening if an enum already exists and we edit it. This can cause an issue where, if the first enum is in the results array, it can prevent `ensureEnums` from creating other missing enum columns.
This PR adds a test that exposes the issue and then I move the increment into the correct scope.
> fix(postgres): correct existing enum type matching

- .github/workflows/ci.yml
Builds using Node 10 were broken due to an incompatibility of the build process in ibm_db and python 3.11+. This fixes it for now
> ci: use ubuntu-22.04 for jobs that use Node 10

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
The goal of this PR is to start using the new issue types instead of labels in our repository
I have not yet removed the labels from the issue templates, because I cannot find any documentation for non-form issue templates that talk about issue types. This is a test PR to see if it even works
If it works, we'll be able to replace our labels with issue types
> meta: use issue types instead of labels

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
This PR is a follow-up on https://github.com/sequelize/sequelize/pull/17753, now that issue types have been tested with success:
- https://github.com/sequelize/sequelize/issues/17755
- https://github.com/sequelize/sequelize/issues/17754
We'll still need to replace all existing bug/feature labels with issue types, on older PRs.
I don't know if there is an automated way to do this yet
> meta: remove bug/feature labels from issue templates

- packages/utils/package.json
The build process notes that the types export is redundant, node export only for require and import options.
> fix: remove redundant types export in package.json
