sequelize/sequelize

docs/api/sequelize.md, docs/articles/getting-started.md, docs/docs/installation.md, docs/docs/usage.md, docs/index.md
Added MSSQL to the documentation to reflect its support. Also note, postgres was added to dialectOptions support. Probably, should have been another commit/pull request. ¯\\_(ツ)_/¯
=> Add MSSQL to documentation

changelog.md, lib/dialects/mssql/query-generator.js, lib/dialects/mssql/query.js, lib/model.js, test/model.test.js
See #2847.
This throws an error similar to the one that's thrown if `Model.update()` is called with no where clause. I couldn't find a test that checks the same for `.update()` so I added one there too.
=> Throw an error if no where clause is given to Model.destroy()

test/instance/update.test.js
Sequelize tries to optimize which fields are being updated by
checking previous data values, and determining whether or not
fields should be used in an UPDATE clause. Unfortunately, the
case where NO fields should be used in the clause was never
checked.
I'm just committing the broken test here, I'm on vacation :smile:
=> broken test for update short path

docs/docs/models.md
Period codes were displaying incorrectly when wrapped in a code block: 
> This is possible since `v1&period;6&period;0` and is called eager loading
Changed that to display periods correctly.
=> fix formatting of periods

package.json
IMHO `pg-hstore` should only be installed if the developer is using PostgreSQL, that's why I moved it to `devDependencies`. If this PR gets merged we should also update the docs regarding pg integration.
The version was also bumped since it includes [an update](https://github.com/scarney81/pg-hstore/pull/19) when parsing objects.
=> Move pg-hstore to devDependencies

docs/articles/getting-started.md
Referencing issue https://github.com/sequelize/sequelize/issues/2899. 
Many of the code snippets that should have had a colon instead had a period. Periods were appropriate for some code blocks (and I left those as periods), but these should have colons:
=> Changed periods to colons before code snippets

docs/articles/getting-started.md
I thought these couple sentences were easier to understand with a quick re-wording.
=> .docs-fixed typos in getting-started.md

lib/dialects/abstract/index.js, lib/dialects/abstract/query-generator.js, lib/dialects/mssql/index.js, lib/dialects/mssql/query-generator.js, lib/dialects/mssql/query.js, lib/dialects/postgres/index.js, lib/dialects/postgres/query-generator.js, lib/query-interface.js, test/model/create.test.js
The dialect support for return values has been refactored
to make detecting it more readable for the two dialects
that currently support it. Tests have also been added for
regular creates as well as bulkCreates for returning these
values
=> refactor support for return values on insert/update

lib/dialects/mssql/index.js, lib/dialects/mssql/query-generator.js, lib/dialects/mssql/query.js, lib/query-interface.js, test/associations/belongs-to-many.test.js, test/associations/has-many.test.js, test/instance.test.js, test/instance/update.test.js, test/model.test.js, test/model/and-or-where.test.js, test/query-interface.test.js, test/sequelize.test.js
Up until now the mssql dialect has been using pseudo schema support
a la the mysql dialect, even though it supports real schemas. This
changeset adds full support for mssql schemas to the dialect, as
well as a few relevant changes (specifically using bracket notation
for object references, instead of quotation marks).
=> add proper schema support for mssql dialect

lib/dialects/abstract/query-generator.js, test/include.test.js
Fixes #2906.
Breaking change: it is mandatory to provide the order when using the array notation.
@mickhansen I think we should create an abstract query-generator test file and add the missing tests there. I can also check if the number of arguments in the array is 1 and keep the BC in that case. Thoughts?
=> Add order keywords whitelist

lib/dialects/mssql/connection-manager.js
Per the [tedious api](http://pekim.github.io/tedious/api-connection.html#function_newConnection), dialectOptions should be placed in config.options.
=> Fix where dialectOptions are placed in the config object

docs/docs/getting-started.md
Found a typo in the getting-started doc. Believe this edit clarifies intention.
=> Fix typo in getting-started.md

docs/docs/associations.md
This behavior surprised some of us coming from hibernate.
Perhaps the root problem was that I didn't know to look here: 
http://sequelize.readthedocs.org/en/latest/api/associations/#hasonetarget-options
=> Clarify location of foreign key.

lib/promise.js, package.json
"Significantly improve parallel promise performance and memory usage (+50% faster, -50% less memory)", https://github.com/petkaantonov/bluebird/blob/master/changelog.md#260-2015-01-06
Thought this should be added :)
It's backwards-compatible and the sequelize tests run green
=> updated bluebird to 2.6.2

docs/docs/associations.md
Added missing curly brackets in Associations docs for Belongs-To-Many
=> docs(associations): missing curly brackets in Belongs-To-Many

docs/docs/models.md
These changes should make this more readable:
=> Updated punctuation on models.md

lib/instance.js
The `instance.increment` (and also, by extension, the `instance.decrement`) function was not mapping field names for passed fields, or the primary key. This fixes that using conventions found elsewhere in the instance.js file.
=> Field Name mapping was not being run on increment/decrement functions

lib/dialects/sqlite/connection-manager.js, lib/sequelize.js, test/transaction.test.js
When committing transactions on in-memory (:memory:) sqlite databases the connection should not be closed - closing the connection causes the database to be dropped/reset. This request contains a test as well as a (somewhat hacky) solution to this problem.
=> Prevent closing connections on transaction commit on sqlite in-memory databases

docs/docs/models.md
A series of typo fixes in the "model" portion of the docs.
=> fix typo in docs

lib/model-manager.js
Fixes support on node@0.11.15+ and io.js.
=> Fix assignment to read only property on `getDAO()`

.travis.yml
In 2 days, Travis-CI will start officially supporting postgresql 9.4. All tests pass on this version.
=> Use postgresql 9.4 on .travis.yml

docs/api/sequelize.md, lib/dialects/mysql/query-generator.js, lib/sequelize.js, test/integration/dialects/mysql/query-generator.test.js
The initial AUTO_INCREMENT value for the table.
=> Add options.autoIncrement to MySQL

lib/dialects/mssql/connection-manager.js
This PR checks if in the passed dialect options for MS SQL an instanceName property was defined. It sets the instanceName property on the config and omits the port property, so that the tedious library will use the instance name instead of direct port connection.
Note: if a port and a instanceName would have been provided, tedious would throw an exception.
Tested with a local SQLExpress 2008 installation.
Signed-off-by: Luca Moser <l.moser@triumph-adler.ch>
=> Adds support for instance name based MS SQL connections.

lib/dialects/abstract/query-generator.js, test/integration/dialects/postgres/dao.test.js
The escaping system used for `findOrCreate` mangles any data that has `$` in it so insertions into JSON columns with values of that sort become incorrectly escaped.
This patch makes a minor alteration to the way functions are generated. The typical `$$` delimiter is problematic, user data could quite easily contain that, so instead a dynamically generated one is introduced. The probability of user data conflicting with a UUID seems exceedingly low.
This should fix a problem where this will work:
Model.create({ name: 'test', json_column: { value: '$$' })
Yet this will not due to escaping conflicts:
Model.findOrCreate({ where: { name: 'test' }, { defaults: { json_column: { value: '$$' } })
This should also fix other situations where, for whatever reason, the procedure was wrapping around …
=> Improvements to Postgres function escaping, use dynamic delimiter to avoid conflict with data

lib/dialects/mssql/connection-manager.js
https://github.com/sequelize/sequelize/pull/3098 introduced a regression in MSSQL ConnectionManager when `config.dialectOptions` was undefined, causing an exception:
```
Possibly unhandled TypeError: Cannot read property 'instanceName' of undefined
at [...]/node_modules/sequelize/lib/dialects/mssql/connection-manager.js:36:30
```
This patch changes it so that the existence of `config.dialectOptions` is checked before trying to access it's properties. It might be a good idea to add a test case to connection-manager.test.js that tests that connections without certain options set.
=> Fix regression in MSSQL ConnectionManager

docs/docs-generator.js
There is an issue with the docs generator that is causing param comments that offer more than 2 acceptable types to break formatting, pushing the third parameter into the Description box, and causing the description to be completely lost.
You can see this problem here, where the `options*` parameter has a description of `String`.
[Docs](http://sequelize.readthedocs.org/en/latest/api/model/#scopeoptions-model) | [Source comment](https://github.com/sequelize/sequelize/blob/6f46f9802f01461a069c6e3ea22c207153ced9e9/lib/model.js#L501)
This was caused by use of String.prototype.replace with a substring argument, which is not a global replace, so subsequent pipes after the first in a param list would not be HTML-entity-ized. This patch simply changes them into regex with global flags. …
=> Fix non-global string replace for docs

lib/data-types.js, lib/dialects/postgres/query-generator.js, lib/dialects/postgres/query.js, lib/dialects/postgres/range.js, lib/errors.js, lib/model.js, lib/sequelize.js, test/integration/dialects/postgres/dao.test.js, test/integration/dialects/postgres/error.test.js, test/integration/dialects/postgres/range.test.js, test/integration/sequelize.test.js, test/integration/support.js
This pull request contains basic support for built-in range datatypes (can be extended to support custom user-defined types though but I don't know any use cases for it yet, moreover it will be still returning them but as a strings).
You can read more about range types in official documentation ([here](http://www.postgresql.org/docs/9.4/static/rangetypes.html)).
Why is usage of range datatype interesting? Mostly because of flexibility for constraints it allows to create. While UNIQUE is a natural constraint for scalar values, it is usually unsuitable for range types. Instead, an exclusion constraint is often more appropriate. Exclusion constraints allow the specification of constraints such as "non-overlapping" on a range type.
By default, column type can be simply specified as …
=> [PostgreSQL] Support for range datatype

lib/model.js, lib/query-interface.js, test/integration/model.test.js
I was trying to run a complex count query that utilized multiple attributes and group by columns. The query was built fine, but I was only getting back the first row of results. I determined that this was due to the `rawSelect` function defaulting `plain` to true.
I added a couple lines to allow `plain` to be set to false in the passed options and if that is done, the data is returned as is.
=> Allow overriding `plain` in rawSelect functions

lib/sequelize.js, test/integration/sequelize.test.js
Tagged SQL queries are queries constructed via ES6 tagged template
strings. For instance, one can do:
```js
var result = sql`SELECT ${1} AS "var"`;
```
The `sql` tag can transform the template string so that it returns
something like:
```js
var result = { query: 'SELECT ? AS "var"', values: [1] };
```
This makes it ideal for writing elegant SQL by passing the tagged query,
contaning the `query` and `values` properties to `sequelize.query`.
This support could remain for *internal* usage only for now.
=> Add support for tagged SQL queries

lib/hooks.js, lib/model.js, lib/sequelize.js
The existing Hooks mixin explicitly defines methods for all hooks on
the Sequelize instance or a given Model. This modifies the Hooks module
to provide a single method "applyTo", which mixes in the base Hook
functionality (addHook, runHooks, etc), as well as autogenerates
declarative hooks for the object its mixing in to (Model.beforeCreate,
Sequelize.beforeDefine, etc).
**NOTE:** the hooks and hookAliases are also exported in expectation of another PR I can get up soon (hopefully) that cleans up the hooks tests by generating them programmatically rather than 4k lines of explicit tests
=> refactor Hooks mixin

lib/query-chainer.js
Removing the warnings of:
success|ok() is deprecated and will be removed in 2.1, please use promise-style instead.
failure|fail|error() is deprecated  and will be removed in 2.1, please use promise-style instead
When using the QueryChainer().add()
=> Changing query-chainer to promise-style

lib/dialects/abstract/query.js, lib/dialects/postgres/query.js, lib/dialects/postgres/range.js, lib/model.js, test/integration/dialects/postgres/dao.test.js
Well, this pull request includes some refactored code for processing "custom" fields (i.e., `RANGE` and `HSTORE`) as well as fix for such fields to be parsed in child models (which were apparently not being processed, only those in parent model were).
In terms of performance, spy-js was used to check it and results show that there is no performance degradation while parsing child model attributes in a way, proposed by this pull request.
Also, tests for such cases were added as well. :wink:
=> [PostgreSQL] Parsing included fields of HSTORE and RANGE datatype

docs/articles/getting-started.md, docs/docs/instances.md, docs/docs/models.md, docs/index.md, lib/instance.js
Would you mind, if I'd insert a "Deprecated" area? I think it's useful to keep old information but to keep depcreated stuff separated from the rest of the docs.
=> Docs: replace .values with .get({plain: true})

lib/dialects/mssql/connection-manager.js
Tedious error events must be handled in the connection manager in
order to prevent said errors from crashing an app using sequelize
to connect to a mssql database.
=> prevent tedious errors from taking down app

lib/dialects/mssql/connection-manager.js
The previous commit incorrectly invalidated the connection, when we
should really be removing the connection from the pool completely.
This also fixes an error in the disconnect logic, which was erroneously
checking connection.connected to identify an already disconnected
connection.
=> fix tedious error handling

lib/errors.js, test/integration/error.test.js
Before:
```
Possibly unhandled SequelizeValidationError: Validation error
at /home/phanect/dev/notel-api/node_modules/sequelize/lib/instance-validator.js:150:14
...
```
After:
```
Possibly unhandled SequelizeValidationError: field_name cannot be null
at /home/phanect/dev/notel-api/node_modules/sequelize/lib/instance-validator.js:150:14
...
```
=> Show more appropriate error message for model validation error

lib/dialects/abstract/query-generator.js, test/integration/associations/belongs-to-many.test.js
Adds a failing unit test and proposed fix for #3279 
The fix might be a bit naive, so if you just want the failing unit test I can pluck that commit out instead.
=> Fix invalid column name in many-to-many JOIN query

lib/dialects/abstract/query-generator.js, test/unit/sql/where.test.js
Basically adds the NOT operator in front of whatever tuple generated if $not: {anything} is used.
=> $not as grouping comparator

lib/dialects/abstract/query-generator.js, test/unit/sql/where.test.js
```js
Model.findAll({
where: {attr: {$in: sequelize.literal('…')}}
}).then(…);
```
=> $in and $notIn support literals.

lib/sequelize.js, test/integration/sequelize.test.js
If I define default getters and setters and create a Modle with some getter / setters themselves, the default ones won't be added.
I think we should handle getters & setters the same way we handle classMethods & instanceMethods.
=> Recursive Extend Model Default Options for getterMethods and setterMethods

lib/instance.js, test/integration/instance/update.test.js
The update method of an instance keeps track of possible side effect of setter methods and includes affected attributes in the save. Should fix #3221
=> .update include attributes changed by setter methods

lib/dialects/sqlite/query-generator.js
Looks like regression bug described in #3113 was still present in SQLite. This PR fixes that.
=> fix: use new whereQuery in SQLlite updateQuery

lib/query-interface.js, test/integration/query-interface.test.js
Sequelize was creating ENUM Types with only the attribute's key name.
This is not always a problem, but if we add a 'field' value to the attribute, the CREATE TABLE SQL will use that value to fetch the created ENUM, and fail.
```JS
this.queryInterface.createTable('SomeTable', {
someEnum: {
type: DataTypes.ENUM,
values: ['value1', 'value2', 'value3'],
field: "otherName"
}
});
```
Would create ENUM Type enum_SomeTable_someEnum
And create table would look for a ENUM Type enum_SomeTable_otherName
=> Fix ENUM Type Name

lib/associations/mixin.js
On line 19, 'useful' was misspelled as 'usefull'. It has now been changed to its proper spelling.
No other changes have been made to this document or the rest of the repo :)
=> Fixed misspelling in mixin.js

lib/errors.js, lib/instance-validator.js, test/integration/error.test.js
Sequelize.ValidationError now uses provided message if available, previously any provided message was simply discarded.
=> Bugfix: sequelize validation error discarding custom message

docs/api/associations.md, docs/api/datatypes.md, docs/api/errors.md, docs/api/hooks.md, docs/api/instance.md, docs/api/model.md, docs/api/promise.md, docs/api/sequelize.md, docs/api/transaction.md, docs/docs-generator.js, lib/hooks.js
When attempting to build the docs through `npm run docs`, I encountered some errors relating to some things being undefined. Exact error can be found below.
Some digging brought up two things.
* The usage of `_.where` inside `getTags()` - `docs/docs-generator.js`
* Some comment sections in `lib/hooks.js` that didn't have a code body directly below them (probably as a result of some refactoring).
Potential fixes for both are here, along with rebuilt docs. Let me know if there's something in here that needs another looking at. Thanks!
```
> sequelize@2.0.5 docs /Users/harimohanraj/Code/os/sequelize
> node docs/docs-generator.js
/Users/harimohanraj/Code/os/sequelize/docs/api/errors.md
/Users/harimohanraj/Code/os/sequelize/docs/docs-generator.js:91
if (paramTag.name.indexOf('.') === -1) {
^ …
```
=> Some fixes to docs generator

changelog.md, lib/query-interface.js, test/integration/instance.validations.test.js
This fixes an issue that has been mentioned a few times about unique constraints not working when using `Model.update()`. I simply set `dao.__options` = `dao.options` and it didn't seem to cause any issue, however I wouldn't be opposed to doing an `||` check in each of the dialect implementations as mention in a previous PR (it just seemed like excessive work)
=> Allow Model.update() to handle unique constraints - Fixes #3474

lib/dialects/mysql/query.js, lib/dialects/postgres/query.js
The error messages are not parsed in a multi language friendly way. If the database in use is not english, error messages are checked with a match that might fail. This fixes the app crash.
This is definitly not a very good solution but more a kind of a hotfix. After all some time should be invested to check if there's a better solution. I couldn't come up with a good regression test for this either. Probably the best way to write a regression test for this is to fake each error with a foreign language. I do not have the time for that right now though.
=> Foreign languages used in the db might crash the app

lib/dialects/sqlite/query-generator.js, test/integration/dialects/sqlite/query-generator.test.js
Given the following Employee:
var Employee = sequelize.define("Employee", {
id: {
type: dataTypes.INTEGER,
autoIncrement: true,
primaryKey: true
},
name: dataTypes.STRING
});
When the Sync() is called
Then I expect the following create statement:
CREATE TABLE IF NOT EXISTS `Employees` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `name` VARCHAR(255));
But got:
CREATE TABLE IF NOT EXISTS `Employees` (`id` INTEGER PRIMARY KEY, `name` VARCHAR(255));
=> Sqlite: AUTOINCREMENT wasn't present in the create statement when field is primary key.

lib/dialects/postgres/query-generator.js
If you were to run a migration like this:
```javascript
down: function (queryInterface, Sequelize) {
return queryInterface
.removeColumn(
{
tableName: 'test_table',
schema: 'awesome_schema'
},
'name'
);
}
```
A migration down gives an error:
```
Possibly unhandled TypeError: Object #<Object> has no method 'indexOf'
at Object.module.exports.QueryGenerator.quoteIdentifiers (/Users/petemertz1/dev/lynx-core/node_modules/sequelize/lib/dialects/abstract/query-generator.js:752:23)
at Object.module.exports.QueryGenerator.removeColumnQuery (/Users/petemertz1/dev/lynx-core/node_modules/sequelize/lib/dialects/postgres/query-generator.js:227:25)
at module.exports.QueryInterface.removeColumn (/Users/petemertz1/dev/lynx-core/node_modules/sequelize/lib/query-interface.js:361:37)
at …
```
=> With dialecets in postgres, removeColumn currently fails.  This fixes it

changelog.md
* first commit fixes a typo in the changelog
* second commit adds a hint at a migration path from `.success` to `.then` to the notes for the 2.1.0 release.
=> add hint at migration path to `.then` to 2.1.0 notes.

package.json
This should fix the issue that iojs 2.0 does not run the sqlite tests on travis.
Reference #3653
=> Update sqlite dev dependency to fix an issue with nan and travis

lib/sequelize.js, test/integration/transaction.test.js
The pool of transactions will be drained if errors occur in the transaction block. 
Without the patch the following will result in:
```javascript
sequelize.transactions(function(t) {
throw new Error('test');
});
```
Executing (280fa819-4f22-4c4d-a511-3a262e1040a0): START TRANSACTION;
Executing (280fa819-4f22-4c4d-a511-3a262e1040a0): SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
Executing (280fa819-4f22-4c4d-a511-3a262e1040a0): SET autocommit = 1;
----
Missing: `Executing (280fa819-4f22-4c4d-a511-3a262e1040a0): ROLLBACK;`
=> Fix transactions not rolling back properly

.travis.yml, changelog.md, lib/model.js, lib/sequelize.js, lib/utils.js, test/integration/associations/belongs-to-many.test.js, test/integration/include/findAll.test.js, test/integration/model/and-or-where.test.js, test/integration/model/update.test.js, test/integration/transaction.test.js
This fixes the regression introduced in 2.1.2 and fixes the build script to use iojs 1.0 as long as travis can't install the proper nan version (needed for pg-native).
I also inserted missing changelog entries and fixed a deprecation message in a test.
=> Fix build and regression

changelog.md, lib/dialects/postgres/query-generator.js, test/integration/query-interface.test.js
Fixes #3693
This is part of an effort to get indexing on tables with schemas working.  showIndexesQuery needs to be able to support a tableName when it has a schema (it currently returns incorrect results - an empty set - when there is a schema included).
Since pg_class doesn't contain schemas the fix is to use the tableName only as my investigation shows that this will return the correct indexes for the table.
=> fix showIndexQuery so appropriate indexes are returned when a schema is used

lib/instance.js, test/integration/instance.test.js
If the instance is under multiple primary keys, the `where` section of query string should using multiple primary keys.
=> fix a bug that using `Instance::destroy()` under multiple primary keys

lib/promise.js, package.json, test/integration/cls.test.js
This is a fix for https://github.com/sequelize/sequelize/issues/3686.
I decided to shim only the documented bluebird API so it's less likely to break due to internal changes.
I basically shimmed all bluebird methods that accepts functions except `try` and `method` since the former call the function synchronously and the later just wrap the function.
I tested the change with my code base and it works. To be honest, I most probably have no idea what I'm doing here so a thorough review is more than welcome.
=> Fix CLS propagation for all Bluebird methods

lib/sql-string.js, package.json, test/integration/timezone.test.js
Hello,
Sequelize does not appear to support named timezones (such as `America/Los_Angeles`), so an application using Sequelize must manually change the `timezone` option if the database's UTC offset changes (such as when daylight savings kicks in).
Although the documentation does not mention support for this, digging around I found issue #2059, which seems to imply support for this behavior. However, using a named timezone identifier as an option (no matter what the timezone) results in the data always being inserted as UTC (wheras using a numeric offset, such as `-07:00` works as expected).
I'm a little curious as to whether this was ever supported, or if I'm just misunderstanding things. If I'm on the right track with this, let me know if you’d like me to clean up the testing and docs …
=> add support for named timezones

lib/dialects/postgres/query-generator.js
Hi,
Actually the postgres delimiter for define a function is $$.
An error are returned if we have this delimiter in the query ('joey bada$$' for example)
So I propose to change the delimiter $$ to $func$ which is less common
=> Change postgres delimiter

lib/model.js, test/integration/model.test.js
So when using `Model.prototype.update` to update the table there's an issue if you're using some kind of magic setter like so:
```js
var User = sequelize.define('User', {
name: DataTypes.STRING,
age: DataTypes.INTEGER,
details: {
type: DataTypes.VIRTUAL,
set: function (value) {
this.set('name', value.name);
this.set('age', value.age);
}
}
}
```
This isn't a tremendously salient example but it comes up quite frequently when you're trying to obfuscate complex data types from an API. My line of thought is that the following:
```js
Model.User.update({ details: { 'age' : 40, 'name' : 'Bill' } }, { where: { name: 'Tim' } });
```
Should have the effect of updating age and name through the details setter. At the moment it doesn't as update doesn't have an impact on side effect attributes. This …
=> Allow updating virtual setter side effects from Model

changelog.md, lib/model.js, test/integration/hooks.test.js
I also removed some old callbacks from some hooks.
=> instance.changed() in beforeUpdate hook would always be false. Fixes #3631

lib/utils.js, test/unit/utils.js
This pull request implements the fix mentioned here:
https://github.com/sequelize/sequelize/issues/3016
Basically, the call to Error.captureStackTrace(...) was in 'this' as the 2nd parameter.  However, 'this' was not actually a reference to the function itself; instead, it was a reference to the object that owned the function.  Consequently, the 'stack' function was not filtered from the stacktrace properly.
=> Call stacks are computed properly

changelog.md, docs/docs/associations.md, examples/enforce-referential-integrity/models/Series.js, examples/enforce-referential-integrity/models/Video.js, lib/associations/belongs-to-many.js, lib/associations/helpers.js, lib/dialects/mssql/query-generator.js, lib/dialects/mysql/query-generator.js, lib/dialects/postgres/query-generator.js, lib/dialects/sqlite/query-generator.js, lib/model-manager.js, lib/model.js, lib/sequelize.js, lib/utils.js, package.json, test/integration/associations/belongs-to-many.test.js, test/integration/associations/belongs-to.test.js, test/integration/associations/has-many.test.js, test/integration/associations/has-one.test.js, test/integration/dialects/mysql/query-generator.test.js, test/integration/dialects/postgres/query-generator.test.js, test/integration/dialects/sqlite/query-generator.test.js, test/integration/include/schema.test.js, test/integration/model.test.js, test/integration/model/attributes/field.test.js, test/integration/query-interface.test.js, test/integration/sequelize.test.js, test/integration/utils.test.js, test/unit/utils.test.js
This PR transforms the `references` property of a model column into an object and groups the key property below it, too.
Relates to https://github.com/sequelize/sequelize/pull/3702
=> Make `references` an object

lib/sequelize.js
PR #3754 was an horrible attempt to edit the API docs.
This PR is the correct one.
=> Add 'mssql' as dialect option in API docs (replaces #3754)

changelog.md, docs/api/associations.md, docs/api/datatypes.md, docs/api/deferrable.md, docs/api/errors.md, docs/api/hooks.md, docs/api/instance.md, docs/api/model.md, docs/api/sequelize.md, docs/api/transaction.md, docs/docs-generator.js, docs/docs/models-definition.md, docs/docs/transactions.md, lib/deferrable.js, lib/dialects/abstract/index.js, lib/dialects/abstract/query-generator.js, lib/dialects/postgres/index.js, lib/dialects/postgres/query-generator.js, lib/query-interface.js, lib/sequelize.js, lib/transaction.js, lib/utils.js, mkdocs.yml, test/integration/sequelize/deferrable.test.js, test/unit/utils.test.js
This pull request allows the definition of deferrable constraints for foreign keys in PostgreSQL.
todo: 
New functions:
* Transactions can be initialized with a `deferrable` option that triggers a specific defer query after beginning the transaction 
* Model properties that references other models can now specify the option `references.deferrable` which adds the respective deferred fragment to the query
* `Sequelize.Deferrable` and `sequelize.Deferrable` are referencing an object that contains the possible options.
Example #1 for constraints that are initially immediate but temporarily deferred:
```
var Model = sequelize.define('model', {
some_id: { 
type: Sequelize.INTEGER,
references: {
model: SomeOtherModel,
key: 'id',
deferrable: Sequelize.Deferrable.INITIALLY_IMMEDIATE
}
}
})
return …
```
=> Deferrable constraints for PostgreSQL

changelog.md, lib/associations/mixin.js, lib/dialects/abstract/query-generator.js, lib/instance.js, lib/model.js, lib/transaction.js, lib/utils.js, test/integration/model/json.test.js, test/unit/sql/data-types.test.js, test/unit/utils.js
I'm uncertain if UUIDV1 and UUIDV4 is actually right for mysql and mssql. I guess it should be just as the general UUID? Fixes #3324 <s>(can't reproduce the error - seems to be fixed already).</s>
=> Fix regression in util.toDefaultValue not returning the data types. Closes #3324, #3002 and #3410

lib/sequelize.js, lib/sql-string.js
If Object.create('null') is used to create the object, it loses the
prototype. Calling hasOwnProperty through Object.prototype ensures that
hasOwnProperty is safely called. For further details, refer to the
comments on the issue.
=> Fixes #3799 hasOwnProperty is now called through Object.prototype

changelog.md, lib/dialects/mysql/query-generator.js, test/integration/dialects/mysql/query-generator.test.js
I took the freedom to do this since @sitexw did not respond anymore.
=> Add support for keyword `after` in options of a field. Closes #3166

docs/api/associations.md, lib/associations/mixin.js
Current typo as seen in the hasMany bullet:
=> Fixes typo in associations doc regarding Mixins (specifiy -> specify)

changelog.md, lib/associations/belongs-to.js, lib/associations/has-many.js, lib/model.js
In some cases `options.logging` is not being passed around within Sequelize correctly.
e.g. `Model#destroy()` does not pass `options.logging` to it's internal call to `Model#findAll()`.
This PR fixes these.
However, I'm not confident that I've found them all, and I guess it might need some test coverage. I'm opening a separate issue about this broader question.
=> Fix `options.logging` not being passed to queries

changelog.md, lib/data-types.js, lib/dialects/mssql/data-types.js, lib/dialects/mssql/index.js, lib/dialects/postgres/data-types.js, lib/dialects/sqlite/data-types.js, test/unit/sql/data-types.test.js
This fixes the issue found in #3827
=> Fix some data types in mssql and postgres

docs/api/associations.md, docs/api/datatypes.md, docs/api/deferrable.md, docs/api/errors.md, docs/api/hooks.md, docs/api/instance.md, docs/api/model.md, docs/api/sequelize.md, docs/api/transaction.md
The "view code" link is currently a broken link across the docs. This updates the links to point to the latest release tag (3.1.1)
=> Update API docs view code links

changelog.md, lib/data-types.js, lib/dialects/mssql/data-types.js, lib/dialects/mysql/data-types.js, lib/dialects/postgres/data-types.js, lib/dialects/sqlite/data-types.js, test/unit/sql/data-types.test.js
This is on top of #3836 and I wanted to get your feedback what you think about the implementation. So you only have to look at the "Initial commit" changes.
If someone uses a data type in a way that is not supported we'd now warn the user about it including what we do instead and presenting the link to the data types as they are in the current dialect.
=> Type warnings

docs/docs/migrations.md, lib/sequelize.js
1. Update migrations.md section on programmatic use to point to uzmug
1. Removed Sequelize.prototype.migrate as it call getMigrator() which no longer exists
=> removed references to getMigrator()

lib/instance.js, test/integration/instance.test.js
When creating an instance, there is no 'truthiness' check performed on the primary key, which allows creating an instance with a primary key of 0.
This instance can be queried for with no issues, but, currently, the instance cannot be updated, because there is a simple boolean check and a value of 0 fails. This pull request changes the check to look for `undefined`.
I'm not sure if the unit test I wrote is sufficient. Let me know how else I could check it.
=> Allow instance with primary key of 0 to update

changelog.md, lib/dialects/postgres/query-generator.js, test/unit/sql/json.test.js
Currently, generating an array of JSONB elements in postgres incorrectly specifies the type as `::JSON[]` in the generated query, resulting in an error:
```
SequelizeDatabaseError: column "my_array_column" is of type jsonb[] but expression is of type json[]
```
Since `DataTypes.JSONB` inherits from `DataTypes.JSON`, both cases fall into the same clause, which doesn't handle `JSONB`.
=> Fix generating JSONB arrays in postgres.

.travis.yml
See #3653
io.js v2 is working again on Travis!
I've changed .travis.yml to track against the latest version of the last two major releases. When 3.0 is released, I think there would be a good case for changing travis support to test against v2.x and v3.x.
=> Reenable iojs v2 testing on travis

test/integration/configuration.test.js
On my local machine (OS X 10.9.5, MySQL 5.6.19, Node 0.12.2, Sequelize latest master), the test for "Connections problems should fail with a nice message when we don\'t have the correct server details" was failing consistently.
This fixes it on my machine, but not sure if this may work otherwise on other machines.
=> Fix MySQL failed connection test

changelog.md, lib/associations/has-many.js, lib/dialects/sqlite/query-interface.js, lib/instance.js, lib/model.js, lib/plugins/counter-cache.js, lib/query-interface.js, lib/sequelize.js, test/integration/query-interface.test.js
This PR fixes all the places in the codebase where `options.logging` was not being passed from one method call to child method calls. These cases resulted in the `options.logging` function not being called when SQL queries are executed.
All these cases were found using PR https://github.com/sequelize/sequelize/pull/3843.
=> Fix `options.logging` not being passed within Sequelize

lib/promise.js, test/integration/cls.test.js
Calling `.nodeify()` on a promise loses CLS context.
This PR fixes this.
=> Add CLS support to `nodeify` promise method

lib/sequelize.js
Fixed javascript casing to JavaScript in comments as per instructions given here: https://github.com/sequelize/sequelize/pull/3907 . No changes to markdown syntax were made.
=> Fixed typo in code comments

docs/api/sequelize.md
Fixed casing from javascript to JavaScript. Only changed description comments, no changes to markdown syntax or source files were made.
=> Fixed JavaScript spelling in API sequelize doc

changelog.md, lib/promise.js, test/integration/cls.test.js
Fixes https://github.com/sequelize/sequelize/issues/3909
Calling `.done()` on a promise was losing CLS context.
=> Add CLS support to `done` promise method

changelog.md, lib/dialects/abstract/query.js, lib/dialects/mssql/query.js, lib/dialects/mysql/query.js, lib/dialects/postgres/query.js, lib/dialects/sqlite/query.js, lib/model.js, test/integration/instance.validations.test.js
Unique constraint errors always returned a message in the form of `[fieldname] Must be unique`. This allows users to specify custom failure messages consistent with the style of other built-in validators.
Example:
```
var Model = Sequelize.define('model', {
name: { 
type: Sequelize.STRING, 
unique: { args: true, msg: 'custom unique error message' }
}
});
=> Add support for unique constraint custom error message

lib/instance.js
Avoids changes created by other's getters
=> .equals() should compare dataValues directly

docs/api/associations.md, docs/api/datatypes.md, docs/api/deferrable.md, docs/api/errors.md, docs/api/hooks.md, docs/api/instance.md, docs/api/model.md, docs/api/sequelize.md, docs/api/transaction.md, docs/docs-generator.js
None of the current links referenced in the **See:** sections of the [docs](http://docs.sequelizejs.com/en/latest/) are working. For example, clicking on [Sequelize#sync](http://docs.sequelizejs.com/en/latest/api/api/sequelize#sync) under the [Model documentation](http://docs.sequelizejs.com/en/latest/api/model/#sync) for `sync()`:  
brings you to to a page not found.
The issue is that the link automatically generated has repeated `/api` (see http://docs.sequelizejs.com/en/latest/api/api/sequelize#sync for an example where `/api` is repeated).
This PR removes the repeated `api/` from `docs-generator.js` and re-creates the associated documentation.
=> Fix incorrect paths created for "See:" links in docs generator 

lib/query-interface.js, test/integration/associations/has-one.test.js
hasOne actually means "has zero or one".
The current behavior of {onDelete:'cascade',hooks:true} looks for an associate and fails to execute ${non-existent instance}.destroy().
This patch checks for the non-existence and aborts gracefully.
=> handle hasOne onDelete cascade when no associate

package.json
moment-timezone is the only package out-dated today : https://david-dm.org/sequelize/sequelize
Changelog : https://github.com/moment/moment-timezone/blob/0.4.0/changelog.md
(for main part new IANA TZDB data)
Thanks !
=> Update moment-timezone to 0.4.0

lib/dialects/abstract/query-generator.js, lib/dialects/mssql/data-types.js, lib/dialects/mssql/index.js, lib/dialects/mssql/query-generator.js, lib/query-interface.js, test/integration/trigger.test.js, test/unit/sql/insert.js, test/unit/sql/update.js
closes https://github.com/sequelize/sequelize/issues/3284
adds a temp table to get the output rows of insert,update and delete
queries when there is a trigger on a table.
Sits behind a flag called hasTrigger on the model
Added tests that cover insert,update and delete queries
=> adds support for table triggers in mssql dialect

lib/model.js, lib/query-interface.js, test/integration/model/upsert.test.js
Currently, a `defaultValue` set on the model will be used in every upsert operation. This is fine for when upsert INSERTs, since that is when default values are used/needed. However, upsert is also using defaultValue on INSERT, which is causing data to be overwritten and lost by the default values. 
~~I've included a test that is currently broken by this bug, I haven't had time to look into a fix yet.~~ EDIT: fix also added
/cc @mickhansen @janmeier (from the last upsert issue we worked on)
=> upsert overwrites data with default values on update

test/integration/include/findAndCountAll.test.js
This is a test case for `findAndCountAll` returning an incorrect value for `result.count`, as the where statement in the include makes the `count()` sql function counts all rows instead (3 in this case) of only matching `Foo`s (2 in this case).
See issue #4015
=> Add failing test case for findAndCountAll with a include and where

lib/utils.js
lib/utils.js currently breaks lodash's includes() function in a project by mixing in its own includes() function. See example below (full example at https://github.com/appropos/sequelize-lodash-includes-bug)
var _ = require('lodash');
// Passes
assert(!_.includes(['foo-9', 'foo-10'], 'foo-1'));
require('sequelize');
// Fails
assert(!_.includes(['foo-9', 'foo-10'], 'foo-1'));
This PR simply removes the custom includes() function in favor of lodash's function. lodash's function works the same except for when `needle === ''` and `str` is falsy. So for the following examples, lodash will return `false` while the (current) custom function will return `true`:
Utils._.includes(undefined, '')
Utils._.includes(null, '')
Utils._.includes('', '')
At present, includes() appears to only be called with …
=> Don't override lodash includes() function.

lib/model.js, test/integration/model.test.js, test/integration/model/scope/count.test.js
having order option in model’s scope when performing a count kicked out
this error:
SequelizeDatabaseError: column “xxxx” must appear in the GROUP BY
clause or be used in an aggregate function
=> fixes problem with order in scope when counting

lib/model.js, test/integration/include/findAll.test.js
This bring in the changes discussed in #3920, disabling the automatic addition of the primary key field to the attributes returned by a query, and thereby allowing aggregation in more cases, when raw is set to true.
This includes the changes and tests. Is there any documentation anywhere that needs to be updated in line with this?
=> Do not automatically add primary key to attributes (or include[].attributes) if raw is set

docs/api/model.md, docs/docs/models-definition.md, lib/model.js
Here's a few fixes to broken links that point to the documents in the api/ directory.
To ease review I didn't run the api doc update script as it would've made the diff quite verbose. Instead I made the changes directly to both the jsdoc comment in lib/model.js and the generated file.
=> Fix broken links to api/ pages in the documentation.

lib/model.js
In upgrading from `2.1.3` to `3.x`, I noticed a bug.
I structure my service code written in Hapi in such a way that I declare my query options outside of specific request handlers. It looks something like this:
```js
// object literal is a singleton
const opts = { /* my opts */}
export function handlerFoo(request, reply) {
MyModel.findById(opts)
.then((data) => reply(data));
}
export function handlerBar(request, reply) {
MyModel.findAll(opts)
.then((data) => reply(data));
}
```
The way the code is currently written, the internals of `Model#findById` and similar calls actually modify in place the options passed to them. This is generally fine if the options were declared in the execution context of the request handler, but any *long-lived* objects are modified permanently, creating pretty …
=> Hotfix: Wrap referenced options arguments in _.clone

lib/model.js
Changes the name of the argument taken by `Model#findAndCount()` to `options`. Was previously `findOptions`.
This makes no functional difference - just brings it into line with the rest of the codebase.
=> Standardize `findAndCount` arguments

docs/docs/models-definition.md
It seems the author moved it's repository from [node-validator](https://github.com/chriso/node-validator) to [validator.js](https://github.com/chriso/validator.js).
=> Update documentation: node-validator is validate.js

changelog.md, lib/model.js, test/integration/cls.test.js
This fixes the issue. Sometimes the transaction from cls might be null and therefor should not be added.
I'll try to find a nice test too.
=> Do not add a transaction in findOrCreate if there is none. Fixes #4133

docs/docs/transactions.md
The previous example code is buggy because you need to get specified isolation level from Sequelize.Transaction.ISOLATION_LEVELS instead of Sequelize.Transaction.
=> Fix the bug in transactiona document.

lib/instance.js, lib/model.js
Currently the options are not passed along, which breaks ssaclAttributeRoles and might break other plugins.
Generally all options should just be propagated (unless they need to removed cause they will break the method).
=> update should pass options to set

lib/dialects/postgres/query.js
This simply adds the error message to the exception, so the root problem can more easily be diagnosed.
=> Include the error message in the exception to ease debug

docs/docs/instances.md
The documentation for the .create() function was incorrect in how to specify a filter for fields being saved.
=> Fix documentation of fields filter for create function

changelog.md, docs/docs/instances.md, lib/instance.js, test/integration/hooks.test.js, test/integration/instance.test.js
Hi,
This PR refers to cases where one instance is hydrated from database, some processing is done and no field changes, but when ```instance.save()``` is called one update with field ```updatedAt``` is sent to database. 
From my point of view even without the option silent turned on this SQL should not be sent. What you think?
=> Update sent to database when nothing changed in instance

lib/associations/mixin.js
Very small fix, it's now possible to control belongsToMany association timestamps, by default it uses global timestamp option value.
````js
Model.belongsToMany(Model, {
foreignKey:  'model_id'
through: 'my_through_table',
timestamps: false
});
````
=> Bug fix: #3266 - belongsToMany junction table timestamp

lib/model.js
The `@return` tag says that this method returns `Promise<Instance>`, while the
real return contains also an `initialized` boolean value.
Even though this behavior is already described in the JSDoc, it's more evident if
it's in the `@return` tag. I relied on it and my tests were breaking because I didn't
read the full docs for that method!
=> Update JSDoc of Model.prototype.findOrInitialize()

lib/data-types.js, test/unit/sql/data-types.test.js
Validating if a value is a string using typeof fails if the string has been created using `new String` this fixes this.
```javascript
var test1 = 'my test';
var test2 = new String(10);
console.log(typeof test1); # string
console.log(typeof test2); # object
console.log(Object.prototype.toString.call(test1)); # [object String]
console.log(Object.prototype.toString.call(test2)); # [object String]
```
I also have added a new assertion to cover that case.
=> String validation fix

lib/dialects/postgres/query-generator.js, test/unit/sql/delete.test.js
Hi.
When I tried like following code, sequelize generated wrong SQL.
var Sequelize = require('sequelize');
var sequelize = new Sequelize('db', 'user', 'pass', { host: 'localhost', dialect: 'postgres' });
var User = sequelize.define('test_user', {
id: {
type:       Sequelize.INTEGER,
primaryKey: true,
field:      "test_user_id",
}
}, { freezeTableName: true, timestamps:false });
User.create({id: 1}).then(function(u) {
console.log(u.id);
u.destroy().then(function(){
console.log('delete success !!');
}); // error
});
/* Log ---
Executing (default): INSERT INTO "test_user" ("test_user_id") VALUES (1) RETURNING *;
1
Executing (default): DELETE FROM "test_user" WHERE "id" IN (SELECT "id" FROM "test_user" WHERE "test_user_id" = 1 LIMIT 1) // *** WRONG SQL HERE
Unhandled rejection …
=> Fixed a bug that wrong sql generated when destroying in pg.

lib/instance.js, test/unit/instance/decrement.test.js, test/unit/instance/destroy.test.js, test/unit/instance/increment.test.js, test/unit/instance/reload.test.js, test/unit/instance/restore.test.js
I got "not-null constraint" error because the previous save(opt) call inserted "fields" into opt.
This may cause confusing errors.
=> option object shouldn't be updated internally.

lib/sequelize.js, test/integration/sequelize.test.js
When the authenticate method catches errors, it wraps those errors in a new Error() call, rather than just throwing the original error. This gobbles up the original name and message into the new error's message parameter, making it more difficult to make use of the error result than necessary.
What's currently happening:
```javascript
var seqError = new sequelize.Error('YOLO');
try {
throw new Error(seqError);
} catch (e) {
if (e instanceof sequelize.Error) {
console.log('Hooray, I can tell this is a Sequelize error!');
} else {
console.log('Bummer. I cannot easily distinguish this from a generic error.');
}
}
```
```
Bummer. I cannot easily distinguish this from a generic error.
```
What would be preferred:
```javascript
var seqError = new sequelize.Error('YOLO');
try {
throw seqError;
} …
```
=> Throw the original error from authenticate

docs/docs/models-usage.md
Clarify the phrases, "Notice that the accessor is singular/plural" - which may be confusing as the term, "accessor", typically refers to code
=> Docs: Clarify the phrases, "Notice that the accessor is singular/plural" in models-usage.md

changelog.md, lib/dialects/abstract/query-generator.js, test/unit/sql/where.test.js
Fixed `operator does not exist` exception when using queries like:
```js
{
'data.age': 4
}
```
Fixes: https://github.com/sequelize/sequelize/issues/3824
=> JSON: Cast key when using the equality operator

changelog.md, lib/dialects/abstract/query-generator.js, test/unit/sql/where.test.js
Respect custom field names when doing nested json queries like:
```
{
"metaData.audio.length": {
$gt: 20
}
}
```
where `metaData` has a custom field name defined.
=> Support custom field names in json queries

changelog.md, lib/dialects/sqlite/connection-manager.js, test/integration/configuration.test.js
SQLite allows different connection modes (READONLY, READWRITE, CREATE). This PR allows passing through these options via `dialectOptions.mode` which was kind of expected in the first place. By default is sets the connection mode to sqlite's default which is READWRITE | CREATE.
Added some tests to verify the same. Did not update documentation since my expectation was that this should work via `dialectOptions` already.
Not sure how to get rid of query console logging:
```
Executing (default): CREATE TABLE foo (faz TEXT);
```
=> Pass through connection mode options to sqlite

lib/dialects/mssql/query-generator.js, test/unit/sql/remove-column.test.js
* As per the syntax tree at:
https://msdn.microsoft.com/en-gb/library/ms190273.aspx
the correct syntax for removing a column is:
ALTER TABLE users DROP COLUMN name;
instead of:
ALTER TABLE users DROP name;
which is instead the syntax to drop the 'name' constraint.
----
I noticed this wasn't working for our migrations against an MSSQL DB.
I haven't implemented any tests yet -- I'd like to check this change is sound in principle before going any further.
It looks like I could implement some tests at:
>test/integration/dialects/mssql/query-generator.test.js
(note that it looks like there are no mssql integration tests yet)
Are there any other places I should add tests?
=> Fix removeColumnQuery for mssql dialect

changelog.md, package.json
Reverts sequelize/sequelize#4332
Appearently travis did not properly test the updated deps because of node_modules caching, so I'll have to revert this
@josephpage Didn't your experience any problems when running the tests locally?
=> Revert "Update dependencies"

changelog.md, package.json
Follows #4332 and #4339.  Passes tests locally.
This PR resolves bad score of [dependency status (david-dm.org)](https://david-dm.org/sequelize/sequelize)
- MAJOR : toposort-class@1.0.1 - No breaking changes known - [Release notes](https://github.com/gustavohenke/toposort/releases)
- MAJOR : validator@4.0.2 - No breaking changes known for [4.0.2](https://github.com/chriso/validator.js/commits/master) (:warning: Breaking changes/bugs introduced in 4.0.3 : #4339 )
- MAJOR : wkx@0.1.0 - No breaking changes known - [See commits history](https://github.com/cschwarz/wkx/commits/master)
- Changelog
=> Update dependencies 2

docs/docs/models-usage.md, docs/docs/querying.md
Changed:
- `docs/docs/querying.md`: added `$and` and `$or` to list of operators
- `docs/docs/models-usage.md`: added `$and` and `$or` to list of operators
- `docs/docs/models-usage.md`: added `$any` to keep consistent with `docs/docs/querying.md`
=> added query params to docs

lib/model.js, test/integration/include/seperate.test.js
Should sequelize attempt to include the missing id field? Should it raise an appropriate error?
=> include with separate:true fails if id is not part of the attributes list

lib/dialects/abstract/query.js
When nesting associations, if the model doesn't have a primary key, the code will now check and see if there is at least one unique key, and if there is, it will use one to create the hash that identifies each different row of results.
This change is in response to #4274
=> groupJoinData checks UniqueKeys if no PrimaryKey is set

lib/sequelize.js
This PR adds `version` property to `Sequelize` - the version number of Sequelize in use.
This is useful e.g. for plugins where API has changed between different versions of Sequelize, and the plugin wishes to support multiple versions. See https://github.com/overlookmotel/sequelize-definer/blob/master/lib/patches.js for an example.
=> Sequelize version number as property of sequelize

lib/instance.js
- Possibly fix #4423
- Rename Instance `options` to `$options` to prevent value
overwriting with models that have a column named `options`
- Also rename Instance `__options` to `$modelOptions` to avoid confusion
between $options and __options.
=> Rename Instance private options and __options

changelog.md, lib/instance.js, test/integration/instance.test.js
Fix issue #4353. Set to null a destroyed association after an instance reload.
=> Fix instance reload doesn't set to null a destroyed include

lib/data-types.js
Changed "The datatypes are used when definining a new model using" to "The datatypes are used when defining a new model using".
=> Update spelling in line 11 of sequelize/lib/data-types.js

docs/docs/instances.md
Edits a potentially confusing typo in a code example.
**steps to repro:**
1. go to http://docs.sequelizejs.com/en/latest/docs/instances/
2. scroll to section that says "Built instances will automatically get default values when they were defined."
**expected:**
code example should say
```
var Task = sequelize.define('Task', {
title: Sequelize.STRING,
rating: { type: Sequelize.STRING, defaultValue: 3 }
})
```
**actual:**
code example has **Project** instead of **Task** as the first param in the `sequelize.define` method when defining the Task class. 
```
var Task = sequelize.define('Project', {
title: Sequelize.STRING,
rating: { type: Sequelize.STRING, defaultValue: 3 }
})
```
See screenshot of existing problem below:
=> Fixed 'define' method parameter in example for building instances

changelog.md, lib/transaction.js, test/integration/transaction.test.js
Hi.
This is a minor patch fixing issue reported by me [#4491](https://github.com/sequelize/sequelize/issues/4491). I have added a guard check in **commit** and **rollback** in **lib/transaction.js** to disallow multiple commit/rollback on a single transaction. Also to fix connection exhaust bug when an error occurs in method **prepareEnvironment** promise chain I rollback half-initialized transaction before propagating error.
=> commit/rollback multiple times when not using CLS

lib/instance.js, lib/model.js, test/integration/sequelize.test.js
This is a quick fix for #4481.
With this modification, `defaultValue` of deletedAt  is used instead of `NULL`, in functions `paranoidClause` and `restore`.
I am having trouble setting up Docker and haven't written tests yet, but they are working fine with the site I am currently developing.
I will look more into testing if it's a necessary step.
=> quick fix for #4481 , paranoid uses defaultValue of deletedAt

lib/dialects/mssql/connection-manager.js
Hi.
I saw a use-less trailing comma in mssql's connection manager, in constructor where default connection config is declared. I removed it! :laughing:
=> removed trailing comma from mssql connection manager connection config.

changelog.md, lib/dialects/abstract/query-generator.js, lib/dialects/abstract/query.js, lib/model.js, lib/sequelize.js, test/integration/model/update.test.js, test/integration/sequelize.test.js
Add feature #3714. 
This also allows the `returning: true` [option](https://github.com/sequelize/sequelize/blob/2c4a9f3cf9887fb33c31e397e758dd4aa3374d01/lib/model.js#L2064) for `update` in postgres to work properly. Currently it [generates](https://github.com/sequelize/sequelize/blob/e948dc8fdc6be90c54441e091472a0c5d72899ce/lib/dialects/abstract/query-generator.js#L212) out `RETURNING *`, which faces the same problem as described with raw queries in #3714.
=> Map raw field names to attributes.

lib/model.js
Fix recursively inject 'where' with defaultScope and paranoid:true #4456
=> Fix recursively inject 'where' with defaultScope and paranoid:true

lib/model.js
@mickhansen the fix contained in #4518 is really better than the one reverted by this commit because it use `optClone` which take care of Sequelize objects. Moreover, the integration test add by my previous commit ensure no regression.
=> Revert scopeInclude clone. Better fixed by #4518

lib/instance-validator.js
Enable .validate(options.skip) to skip specific model/custom validators #4527
Return false to exit iteration early when using _.each and _.forIn , as per lodash docs
=> Feature #4527 "skip" option for custom validators

changelog.md, lib/instance.js, test/unit/instance/changed.test.js
I'm using a JSONB attribute but I'm not able to save the data using set() on my instance object. When reading the documentation is says that using a dot.separated key should change the instance and flag the entire object as changed. If I inspect the instance object I can see that the "_changed" property now contains my dot.separated keys not the entire object key as expected.
Looking at the source code for instance.js I found a problem in the way changed is called when using a det.separated key. I have attached a pull request that actually flag the entire object as changed and I also make sure only to flag if a property has changed.
=> Calling set with dot.separated key on a JSON/JSONB attribute will not flag the entire object as changed

lib/dialects/abstract/query-generator.js, test/integration/include/find.test.js
It now uses the field name instead of the model name.
Fixes #3940.
=> Fixed how an included where is joined so it generates correct SQL code.

changelog.md, lib/associations/index.js, lib/sequelize.js
This PR exposes the `Association` constructor as `Sequelize.Association`. The different association constructors are also exposed as `Sequelize.Association.BelongsTo`, `Sequelize.Association.HasMany` etc.
This is useful for things like:
```js
if (obj instanceof Sequelize.Association) { /* do something */ }
if (association instanceof Sequelize.Association.HasMany) { /* do something */ }
```
=> Expose Association constructor as `Sequelize.Association`

changelog.md, lib/hooks.js, lib/model.js, lib/sequelize.js, test/integration/hooks.test.js
before/afterSync hooks are fired on `Model.sync(...)` call and before/afterBulkSync on `sequelize.sync(...)` call.
=> Added before/afterSync and before/afterBulkSync hooks

docs/docs/hooks.md
=> Fix typo in hooks.md

lib/dialects/postgres/index.js, lib/dialects/postgres/query-generator.js, lib/dialects/postgres/query.js, lib/instance.js, lib/model.js, lib/query-interface.js, lib/sequelize.js, test/integration/model/searchPath.test.js
When you have a multi-tenant application that has the same database models across multiple schemas the current sequelize model paradigm forces you to create a separate model for each schema that is identical except for the schema property of the tableName object. This change adds a dialect option called prependSearchPath that will allow you to pass a searchPath option to any query that will be prepend the query with "SET search_path to ". If the prependSearchPath options is enabled and no searchPath query option is provided it will use DEFAULT which should be the same behavior as before.  By supporting a searchPath option I can now define a common set of models and use them across tenant schemas by passing the correct searchPath. If the prependSearchPath dialect option is not explicitly …
=> Create query and dialect options for prepending schema search_path in Postgres

lib/dialects/postgres/query-generator.js, test/unit/sql/index.test.js
The performance of the existing showIndexes postgres query is very poor if you have many identical table names across multiple schemas. I have added a restriction to the query to filter by schema name when a schema is present on the tableName object.
=> optimize index lookup when schema is known

docs/docs/migrations.md
if using 'sequelize migration:create'
Don't have (migration, DataTypes) parameters , instead of that received (queryInterface, Sequelize) parameters.
=> fix: Created documentation the same way we have for sequelize command.

docs/docs/models-definition.md
Seeing as we're on 3.11 this seems like it should be removed.
=> Remove outdated reference to v2.0

lib/dialects/mssql/connection-manager.js
The current mssql connection manager does not allow for passing in the "domain" to the tedious driver. This patch allows it to pass through by setting it in the dialect options.
=> Added support for passing domain option to tedious.

lib/dialects/postgres/query.js
1. Consistent SQL requests are being made through Sequelize, utilizing the postgres dialect and a pool size of 5.
2. A database failover occurs, which resets all active connections to the database server.
The pool members will get invalidated, and are able to reconnect when the database is accessible. 
1. The Query on error will return a parsed ECONNRESET error message.
2. The client from pool is never marked invalid, so it returned on the next request for a handle.
3. The next query is requested to run on the client from the pool, however it never returns from the request. At this stage, all clients from the pool are active, but will never return, completely locking the system down.
1. The Query will mark the client as invalid.
2. The next query requested asks for a client from the pool. …
=> Force the client to be reaped if an ECONNRESET is returned on query [postgres]

changelog.md, lib/instance.js, lib/model.js
The queries for `Model.findById` and `Instance.reload` don't need to specify a limit of one record, since we're querying with the primary key anyway. Including the limit in the generated SQL is redundant and adds unnecessary complication to the queries.
This is also somewhat related to [issue 4404] (https://github.com/sequelize/sequelize/issues/4404) -- these changes allow `findById` and `reload` to work on MS SQL Server versions before 2012, where previously they were broken due to the `OFFSET FETCH` issue. 4404 isn't completely fixed though, because queries that actually need the `offset` and `limit` options are still broken.
=> Remove usage of "limit" in some places where it's unnecessary

lib/dialects/abstract/query-generator.js, lib/dialects/mssql/query-generator.js, test/integration/include/find.test.js
when the primary key attribute is different from the primary key field
Kind of relates to ##3940. Using the primaryKeyAttribute generates wrong SQL if the database field and the model attributes are named differently.
=> Fixed generated SQL when using find with through.where and required true

docs/api/datatypes.md
Changed `UUID v2` to `UUID v4`, as the implementation shows.
=> fixed typo in datatype description

docs/docs/querying.md
```js
attributes: [[sequelize.fn('COUNT', sequelize.col('hats')), 'no_hats']]
```
Instead of
```js
attributes: [sequelize.fn('COUNT', sequelize.col('hats')), 'no_hats']
```
in querying docs for aggregation using sequelize.fn
=> Aggregation query doc improvement

lib/instance.js, test/integration/instance/values.test.js
This PR improves the `previous()` method by returning an object of the previous values when no `key` is given.
=> Improve `previous()` instance method

docs/docs/querying.md
`order` supports both ordering by an instance's associate's fields as well as any nested associate's fields. `order` also supports aliased associates too. This update adds an example of this functionality to the documentation, so that users are both aware of and how to use this feature.
=> Update querying documentation

lib/sequelize.js, test/integration/configuration.test.js
In response to #4747.
I considered re-writing the code thus that the supported dialects were all defined in one place (e.g in an array), but ultimately decided to [_KISS_](https://en.wikipedia.org/wiki/KISS_principle).
I ran Mocha on the effected file. Something so simple shouldn't introduce a regression but let's what Travis has to say :smirk:
=> Made unsupported dialect error message clearer.

lib/hooks.js
Docs for `beforeBulkUpdate` read:
"A hook that is run **after** updating instances in bulk"
It looks like this line was a simple, accidental copy-and-paste from it's sibling, `afterBulkUpdate`.
This commit changes `beforeBulkUpdate` to read correctly:
"A hook that is run **before** updating instances in bulk"
Thanks for your work on Sequelize!
=> [docs] Fixed beforeBulkUpdate explanation.

changelog.md, lib/model.js, test/integration/model/scope/aggregate.test.js
Applies scopes in Model.aggregate, fixing #4764
=> Apply scopes to `aggregate`, fixes #4764

docs/api/associations/belongs-to-many.md, docs/api/associations/has-many.md, lib/associations/belongs-to-many.js, lib/associations/has-many.js
In the API docs for associations, the `addAssociation()` and `addAssociations()` are incorrectly documented: it is stated that passing `null` as the association argument will remove associations from the entity / object, whereas in fact it will do nothing (i.e., the call will be a no-op).
This is probably due to a cut & paste bug from the `setAssociations()` methods.
=> Fix addAssociations() API docs: null argument does nothing

changelog.md, lib/dialects/abstract/query-generator.js, lib/dialects/postgres/query-generator.js, lib/instance-validator.js, lib/model.js, lib/query-interface.js, package.json, test/integration/dialects/postgres/dao.test.js, test/integration/dialects/postgres/query-generator.test.js, test/unit/sql/enum.test.js
First off, thanks for all the hard work, I'm loving Sequelize. 
I am using Postgres and want to use a non-standard schema for some models. I use ENUM for my model `status` fields, which has lead to problems for me when combined with the non-standard schema.
This PR aims to make Sequelize work perfectly with non standard Postgres schemas.
Please can you glance through the commit and let me know if you're happy with the direction I'm heading. Once I have it working I'll look at extracting the duplication in to a helper function or two.
=> Initial modifications to get enums working with postgres schemas

lib/data-types.js, lib/dialects/mysql/data-types.js, test/unit/sql/data-types.test.js
fixes #4205 for fractional DATETIME support. Perhaps I should add the same functionality for TIME columns also?
=> feat(datatypes) Support fractional DATETIME columns in MySQL 5.6+, fixes #4205

lib/dialects/abstract/connection-manager.js, lib/model.js
Another fix to prevent warnings like http://bluebirdjs.com/docs/warning-explanations.html#warning-a-promise-was-created-in-a-handler-but-none-were-returned-from-it
=> Return null to tell Bluebird non-return is intentional

docs/articles/getting-started.md, docs/docs/associations.md, docs/docs/instances.md, docs/index.md
Closes #4909
Some things I noticed while looking through the source:
- There is a lot of trailing whitespace (which my editor trimmed - initially made a huge diff)
- There are occurrences of Zalgo (sometimes throwing synchronously sometimes async)
- `ModelValidor.prototype.validate()` _returns_ the error instead of throwing it. This means in _every_ call I encoutered there was a `if (err) throw err` handler attached. This looks a lot like it was just regexp-replaced from callback style to promise style. Maybe this behavior should be changed.
- The docs recommend to be a modern developer and use the "newest" Node version 0.10 for contributing
- The code would look _so_ much better with arrow functions. `Promise.bind`, `var self = this` everywhere. Maybe it's time to make the jump from Node …
=> Fixes usage of promise antipatterns in the docs

changelog.md, lib/associations/belongs-to-many.js, lib/associations/belongs-to.js, lib/associations/has-many.js, lib/associations/has-one.js, test/unit/associations/dont-modify-options.test.js
I use sequelize quite often and just discovered are rare case where it doesn't exactly do what imho it is supposed to do. Let's assume we have three tables, where A & B have a string ID and C has an integer ID. Now when we try to connect B and C with A, we run into the problem that if a foreignKey is given as input, it will be *modified* by the associations. Hence this to this weird behavior:
```
var Sequelize = require('sequelize');
var sequelize = new Sequelize('database', 'username', 'password', {
dialect: 'sqlite',
storage: 'foo.sqlite'
});
var A = sequelize.define('A', {
id: {
type: Sequelize.CHAR(20),
primaryKey: true
}
});
var B = sequelize.define('B', {
id: {
type: Sequelize.CHAR(20),
primaryKey: true
}
});
var C = sequelize.define('C', {});
var reqValidForeignKey = { foreignKey: …
```
=> don't overwrite options.foreignKey in associations

lib/instance.js, test/integration/sequelize.test.js
Function of my PR #4490 was broken by PR #4316 at [this line](https://github.com/sequelize/sequelize/pull/4316/files#diff-a5b70841c2143e5d2e0fd98dd3b4cefeR827) .
My tests were not sufficient.
With this PR, instance.destroy will work again, with models having "paranoid" and deletedAt with non-null defaultValue.
Fixed the tests too.
=> Fixed instance.destroy not working for models with "paranoid" and defaultValue of deletedAt set to non-null.

docs/articles/heroku.md, docs/docs/associations.md, docs/docs/getting-started.md, docs/docs/migrations.md, docs/docs/models-definition.md, docs/docs/models-usage.md, docs/docs/raw-queries.md, docs/docs/scopes.md, docs/docs/transactions.md, docs/docs/usage.md, lib/associations/belongs-to-many.js, lib/associations/has-many.js, lib/associations/has-one.js, lib/associations/mixin.js, lib/data-types.js, lib/deferrable.js, lib/instance.js, lib/model.js, lib/sequelize.js, lib/transaction.js
I noticed a misspelling when reading the docs, so I ran a spellcheck on all the doc files and found lots of typos.
I also noticed some of the doc files used character entity names (`&period;`, `&comma;`, `&lpar;`, `&rpar;` etc.) in places where they were unnecessary, so I replaced those instances with the actual characters.
The second commit in this PR is just the result of running `npm run docs`.
=> Fix various typos/misspellings/formatting issues in the docs

lib/utils.js, test/unit/instance/set.test.js
This test is failing - somehow setting a JSONB field mutates the model's defaultValue to whatever was last set. Couldnt identify how that is happening. @mickhansen any clues?
=> Failing .set test

lib/dialects/mssql/connection-manager.js, test/unit/dialects/mssql/connection-manager.js
API for the Tedious driver requires that an entry for `domain`, if present,
be at the root level of the config option passed to the constructor. This
was added in commit 91fc76be10b12e0e5a2c4a9299e5bc05a2956d58.
However, that commit deleted `dialectOptions.domain` from the config object
passed into the Sequelize constructor. Since most config objects are singletons,
this mutation of the config object breaks any subsequent calls to the instance's
`connectionManager.$connect`.
This commit simply removes the call to delete the domain entry.
Fixes #4918
=> [MSSQL] Fix connection manager domain usage

changelog.md, lib/model.js, test/integration/model/scope/findAndCount.test.js
This fixes #4566 by specifically ignoring attributes in `count` (and therefore `findAndCount`). Attributes are mostly likely added by a scope, and when present cause the SQL error
```
SequelizeDatabaseError: column "ScopeMe.username" must appear in the GROUP BY clause or be used in an aggregate function
```
because a bad query is produced (see issue for details).
=> Fix count when scope contains attributes

lib/instance.js
This should solve the follow error stack, by converting the original time to a Date Object.
```
<h1>originalValue.getTime is not a function</h1>
<h2></h2>
<pre>TypeError: originalValue.getTime is not a function
at Instance.set (/node_modules/sequelize/lib/instance.js:348:68)
at Instance.set (/node_modules/sequelize/lib/instance.js:292:16)
at Instance.update (/node_modules/sequelize/lib/instance.js:791:8)
```
=> convert original time to Date object

lib/sequelize.js
The rollbacks are getting called twice when a connection error occurs during an autofunc version of `sequelize.transaction(f)` call. This simple fix just rejects with the original connection error.
This should fail before the error and __pass__ after the fix. I forced a connection error by specifying a bogus database.
```js
'use strict';
/* jshint -W030 */
var chai = require('chai')
, expect = chai.expect
, Support = require('../support')
, current = Support.sequelize;
if (current.dialect.supports.transactions) {
describe(Support.getTestDialectTeaser('Sequelize#transaction.autoFuncErrors'), function() {
describe('then', function() {
// This failure is caused by any connection error (I used a bogus database name)
it('bypasses all promise error-handling and produces uncaught exception', …
```
=> Don't rollback twice on connection error. Fixes issue #4850.

lib/query-interface.js
I noticed one of my migrations wasn't honoring the transaction option I passed in, so I took a look at the code, and was surprised to find that the `transaction` option was being ignored for most of the migration queries. Only the `logging` option is being passed through to `sequelize.query` in most cases.
This allows the transaction option to be passed in as well.
=> Add transaction support to all migration queries

lib/dialects/postgres/query-generator.js
Fixes issue https://github.com/sequelize/sequelize/issues/4631
User needs to supply "databaseVersion" key in options object
when instantiating the Sequelize class in case version is not semver
compliant e.g. "9.5.0beta2" should be passed as "9.5.0"
=> Disables setting AUTOCOMMIT for Postgres >= 9.4.0

changelog.md, lib/model.js, test/unit/model/update.test.js
Fixes #4520 , `values` passed to the `update` method got modified.
As per #4520 whenever we pass the `fields` in options, the caller `values` got modified. It has been fixed. 
While writing tests I discovered `update()` method also add the `updatedAt` key to the caller `values` object. I have added tests for both cases.
I have used cloned version of `values` to fix both issues.
=> Update() modifies the supplied values

lib/dialects/abstract/query-generator.js, test/unit/sql/select.test.js
I have a query which is using including a has-many association with limit and separate attribute as true. It works fine till the above include has one level of included models. However, it does not work with more than one level of included models. 
I have added a fix and test based on my limited understanding. Please review the changes.
=> fix query which has nested include in a parent include with separate true and has-many association

changelog.md, lib/data-types.js
tsrange is range of timestamp without time zone for PostgreSQL. This makes range types complete as of PostgreSQL 9.5.
=> tsrange data type is added.

lib/associations/has-one.js, test/integration/associations/scope.test.js, test/integration/model/scope/associations.test.js
This PR fix two issues:
- the association's `scope` was not injected in `where` clause when eager loaded. This is **extremely critical** because any *raw* that match without the `where` restriction is eager loaded, that could result in sending private data to the client (that's what append to us...),
- the association's `scope` was not used is the creator helper method (ie. `createInstance`)
=> Add support for scope in has-one association

CONTRIBUTING.md, lib/data-types.js
Geometry was introduced but is not on the documentation http://docs.sequelizejs.com/en/latest/api/datatypes
=> Show that sequelize supports geometry on documentation

changelog.md, lib/model.js, test/integration/model/count.test.js, test/integration/model/scope/aggregate.test.js, test/integration/model/scope/count.test.js, test/unit/model/scope.test.js
Refactor `$injectScope` to better checks existence of include in `options.include` based on the related `association`. This PR also fix a bug where include are not validated/expanded in `model.aggregate`.
Fix #4986
Fix #5121
Fix `Cannot read property 'association' of undefined`
=> Do not inject include twice, expand and validate include in aggregate

changelog.md, lib/dialects/mssql/query.js, lib/dialects/mysql/query.js, lib/dialects/postgres/query.js, lib/dialects/sqlite/query.js, lib/model.js, lib/sequelize.js, package.json
Closes #488 
Added an new option `benchmark` and `node-microtime` library to log time in microseconds it took to execute a SQL statement.
=> Feature #488 : Added benchmarking support in query logs

lib/dialects/mssql/query.js, lib/dialects/mysql/query.js, lib/dialects/postgres/query.js, lib/dialects/sqlite/query.js, lib/model.js, lib/sequelize.js, package.json
Implements the `benchmark` feature using the `getTime` and return the query execution time in `milliseconds`. It doesn't depend upon the `node-microtime`
=> Feat #488 : Benchmarks based on the pure JS Date.now()

lib/instance.js
The type is an array of strings for the property names, indeed as described in the comment. Not an object as typed. The documentation page end up contradicting each other.
=> Correct type in documentation in instance save()

lib/associations/has-many.js, test/integration/associations/has-many.test.js
We ran into an issue where we had nested has-many includes. We were using separate=true on these to avoid https://github.com/sequelize/sequelize/issues/2084. We found that if the parent include had a limit set and the nested include did not that incorrect sql was being generated because the options.groupedLimit attribute was not being cleared from the parent. The test I added will fail with a syntax error against the current master code.
=> Fix issue with nested separate includes

lib/dialects/abstract/query.js, lib/query-interface.js, test/integration/transaction.test.js
Minor code fixes to prevent ```[variable] was used before it was defined``` error introduced by jshint@2.9.1.
If any modification is needed, just let me know.
=> Code fixes for jshint@2.9.1

lib/instance.js, lib/model.js, test/unit/model/overwriting-builtins.test.js
If you define an attribute on a model with the same name as a built-in
instance method the attribute's automatically created get/set methods
will overwriting the built-in causing much hilarity.
=> Fixes a bug with user defined attribute names overwriting builtins.

lib/dialects/postgres/query-generator.js, test/unit/sql/create-schema.test.js
This PR adds `IF EXISTS` to the "drop schema" query, similar to the "create table" query found [here](https://github.com/seegno-forks/sequelize/blob/342251100f9040cd21cff4d36a0c3edeabd21a8f/lib/dialects/postgres/query-generator.js#L97).
=> Add `IF EXISTS` to Postgres drop schema query

lib/instance.js, lib/model.js
More appropriate fix for the merge: https://github.com/sequelize/sequelize/pull/5219
Now uses hasOwnProperty to more accurately check if the user attribute
matches a builtin.
=> Updated the fix for user defined attributes overwriting builtins.

changelog.md, lib/model.js, test/integration/instance.test.js
Support silent: true option in bulk update as requested in [#5200](https://github.com/sequelize/sequelize/issues/5200)
If any modification is needed, just let me know.
=> Support silent: true in bulk update

test/integration/hooks.test.js
Remove Promise warnings with type:
```Warning: a promise was rejected with a non-error: [object Object]```
=> Prevent Promise (bluebird) warnings in tests (part 2)

lib/dialects/postgres/query.js
This trivial fix tests whether errDetail is defined before applying the regex. With my configuration, PostgreSQL 8.4 and latest node-postgres, errDetail is undefined.
=> errDetail may be undefined in Postgres formatError

changelog.md, lib/dialects/sqlite/query-generator.js, lib/sequelize.js, package.json, test/integration/transaction.test.js
Added retry on SQL_BUSY state.  Only works for Sqlite right now, but others can be added easily.
Replaces https://github.com/sequelize/sequelize/pull/5157/
=> Added retry and options to retry when queries fail with SQL_BUSY state.

changelog.md, lib/errors.js, lib/instance.js, lib/sequelize.js, test/integration/instance.test.js
Refs to https://github.com/sequelize/sequelize/issues/4844 and https://github.com/sequelize/sequelize/issues/4452
1. properly updates Instance options after reload, that allows access to included association via ```.get({ plain: true}).settings``` or dot notation ```user.settings```
2. throws a error when reloaded instance is not exist in DB
=> Fix Instance.reload issues

changelog.md, lib/query-interface.js, lib/transaction.js, test/integration/transaction.test.js
Fixes issue #5222. 
Moves ```transaction.finished = 'rollback'``` assignment to ```QueryInterface.rollbackTransaction()``` after rollback query call.
=> Fix #5222: prevent race condition after transaction finished

lib/sequelize.js
This makes it so that, if the provided dialect is a supported dialect (eg. postgres) and requiring the dialect throws an error (eg. the 'pg' package not being installed), the actual underlying error and its accompanying stack trace are thrown to the caller, rather than stringifying the error (losing the stack) and reporting the wrong error.
=> Fix "the dialect is not supported" error

lib/dialects/postgres/connection-manager.js, test/integration/dialects/postgres/connection-manager.test.js
Missing semicolon causes a query in the postgres connection manager to fail. Only crops up when fetching hstore oids, since another statement is added without a semicolon in-between.
=> Fix setting postgres timezone while fetching hstore oids.

lib/query-interface.js, test/integration/model/upsert.test.js
`QueryInterface.upsert` accepts values by field name (`.field`) but picked primary key values for the where clause using attribute name. I modified `upsert` so that `.field` is taken into account when collecting data for the upsert where clause. I've also added a failing test case which now passes.
=> Fix for bug #4755

changelog.md, lib/data-types.js, lib/dialects/postgres/connection-manager.js, lib/dialects/postgres/data-types.js, lib/dialects/postgres/index.js, test/integration/model/geography.test.js
Add the GEOGRAPHY datatype support from postgis based on http://postgis.net/docs/using_postgis_dbmanagement.html#PostGIS_Geography which is indeed very similar to the GEOMETRY datatype but takes the roundness of the earth into account.
This is very useful for setting geographical points with a high degree of exactitude.
=> geography and tests

lib/model.js
This fixes issue #5344, where `findAndCount` with eagerly loaded model is broken when using Sequelize with pg. In lodash 4.x, `cloneDeep` does not accept a customizer function, but a new function `cloneDeepWith` does.
=> Fixes issue #5344: Replaced _.cloneDeep with _.cloneDeepWith.

lib/dialects/postgres/data-types.js
I tried to think of a test that is this bug, but could not find an acceptable place in the current suite.
It happens when you just have to connect and make a query to a table with hstore
=> fix usign hstore without model instance

lib/instance.js, test/integration/instance.test.js
If model has `updatedAt` or `createdAt` fields without allowing nulls:
```javascript
createdAt: {
type: DataTypes.DATE,
allowNull: false,
field: 'created_at'
},
updatedAt: {
type: DataTypes.DATE,
allowNull: false,
field: 'update_at'
},
```
then I'm receiving this error:
> { [SequelizeValidationError: notNull Violation: createdAt cannot be null,
notNull Violation: updatedAt cannot be null]
name: 'SequelizeValidationError',
message: 'notNull Violation: createdAt cannot be null,\nnotNull Violation: updatedAt cannot be null',
errors:
[ { message: 'createdAt cannot be null',
type: 'notNull Violation',
path: 'createdAt',
value: null },
{ message: 'updatedAt cannot be null',
type: 'notNull Violation',
path: 'updatedAt',
value: null } ] }
My proposal is to set `updatedAt` and `createdAt` values …
=> Set updatedAt and createdAt values before validation

docs/docs-generator.js
`where` was removed from Lodash 4 in favor of `filter`. Running `npm run docs` errors out with "where is not a function" without this fix.
=> Replaced function removed from lodash 4

package.json
Multiple spaced `GREP` argument will throw error for integration tests. This will throw error
```bash
GREP="should work" npm run test-integration-sqlite
```
Fixed it by properly escaping `GREP` env variable in test command.
=> GREP env now able to use multiple spaced argument

lib/dialects/mysql/query.js, test/integration/query-interface.test.js
Our team relies on the result of `describeTable` method to generate migrations automatically. However, we found that enum types are uppercased by sequellize by mistake.
For example, we have a field with the type of `enum('admin', 'member', 'guest')`, the result of `describeTable` will be `ENUM('ADMIN', 'MEMBER', 'GUEST')`, which is obviously not as same as the former one.
After the changes, the result will become `ENUM('admin', 'member', 'guest')`.
=> fix: describe query should not uppercase the enum type

lib/instance-validator.js
I have had failing unit tests for a while, specifically 
1) correctly specifies an instance as invalid using a value of "012" for the validation "isAlpha"
2) correctly specifies an instance as valid using a value of "abc" for the validation "isAlpha"
3) correctly specifies an instance as valid using a value of "abc" for the validation "isAlpha"
4) correctly specifies an instance as valid using a value of "abc" for the validation "isAlpha"
5) correctly specifies an instance as valid using a value of "abc" for the validation "isAlpha"
6) correctly specifies an instance as invalid using a value of "_abc019" for the validation "isAlphanumeric"
7) correctly specifies an instance as valid using a value of "abc019" for the validation "isAlphanumeric"
8) correctly specifies an instance as valid …
=> Added condition to arg passer for validators.

changelog.md, lib/dialects/abstract/query.js, lib/model.js, test/integration/instance.validations.test.js
This issue was not in the dialect as https://github.com/sequelize/sequelize/issues/4920 hints, but rather in the model definition. Sequelized looks/ed for unique index names when the `unique` property is given as an object, even if it only contains a `msg`. This resulted in, when many columns contained an object like `unique: { msg: '...' }`, it grouping them under the `undefined` key and subsequently ignoring further message definitions.
This PR modifies the building so that the name is pulled out only if defined in the unique property.
=> Multiple custom unique validation messages being overwritten by the first-defined message

lib/dialects/abstract/query-generator.js, test/unit/sql/where.test.js
This is a pull request for a fix to issue #5453 
When a query contains { where: { $or: [] } }, it should return any empty set. Currently, however, the entire WHERE clause disappears. This fix adds WHERE 0 = 1 in the degenerate case so that no data is returned from the query.
=> empty array  in where should return no data

lib/sequelize.js, test/integration/transaction.test.js
The "commit has been called on this transaction" error message usually indicates a problem with chaining of query promises within a transaction block. In more complex transaction blocks it may not be immediately clear which query is improperly chained and the current error message does not help much. This change logs the query (SQL) that the application attempted to run on a finished transaction. This makes it easy to identify a problem in an application.
=> Log which query tried to run on a finished transaction

lib/instance-validator.js, test/unit/model/validation.test.js
* Added locales to `isAlpha`, `isAlphanumeric` and `isMobilePhone`.
* ex:
`isAlpha: 'de-DE'`
`isAlphanumeric: 'de-DE'`
=> Added locales support for localized validations

lib/hooks.js, lib/model.js, test/integration/hooks.test.js
This provides a solution to #4683. This provides a beforeCount hook to the count query, allowing for the user to change the options of count before the database is queried.
I attempted to add an afterCount hook but, because the count is not attached to the model itself, changing it after the database return would require more substantial (probably breaking) changes. Additionally, can't think of a good use case for changing the count after we have queried the database.
Long time user, first time contributor. Hoping to give back more to this great community!
=> add a beforeCount hook

changelog.md, docs/api/hooks.md, docs/docs/hooks.md, lib/hooks.js, lib/instance-validator.js, lib/sequelize.js, test/integration/hooks.test.js
See [ afterValidate hook is not called when validation fails #1626 ](https://github.com/sequelize/sequelize/issues/1626)
I added an async validationFailed hook which is called with modelInstance, options and validationError. If the hook throws an error, it replaces the original validation error.
=> Added validationFailed hook

lib/sequelize.js
Promise.map allows promises to execute in parallel, which can cause
deadlocks when cascading truncates. Promise.each executes promises
sequentially, which should ensure that we don't have two or more
TRUNCATE operations getting in each others' way.
=> Execute promises sequentially rather than parallel

lib/associations/has-many.js
In `HasMany.count()`, replaces SQL call `COUNT(model.primaryKeyName)` with `primaryKeyField` as is used in `Model.count()`. This fixes an error when doing a count() on an association with "id" primary key attribute mapped to a field name other than "id"
=> Use model.primaryKeyField for HasMany.count column

docs/docs/models-definition.md
Way late documentation update for MySQL fractional DATETIME support.
=> Added Sequelize.DATE(6) (MySQL) to docs

changelog.md, lib/errors.js, lib/model.js, lib/sequelize.js, test/integration/model/find.test.js, test/integration/model/findAll.test.js
Allow finder methods to throw `RecordNotFound` error when query returns null set and `kenophobic` mode is `true`. This option can be set per method basis or with model options.
Closes #5480 
Closes #272
> Kenophobic means a person with fear of emptiness or void, You can suggest any other name if want to :)
=> rejectOnEmpty mode

lib/instance-validator.js
Long time user, first time PR-er :)
Trying to see if #5356 can be fixed by casting all values as `String()` in instance-validator before running validator function on them. My use cases for Sequelize are sort of limited so I'm not sure how well this will work, but let's let CI tell us!
=> Cast value as string to pass new Validator.js string requirement

changelog.md, lib/model.js, test/integration/include/findAndCountAll.test.js, test/integration/model.test.js, test/integration/model/findAll/group.test.js, test/unit/model/findAndCountAll.test.js, test/unit/sql/join-include-query.test.js
Fixed the `subQuery` generation which cause nested `includes` to be applied on main query. It also add other tests and fixes achieved due to this fix.
Fixes #4191, Fixes #3009, Fixes #5445
Closes #5530, Closes #5446, Closes #4378
May be it will close more issues, I will check and include tests in further PRs
=> Fix findAndCountAll issues

CONTRIBUTING.md, docs/docs/getting-started.md, docs/docs/models-definition.md
In October 2015 Bluebird moved their documentation to its own domain (see commit https://github.com/petkaantonov/bluebird/commit/94fd4fe67f4a60d0fbf102c7a5c8ed8fdb230310#diff-88333ba11114e014e87198d04680144d)
These changes update the Bluebird links in the Sequelize docs to point to their new locations.
=> Docs: Update links to Bluebird API docs

lib/model.js
After studying #3414 and its performance test suite I tracked back the performance degradation causes. It appears to be these reasons
* Generic performance hit due to Promises (we cant do much about it ?)
* `optClone` method (consumes `300+ ms` for 1501 array elements in `findAll`)
* Hitting the database (450 - 550 ms)
* Other JS execution
I was able to improve the performance by adding a small fix to `optClone` method. These are the results
| Elements / Exec. Count | Fix Applied  | Total Time (ms) | Node | Sequelize |
|---|---|---|---|---|
| 1501 / 5000 | No | 11557 | 0.12 | 1.7.0 |
| 1501 / 5000 | No | 11403 | 0.12 | 1.7.0 |
| 1501 / 5000 | No | 13173 | 0.12 | 2.0.0 |
| 1501 / 5000 | No | 13210 | 0.12 | 2.0.0 |
| 1501 / 5000 | **No** | **16447** | 0.12 | 3.20 |
| 1501 / 5000 | **No** | …
=> Performance improvement for #3414

lib/model.js
This gets added in BulkCreate but not destroy. I need to figure out the model when using a global BulkDelete hook.
=> Model.destroy: add model to options

lib/model.js
Creating a table under a transaction fails if the table has indexes on it. This is because the index is created outside of the transaction, and the table is invisible outside the transaction.
=> Use transaction when creating index

lib/dialects/abstract/connection-manager.js, lib/hooks.js, lib/sequelize.js, test/unit/connection-manager.test.js, test/unit/sequelize.test.js
Closes #5687
Adds a before connection hook as well as supporting a plain object constructor.
Enables use of dynamic credentials for databases by letting the user define empty username/password in the Sequelize options object and then injecting on a per connection basis.
=> Before connection hook

changelog.md, lib/instance.js, test/unit/instance/build.test.js
Creating new model instances in sequelize has an odd behaviour whereby their default values aren't cloned and are therefore shared mutable state between all instances of a class. This means that if we change one if its attributes in one model instance, it gets changed to all other instances as well. Example:
```js
// For a `Model` model with the attribute `data` with `defaultValue` set to `{ foo: 'bar' }`:
var model1 = db.Model.build();
model1.data.foo; // 'bar'
model1.data.foo = 'biz';
model1.data.foo; // 'biz'
var model2 = db.Model.build();
model2.data.foo; // 'biz'
```
The proposed fix applies a deep clone to the objects that are defined as `defaultValue`. This also addresses the edge case of sequelize methods as default values which, due to their nature, aren't meant to be cloned.
=> Fix defaultValues getting overwritten on build

lib/associations/belongs-to-many.js, test/unit/associations/belongs-to-many.test.js
Sequelize 3.19.3, Ubuntu Linux (64-bit) 15.10, Node.js 4.3.2 (LTS).
When declaring a join table with the through option declared as a string, Sequelize creates the through model at runtime, and copies the model validation rules from the source table into the through model. More often than not, the model validation rules from the source table would be inappropriate/undesirable for the join table (since their data fields are different anyway).
It's also worth noting that if a through model is given, this behavior is not exhibited.
Through table as string:
```javascript
'use strict';
let Promise = require('bluebird');
let Sequelize = require('sequelize');
let sequelize = new Sequelize('database', 'username', 'password', {
host: 'localhost',
dialect: 'postgres'
});
let Job = …
```
=> Ignore model-level validation when creating through table using string

lib/associations/belongs-to-many.js, lib/associations/belongs-to.js, lib/associations/has-many.js, lib/associations/has-one.js
With a little help from @mickhansen in Slack i realized that all of the `addX` and `setY` methods added to models through associations work on *existing* rows in the database and can not be used to insert new rows, which is what the `create` association methods are for.
With this PR, i try to clarify this in the docs because it might have clicked for me when i read it like this.
=> Try to clarify adding and setting associations

lib/data-types.js
Fix for #5547. The package `moment-timezone` doesn't have a `utcOffset` method while the package `moment` does. It was probably just assumed that `moment-timezone` would have the `utcOffset` method.
=> utcOffset fix

changelog.md, lib/dialects/mssql/connection-manager.js, lib/dialects/mssql/query.js, lib/dialects/mssql/resource-lock.js, test/integration/dialects/mssql/query-queue.test.js, test/unit/dialects/mssql/resource-lock.test.js
Resolves https://github.com/sequelize/sequelize/issues/4105. Adds a simple queuing mechanism to tedious connections via a resource lock. This will add a small amount of overhead to all requests but will prevent the possibility of interleaving requests on a single connection, especially within a transaction.
Currently broken:
```js
sequelize.transaction(transaction => {
return Promise.all([1, 2, 3].map(id => Model.findById(id, { transaction })));
});
```
Even though these will still *not* happen concurrently, it will no longer result in error.
The queue leverages Bluebird promises to effectively created a linked list queue with each request containing a reference to resolve the next dependent promise. Bluebird `disposer` will …
=> Add query queueing to MSSQL connections

changelog.md, lib/data-types.js, lib/dialects/abstract/query-generator.js, test/unit/sql/data-types.test.js
When the validation on datatypes got reverted and put behind a flag, a new rule was added to allow them only on `INSERT` and `UPDATE` queries. However, these validations are useful for the remaining queries, as well, like `SELECT`.
This PR proposes enabling these validations for all queries. This would still only be applicable to anyone who has enabled the datatypes validation flag, which is disabled by default.
This PR also removes some redundant checks on the affected conditional (`field` and `field.type` have already been checked in an outer conditional) and reduces the level of nesting used to validate the datatype.
=> Enable type validation for all queries

lib/dialects/mssql/connection-manager.js, lib/dialects/mysql/connection-manager.js, lib/dialects/postgres/connection-manager.js, lib/dialects/sqlite/connection-manager.js
ConnectionManager: Re-throw initialization errors unless they are MODULE_NOT_FOUND. This prevents such errors from being misleadingly overridden.
As described in https://github.com/sequelize/sequelize/issues/3302#issuecomment-199238449
=> ConnectionManager: Re-throw initialization errors

changelog.md, lib/dialects/postgres/query-generator.js, test/support.js, test/unit/sql/delete.test.js
deleteQuery assumes a model exist and tries to extract primary keys from it, even when this is an unnecessary step. This change prevents model.primaryKeys from being accessed unless options.limit is provided.
It also throws a more friendly error if model is not defined.
Fixes #5615
=> only check model keys for delete with limit

docs/docs/models-definition.md
Just added a couple of commas and a semicolon on the code sample for model definition validations. Even though it won't really make a difference when you try to run the code, I felt I should get it fixed. Hoping this is a good first PR.
=> fixed a couple of commas and a semicolon on the validation docs

docs/docs/associations.md
I'm not positive that this was what was intended originally, but as it currently is, this code snippet isn't valid javascript.  I was able to find no example of `through` taking anything other than a string, but it does seem like `attributes` and `where` can both go in `include`, so I assume that this is the right way.  This also makes sense given the context of the example.
=> Fixing associations doc

changelog.md, lib/instance.js, test/integration/model/create/include.test.js
This PR adds the ability to pass custom options when creating nested records using `Model.create` and `options.instance`. It also add `parentRecord` to nested options to have a context.
=> Add context and custom options to deep creation

docs/docs/hooks.md
No instances in params for bulk commands; see https://github.com/sequelize/sequelize/blob/master/lib/hooks.js#L58
=> update hooks doc

changelog.md, lib/dialects/abstract/query-generator.js, test/unit/sql/where.test.js
Closes #5736 
Closes #4064
I have detected the presence of `LIKE` and `ANY`, fixed the query if they are used in specific order.
cc @mickhansen @janmeier
=> Fix #5736, Invalid query generated when using LIKE with ANY

changelog.md, lib/dialects/postgres/data-types.js, test/integration/data-types.test.js, test/integration/dialects/postgres/dao.test.js
Closes #4893 , returns good old string rather than parsing DECIMAL value to float.
@janmeier
=> Fixed #4893, DECIMAL precision for Postgres 

CONTRIBUTING.md
The contributing docs suggested using `boot2docker-cli` to manipulate `boot2docker` on OSX (See section 3b). However, `boot2docker-cli` is officially deprecated in favor of Docker Machine. Hence I add some tips to section 3a) and deprecate `boot2docker-cli` in section 3b).
AFAIK, The section 3b) can be removed later to reduce the effort of setting up contributing environment.
Signed-off-by: J Huang <i@jhuang.me>
=> deprecate boot2docker-cli in contributing docs

changelog.md, lib/data-types.js, lib/utils/validator-extras.js, package.json, test/unit/sql/data-types.test.js
validator@5.0.0+ has stopped coercing input values as strings and, since version 4, the library has been printing deprecation notices everytime a non-string is passed to it.
All `validate` functions now correctly handle theses cases by delegating this work to lodash functions.
- Improves on https://github.com/sequelize/sequelize/pull/5599, but for `typeValidation`.
- Closes https://github.com/sequelize/sequelize/pull/5701.
- Closes https://github.com/sequelize/sequelize/issues/5782 (probably the user installed `validator@5` manually).
=> Improve validation when dealing with non-strings

changelog.md, lib/associations/belongs-to-many.js, lib/associations/belongs-to.js, lib/associations/has-many.js, lib/associations/has-one.js, lib/dialects/postgres/query-generator.js, lib/instance-validator.js, lib/instance.js, lib/model.js, lib/query-interface.js, lib/sequelize.js, lib/utils.js
Clones `options` object within all Sequelize methods. This means that for the user code calling a Sequelize method, the object passed as `options` will never be modified.
For further discussion, see: PR https://github.com/sequelize/sequelize/pull/5836
=> Clone options object within all Sequelize methods

changelog.md, lib/model.js, test/integration/include/findAndCountAll.test.js, test/integration/include/paranoid.test.js, test/integration/model/attributes/field.test.js, test/integration/model/find.test.js
Closes #5880 , `deletedAt` field is compared against `CURRENT_TIMESTAMP` rather than `IS NULL`. It also check for `IS NULL` in case `deletedAt` is not set at all.
=> Fix #5880, deletedAt compare against NOW

changelog.md, lib/dialects/mysql/connection-manager.js, test/integration/data-types.test.js
Fixes #5176 
By using the API of `node-mysql` now `mysql` dialect can represent `BIGINT` in string form. In Addition to that this conversion will only happen when number is too big for JS to handle.
So this change will not effect small numbers. If a number gets big enough to get truncated we will convert it to `string` to save valid number.
cc @janmeier @mickhansen
=> BIGINT converted to strings when required (mysql)

changelog.md, docs/api/sequelize.md, docs/docs/usage.md, lib/dialects/abstract/connection-manager.js, lib/sequelize.js, test/config/config.js, test/integration/dialects/mysql/connector-manager.test.js, test/integration/sequelize.test.js, test/unit/configuration.test.js
Closes #5686 
Removed support for `pool:false`. If config specifically set `pool:false` an error will be thrown. Otherwise default pool config will be used. Document updates are included as well.
Full change list
=> Removed support for pool:false

changelog.md, lib/instance.js, test/integration/model/create/include.test.js
Trigger the `afterCreate` hook when all included records have been created.
@mickhansen we have discus about that in a previous pull request. You say that's a breaking change, but after deep look, this just a bug fix to be consistent with what append for HasOne associations.
Are you okey to merge something like that, if ok, I will add some tests.
=> After create hook

lib/model.js
Use case for this is generic cache invalidation using the options.model.name and options.where.id or obj.id
=> feat(model): put model in options for hook access

changelog.md, lib/dialects/mysql/query.js, test/integration/model.test.js, test/integration/sequelize.test.js
+ One caveat, tests are failing on `master`. My tests fail identically to those on `master`.
- [N/A] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
This provides the ability for MySQL logs to be reported using the existing `sequelize.log()` functionality. This should help people find issues which MySQL doesn't consider errors, but does consider worthy of warning on.
=> Adding the ability to log warnings if they are present in MySQL.

docs/api/model.md, lib/model.js
The options.cascade row of the table in Model#truncate seemed to be formatted incorrectly
=> Model#truncate - Fixing documentation formatting

changelog.md, lib/associations/has-one.js, test/unit/associations/has-one.test.js
Closes #5247
`hasOne` was not using the `options.as` alias for generating foreign key names. Now it does :)
cc @janmeier
=> hasOne now prefer for options.as foreign key name

lib/model.js
This PR ensure that an attribute of type `DATEONLY` is considered as a date attribute. It's now parse as date when set to the model.
=> Add DATEONLY attributes to _dateAttributes

changelog.md, lib/dialects/mssql/connection-manager.js, test/integration/dialects/mssql/connection-manager.test.js
When handling disconnects, the MSSQL connection manager was passing a raw connection to the pool destroy method instead of a mutex as expected.
Closes https://github.com/sequelize/sequelize/issues/5964
=> Closes #5964 -- Fix MSSQL disconnect handling

changelog.md, docs/docs/associations.md, lib/associations/belongs-to-many.js, lib/associations/belongs-to.js, lib/associations/has-many.js, test/integration/associations/belongs-to-many.test.js, test/integration/associations/scope.test.js, test/integration/include/findAll.test.js, test/integration/include/schema.test.js, test/integration/model/scope/associations.test.js, test/unit/associations/belongs-to-many.test.js, test/unit/associations/belongs-to.test.js, test/unit/associations/has-many.test.js
Closes #5267
cc @mickhansen , @janmeier
=> Task 5267, Make all association to prefer `as` their foreign key name

changelog.md, docs/docs/models-definition.md, docs/docs/querying.md, lib/data-types.js, lib/dialects/abstract/query-generator.js, lib/dialects/postgres/data-types.js, lib/dialects/postgres/index.js, lib/dialects/postgres/range.js, test/integration/dialects/postgres/dao.test.js, test/integration/dialects/postgres/range.test.js, test/unit/sql/where.test.js
This PR tends to clean up some issues with the range types
In order to support `contains element` ( `@>` ) Range should be able to stringify it's subtype too.
=> Tidy up range type

changelog.md, lib/dialects/abstract/query-generator.js, lib/dialects/mysql/index.js, test/unit/transaction.test.js
Closes #3568
`MySQL` transactions were broken because of `AUTO COMMIT`. Setting it to `0` will not work because it will remain same for whole connection. It can be solved if we don't send any `AUTO COMMIT` option at all. `MySQL` automatically keep a transaction under `0` and reset setting to `1` beyond transaction.
=> Fix 3568, MySQL transaction are not set to AutoCommit now

test/integration/data-types.test.js
Closes #4770 , I confirmed with a test that creating `ENUM` with spaces is indeed possible
=> ENUM allow spaces in their definition

lib/dialects/mysql/query-generator.js, test/unit/sql/add-column.test.js, test/unit/sql/change-column.test.js
When creating a foreign key constraint in MySQL, use the template
`{referring_table}_{attribute}_foreign_idx`, rather than just
`{attribute}_foreign_idx`, to avoid duplicate constraint names.
See GitHub #5826
=> Include tableName in MySQL fk contraint names

test/integration/instance.test.js, test/integration/instance.validations.test.js
Required for other ES6-refactorings to pass. I don't know why this doesn't fail on master.
=> Test fixes

test/integration/associations/belongs-to.test.js
This PR fixes a test which intermittently fails on MSSQL on Travis. e.g.: https://travis-ci.org/sequelize/sequelize/jobs/136937830
The issue is that the order in which the `User` instances is created in this test isn't necessarily the same as the order in the code. Most of the time it is, but sometimes not and so sometime the `id`s of the Users are in an unexpected order. When this happens the test fails. Hence failure which is only intermittent.
There doesn't appear to be anything wrong with the actual behavior that the test is testing for.
=> Fix intermittently failing test on MSSQL

lib/model.js
This moves all logic from `Model.build()` to the constructor, so they accept the exact same parameters. The only difference is `build()` can also take an array of values. Also makes `values` optional.
=> Make new Model() identical to Model.build()

changelog.md, lib/dialects/abstract/query-generator.js, test/integration/model/findAll/order.test.js
[FIXED] Fixed an issue where custom-named model fields break when offsetting, ordering, and including hasMany simultaneously. #5985
=> Closes #5985 - Cannot query a custom-named field when offsetting, ordering and using hasMany simultaneously (v3 pull request)

lib/model.js
`toString()` should not return `[object SequelizeModel:name]`, as a model is not an object anymore, but a class (function). The default behaviour for a class/function is to return the class source, like `class MyModel extends Sequelize.Model {...` which also gives you the information that it is a Sequelize model and the model name.
=> Don't override toString() in Model

changelog.md, lib/model.js, test/integration/model/count.test.js
Fixes #5057 , A regression issue in which `attributes` are not included in count any more.
=> Fix #5057, Count no longer include attributes

changelog.md, lib/dialects/abstract/query-generator.js, lib/dialects/mssql/query-generator.js, lib/dialects/mysql/query-generator.js, lib/dialects/postgres/query-generator.js, lib/dialects/sqlite/query-generator.js, lib/sequelize.js, lib/utils.js, package.json
As discussed in #6023.
This PR:
* Updates [inflection](https://www.npmjs.com/package/inflection) dependency to latest and pins the version
* Exports all used [inflection](https://www.npmjs.com/package/inflection) methods as methods of `Utils`
* Updates codebase to use e.g. `Utils.underscore()` rather than `inflection.underscore()`
* Allows a later version of [inflection](https://www.npmjs.com/package/inflection) to be set by user with `Sequelize.Utils.inflection = require('inflection')` and `Utils.pluralize()` etc will use this overriden version of [inflection](https://www.npmjs.com/package/inflection).
I will add to the [test shims](https://github.com/sequelize/sequelize/blob/master/test/supportShim.js) to check that `inflection` is not accessed directly once PR #5836 is merged.
=> Inflection

changelog.md, lib/associations/has-one.js, test/integration/associations/has-one.test.js
Fixed #6069 
Closes #6075 
`injectSetter` was assuming we always pass the instance but we should be allowed to use primary keys as well.
Now update on `hasOne` relation will work with `primaryKey` as well.
Thanks @arnaudbesnier for submitting a test case :)
=> Fix #6069, HasOne throws erro when try to update using a primary key

changelog.md, lib/model.js, test/integration/model/count.test.js
Closes #4442 
Fixes #4840 
Closes #3740
`distinct` option with `Model.count` was broken because it generates a SQL query like 
`COUNT( DISTINCT(*) )` which is incorrect.
As noted in issues mentioned above, we should allow an option to pass the `col` so `distinct` can work as expected.
PR #3740 can be closed because #3019 is closed and missing `Model.count` `paranoid` documentation is added in this PR
=> Fixes #4840, Model.count allow passing col to count on

changelog.md, index.js, lib/dialects/abstract/connection-manager.js, lib/dialects/mssql/connection-manager.js, lib/dialects/mssql/query.js, lib/dialects/mysql/connection-manager.js, lib/dialects/mysql/query.js, lib/dialects/postgres/connection-manager.js, lib/dialects/postgres/query.js, lib/dialects/sqlite/connection-manager.js, lib/dialects/sqlite/query.js, lib/hooks.js, lib/sequelize.js, lib/utils.js, lib/utils/logger.js, package.json
Closes #2852
Closes #851 
Added support for logging via DEBUG module.
Also used `depd` module to show deprecation warning. Setup a module for handling all logging tasks.
=> Fix #2852, Added DEBUG support and intensive connection logging

changelog.md, lib/promise.js, package.json, test/unit/promise.test.js
As discussed in #5974, this PR makes `Sequelize.Promise` an independent copy of the [bluebird](https://www.npmjs.com/package/bluebird) promise library.
The implications of this are:
* The shims applied to `Sequelize.Promise` for CLS support no longer affect the global instance of bluebird (returned from `require('bluebird')`)
* `Promise` used internally in Sequelize will not be affected by any patches / global options applied by another module to global `Bluebird`
* Promises returned from all Sequelize async methods are `instanceof Sequelize.Promise` but will not be `instanceof require('bluebird')`
It also opens the door for us to use `Promise.coroutine.addYieldHandler()` to allow yielding arrays of promises within coroutines …
=> Use independent copy of bluebird (closes #5974)

lib/model.js, lib/utils.js, lib/utils/logger.js, test/integration/associations/belongs-to.test.js, test/integration/data-types.test.js, test/integration/include/find.test.js, test/integration/instance.test.js, test/integration/model/attributes.test.js, test/integration/model/create.test.js, test/integration/model/findAll.test.js, test/integration/model/upsert.test.js
Closes #5322
Show warning if following conditions are satisfied 
- No `options.where` in `findAll` (or any other finder method)
- Model `attributes` are found in `options` passed to `findAll`
**Warning will look like this**
=> Fix #5322, warn if forgot to pass options.where

changelog.md, docs/docs/hooks.md, lib/hooks.js, lib/model.js, test/integration/hooks/create.test.js, test/integration/hooks/hooks.test.js, test/integration/hooks/updateAttributes.test.js
Closes #2702
Added `beforeSave` and `afterSave` hooks. These are independent hooks executed after their counterparts i.e. `before/after` `create/save` hooks, Order has been updated in docs.
Also now we can remove hooks by references
=> Fix #2702, before/after Save hook

changelog.md, docs/docs/hooks.md, lib/hooks.js, lib/model.js, test/integration/hooks/upsert.test.js
Closes #3965 
Added `before/after Upsert` hooks with tests and documentation update.
=> Fix #3965, before/after upsert hooks

changelog.md, lib/model.js, test/integration/hooks/find.test.js
Closes #5675
`options` now conformed after beforeFind hook so change in hook can be properly parsed as well.
=> Fixed #5675, beforeFind issue with options modification

lib/errors.js, lib/model.js
I literally just added the ability to catch invalid scope errors. My api allows user's to input scopes, and I need a way of catching those input errors. Adding this to the sequelize package seemed like the perfect work around for me, and it doesn't hurt to be there ;)
=> Added the ability to catch invalid scopes

docs/docs/raw-queries.md
Show example of wildcards and array replacements in raw-queries documentation. People that are using sequelize mainly for raw queries are likely to miss this information that is only on other documentation pages.
=> Show example of wildcards and array replacements

changelog.md, lib/data-types.js, lib/sequelize.js, lib/utils/validator-extras.js
Closes #6196 , Sequelize patching to validator will not modify the global instance.
Also fixed case where `isDecimal` method will return an `Array` instead of `Boolean`.
=> (clean up) Closes #6196, Don't global patch validator

lib/dialects/abstract/query-generator.js, test/integration/model/find.test.js
When writing more involved attribute definitions with functions (e.g. `attributes: [[sequelize.fn('COUNT', sequelize.fn('DISTINCT', sequelize.literal('CASE WHEN `rulez.acks`.`id` IS NULL AND...)` it happened to me couple of times already that I forgot to specify the actual alias for that attribute. In other words, the attribute was mistakenly defined as `['definition']` instead of `['definition', 'alias']`. In such cases, Sequelize fails with the following error:
```
Unhandled rejection TypeError: s.replace is not a function
at removeTicks (/opt/insights/sequelize/lib/utils.js:445:12)
at Object.addTicks …
```
=> Better validation of attribute definitions

changelog.md, lib/dialects/abstract/query-generator.js, lib/dialects/sqlite/query-generator.js
Renamed ignore to ignoreDuplicate to have a consistent behavior with bulkCreate.
There are tests in place for this.
=> Rename ignore into ignoreDuplicates

changelog.md, lib/dialects/mssql/query-generator.js, lib/dialects/mysql/query-generator.js, lib/dialects/sqlite/query-generator.js, test/unit/dialects/mysql/query-generator.test.js, test/unit/sql/index.test.js
Fixes #5888 , `MySQL` and `SQLite` were not properly quoting index names when removing.
=> Fix #5888, properly quote index when removing

changelog.md, lib/dialects/postgres/data-types.js, test/integration/data-types.test.js
Fixes #5747 , Incorrect `OID` was used for `Int4` in `range` type.
=> Fixed #5747, Properly parse Int4 range types

changelog.md, lib/model.js, test/integration/include/findAndCountAll.test.js, test/integration/model/count.test.js, test/unit/model/count.test.js
Currently the `count` and `findAndCount` and diverge in the build queries with the same query object. This unifies those two, removes unnecessary duplicated checks and fixes a bug which quite a few people ran into by optimistically removing all includes for [performance reasons](82403cfc1d165e2a01b6b0170efae6fc0355ba85).
I want to have fast queries but primarily stability is important. I'm willing to have a look at this in more detail to improve the performance later.
Fixes #1142 #2145 #2968 #3936 #4146 #4194 #5526 #5680 #6123 (I went through to many issues to always be certain but likely all get fixed by this).
Fixes partly #2886 #3319 #4737 #5465 (people that commented had similar issues or a part of the issue is fixed with this)
Somehwat related #2713
I know there should be tests …
=> Fix count queries with includes

changelog.md, lib/model.js, test/integration/model/count.test.js
This fixes a missed case for the new col option from #6114
[edit]
__Note__: Count is still not working with multiple fields e.g. a composite primary key. And is it really the best idea to add a new option instead of overloading the distinct option to also allow strings instead of a boolean?
[/edit]
=> Fix model.count with includes and specified column

changelog.md, lib/model.js, test/integration/model/create.test.js
Closes #4476 
Closes #3908
Closes #4103
Closes #3764
Closes #4600
Closes #4646 (PR Test case)
Closes #3789
Now `fields` will be properly maps to `attributes`
=> Fixes bulkCreate, Now it properly maps fields to attributes

changelog.md, lib/sequelize.js
Closes #5788, Passed `options.logging` directly to query so it can respect global `logging` options.
=> Fix #5788, passed sync options.logging to query directly

lib/dialects/mssql/query-generator.js, test/unit/sql/offset-limit.test.js
Quite the simple fix. Applies to MSSQL only.
To reproduce: Create two models and relate them. Then query one with an include of another and then ensure the query has NO order by BUT has an OFFSET or LIMIT. When the order by is automatigically prepend by mssql/query-generator.js, the table reference is not present.
I have tested in my environment but unsure how to make ya'll certain this is the right fix. It is though, I'm using it.
=> fixes msssql only error when no order by but has offset or limit present

docs/docs/associations.md
If not, a primary key for taggable_id is created, so no more than one tag per taggable could be created.
=> Primary key should be same as unique key (doc change) 

lib/dialects/mssql/query-generator.js, lib/dialects/mysql/query-generator.js, lib/dialects/postgres/query-generator.js, lib/dialects/sqlite/query-generator.js
This changes the QueryGenerators to use real prototypal inheritance instead of copying over properties with `_.extend` and `_.clone`. This uses a new ES6 feature, prototype initialization in object literals. This is not mutation of the prototype at runtime, but at object creation, it is the syntactic equivalent to `Object.create()` (JSHint is too stupid to detect this, ESLint will not complain). Turning these into classes doesnt make sense because they are just static objects with some methods on them. I feel this is probably one of the best use cases out there for this feature.
=> Use prototypal inheritance for QueryGenerators

changelog.md, lib/dialects/abstract/query.js, test/integration/model/findAll.test.js
Using `through.attributes:[]` or `include.attributes: []` doesn't ignore any attributes, It throws error in most cases. Fixed it by checking if parent include exists before trying to push child include in it.
Closes #5078
Closes #4222
Closes #5958
Closes #5590
Closes #6139
Closes #4866
Closes #6242
=> Fixed attribute:[] issues when using them in include or through

changelog.md, lib/dialects/postgres/data-types.js, test/integration/model/geography.test.js, test/integration/model/geometry.test.js
Fixes #6194 for `master v4` branch. Now we properly escape the `GEOMETRY` and `GEOGRAPHY`. `v3` fix can be found in PR #6302
=> Fixes #6194 (v4), GEOMETRY and GEOGRAPHY types now properly escaped

changelog.md, lib/dialects/postgres/data-types.js, test/integration/model/findAll/order.test.js, test/integration/model/geography.test.js, test/integration/model/geometry.test.js
Fixed #6194, Now we properly escape `GEOGRAPHY` and `GEOMETRY`
=> Fixed #6194, SQL Injection attack in GEOMETRY and GEOGRAPHY types

lib/data-types.js, test/integration/model/geometry.test.js
After reading CVE details I realized this issue was also applicable for MySQL case but apparently by injecting wrong values to `coordinates`.  It also point to an issue in `WKT` library
Linking #6194
=> MySQL GEOMETRY / GEOGRAPHY injection case

changelog.md, lib/data-types.js, lib/dialects/mysql/data-types.js, test/unit/sql/data-types.test.js
Closes #2038 , `DECIMAL` was missing implementation for `UNSIGNED` and `ZEROFILL`, Added for `MySQL`
=> Fixes #2038, Added missing UNSIGNED / ZEROFILL support for DECIMAL

docs/docs/getting-started.md
I thought the getting started guide missed Your first query, because if you go to the actual page that says "Querying", you don't get any information about actual querying, you have to go to "model usages" which is not quite logical.
So no people can start in the getting started guide like many people do and then go to the correct place to read more.
Also correct the section about promises to sound more nice.
Also `fieldName` and `freezeTableName` is nice features, but not something you need in a getting started guide. It just makes it look more complicated.
I even think that the `pool:` option in "Setting up a connection" should be removed, because who needs that anyways when they are first getting started? I could make new people think that they need it.
=> Docs: Updating getting started with Your first query

test/integration/include/seperate.test.js
Added explicit ids to 'should work with two schema models in a hasMany association' test to make sure the order assumed in the assertions of the test will always be correct. This fixes #6320.
=> Seperate test fix

README.md, docs/index.md, mkdocs.yml, package.json
Since io.js has been merged into the main Node.js project and there hasn't been a new release in almost a year, I think it's safe to remove any references of it from the project. I did notice there was a pre-existing PR for this (#4791), but it was closed without explanation. So, pushing this again.
=> Remove references to io.js

lib/sequelize.js
- [x ] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
this change makes it possible to initialize Sequelize with a DSN that contains a password which contains one or more ":" characters, e.q.
```js
const Sequelize = require('sequelize')
const instance = Sequelize('mysql://root:234*%25%26%23%24%5E%40%23%7B%7D::\'.%26%40%40@localhost:3600', {});
```
in this example the MySQL password would be: `234*%&#$^@#{}::'.&@@`
without this change Sequelize attempts to connect to MySQL with a password of `234*%&#$^@#{}` ... this is a truncated password that results in a failed connection.
=> make it possible to use ":" in passwords in a DSN

test/integration/include/seperate.test.js
The origin  test "should work with two schema models in a hasMany association" relys on the record insert order which makes the result randomly
Add record id explicitly and query in explicitly order
=> Fix the unstable test "should work with two schema models in a hasMany association"

docs/docs/scopes.md
Added a missing piece regarding invoking `.scope()` on an `include`d model in a `scope` definition.
=> [Docs] Add include:[{model: User.scope('...')}] section

changelog.md, lib/dialects/sqlite/connection-manager.js, lib/sequelize.js
- [Y] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [N] Does your issue contain a link to existing issue (Closes #[issue]) or a description of the issue you are solving?
- [N] Have you added new tests to prevent regressions?
- [Y] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [Y] Have you added an entry under `Future` in the changelog?
Added SQLCipher support to SQLite by utilising the password connection parameter. No unit tests were written as they would be unsuitable. Integration tests weren't written as it requires changing the project from using SQLite to SQLCipher. It was tested against my own project and the encryption was correctly applied.
Same change as described in #6020 and …
=> Added SQCipher support for SQLite

docs/docs/migrations.md
Added examples to the documentation to show how to use custom schema when executing migrations.
Resolved #4768
=> (docs) #4768 Add schema examples for migrations

changelog.md, lib/dialects/postgres/query-generator.js, test/unit/sql/select.test.js
Alwasy quote identifier which has '.'
=> Fix the wrong Postgres SQL of nested include when quoteIdentifiers is false

lib/model.js, test/integration/model.test.js
I'm getting the following deadlock errors when creating indexes concurrently in postgresql 9.4.
```
{ [SequelizeDatabaseError: deadlock detected]
name: 'SequelizeDatabaseError',
message: 'deadlock detected',
parent:
{ [error: deadlock detected]
name: 'error',
length: 297,
severity: 'ERROR',
code: '40P01',
detail: 'Process 10931 waits for ShareLock on relation 3878009 of database 25217; blocked by process 10933.\nProcess 10933 waits for ShareLock on virtual transaction 2/3266; blocked by process 10931.',
hint: 'See server log for query details.',
position: undefined,
internalPosition: undefined,
internalQuery: undefined,
where: undefined,
schema: undefined,
table: undefined,
column: undefined,
dataType: undefined,
constraint: undefined,
file: 'deadlock.c',
line: '956',
routine: …
```
=> deadlock detected when creating concurrent index

lib/dialects/mssql/connection-manager.js, lib/dialects/sqlite/connection-manager.js
This is a simple fix for webpack and probably browserify to pick up the dialect packages. postgres and mysql already contain this logic, I needed for mssql but I also added for sqlite for consistency.
=> Ease dialect require for webpack

.eslintrc.json, package.json
First step towards #5963 
Even though a great part of the library (tests) is not in ES6 yet and there are a whole lot of lint issues, I noticed that the continued development already introduced more style issues that did not get caught by JSHint. I decided it would be the best to add the `.eslintrc` now, so IDEs can pick it up and warn contributors about style issues while writing code.
I tried to match the current code style of the library as much as possible. Some issues like `no-extra-boolean-cast` are heavily used in the whole library, so I added them as warning for now. It is configured to especially error on not using ES6 (let/const/arrow functions etc) and I already used this file to do my refactors. One really nice thing is also that ESLint detects indentation errors while JSHint …
=> Add eslint

changelog.md, docs/articles/getting-started.md, docs/docs/getting-started.md, docs/docs/usage.md, lib/dialects/mysql/connection-manager.js, lib/dialects/mysql/data-types.js, lib/dialects/mysql/query.js, package.json, test/integration/data-types.test.js, test/integration/dialects/mysql/connector-manager.test.js, test/integration/include/seperate.test.js, test/integration/model.test.js, test/integration/sequelize.test.js
Closes #6327 , With this all dialects driver support the ability to use the prepared statements. Its first step towards #3495 
**Notable changes**
- `MySQL` doesn't support named timezones ( out of box ) so I have used `moment-timezone` to convert named timezone to their relative offsets.
- ~~`node-mysql2` provides `createConnection()`, which directly connect with server ( `node-mysql2` offers `connect` method). It can throw `EventEmitter` based errors which can only be caught using `domains`. I am open to other ideas if we do not want to use `domains`~~ We no longer use `domains`, thanks @felixfbecker for pushing me to find alternate solution :)
- `mysql` dialect now parse `BLOB` , to return `null` in case we get an empty buffer.
**Performance**
`sequelize-benchmark` reports improvement …
=> Migrate to Node-MySQL2

changelog.md, lib/dialects/postgres/query.js, test/integration/dialects/postgres/dao.test.js
The origin code change the row attributes order which makes  AbstractQuery._groupJoinData can't append the join data to the root.
Modify the code to keep the key sequence when translate the lower case key name to camelcase name
Another solution is to modify https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/query.js#L481. However, I don't want to introduce the performance overhead on other database. But the order returned by Object.keys is arbitrary. So AbstractQuery._groupJoinData is builtin on a specific JS runtime behavior and may be wrong in the future.
=> Let nested include query returns results when quoteIdentifiers is false on Postgres

lib/sequelize.js, test/integration/sequelize.test.js
Changes from using `_.isPlainObject` to checking with `typeof === 'object'` to support custom class instances like from `sql-template-strings`.
=> Use typeof instead of _.isPlainObject

changelog.md, docs/api/model.md, lib/dialects/postgres/query-generator.js, lib/model.js, test/unit/sql/delete.test.js
Model.truncate() is optionally allow to reset the sequence of the primary key 
by passing the option restartIdentity to true.
```sql
TRUNCATE table_name RESTART IDENTITY;
```
This change is only for Postgres because MySQL and SSQL already restart the counter when you truncate a table.
=> Close #5356 : Add option to restart identity when truncate

lib/sequelize.js
=> Export data types under DataTypes namespace

changelog.md, lib/associations/belongs-to-many.js, lib/associations/has-many.js, lib/associations/helpers.js, lib/model.js, lib/sequelize.js
- Removes the `modelManager` argument. I checked the code and the only way `modelManager` was ever used was to get `modelManager.sequelize`, which is already available at `Model.sequelize`.
- I moved the docs from `Sequelize.define()` to `Model.init()` since that is the primary API for the future. Added a _See ..._ note.
- `sequelize` is passed as option in `options`. The plan is to one day make it optional, for now it is required. This is actually the way it was passed to Model.init in v3 already.
- Moved important logic like option merging that was still in `Sequelize.define()` to `Model.init()`
One thing I don't know though is what should happen to the `beforeDefine` hook. I moved it to `Model.init`, but the name is kind of confusing. The problem is though that there is already the …
=> Clean up Model.init() API

docs/docs/querying.md
It's minor update of documentation - operator `$eq` is now documented.
=> Added information about  operator $eq

changelog.md, lib/data-types.js, test/unit/model/validation.test.js
Currently the type validations for dates are very strict. Most of the type validations accept strings as input and this should also be the case for dates as far as I see it.
=> Fix type validations being to strict for dates

lib/sequelize.js, package.json, test/integration/assets/es6project.js, test/integration/sequelize.test.js
https://github.com/sequelize/sequelize/pull/6493#issuecomment-242351497
> @janmeier I don't know why the test needs a babel dep though. The issue you linked was that `sequelize.import()` did not support models exported as a `default` export instead of `module.exports`. If we need a test at all for this, it should be enough to import a simple model that is exported with `exports.default`. The change in Babel was more a fix than a change, previously it was not conforming to the ES6 spec. The issue therefor is more about ES6 support for model files and not Babel support - TypeScript uses ES6 modules aswell, and I don't think we should test integration with every possible transpiler out there.
=> Remove Babel devDependency

changelog.md, lib/dialects/abstract/query-generator.js, test/unit/sql/select.test.js
The problem is that if you make a select query with `order`,`limit`,`offset` clauses and with `include` of a association which will cause subquery generation. The `order` clause is not included in the subquery when you provide `order` option in form of plain string (not an array). This pull request fixes that.
=> Bugfix/order clause in subquery - for  the `master`

README.md
This badge was linking straight to Slack, which requires an invite. Now it links to the inviter app on Heroku.
=> Adds link to Slack inviter

lib/sequelize.js
Addresses #6435 in v3, as discussed in PR #6438. Also, totally messed up #6577, which is essentially the same PR, but this one is rebased appropriately.
- Not sure about how the Future log works. Should that only be used for v4?
- Not sure if this needs tests. If could add something to check if DataTypes exists on the Sequelize prototype, but there is no precedent for this, such as with Validator or Transaction.
Currently, DataTypes are accessed on the Sequelize object by using the type's name: `Sequelize.INTEGER`.
This change _additionally_ adds data types under the DataTypes namespace: `Sequelize.DataTypes.INTEGER`
=> Backport data types under DataTypes namespace to v3.

lib/associations/has-many.js, lib/dialects/abstract/query-generator.js, test/integration/model/findAll/groupedLimit.test.js, test/unit/sql/select.test.js
This code is the first step towards better support for BTM associations in https://github.com/mickhansen/dataloader-sequelize/
TL;DR - Dataloader batches multiple simultaneous calls to `BTM.get` e.g. `project.getMembers()`, into a single query. This is similar to what `include.separate` does for hasMany, with some extra smarts.
I've changed the `groupedLimit.on` code to accept an an array of `[association, string]` to signify that reach row should be joined. We need this to support BTM, because we need to filter on the join table. In the project <-> users example, we already have a list of project ids, and we want to find a limited amount of matching users for each project.
This should also be the first step towards `include.separate` support for belongs to many.
=> Grouped limit include

changelog.md, lib/dialects/abstract/query-generator.js, test/unit/sql/select.test.js
Note: because I use `postgres v9.3` few test cases (14) does not pass because of unsupported new features which were introduces in postgres v9.4 like (jsonb, type geometry)... I expect the tests to work including those which are using new features of postgres v9.4. Although I did not run tests wit postgres v9.4 installed.
The problem is that if you make a select query with `order`,`limit`,`offset` clauses and with `include` of a association which will cause subquery generation. The `order` clause is not included in the subquery when you provide `order` option in form of plain string (not an array). This pull request fixes that.
=> Bugfix/order clause in subquery - for the `v3`

docs/api/sequelize.md
This is *only* a documentation PR.
It's just slightly annoying that these URLs are just text in the markdown and not links so I tweaked it up a bit.
=> Linkify URLs in the docs

changelog.md, lib/dialects/postgres/query-generator.js, test/integration/dialects/postgres/query-interface.test.js
I have 1 failing testing on my system with the current master branch before adding my changes 
Failing test:
[POSTGRES] DataTypes should parse an empty GEOMETRY field:
SequelizeDatabaseError: Too few ordinates in GeoJSON
All others are passing.
no
Changes are around the postgres query generator to address some issues I found when attempting to use dropFunction and createFunction. The root cause of the issue was due to the function expandFunctionParamList. Along the way I also found an issue with dropFunction in which the generated sql lacked a space after the keyword 'FUNCTION' ex: "FUNCTION myfunc" vs "FUNCTIONmyfunc".  I've also added tests for createFunction and dropFunction and I've stubbed out some tests for renameFunction.
=> Update postgres query interface

changelog.md, lib/dialects/abstract/query-generator.js, test/integration/associations/belongs-to.test.js
Fixes the reversed keys issued in #6400 for a belongsTo-association join.
Closes #6400
=> V4 fix belongsto foreignkeys

changelog.md, lib/dialects/abstract/query-generator.js, test/integration/associations/belongs-to.test.js
Fixes the reversed keys issued in #6400 for a belongsTo-association join.
Closes #6400
=> V3 fix belongsto foreignkeys

.gitignore, lib/dialects/abstract/query-generator.js
This is already done for update queries but was missing for inserts.
=> Mix in default options for insert queries.

changelog.md, lib/dialects/mssql/query-generator.js, test/unit/sql/create-table.test.js
Prior than this fix this query was generated:
```SQL
CREATE TABLE [viz] ([right] VARCHAR(255) CHECK (right IN(...
```
`right` was not escaped and MSSQL didn't like it.
=> Fix unescaped field in MSSQL query generation

docs/api/model.md, lib/model.js
Small documentation fix; added space after period in two places.
=> Docs: Small formatting fix

.travis.yml, docker-compose.yml, test/config/.docker.env
I recently broke docker setup for testing locally when adding Takis support (#6774), Basically Postgres and MySQL both were trying to run on same port. This PR fix this
=> Fixing docker for devs :cat:

lib/model.js, test/integration/instance.test.js
- [√ ] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [√] Have you added new tests to prevent regressions?
add options.silent support for Instance increment and decrement method, so you can use 
```
user.increment('count', {silent: true})
```
to prevent update the updatedAt field.
But I got a error run npm …
=> add options.silent support for Instance increment and decrement.

changelog.md, lib/model.js, test/integration/model/paranoid.test.js
`restore` was ignoring the `field` attribute from `deletedAt`, trying to query to non existing column. I have fixed it by using `field` if available
=> (fix) restore ignore field from deletedAt attr

changelog.md, lib/associations/belongs-to-many.js, lib/model.js, test/integration/assets/es6project.js, test/integration/model/findAll/groupedLimit.test.js
When `groupedLimit` was used on a N:M relationship whoes junction/through model was paranoid, queries generated didn't include the paranoid clause. I have fixed it by applying paranoid clause when we have this case
Also `BelongsToMany` options incorrectly uses source model `options`, this is fixed as well
=> fix: groupedLimit on paranoid junction table

lib/instance.js, test/unit/instance/set.test.js
Before this change it is not possible to use `instance.set('date', '1970-01-01')` when:
-  model has allowNull: true
- instance retrieved from database and thus date having null as value.
=> fix instance.set '1970-01-01' to null field

changelog.md, lib/utils.js, test/integration/instance/update.test.js, test/integration/timezone.test.js
Closes [#6441](https://github.com/sequelize/sequelize/issues/6441)
Added mysql to the list of dialects that return milliseconds from the now function. Updated timezone test to account for milliseconds in the time being compared.
=> Milliseconds in time stamps for createdAt, updatedAt for MySQL 

changelog.md, docs/api/sequelize.md, lib/dialects/mysql/query-generator.js, test/integration/sequelize.test.js, test/unit/dialects/mysql/query-generator.test.js
This commit adds `ROW_FORMAT` support to the query-generator for
the mysql dialect by adding `options.format` for sequelize.define().
InnoDB's new Barracuda file format offers 2 new types of row formats
which offer significant improvements if working with utf8mb4 collation
by supporting index key prefixes up to 3072 bytes instead of the
default of 767 bytes offered with COMPACT or REDUNDANT row types
offered in the legacy Antelope file format.
Fixes #6824
=> Fixes #6824 Add ROW_FORMAT support to mysql query-generator

.gitignore, changelog.md, lib/dialects/mssql/index.js, lib/dialects/mssql/query-generator.js, lib/dialects/mssql/query.js, lib/model.js, test/integration/hooks/upsert.test.js, test/integration/model/upsert.test.js
This MR enables `upsert` query for MSSQL dialect using [SQL Server MERGE](https://msdn.microsoft.com/en-us/library/bb510625.aspx) statements.
- Adds IDENTITY_INSERT(autoIncrement) wrapper if autoIncrement columns are given a value
- Tries to use PrimaryKey for the join clause. Else uses Unique keys
- Handles both primary and unique composite key case
- Partial Primary/Unique Keys are filtered out as we cannot find a unique row if specified
- MySQL returns 1 for inserted, 2 for updated. Similar output is achieved in MSSQL using `$action` which returns Insert/Update based on the executed query.
- Modified hooks test to explicitly pass either primaryKey/uniqueKey as either of them should be passed for upsert.
- Used `const` in places as suggested by eslint
- Added `WITH(HOLDLOCK)` hint to …
=> UPSERT functionality for MSSQL

changelog.md, lib/associations/belongs-to-many.js, lib/associations/belongs-to.js, lib/associations/has-many.js, lib/associations/has-one.js, lib/associations/helpers.js, lib/associations/mixin.js, test/unit/associations/belongs-to-many.test.js, test/unit/associations/belongs-to.test.js, test/unit/associations/has-many.test.js
Fixes https://github.com/sequelize/sequelize/issues/6682
All methods (get/set/create/etc.) of all associations are now exposed.
=> Association mixins refactoring

lib/dialects/sqlite/query.js
Backport for: #5931
Closes #5755
Port changes from #5755 to **v3** branch.
=> Fix issues №5755 for v3 branch

changelog.md, lib/dialects/abstract/query-generator.js, test/integration/include/findAll.test.js
=> generateThroughJoin Fix - V3 port

changelog.md, docs/api/sequelize.md, lib/dialects/abstract/query-generator.js, test/integration/utils.test.js, test/unit/utils.test.js
- I did not with mssql (don't have it available)
- linting seems broken in master (13k problems)
- not yet, want to hear team's opinion on the change first
https://github.com/sequelize/sequelize/issues/6666
Makes it possible to pass condition objects (e.g. `{foo: 'bar'}`) to `Sequelize.fn()`, `Sequelize.cast()`.
This makes it easy to use conditional counts in Sequelize queries, e.g.
`Sequelize.fn('sum', {name: 'Fred'})` which results in `SUM(``name``= 'Fred')` which can be used in attribute definition to count entities for which the condition matches.
I did not get a chance to test with mssql as I do not have it available. If …
=> support condition objects in utility functions #6666

lib/dialects/postgres/data-types.js, test/integration/data-types.test.js
=> Fixed range integer parsing

lib/sql-string.js
This PR adds a more informative error message so you actually know what caused the error.
Before:
```
TypeError: sql.replace is not a function
at Object.format (/Users/contra/Projects/staeco/node_modules/sequelize/lib/sql-string.js:87:14)
at Object.format (/Users/contra/Projects/staeco/node_modules/sequelize/lib/utils.js:119:20)
at Object.getWhereConditions (/Users/contra/Projects/staeco/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2303:24)
```
After:
```js
Error: Invalid SQL string provided: ST_Intersects(123)
at Object.format (/Users/contra/Projects/staeco/node_modules/sequelize/lib/sql-string.js:87:14)
at Object.format (/Users/contra/Projects/staeco/node_modules/sequelize/lib/utils.js:119:20)
at Object.getWhereConditions …
```
=> add a more informative error message

changelog.md, lib/model.js, test/integration/model/paranoid.test.js
This is a version of #6916, ported against `master`.
This fixes an issue where `undefined` was returned when using a soft-delete on MSSQL because the query type of the `UPDATE` query that ran the soft-delete was not properly set.
=> Bugfix: Return value in MSSQL soft-delete

changelog.md, lib/model.js, test/integration/model/paranoid.test.js
This fixes an issue where `undefined` was returned when using a soft-delete on MSSQL because the query type of the `UPDATE` query that ran the soft-delete was not properly set.
=> v3 Bugfix: Return value in MSSQL soft-delete

changelog.md, lib/instance-validator.js
Closes #6531 
Will add the changelog after reviews
=> Fix: custom msg not used for notNull validations

lib/data-types.js, lib/dialects/abstract/query.js, lib/sequelize.js, lib/utils/parameter-validator.js, lib/utils/validator-extras.js, package.json
**Updated**
https://github.com/chriso/validator.js/releases/tag/6.2.0
https://github.com/cschwarz/wkx/releases/tag/v0.4.1
**Deprecation / Warning / Logging**
Various warning and logging message, we now fully use `Utils.<Logging>` stuff for this
=> Deprecate stuff / Update critical libs

changelog.md, lib/dialects/abstract/query-generator.js, lib/dialects/mssql/query-generator.js, lib/model.js, test/integration/model/update.test.js, test/unit/dialects/mssql/query-generator.test.js, test/unit/sql/update.js
SQL Server uses TOP(n) keyword to limit the number of updated rows.
https://msdn.microsoft.com/en-us/library/ms177523.aspx
Closes #6636
=> Fixes MSSQL Limit in update query, closes #6636

changelog.md, lib/errors.js, lib/instance-validator.js, test/unit/model/validation.test.js
Fixes #3899 , Error object for validation error was always missing `value` field, which is important for front end validation etc. It was broken for `custom` and `builtIn` validators. Now its fixed, regression included
Will add change log after reviews
=> Fix #3899 no value in built-in/custom validation errors

docs/docs/models-definition.md
Spelling fix in docs for model definition 
geomerty => geometry
=> update doc: models-definition spelling fix

appveyor-setup.ps1, changelog.md, lib/dialects/abstract/query-generator.js, lib/dialects/mssql/index.js, lib/dialects/mssql/query-generator.js, lib/dialects/mssql/query.js, lib/query-interface.js, lib/transaction.js, test/integration/model/create.test.js, test/integration/sequelize.transaction.test.js, test/integration/transaction.test.js
=> Transactions for SQL Server - V3 backport

changelog.md, lib/associations/mixin.js, lib/dialects/abstract/query-generator.js, lib/errors.js, lib/model.js, test/integration/model/find.test.js, test/integration/model/findAll.test.js, test/unit/model/include.test.js
This PR aims to make error messages that appear when using the `include` keyword more user friendly. Currently, if a user specifies an association incorrectly within the `include` keyword, Sequelize throws an error stating: "Target is not associated with Source!", substituting model names where appropriate. This error message is very helpful in the instances when the target and source models are not associated; however, this is currently the only error message thrown when `include` statements are erroneously specified, even when the source and target models are associated!
I've broken down incorrect `include` statement usage into …
=> Make Eager Loading Error Messages More User-Friendly

lib/model.js
(I have not been able to test against `master` due to  `npm install` failing with `gyp: Call to 'pg_config --libdir' returned exit status 127 while in binding.gyp.  However this is reproduceable with latest version in npm and the code seems largely unchanged, so I'm assuming this is still an issue...?)
https://gist.github.com/broofa/cee97d28e3923ad62438561438f7e12a is a standalone test case showing how sequelized.options.define.defaultScope.options.attributes is overwritten when defining a model.    It logs the state of of this property before, between, and after doing two define() calls.  The output I see (Sequelized v3.27.0) is this:
```
kieffer@Roberts-MacBook-Pro$ node …
```
=> Clone defaultScope so it doesn't get overwritten in Model#init

changelog.md, lib/dialects/mssql/query.js, test/integration/model/upsert.test.js
SQL SERVER `MERGE` statement is used in upsert query. The foreignKey violations were formatted as sequelizeDatabaseError. Added `MERGE` statement to mssql formatError method
Closes #7011
=> [MSSQL] Format Merge Statement foreignKey violation as ForeignKeyConstraintError

lib/sequelize.js
As the title says. #6971 for details
=> Clone defaultScope so it doesn't get overwritten in Model#init v3

lib/associations/base.js, lib/associations/belongs-to-many.js, lib/associations/belongs-to.js, lib/associations/has-many.js, lib/associations/has-one.js, lib/instance-validator.js, lib/instance.js, lib/model-manager.js, lib/model.js, lib/model/attribute.js, lib/sequelize.js, lib/transaction.js
Small backport of my ES6 refactor for v3. Makes imports like
```ts
import {Sequelize} from 'sequelize'
```
possible and the TypeScript definitions easier.
=> ES6 import v3

changelog.md, lib/model.js, test/unit/model/findall.test.js
This PR resolves issue #7030. In addition, it adds an additional warning when invalid options are provided to findAll (and all of its callers). If a user passes an invalid option to this function, chances are his intention was to do something else. The goal of this PR is to help developers identify and correct their mistakes early.
=> Improved findall warnings

changelog.md, lib/model.js, test/unit/model/scope.test.js
`npm run test-sqlite` and `npm run test-postgres` pass. I don't have the other dialects setup and configured locally.
Closes #7058 
Add test that fails before the change.
This PR changes [.splice](https://github.com/sequelize/sequelize/blob/master/lib/model.js#L1306) to `.slice` to ensure that the original methods array is not modified so the scope objects may be reused in consecutive calls to `.scope`.
=> Consecutive function scopes

docs/docs/associations.md
> Defining ``through`` is required. 
When I was reading through I accidentally read over this a few times, bolding will make it stand out more.
New:
> Defining ``through`` is **required**.
=> Documentation: Bolded that through is required for Belongs-To-Many associations

changelog.md, lib/dialects/mssql/query-generator.js, lib/dialects/mssql/query-interface.js, lib/dialects/mysql/query-interface.js, test/integration/query-interface.test.js, test/unit/dialects/mssql/query-generator.test.js
When the `removeColumn` method is called on a primaryKey column, SQL Server errors as the primaryKey column has an associated constraint which should be dropped before dropping the primaryKey column.
- Added `getPrimaryKeyConstraint` method to retrieve primary key constraint based on tableName and columnName.
- Extends #4943
=> MSSQL removeColumn method fix for primaryKey column

changelog.md, test/integration/sequelize.test.js
This removes the after function from `test/integration/sequelize.test.js` that unlinks `test/integration/assets/es6project.js` as well as the `fs` requirement at the top.
=> V3: test/integration/assets/es6project.js gets deleted

changelog.md, docs/docs/transactions.md, lib/dialects/mssql/connection-manager.js, lib/dialects/mssql/query-generator.js
1. Tedious accepts isolationLevel to be passed to beginTransaction query. Since we do the same [here](https://github.com/sequelize/sequelize/blob/master/lib/dialects/mssql/query.js#L54), we can skip the `setIsolationLevelQuery`. The `setIsolationLevel` query is skipped by the [this](https://github.com/sequelize/sequelize/blob/master/lib/query-interface.js#L833-L837) existing snippet.
2. Enable debugging of tedious. Tedious can be run in debug mode by passing debug object with available options from [tedious api](http://tediousjs.github.io/tedious/api-connection.html) via `dialectOptions`. Added debug listener
=> MSSQL - Skip isolationLevel query, enable tedious debugging

changelog.md, lib/errors.js, lib/model.js, test/unit/model/findall.test.js
Currently, if a user attempts to pass a string into the attributes option of findAll, Sequelize throws the following error:
Unhandled rejection TypeError: attributes.map is not a function
at Object.escapeAttributes (/Users/nickdrane/coding/patch/sequelize/lib/dialects/abstract/query-generator.js:1028:37)
at Object.selectQuery (/Users/nickdrane/coding/patch/sequelize/lib/dialects/abstract/query-generator.js:800:28)
at QueryInterface.select (/Users/nickdrane/coding/patch/sequelize/lib/query-interface.js:635:27)
at Promise.try.then.then.then (/Users/nickdrane/coding/patch/sequelize/lib/model.js:1513:34)
at tryCatcher …
=> Throw an error when attribute options are not formatted correctly

changelog.md, lib/dialects/abstract/query-generator.js, lib/model.js, lib/query-interface.js, test/unit/dialects/mssql/query-generator.test.js, test/unit/dialects/mysql/query-generator.test.js, test/unit/dialects/postgres/query-generator.test.js, test/unit/dialects/sqlite/query-generator.test.js
Closes #7112.
As suggested by the issue #7112:
- Reuse and rename the `query-generator::incrementQuery()` to `query-generator::incrementOrDecrementQuery()`, which now receives a boolean argument to represent the intention of incrementing or decrementing.
- Rename `query-interface::increment()` to `query-interface::incrementOrDecrement()` to pass the option `options.increment`.
- Change the `model::decrement()` implementation to call `model::increment()` with the option `increment = false`.
Doubts: Tests are passing (`npm run test-docker`), but should we add any test for this internal change?
=> Fix `Instance.decrement` precision problems

lib/model.js, test/integration/model/create/include.test.js
Fixes the issue I described in the comments of #7159, which is exactly the same issue except it's located in a different code path.
The following example from the documentation mentions the creation of associations with belongsToMany relations in one step, but it didn't actually work. This PR makes it work.
http://docs.sequelizejs.com/en/latest/docs/associations/#creating-elements-of-a-hasmany-or-belongstomany-association
=> Fixes creation of polymorphic belongToMany associations in one step #7159

changelog.md, lib/instance.js, test/integration/instance.test.js
Closes: #6356 
Fix ER_EMPTY_QUERY reject on update only virtual fields and add test.
=> V3 Fix issues #6356

changelog.md, lib/dialects/mssql/query-interface.js
Use lodash `_.assign` to pass user defined options such as transaction to MSSQL `removeColumn` queries
=> Pass options object to MSSQL removeColumn queries

changelog.md, lib/instance.js, test/unit/instance/previous.test.js
Previous method of the instance was working incorrectly
=> Fix correct previous value

changelog.md, lib/dialects/mssql/data-types.js, test/unit/sql/data-types.test.js, test/unit/sql/insert.js
Closes https://github.com/sequelize/sequelize/issues/5403
=> MSSQL - Changed DataTypes.DATE to use DATETIMEOFFSET datatype

lib/associations/belongs-to-many.js, test/integration/associations/belongs-to-many.test.js
fixing issue for v3: https://github.com/sequelize/sequelize/issues/7153
=> Fixes setAssociation with scope

changelog.md, lib/dialects/sqlite/query-generator.js, test/unit/dialects/sqlite/query-generator.test.js
This PR fixes a bug in the query generator for Sqlite, in which the definition of a composite unique constraint would not properly wrap in quotes the column names. This causes the statement to fail whenever a column name is the same as a reserved keyword (like `order`, `group`, `index`, ...), or when it contains certain non alpha-numerical characters (like a space).
For example the following declaration:
```js
this.sequelize.define('user', {
name: {
type: Sequelize.STRING,
unique: 'uniqueConstraint'
},
'column with space': {
type: Sequelize.INTEGER,
unique: 'uniqueConstraint'
}
});
```
would generate the following statement (new lines added for readability):
```sql
CREATE TABLE IF NOT EXISTS `users` (
`id` INTEGER PRIMARY KEY AUTOINCREMENT,
`name` VARCHAR(255),
`column with space` …
```
=> Add quotes around column names for unique constraints in sqlite (fixes #4407)

changelog.md, lib/model.js, lib/query-interface.js, test/integration/model/upsert.test.js, test/unit/model/indexes.test.js
`indexes` defined via the following snippet are not added to `Model.rawAttributes`.
```javascript
const User = current.define('User', {
name: DataTypes.STRING,
address: DataTypes.STRING
}, {
indexes: [{
unique: true,
fields: ['name', 'address']
}]
});
```
`Model.upsert` query uses `rawAttributes` to find primary/unique indexes and hence the upsert query would fail in case of the above model definition.
Fixes https://github.com/sequelize/sequelize/pull/6842#issuecomment-274774286
=> Added unique indexes to rawAttributes

changelog.md, lib/dialects/sqlite/query-generator.js, test/unit/dialects/sqlite/query-generator.test.js
This is a backport to V3 of the fix to the issue addressed in the PR #7224. It fixes the issue #4407.
=> V3 Add quotes around column names for unique constraints in sqlite (fixes #4407)

changelog.md, lib/model.js
replace a critical usage of `Array.concat` with a `for` loop and `Array.prototype.push` for a performance improvement on large queries
This change provides a performance boost to large queries. I found this when profiling an ugly query that returns tens of thousands of rows, with `include`s 4 levels deep. The line with `Array.concat()` is called hundreds of thousands of times and is a bottleneck.
For loops are [much faster](https://jsperf.com/array-concat-vs-push-sequelize) and in my real-world testing with the ugly query, was about 3 times faster, going from 60-90s down to about 21s.
Attached: part of the `node --profile` output …
=> performance: replace a critical usage of Array.concat with for loop/push

changelog.md, lib/sequelize.js, test/integration/error.test.js
This PR is to expose the new OptimisticLockError introduced in #6637 so users may detect and handle conflicts accordingly. Unless I'm overlooking something, optimistic locking will not be fully functional until the error is available outside the project.
Tests have been added much like those for other errors (e.g. ValidationError).
=> Expose OptimisticLockError on Sequelize object (#6637)

docs/docs/models-usage.md
Found a spot in the documentation duplicated some text it said: 
> code code
so I removed the duplicate text.
=> Duplicated word 'code' removed.

lib/model.js, test/integration/model/update.test.js, test/unit/instance/previous.test.js
Fixed incorrect changes in `previous` method working from https://github.com/sequelize/sequelize/pull/7189#issuecomment-281325021
Actual issue that PR was trying to solve was `incorrect previous value when using custom getter / setter`. So I have added few more unit tests and a fix for that issue @nemisj 
This will also conform with the fact that `_previousDataValues` should be set in last stage of hook lifecycle.
@BorisKozo @barriber initially pointed out this issue, you guys please have a look on new changes as well
=> restore setDataValue, fixed set issue with customGetter/Setter

changelog.md, lib/model.js
This is a revision of PR #7290 to address part 2 of issue #7204. The clause used for soft deletes should compare `deletedAt` using `$gt` and not `$gte` so records are *never* returned after they've been deleted.
The original PR for this issue also attempted to address server/database timezone inconsistencies but these changes have been abandoned in favor of configuring the database for UTC (see #7290 for details).
=> Deleted records can be queried in the same second

changelog.md, lib/query-interface.js, test/integration/query-interface.test.js
=> Show a reasonable message when column is missing in renameColumn

changelog.md, lib/dialects/abstract/query-generator.js
In generating the bulk insert query, the serials are stored in an array. This array can potentially be up to size N, which is the number of rows to be created.
When generating the tuples at a later stage, we walk through the records one-by-one - O(N) iterations. However, in a single iteration, we were performing a lookup in the serials array (indexOf costs O(N)),
leading to a O(N^2) runtime and poor performance for large number of records inserted.
This patch converts the serials array into an object map instead, so lookups cost O(1) time.
=> fix: Make bulkCreate run in O(N) time. Closes issue #4247.

changelog.md, lib/transaction.js, test/integration/replication.test.js
Closes https://github.com/sequelize/sequelize/issues/7323
`transaction()` accepts one more option, called `readOnly`. If true, the transaction is run on the read-replica.
=> read-only transactions for use on read-replicas

changelog.md, lib/model.js, test/unit/model/removeAttribute.test.js
Fix for Issue #7318 - removeAttribute('id') results in undefined: null data value (https://github.com/sequelize/sequelize/issues/7318)
Added regression test for the fix
=>  removeAttribute('id') results in undefined: null data value (#7318)

changelog.md, docs/api/sequelize.md, lib/model.js, lib/sequelize.js, test/integration/model/sync.test.js
This patch should provide an easy way to migrate the database automatically on the fly in a development environment. This is my first PR to an open source project, so let me know if anything should be structured differently.
This patch allows for altering existing tables when syncing. This will sometimes destroy data if there is no direct conversion from the existing type to the new type. When removing a column, the data in the deleted column will be destroyed. When adding a column, the data in the added column will be the default value.
~~Also, where should I put the tests as I couldn't find `sync` being tested anywhere I could only find sync being used in the hooks test and in most tests as a prerequisite.~~
Everything is tested …
=> Added feature to alter tables on sync. Fixes #537

.npmignore
Including esdoc in the latest v3.30.3 release adds an additional 130MB to what was previously 14MB in the v3.30.2 npm release. This change brings it back down to something sane.
=> don't include esdoc in npm release

lib/dialects/mysql/query-generator.js, test/unit/sql/add-column.test.js, test/unit/sql/change-column.test.js
This is simply a backport of #6008 which is already accepted on master and part of the v4 branch.
This fixes a problem with duplicate foreign key constrain names in MySQL (issue #5826). Instead of using the collision-prone template `{attribute}_foreign_idx`, this change will cause `{referring_table}_{attribute}_foreign_idx` to be used instead.
=> Backport #6008 - Avoid duplicate MySQL foreign key names

changelog.md, lib/model.js, test/integration/instance/values.test.js
Makes it possible for model getters to behave differently in different contexts. For example, a model definition may need to be different for different version of a RESTful API.
```js
rating: function (key, options) {
const value = this.getDataValue('rating'); // rating is stored as integer with values 1-100
if (context.apiVersion === 1) {
return value / 20; // in /v1 we use 1-5 rating system
}
return value;  // in /v2 and newer we use 1-100 point rating system
}
```
the parameter is passed like this:
```js
product.get({plain: true, apiVersion: req.param.apiVersion}
```
=> #7404 make it possible to pass parameters to getter functions

lib/sequelize.js
Template skipped (documentation only).
Based on [this stackoverflow](https://stackoverflow.com/questions/30452977/sequelize-query-compare-dates-in-two-columns) I added some more explanation as to what sequelize.col does.
Also, changed 'a object' to 'an object'.
Fixed version of [this pr](https://github.com/sequelize/sequelize/pull/7449)
=> Grammar fix and more explanation of sequelize.col

changelog.md, lib/dialects/postgres/query-generator.js, test/integration/query-interface.test.js, test/unit/dialects/postgres/query-generator.test.js
Previous changes to support schemas in QueryInterface generated invalid Postgres SQL when attempting to change a column to an enum value.
Instead of generating
```sql
ALTER TABLE "myTable" ALTER COLUMN "col_1" TYPE "public"."enum_myTable_col_1" USING ("col_1"::"public.enum_myTable_col_1");
```
with this change we will now generate
```sql
ALTER TABLE "myTable" ALTER COLUMN "col_1" TYPE "public"."enum_myTable_col_1" USING ("col_1"::"public"."enum_myTable_col_1");
```
=> Fixes QueryInterface#changeColumn for enums

changelog.md, lib/dialects/postgres/query.js, test/integration/dialects/postgres/query-interface.test.js
Fixes an issue when calling `showIndex()` on an index that contains a newline in its "fields". Example:
```sql
CREATE INDEX "foobar" ON "users" USING btree ((
CASE (settings->>'type')
WHEN 'foo' THEN 'biz'
WHEN 'bar' THEN 'baz'
ELSE 'qux'
END)) WITH (fillfactor='70')
```
The issue is with a regexp that is matching against `.*` (which doesn't match newlines). This PR replaces that expression with `[^]*` which matches any character that is not _nothing_.
The error that was previously seen when a newline was present was:
```
TypeError: Cannot read property '1' of null
at node_modules/sequelize/lib/dialects/postgres/query.js:139:85
at Array.forEach (native)
at node_modules/sequelize/lib/dialects/postgres/query.js:135:15
```
=> Fix `showIndex()` query regexp

docs/docs/schema.md
I was just browsing through documentation and it wasn't really too easy for me to find about migrations when I was in "Working with table schemas". So I just added a hint where user can read more about below functions since they don't link to
=> Add hint about migrations section

docs/docs/models-usage.md
The documentation of findOrCreate previously had no precise indication of what to expect findOrCreate to return. I added that it returns an array with two parts in the comments that had already existed in the examples. I also fixed an inconsistency where it looked as if the first item would be returned anonymously and the second would be returned as a key/value pair of 'created' and a boolean. In fact, both are returned anonymously.
I only changed the documentation.
=> 'clarifying the return value of findOrCreate'

changelog.md, lib/dialects/abstract/query-generator.js, lib/dialects/sqlite/query-generator.js, test/integration/model/json.test.js, test/integration/model/paranoid.test.js
Update on any model with `JSON/JSONB` attributes would fail if we try to query on such attributes. So example given below will fail
```js
Model.update({ name: 'Sintara' }, {
where: {
'data.name.settings.edit': true
}
})
```
```js
Model.update({ name: 'Sintara' }, {
where: {
data: {
name: {
settings: {
edit: true
}
}
}
}
})
```
As update was broken, it also affected paranoid model with `JSON/JSONB` attributes.
I have fixed this by passing `options` to `whereQuery`. I have adjusted way `fieldType` was chosen in `whereItemQuery`, so its properly set. Added some tests so this wont happen again.
Closes #7378
Fixed #7376
Fixed #7400
Fixed #7444
=> Fixed: jsonb/json update or softdelete fails

changelog.md, lib/dialects/postgres/query-generator.js, test/integration/query-interface.test.js, test/unit/dialects/postgres/query-generator.test.js
Previous changes to support schemas in QueryInterface generated invalid Postgres SQL when attempting to change a column to an enum value.
Instead of generating
```sql
ALTER TABLE "myTable" ALTER COLUMN "col_1" TYPE "public"."enum_myTable_col_1" USING ("col_1"::"public.enum_myTable_col_1");
```
with this change we will now generate
```sql
ALTER TABLE "myTable" ALTER COLUMN "col_1" TYPE "public"."enum_myTable_col_1" USING ("col_1"::"public"."enum_myTable_col_1");
```
=> V3 backport: Fixes QueryInterface#changeColumn for enums

docs/getting-started.md
Add Yarn installation scripts to getting started documentation. With many developers making use of Yarn as of late, providing quick copy/paste scripts will prevent developers from having to type the scripts manually.
=> Update installation docs to include Yarn

changelog.md, lib/model.js, test/integration/instance.test.js, test/unit/instance/is-soft-deleted.test.js
Since users can rename the `deletedAt` field when creating a model it is helpful to have a `isSoftDeleted` so other users of the DB don't have to hard code the custom `deletedAt` field name throughout their codebase.
Addresses: https://github.com/sequelize/sequelize/issues/7408
=> Add `isSoftDeleted` helper method to model instances

lib/dialects/postgres/query.js
Removes unreachable code in postgres query error handling highlighted by #7680
=> Fix #7680 unreachable code in postgres query error handling

docs/models-usage.md
Hello.
It looks like the documentation for `include.paranoid` got it backwards. This fixes it.
Should probably be merged to v3 branch too.
Regards,
Laurent
=> Fix documentation of include.paranoid

test/integration/dialects/mysql/connector-manager.test.js
Introduces dialectOptions.foundRows configuration option that can be set to bring back
update behavior from before this commit https://github.com/sequelize/sequelize/commit/4f95f176eba4a7ad7c71108dd48955884d16eb6b
https://github.com/sequelize/sequelize/issues/7184
=> #7184 Regression in affected rows reporting for updates

changelog.md, docs/usage.md, lib/sequelize.js, test/unit/configuration.test.js
If the dialect is 'sqlite', then we parse host+pathname as a file path.
sqlite documentation suggests that this is the right way to parse them:
https://sqlite.org/c3ref/open.html#urifilenameexamples
If the "storage" option is provided, then that wil take precedence.
Examples:
sqlite:subfolder/dbname.db => subfolder/dbname.db
sqlite:/home/abs/dbname.db => /home/abs/dbname.db
Closes #4721
=> Add relative and full path support for sqlite

lib/dialects/abstract/connection-manager.js, lib/dialects/mysql/connection-manager.js, test/integration/dialects/mysql/connector-manager.test.js, test/integration/include/findAndCountAll.test.js
Continuation of ideas from https://github.com/sequelize/sequelize/pull/7626 
**Notable changes**
- No destroy from pool (Same as #7626) when handling disconnects
- No timers for watching eventual pool errors
- Wont crash when ETIMEOUT error occurs eventually
```js
'use strict';
/*
* Copy this file to ./sscce.js
* Add code from issue
* npm run sscce-{dialect}
*/
const Sequelize = require('./index');
// const sequelize = require('./test/support').createSequelizeInstance();
let dbConfig = {
username: 'sequelize_test',
password: 'sequelize_test',
port: '8999',
dialect: 'mysql',
syncOnAssociation: false,
host: '127.0.0.1',
seederStorage: 'sequelize',
pool: {
min: 1,
max: 5,
acquire:  10000,
},
dialectOptions: {
connectTimeout: 10000
}
}
let pool = new Sequelize(dbConfig.database, …
```
=> fix: pooling fails to handle disconnection

changelog.md, lib/sequelize.js, test/unit/configuration.test.js
=> fixed #7735, sqlite memory url no longer works

docs/models-usage.md
The original code I found in the docs was:
```
User.findAll({
where: {
'$Instruments.name$': { $iLike: '%ooth%' }
}
include: [{
model: Tool,
as: 'Instruments'
}]
})
```
This code does not have a comma between the key `include` and the key `where`. People who would copy/paste this code would get an error. So a comma was added.
=> Fix small typo in models-usage.md

docs/models-definition.md
Column comments are not a currently supported feature and should not possess documentation references.
Documentation should be readded when the feature is supported once again; until then, the documentation is inaccurate and misleading to users.
=> Remove documentation regarding column comments

changelog.md, lib/dialects/abstract/query-generator.js, lib/model.js, lib/query-interface.js, test/integration/model.test.js, test/unit/dialects/mssql/query-generator.test.js, test/unit/dialects/mysql/query-generator.test.js, test/unit/dialects/postgres/query-generator.test.js, test/unit/increment.test.js
I move the instance method `increment` code to be class method `increment`.
The original instance method `increment` will simply add `this.where()` to `options.where` and then call `this.constructor.increment()`.
This is the very first open source contribution I do.
Please give me any advices to improve this PR :-)
I will write document and changelog if this PR is acceptable
close #6359
=> add class method "increment"

changelog.md, lib/dialects/abstract/connection-manager.js, test/integration/dialects/abstract/connection-manager.test.js
closes https://github.com/sequelize/sequelize/issues/7751
As mentioned in https://github.com/sequelize/sequelize/issues/7751, db.close() was not doing what it was supposed to.  It looks like during the `generic-pool` library upgrade the pool.drain() implementation was changed from taking a callback to returning a promise (https://github.com/coopernurse/node-pool/blob/master/lib/Pool.js#L481), but the sequelize code was not updated.  Because of that, the function being passed as a callback was never being called.  Adding a `.then` with the same function seems to fix the problem.
I didn't go looking for other `generic-pool` callbacks that may have this same issue.
I'm also not quite sure of the best way to test this change, some insight would be appreciated.
=> ConnectionManager.close not closing database connection completely 

docs/associations.md
_Documentation change only_
Should reference products instead of projects in "Creating elements of a "HasMany" or "BelongsToMany" association" section.
=> Minor typos

docs/upgrade-to-v4.md, lib/model.js, test/unit/instance-validator.test.js
In 4.0, `model.validate()` was changed to return a promise that resolves
only on success and rejects on error. Previously, it would return a
promise that resolved to either `undefined` on success or some
`ValidationError` on error. The upgrade guide did not mention this
breaking change, and the documentation did not reflect the change. A
test was added to show the intent of the documentation.
Closes #7769
=> docs(Model): Correct Model.validate() documentation

docs/hooks.md
If callback on hooks dont will be implemented, then remove it from docs:
See https://github.com/sequelize/sequelize/issues/7792 for related issue
=> Remove hooks callback from docs ref #7792

lib/errors/index.js, test/unit/errors.test.js
This fixes stacktraces of custom errors that subclass `BaseError` not having their error name in the stacktrace (issue #7770). I've also added unit tests to all the custom errors to check if the stacktrace contains the error name.
=> Fixed missing captureStackTrace for errors. (closes #7770)

.github/stale.yml
This adds https://github.com/probot/stale.
After 60 days of silence on an issue, it will post a friendly comment on it asking whether it is still valid as it has not received activity in a long time.
If no further activity occurs in the following 7 days, it will be automatically closed.
We have 886 open issues, more than any of us could ever go through. Lets make the Sequelize issue tracker manageable again.
=> chore(issues): add probot/stale

docs/css/style.css, docs/plugins/esdoc-sequelize.js
This replaces the Google Custom Search box with search powered by Algolia.
The crawler is already set up.
It seems like searching the API reference doesn't work yet, but I assume that is just a misconfiguration of the crawler, see https://github.com/algolia/docsearch-configs/pull/172
Still, I find this search already much more useful than Google Custom Search.
Styles were just hacked together quick, but I think it looks quite nice.
=> docs(search): use Algolia for search

lib/dialects/sqlite/query-generator.js, test/unit/dialects/sqlite/query-generator.test.js
=> fix(7758): quote attributes in alterConstraint and renameColumn queries

docs/getting-started.md
I added a hint for the await keyword wich has increasing support. But maybe useless because everyone should know this possibility for promises.
I added a hint for the usage of async/await instead of `.then` to the documentation.
=> Hint for async

lib/dialects/postgres/connection-manager.js
- [yes] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [yes] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [NA] Have you added new tests to prevent regressions?
- [No] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [Yes] Did you follow the commit message conventions explained in CONTRIBUTING.md?
Closes #7896
idle connections were getting prematurely dropped/closed by the backend, in order to avoid this problem the underlying pg module introduced 'keepAlive' option in its v6.0.0 which was missing from the sequelize library, this PR allows the user to …
=> Pick keepAlive dialectOption

docs/usage.md, lib/dialects/postgres/connection-manager.js, lib/dialects/postgres/query.js
Upgrade pg API usage to be forward compatible with version 7. Also gets rid of the deprecation warning.
Closes #7818
=> feat(dependency): Support pg version 7

lib/sql-string.js, test/unit/dialects/postgres/query-generator.test.js
This pull request closes #7950.
> **Issue**: Wrong escaping of text in array (`'` should escape as `''`, not `\'`).
>
> **Cause**: A context losing when passing options.
=> Fix $contains escaping

lib/dialects/abstract/query-generator.js, test/unit/sql/where.test.js
fixed an issue with LIKE/ILIKE when used with the ALL keyword.
it already worked fine for the ANY keyword, but was missing the parentheses when I tried with ALL.
extended the tests a bit to cover all LIKE/ILIKE/NOT combinations.
=> fix(query-generator): add parentheses to queries when using ALL with LIKE

lib/dialects/postgres/connection-manager.js
In case the initial query contains multiple statements in the [postgres connection manager](https://github.com/sequelize/sequelize/blob/master/lib/dialects/postgres/connection-manager.js#L156), the result will be an array which is not being handled here. Since we are only interested in the rows from the very last statement, we can skip the rest.
This fixes #7985
=> 4.4.0 breaks pg connection initialization

lib/sequelize.js
The default has been removed in v4. Updating the docs to match the signature.
Closes #7958
=> docs(change): Remove default for dialect

docs/usage.md, lib/dialects/abstract/connection-manager.js, lib/sequelize.js
Adding a new option to `defaultPoolingConfig` for overiding the default _evictionRunIntervalMillis_ when instantiating connection pools using `node-pool`. You can see how evictions are never ran if this setting remains 0 https://github.com/coopernurse/node-pool/blob/master/lib/Pool.js#L351
This PR is a bandaid for several recent "open" issues: https://github.com/sequelize/sequelize/issues/7884 and https://github.com/sequelize/sequelize/issues/7882 and possibly https://github.com/sequelize/sequelize/issues/7616
=> Evict stale connections

.travis.yml
With this update Sequelize will start using build stages from Travis https://docs.travis-ci.com/user/build-stages/
There will be three stages
1. Tests (Node v6 / v4)
2. Documentation (Surge)
3. Semantic Release
This will allow us to release documentation and package update after all tests are completed. This will fix https://github.com/sequelize/sequelize/issues/7983
=> build(travis): improve build process

lib/hooks.js, test/unit/hooks.test.js
- [ x ] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [ x ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ x ] Have you added new tests to prevent regressions?
- [ N/A ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ x ] Did you follow the commit message conventions explained in CONTRIBUTING.md?
Bugfix: `removeHook` removes hooks that you want to keep, if some hooks are named and some are not named.
Steps to reproduce:
1. Add an unnamed `beforeCreate` hook. `Model.addHook('beforeCreate', (…) => {…});`
2. Add a named `beforeCreate` hook to the same …
=> fix(hooks): removeHook should only remove the specified hook

.github/stale.yml
I'm not sure if this is desired or not, but I added the `feature` label to the exempt issues labels.  I did this because it seem to me that closing a PR due to inactivity alone isn't a great experience for the community. 
For example the streaming issue here #2454 that likely needs another issue completed to be finished #2325 are both marked as `stale` and were closed. 
From a user standpoint, and a person who wants both of those features, it's disappointing to see them get closed without explanation with each has a good amount of interest in the Sequelize community.
=> Add feature issues to exempt issues for stale issues

docs/associations.md
Just fixing some JavaScript errors in the association docs
=> docs(associations): fix syntax error

docs/models-definition.md
In models-definition the markdown code used to link to (#id) configuration on same page did not lead to the configuration id set up on same page but rather looked for #configuration with respect to the base set up (i.e. ../../  which results to main index). I have changed the documentation models-definition.md file so that it can direct user to #configuration id on the same page(i.e. models-definition)
When a user opens
http://docs.sequelizejs.com/manual/tutorial/models-definition.html
there are three links on the page that should redirect to 
http://docs.sequelizejs.com/manual/tutorial/models-definition.html#configuration
but they actually redirect to 
http://docs.sequelizejs.com/#configuration
In models-definition.md
i have changed the markdown link so that the redirection is done …
=> Fix documentation - redirection link in docs/models-definition.md 

lib/dialects/abstract/query-generator.js
fix: maintable.as is different from tablename.
should be quoted using  quoteIdentifier method
This PR is not for solving any bug or critical issues. It is for improving quality of code base.
Sequelize has  well organized code base and it is easy to customize it for complex application.
This is PR will a fix a minor deviation from the  existing code convention
This is the summary of change: 
while generating select query, we are quoting "tablename" part and "tablename.as" part using same function ( quoteTable function ).
But, tablename can have a schema part but the "tablename.as" part can not have schema. so that part should be quoted using quoteIdentifier method
=> fix: maintable.as should be quoted using  quoteIdentifier method

lib/model.js, test/unit/instance/to-json.test.js
Whenever `toJSON()` is used and returned result is modified, it breaks the internal state of the
instance
=> fix(instance): toJSON returns internal object, instead of a copy

lib/associations/helpers.js, lib/dialects/postgres/query.js, lib/sequelize.js
Closes #8173
It seems `sequelize.queryInterface` was being set on first call to `sequelize.getQueryInterface()`.
Now https://github.com/sequelize/sequelize/pull/8160 cleaned up some old code, it also cleaned up `findAutoIncrementField` from `QueryGenerator`, thus model doesn't need to call it anymore.
Which exposed this issue, now `queryInterface` was not being initialized until very first query call or use of `getQueryInterface()` in code.
This PR will fix it
=> fix(sequelize/constructor): queryInterface was initialized on first use

lib/utils/validator-extras.js
- [ ✓ ] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [ ✓ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ✗ ] Have you added new tests to prevent regressions? (_no, but there's no longer a deprecation warning while running them_)
- [ ✗ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ✓ ] Did you follow the commit message conventions explained in CONTRIBUTING.md?
Avoid a deprecation warning when calling `isDate` closes #8170 
**Tests before**
```
...
✓ correctly specifies an instance as valid using a value of "f47ac10b-58cc-4372-a567-0e02b2c3d479" …
```
=> fix(validations): prevent deprecation warning in isDate 

lib/associations/mixin.js
When using the patterns demonstrated here: https://github.com/sequelize/express-example/blob/master/models/index.js, it's possible to accidentally pass in `undefined` as the target of an association. This results in a stack trace that isn't obvious. Instead, the lines that assume that the target is defined can check that assumption.
=> Handle passing in undefined as an assoc target

lib/model.js, test/unit/model/scope.test.js
Add 'group' to items to be concatenated when combining scopes. Work based on @Mijago's fork.
Closes #6690
=> feat(scopes): allow scope `group`s to be concatenated

docs/hooks.md
https://github.com/sequelize/sequelize/issues/7784
1. A note that `.addHook()` is an alias to `.hook()`
2. Add an example of hook declaration with name parameter
3. Add a note that there would be no conflict if multiple hooks would have the same name
=> docs(hooks): some refinements of hooks declarations

lib/sequelize.js, test/integration/sequelize.test.js, test/unit/query.test.js
Connections should be release after retry rather than being released after every query.
It will cause `'Resource not currently part of this pool'` error if it's released after every query.
In v3, sequelize use `coopernurse/node-pool@2.4.8` which won't raise a error if a connection is released multiple times. See here [https://github.com/coopernurse/node-pool/blob/v2.4/lib/generic-pool.js#L420](https://github.com/coopernurse/node-pool/blob/v2.4/lib/generic-pool.js#L420)
But in v4, sequelize use new version of `coopernurse/node-pool` which will return a rejected promise if a connection is released multiple times. See here [https://github.com/coopernurse/node-pool/blob/master/lib/Pool.js#L422](https://github.com/coopernurse/node-pool/ …
=> fix(sequelize/query): release connection after retry

lib/dialects/abstract/query-generator.js, test/unit/sql/select.test.js
There is a bug https://github.com/sequelize/sequelize/issues/8275 and it may be fixed by just removing part of SQL statement that looks like redundant (at list for me)
The point of change is that now `order` statement is applying to both main query and sub query. It looks like there is no need for second `order`ing. Also this would also fix a mentioned bug
=> fix(abstract/querygenerator): remove duplicated order expression on outer query

.travis.yml, docker-compose.yml, lib/dialects/abstract/connection-manager.js, lib/dialects/mssql/connection-manager.js, lib/dialects/mysql/connection-manager.js, lib/dialects/postgres/connection-manager.js, lib/sequelize.js, test/config/.docker.env, test/config/config.js, test/integration/dialects/abstract/connection-manager.test.js, test/integration/dialects/mssql/connection-manager.test.js, test/integration/dialects/mysql/connector-manager.test.js, test/integration/replication.test.js
This is basically a hack but pooling library has given us no options. Pool acquire call
now resolves even if there is an error. We simply check if its an error instance or not
and reject accordingly.
Read more here https://github.com/sequelize/sequelize/issues/7884#issuecomment-330136439
`_determineConnection` method can be used to check if thing returned by pooling library is
actaully a connection or error
Closes #7884
Closes #7616
Closes #8014
Closes #8133
Closes #8322
Closes #8185
Closes #8098
Closes #8076
Closes #8014
=> fix(abstract/connection-manager): acquire call never finishes

lib/dialects/postgres/connection-manager.js
node-postgres recently added support for 'statement_timeout' -- a per connection query timeout.
See https://github.com/brianc/node-postgres/pull/1436
=> Pass-through postgres connection option 'statement_timeout'

lib/dialects/abstract/query-generator.js, test/unit/dialects/mysql/query-generator.test.js, test/unit/dialects/postgres/query-generator.test.js, test/unit/dialects/sqlite/query-generator.test.js
Use aggregate function I got the following sql:
```
'SELECT "userId", sum("cost") AS "sum" FROM "creative_projects" AS "creative_projects" WHERE "creative_projects"."userId" IN ('sub') AND ("creative_projects"."createdAt" >= '2017-03-31 16:00:00.000 +00:00' AND "creative_projects"."createdAt" < '2017-09-30 16:00:00.000 +00:00') GROUP BY userId;'
```
Obviously the quote is miss in `userId`.
=> fix(query-generator): Options.group should be quoted

lib/data-types.js, test/integration/associations/has-many.test.js, test/integration/data-types.test.js
Fixes comment mentioned [here](https://github.com/sequelize/sequelize/pull/8357/files#r141506197)
`DATEONLY` fields were sanitized wrong when being `NULL`.
=> Fix null check for DATEONLY

lib/model.js, test/integration/instance.test.js
Closes #8382
Infinity date support is pretty new in Sequelize (1 day old), so it still has some kinks to work out. This PR fixes https://github.com/sequelize/sequelize/issues/8382.
=> fix(model): properly serialize WHERE attributes in soft deletes

lib/model.js, test/unit/instance/set.test.js
lint is not Windows-friendly - gives many "Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style" warnings
Some models can define a custom setter to modify the value that is set. For determining whether a column is changed, the original value needs to be compared with the value that is really set, not with the value that was input and modified.
=> fix(model): do not mark a column as changed if a custom setter sets it to the same value

lib/dialects/mysql/query-generator.js, test/integration/query-interface.test.js, test/unit/dialects/mysql/query-generator.test.js
Fixes issue I opened here https://github.com/sequelize/sequelize/issues/8385 about dropping unique contraint column.
Before removing a column, the mysql dialect checks that there's no foreign keys attached to it with this query:
```
SELECT CONSTRAINT_NAME as constraint_name FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE (REFERENCED_TABLE_NAME = 'users' AND REFERENCED_COLUMN_NAME = 'email') OR (TABLE_NAME = 'users' AND COLUMN_NAME = 'email')
```
It looks to me like [KEY_COLUMN_USAGE](https://dev.mysql.com/doc/refman/5.7/en/key-column-usage-table.html) table stores not just foreign keys but all constraints. In my failing case, `email` is unique and present in this table, so sequelize aborts the removeColumn.
The fix is to add an …
=> bugfix: removing unique contraint column (#8385)

lib/model.js, test/integration/model/upsert.test.js
Closes #8396
Similar to #8383, but for upserts. Sequelize wasn't serializing attributes in the WHERE clause on the UPDATE branch.
=> fix(postgres/date): upserts with Infinity

docs/models-usage.md
=> docs(models-usage): fix minor comma omissions in findAll

lib/errors/index.js
The way Sequelize instantiates some of its Error subclasses confuses Bluebird into thinking that Promises are rejected with non-Error objects, so you get warnings when running with `BLUEBIRD_DEBUG` enabled.
See https://github.com/petkaantonov/bluebird/issues/990
=> fix(errors): spurious Bluebird warnings

docs/models-usage.md
Added a new line between the list and code block in `findAndCountAll` section, so the esdoc markdown parser does not break the page.
This is how it looks now:
http://docs.sequelizejs.com/manual/tutorial/models-usage.html#-findandcountall-search-for-multiple-elements-in-the-database-returns-both-data-and-total-count
=> Tiny markdown change to fix esdoc formatting

lib/model.js, lib/query-interface.js, lib/utils.js, test/integration/model.test.js
Closes #8406
Fixes paranoid clauses where the `where` only has symbols. See https://github.com/sequelize/sequelize/issues/8406.
I'll also work on adding more tests so we can completely close https://github.com/sequelize/sequelize/issues/8423, but this is ready to merge if we want a quick fix for #8406, which is kind of a big issue for a lot of users.
=> fix(model): handle Symbol-only where clauses

lib/dialects/abstract/query-generator.js, test/integration/query-interface.test.js
Previously, `queryInterface.addIndex({schema: 'foo', tableName: 'bar'}, ['baz'])` would create an index named `[object_object]_baz`.
=> fix(abstract/querygenerator): correctly name indexes that live in custom schemas

lib/dialects/sqlite/query-generator.js, lib/model.js, test/unit/sql/update.test.js
By default SQLite is compiled with `SQLITE_ENABLE_UPDATE_DELETE_LIMIT` off. That means the `UPDATE` statements would not support an optional `LIMIT` clause. By using `UPDATE ... WHERE rowid IN (SELECT rowid FROM ... WHERE ... LIMIT n)` instead it can provide support in environments without such feature.
=> feat(sqlite/query-generator): sqlite update queries now support limit via rowid

test/unit/instance-validator.test.js, test/unit/model/find-create-find.test.js
Using the the pattern `sinon.stub(...).returns(Promise.reject(...))` would cause occasional
"Unhandled Rejection" messages from the Bluebird unhandled rejection handler. The pattern has been
removed in favor of a replacement function.
See a discussion of the issue [here](https://github.com/petkaantonov/bluebird/issues/313).
=> fix(unittest): Refactor tests to not use Sinon Syntactic Sugar

lib/dialects/abstract/query.js
SqlString.escape() has three arguments but query.js called it with four, resulting in runtime error.
Sorry, but  'no' for all questions, this is obvious typo fix from github Edit function.
=> fix(query): incorrect arguments passed to SQLString.escape

lib/dialects/sqlite/query-generator.js, test/unit/sql/delete.test.js
By default SQLite is compiled with `SQLITE_ENABLE_UPDATE_DELETE_LIMIT` off. That means the `DELETE` statements would not support an optional `LIMIT` clause. By using `DELETE ... WHERE rowid IN (SELECT rowid FROM ... WHERE ... LIMIT n)` instead it can provide support in environments without such feature.
(This is a companion PR to #8450.)
=> feat(sqlite/query-generator): sqlite delete supporting limit via rowid

README.md
This PR adds a small note stating the project has not yet supported `pg@7`. When searching across issues it is not uncommon to see comments regarding this gotcha. Hope that this note would do it for now.
=> docs(readme): updated the readme stating pg@7 is not supported yet

lib/instance-validator.js, test/integration/instance.validations.test.js, test/unit/instance-validator.test.js
Closes #8498
Include `Model.name` in `allowNull` validation error messages. There are probably more things that we could include in this message, and more places we should include `Model.name`, but I figured I'd start with this.
=> feat(instance-validator): add model name to allowNull messages

docs/migrations.md
The created table is pluralized (`Users` instead of `User`)
=> Fix migration documentation: pluralize table

lib/dialects/abstract/connection-manager.js
This should result in smaller amount of simultaneosly opened connections, as unused extra connections will be closed
=> Prefer to reuse connections

lib/dialects/mssql/query.js, lib/dialects/mysql/query.js, lib/dialects/postgres/query.js, lib/dialects/sqlite/query.js, lib/errors/index.js, lib/instance-validator.js, test/integration/error.test.js, test/integration/model/create.test.js, test/unit/dialects/mysql/errors.test.js
This PR is looking to make the `ValidationErrorItem` class more useful by adding extra/new structured data to the instances. 
The reasoning for these changes are:
1. in order to expose more useful validation-error information at the point that we want to output/log/display the errors so that we can facilitate showing/creating messages in different languages and for different types of users - in multi-lingual systems the internal error message property is unlikely to be in the current users' language and is likely to be technical in nature - we want to be able to generate localized error messages "after the fact" and in order to create useful message we need the extra information about which validator (if applicable), and it's arguments (e.g. so you can generate a message such as "lengte …
=> feat(validation): new properties for ValidationErrorItem class

docs/css/style.css
=> docs(globalStyling): fix pre tags text overflow

lib/data-types.js
remove brackets of `length` parameter, which may mislead users to pass an array as the parameter at the very first time.
=> docs(DataTypes): correct type of TEXT's parameter

.github/PULL_REQUEST_TEMPLATE.md
So users can click on it for reference
=> docs: add link to CONTRIBUTING.md

lib/transaction.js
Transaction on MSSQL fails because the transaction identifier is greater than 32 bit. "-savepoint-" is appended to a 20 bit uuid whose length goes beyond 32 characters after 9 transaction. reducing this text to minimal characters like "sp" resolved the issues.
Related issues: #3950 #5959
=> Fix transaction error on MSSQL

docs/upgrade-to-v4.md
Closes https://github.com/sequelize/sequelize/issues/8713
=> docs(migration): document mysql2 DECIMAL type incompatibility (#8713)

lib/model.js, test/integration/model.test.js
Closes #8338
This PR makes `Model.update` respect `paranoid`. See #8338.
=> feat(model): support paranoid updates

lib/query-interface.js
Closes #8741
queryInterface.createFunction() does not support ability to pass options to sequelize.query().
I extended signature of this function similar to createTrigger() approach - separate extended SQL function description options with options that passed to sequelize.query().
=> fix(query-interface): add ability to pass options from createFunction() call

lib/dialects/abstract/query-generator.js, test/integration/model/findAll.test.js
Closes #8739
Use correct column name when ordering by an attribute projected from a sub-query. See #8739.
=> fix(model): ordering by renamed sub-query attribute

lib/model.js, test/unit/model/scope.test.js
*The name of the used scope is now stored in a instance property "_scopeNames" which contains the list of all scope used in the query
Resolves #7433 
Property `_scopeNames` is added to the instance, this is useful when in need to check for the used scope in hooks, this holds a lists of all used scopes. If `scope()` was not called then `_scopeNames` holds `defaultScope` as the only item in the list.
=> Added _scopeName property in instance

docs/associations.md, docs/instances.md, lib/dialects/abstract/query-generator.js, lib/model.js, test/integration/instance.test.js, test/unit/dialects/postgres/query-generator.test.js
Add handling for a `returning` option in arithmetic queries (`increment` and `decrement`). Defaults to `true` to maintain expected behavior.
Closes #8727
=> feat(postgres): returning option for arithmetic queries (#8727)

lib/dialects/abstract/connection-manager.js
Actual a memory management improvement, now Sequelize will consume less RAM. I noticed connection manager reference is not released. There are still more issues but I just got time to track this one over last weekend
=> perf: dont keep bounded reference of connection manager

lib/dialects/mssql/query.js, test/unit/dialects/mssql/connection-manager.test.js, test/unit/dialects/mssql/query.js, test/unit/dialects/mssql/query.test.js, test/unit/dialects/mssql/resource-lock.test.js
Parameters are not properly converting to their MSSQL counterparts beyond the first occurrence of each name. For example:
`select $one as foo, $two as bar, $one as baz`
Becomes:
`select @one as foo, @two as bar, $1 as baz`
This pull request fixes the conversion by removing code that does not apply to the MSSQL dialect.
=> fix(mssql): improper parameter binding sql generation

lib/dialects/abstract/connection-manager.js
Fixes https://github.com/sequelize/sequelize/issues/8781
Closes https://github.com/sequelize/sequelize/issues/8780 
`beforeExit` by design can be called multiple times and even prevent process shutdown from empty event loop. In Sequelize case it was used to drain generic-pool which for some reason will repeat beforeExit process in series. (Using high memory in some cases)
Users should use `close` to shutdown pool and process should auto exit due to empty REPL
=> fix(connection-manager): only use close to shutdown

lib/dialects/mysql/query-generator.js, test/integration/model/json.test.js, test/integration/model/paranoid.test.js, test/unit/sql/where.test.js
Fixes #8718 , JSON sub path if contain hyphen / dashes it will break find query. We need to quote paths properly to be a valid ECMAScript identifier
https://bugs.mysql.com/bug.php?id=81896
=> fix(mysql/json): properly quote JSON path to be valid ECMAScript name

lib/dialects/abstract/query-generator.js, test/unit/dialects/abstract/query-generator.test.js
Issue #8816 found bug with `Op.is`. When it has a null value it checks for `IS NOT`. This happens because the `Op.ne` check with null value is not comparing with the passed comparator. Adding in that comparison stops `Op.ne` catching other operators (such as `Op.is`)
Added a test which fails before and passes after for `Op.is`, alongside `Op.eq` to check they have the same output. There is no existing `Op.eq` test either, which catches its change to `Op.is` so this also adds that
=> Issue 8816 found bug with Op.is. When it has a null value it checks for IS NOT. This fixes

lib/query-interface.js, test/integration/data-types.test.js, test/integration/dialects/postgres/regressions.test.js
Fixes https://github.com/sequelize/sequelize/issues/8749
This issue was caused due to improper datatypes refresh after new OIDs are obtained
=> fix(postgres): base type wont work after model with ENUM is synced

lib/model.js, test/integration/model.test.js
=> fix: destroy with paranoid ignores operators

docs/querying.md
The comment line contains some left overs from the copied line above that don't apply to `sequelize.random()`.
=> docs(querying): improve random order comment

lib/model.js, lib/utils.js, test/integration/model/create.test.js
=> fix(datatypes): Sequelize.NOW set milliseconds to zero

lib/dialects/mssql/query-generator.js, lib/dialects/mssql/query.js, lib/dialects/postgres/query-generator.js, lib/dialects/postgres/query.js, lib/dialects/sqlite/query-interface.js, lib/model.js, lib/query-interface.js, test/integration/model/upsert.test.js, test/unit/model/upsert.test.js
Close https://github.com/sequelize/sequelize/issues/3354
Sequelize still doesnot support `ON CONFLICT`, but with using `RETURNING` its now possible for return upserted record.
```js
// current behaviour
const created = await Model.upsert(....values....);
// with options.returning = false
const created = await Model.upsert(....values...., { returning: false });
// with options.returning = true , new feature
const [record, created] = await Model.upsert(....values...., { returning: true });
```
=> feat(upsert): return upserted record with options.returning=true

lib/dialects/abstract/query-generator.js, test/unit/dialects/mysql/query-generator.test.js
When querying with empty `having` object, the query contains an empty `HAVING` clause. The code processing the `where` object checks if it contains any statements, the code processing `having` didn't. I added that.
=> fix(selectQuery): Don't add empty HAVING clause

lib/model.js, lib/utils.js, test/integration/model/scope.test.js, test/unit/utils.test.js
`lodash.defaults` doesn't pick Symbol properties, this was breaking scopes.
Discussion in https://github.com/sequelize/sequelize/issues/8473#issuecomment-359517259
I have modified `lodash.defaults` as `Utils.defaults` which works for Symbol properties. Replaced in other places where I think was suitable, that should fix multiple potential issues with Symbol operators assignment.
=> fix(symbols): symbols not assigned by lodash.defaults

docs/migrations.md
The config.json example in the migration tutorial is not valid JSON. Added double quotes and removed dynamic attributes from the example to make it valid.
=> docs(migrations): fix config.json example

lib/model.js
When using `separate: true` the offset is not omitted from the parent options. If you use pagination with find separate, the included records are not correctly loaded.
=> fix(model): omit `offset` in findSeparate

lib/sql-string.js, test/unit/sql/where.test.js
This escapes the null character for Postgres, which it does not allow. 
Closes #6311
=> fix(escape): Remove null character in postgres

lib/dialects/postgres/connection-manager.js
This problem happens under the following circumstances:
* Several sequelize instances, connecting to different databases.
* Each database contains some custom enum types, with overlapping OIDs (so databaseB has typeA with oid X, while databaseB has typeB, also with oid X)
Since the two sequelize instances share the same copy of the pg lib, they will overwrite each others' type parsers. This is especially appearent when the datatype in one db is an array, and the other is not - So suddenly what you expect to be a string is now an array.
I've fixed this by keeping a local copy of the oids on the connection manager and setting the type parser on the pg client instance, instead of mutating the pg-types object.
Tested on snaplytics, where it fixed the bug that suddenly an enum type became an …
=> fix(postgres/conectionmanager): Don't leak OIDs between instances

lib/query-interface.js
Hello,
I just change the case for "options.type" in documentation for "queryInterface.addConstraint".
It seems that the type option must be in lower case.
=> Fix documentation error

lib/query-interface.js
My PR only contains changes to documentation. In the "createTable" queryInterface method, the parameter "attributes" was set as an Array when it should be an Object.
=> Fix JSDoc for "createTable"

docs/getting-started.md
Running the code provided on Getting Started cause a deprecation warning. This PR adds `operatorsAliases: Op` to the code on Getting Started, which is already recommended in other documents, like [Querying](http://docs.sequelizejs.com/manual/tutorial/querying.html#operators-aliases):
> For better security it is highly advised to use Sequelize.Op and not depend on any string alias at all.
This change was suggested in https://github.com/sequelize/sequelize/issues/8417#issuecomment-337884136 a few months ago and received positive response.
=> docs(Getting Started): Add `operatorsAliases: Op`

lib/dialects/abstract/query.js, test/integration/model/attributes.test.js
Closes https://github.com/sequelize/sequelize/issues/9100
=> fix(sequelize/query): use hasOwnProperty for keys in query (#9100)

lib/sql-string.js, test/integration/sequelize.test.js, test/unit/dialects/abstract/query-generator.test.js
According to the [feature request](https://github.com/sequelize/sequelize/issues/9050) added ability to pass arrays to `sequelize.query()` as replacements.
=> feat(query): add ability to pass arrays as replacements #9050

lib/model.js
Finish missed code refactoring.
Closes #9118, replaced the this.sequlize.getQueryInterface() calls with the models own accessor.
=> refactor(Model): Unify the QueryInterface accessors (Fix issue #9118)

docs/instances.md, lib/errors/index.js, lib/model.js, test/integration/model/bulk-create.test.js
Previously objects passed to the AggregateError did not have a message property, causing them to be
rendered as [object Object] in the console log. This change fixes the issue of a missing message
property.
fixes #8989
=> fix(model): Made sure errors with messages are passed to AggregateError for bulk creates.

lib/dialects/postgres/connection-manager.js, test/integration/model/searchPath.test.js
So here we go with the explanation :)
Problem comes from [here](https://github.com/sequelize/sequelize/blob/master/lib/dialects/postgres/connection-manager.js#L209), the script runs a simple __select__ query, or it belives it does! :D Because if the connection has a searchPath and a prependSearchPath option then actualy 2 statement is executed like: 
```sql
SET search_path to schema1, schema2; SELECT typname, typtype, oid, typarray FROM pg_type WHERE (typtype = 'b' AND typname IN ('hstore', 'geometry', 'geography')) OR (typtype = 'e')
```
But the result handler expects a single result and trying to access the __result.rows__ key which does not exists, this little fix only assures to avoid this edge case.
Wanted to write a test to …
=> fix(postgresql): search path with type query

lib/model.js, test/integration/associations/scope.test.js
Models being created with included associations do not include the association scope on the created models. Example:
```js
const Post = sequelize.define('post', {});
const Comment = sequelize.define('comment', {
title: Sequelize.STRING,
commentable: Sequelize.STRING,
commentable_id: Sequelize.INTEGER
});
Post.Comments = Post.hasMany(Comment, {
foreignKey: 'commentable_id',
scope: {
commentable: 'post'
},
constraints: false
});
const post = Post.create({
comments:[{
title: 'This is a comment'
}]
}, {
include: [Post.Comments]
});
// post.comments[0].commentable == null
```
i.e. association scope is only injected when creating via `Post.Comments.create` (and methods that call it), and not with `Post.create({comments: [...], …
=> fix(scope): include scope on eagerly created associations

lib/model.js, test/integration/model/scope/count.test.js
It is possible to add a scope as a function and have that function return an `include`, where the association included is specified as a String instead of an object. (Yes, that's an edge case.)
See the added test for an example.
This works well with query methods such as `findAll`, but doesn't work with aggregate methods such as `count`. 
I believe this is due to the aggregate methods going through a different code path where the scopes are injected _after_ conforming the options.
Switching the order of the two lines of code fixes the issue. I don't see any side-effect, but I might be missing something.
=> fix(model/aggregate): inject scope before conforming options

lib/dialects/abstract/query-generator.js, lib/model.js, test/integration/include/limit.test.js
Closes https://github.com/sequelize/sequelize/issues/9157
This code introduces `generateSubQueryFilter()` which builds upon code previously developed in `generateThroughJoin()` and `generateInclude()` to guarantee that proper subQueryFilter even in scenarios where multiple levels of duplicating joins are nested in a query that uses LIMIT / OFFSET.
Here's an example:
Consider the following query:
```js
Project.findAll({
include: [{
model: this.User,
required: true,
include: [{
model: this.Hobby,
where: {
name: 'archery'
}
}]
}],
order: ['name'],
limit: 1,
offset: 1
})
```
Project --> User and User --> Hobby are many-to-many queries.
For limit and offset to work properly with duplicating joins it is necessary to push the required …
=> fix(query-generator): generate subQueryFilter even for nested joins

lib/dialects/abstract/connection-manager.js
=> docs(connection-manager): fix typo

lib/dialects/abstract/query-generator.js, test/integration/include/limit.test.js
Closes https://github.com/sequelize/sequelize/issues/9228
Fixes regression introduced in https://github.com/sequelize/sequelize/pull/9188
The problem is that certain subquery filter joins are missing the where clause. While this was implemented correctly for many-to-many joins ([here](https://github.com/sequelize/sequelize/blob/v4.37.4/lib/dialects/abstract/query-generator.js#L1634) and [here](https://github.com/sequelize/sequelize/blob/v4.37.4/lib/dialects/abstract/query-generator.js#L1645) )I missed the other cases ([here](https://github.com/sequelize/sequelize/blob/v4.37.4/lib/dialects/abstract/query-generator.js#L1665))
=> fix(query-generator): 1-to-many join in subQuery filter missing where clause

lib/model.js, test/unit/model/findone.test.js
When querying with `findOne()` Sequelize adds `LIMIT 1` to the query to limit the result size. In combination with duplicating joins this may result in a complicated query (subqueryFilter). An optimization exists in Sequelize where if the query's where clause contains the primary key then `LIMIT 1` is skipped.
This change extends the optimization to also cover unique columns.
=> fix(model): don't add LIMIT in findOne() queries on unique key

lib/model.js, test/unit/model/findone.test.js
Upstream PR: https://github.com/sequelize/sequelize/pull/9248
=> V4: fix(model): don't add LIMIT in findOne() queries on unique key

lib/model.js, test/integration/associations/scope.test.js
Fix an issue introduced by #9127 when eager loading association with complex scope, such as:
```js
Post.hasMany(this.Comment, {
foreignKey: 'commentable_id',
as: 'coloredComments',
scope: {
commentable: 'post',
type: { [Op.in]: ['blue', 'green'] }
},
constraints: false
});
```
When assigning the scope to the instance in `_setInclude`, the instance's property `type` became `comment.type === { [Op.in]: ['blue', 'green'] }`.
This fix move the assignation of the association scope only on creation.
=> fix(scope): do not assign scope on eagerly loaded associations

lib/dialects/mssql/query-generator.js, test/integration/dialects/mssql/regressions.test.js
Closes #9173
Fixes #9008
Fixes #8804
=> fix(mssql): duplicate order generated with limit offset

docs/transactions.md, lib/transaction.js, test/integration/transaction.test.js
Add `afterCommit` hooks for transactions that allows deferring work to
after a transaction has been committed, regardless of if you have
access to the promise chain that created the transaction
Closes: https://github.com/sequelize/sequelize/issues/2805
=> feat(transactions): Add afterCommit hooks for transactions

docs/transactions.md, lib/dialects/abstract/query-generator.js, lib/dialects/mysql/index.js, lib/dialects/postgres/index.js, lib/transaction.js, test/integration/transaction.test.js
https://github.com/sequelize/sequelize/issues/8910 
Adding SKIP LOCKED to lock queries.
Where should I write tests for this?
Where would you like the docs?
=> Adding skiplocked support

lib/associations/belongs-to.js, lib/associations/has-many.js, lib/associations/has-one.js, lib/model.js, test/integration/include/separate.test.js, test/integration/include/seperate.test.js
Fixes #7514 and clean up association codebase
=> fix: inject foreignKey when using separate:true

lib/dialects/abstract/query-generator.js, test/unit/dialects/abstract/query-generator.test.js
When passing a `sequelize.where` created object with another sequelize object in the `logic` property, we enter a case where the comparator is added without padded spaces, causing an error in the generated SQL. This PR adds the missing spaces.
=> fix(query-generator): add spaces around comparator

lib/dialects/mysql/data-types.js
SELECT query returns null instead of empty Buffer for BLOB type
=> Fixed empty blob

docs/instances.md
Rating is tinyint, not string. I think, someone might get confused because of this.
Proof at L33: `==> 3`, not `==> '3'`
=> docs: fixed small mistake

.travis.yml, appveyor.yml, lib/dialects/mssql/connection-manager.js, lib/dialects/mysql/connection-manager.js, lib/dialects/postgres/connection-manager.js, lib/dialects/sqlite/connection-manager.js, test/unit/dialects/mssql/query-generator.test.js
Fixes #9468
Not sure now tests did not caught this, will check CI with this PR
=> fix(connection-manager): mssql datatype parsing

lib/sequelize.js, package.json, test/integration/cls.test.js
Encapsulate promises returned by `retry-as-promised` with `Promise.resolve` to maintain CLS context in `afterXXX` hooks.
fix #9472
fix #9071
=> fix(hook): maintain CLS context in `after` hooks

lib/data-types.js, lib/dialects/abstract/query-generator.js, lib/dialects/mssql/query.js, lib/dialects/postgres/data-types.js, lib/dialects/postgres/query-generator.js, lib/dialects/sqlite/query-generator.js, test/integration/data-types.test.js, test/integration/dialects/postgres/dao.test.js, test/integration/json.test.js, test/integration/model/create.test.js, test/support.js, test/unit/dialects/abstract/query-generator.test.js, test/unit/dialects/mysql/query-generator.test.js, test/unit/dialects/postgres/data-types.test.js, test/unit/dialects/postgres/query-generator.test.js, test/unit/dialects/sqlite/query-generator.test.js, test/unit/sql/insert.test.js
This is a new spin of #9371 where I've removed the `bindParams` option and updated all the INSERT unit tests to match the new syntax. It's thrown up a few issues:
* Data types that don't easily match up with built in JS data types (specifically `GEOMETRY`) cause issues since drivers can't identify them before sending them as bind parameters. They need to be sent using a correct CAST and providing the bind parameter in string form e.g. `GeomFromText($1)` with a valid bind param
* Upsert needs updating - both PostgreSQL and Sqlite override the upsertQuery function in the query generator
=> feat(query-generator): Generate INSERTs using bind parameters

lib/dialects/abstract/query-generator.js, lib/dialects/mssql/data-types.js, lib/dialects/mssql/query-generator.js, lib/dialects/postgres/query-generator.js, lib/dialects/sqlite/query-generator.js, lib/dialects/sqlite/query.js, lib/model.js, test/integration/data-types.test.js, test/integration/model.test.js, test/integration/model/create.test.js, test/unit/dialects/mysql/query-generator.test.js, test/unit/dialects/postgres/query-generator.test.js, test/unit/dialects/sqlite/query-generator.test.js, test/unit/sql/update.test.js
WIP changes to allow UPDATEs to use bind parameters instead of directly included values. For example, instead of:
```UPDATE `myTable` SET `name`='foo',`birthday`='2011-03-27 10:01:55' WHERE `id` = 2```
Generate:
```UPDATE `myTable` SET `name`=$1,`birthday`=$2 WHERE `id` = $3```
(with parameters `'foo'`, `'2011-03-27 10:01:55'` and `2`)
=> feat(query-generator): Generate UPDATEs using bind parameters

lib/sequelize.js, test/unit/configuration.test.js
The [document](http://docs.sequelizejs.com/class/lib/sequelize.js~Sequelize.html#instance-constructor-constructor) says that the username, the password and the database can be passed as options with URL. (e.g. `new Sequelize('mysql://localhost:3306', { database, username, password })`)  
But the current behavior does not honour these fields in options. This PR allows to pass these fields as options.
=> fix(constructor): set the username, the password and the database via constructor options

CONTRIBUTING.md
Fixed issue with an environment dependency otherwise a specific test fails.
#9520: Postgres error.test.js depends on an extension that is not installed by default: `btree_gist`
=> Improve documentation of local database instances setup for test env

lib/associations/belongs-to-many.js, test/integration/associations/belongs-to-many.test.js
When the `rejectOnEmpty` flag is set in a model, an `EmptyResultError` is raised during a `findAll`
promise in add* and set* accessors of the BelongsToMany association. This fix prevents it by
catching only this error and throwing any unexpected others.
fix #9531
=> fix(BelongsToMany): catch EmptyResultError in add* and set* accessors

lib/data-types.js, lib/dialects/mssql/connection-manager.js, lib/dialects/mysql/connection-manager.js, lib/dialects/postgres/connection-manager.js, lib/dialects/sqlite/connection-manager.js, package.json
=> fix: remove terraformer-wkt-parser dependency

CONTRIBUTING.md, lib/model.js, test/integration/model/sync.test.js
=> Fix 9515: sync() with "alter:true" doesn't use field name in model definition

docs/models-definition.md, lib/instance-validator.js, lib/model.js, lib/utils/validator-extras.js, test/integration/model/create.test.js, test/unit/model/define.test.js
…lowNull usage with it
Fixes #1500 
Sequelize can customize `allowNull` error messages with `notNull` validator, but validator throw error when value is not `null` due to deprecation for `notNull`.
I have removed that deprecation, it was only introduced to enforce users to use `allowNull` over `notNull`, I have added some checks that will only allow use of `notNull` with `allowNull: false`.
So overall if users want to prevent null values they can as usual use `allowNull: false`, but if they want to customize that error message, they can use `notNull.msg`
=> change: remove deprecation from notNull for custom messages / enforce use of allowNull with this validator 

docs/models-definition.md, lib/data-types.js, lib/dialects/postgres/data-types.js, package.json, test/integration/data-types.test.js
Adds support for [Postgres network address types](https://www.postgresql.org/docs/9.6/static/datatype-net-types.html). 
This is a continuation of work started by @tadman in https://github.com/sequelize/sequelize/issues/8154.
Closes #8154
=> feat(data-types): CIDR, INET, MACADDR support for Postgres

lib/dialects/abstract/query-generator.js, lib/dialects/abstract/query-generator/transaction.js, lib/dialects/mysql/query.js, lib/utils.js
As of version 3.x of uuid library `require('uuid')` statement is deprecated and should be changed to
`require('uuid/[v1|v3|v4|v5]')` respectively. This PR changes those statements with the new ones.
fix #9591
- Changed `require('uuid')` statements to `require('uuid/v4')` where version 4 used and added an extra require in `utils.js` file to allow also use version 1
- Changed constants' names to `uuidv4` and `uuidv1` to have distinction between them
=> fix(query): uuid require statements fixed

lib/sequelize.js, test/integration/sequelize.test.js
Adding an error message when a value for ARRAY have not been defined.
See issue: #7932
=> Add an error message when a value for array has not been defined

lib/dialects/sqlite/query-interface.js, lib/dialects/sqlite/query.js, test/integration/data-types.test.js, test/integration/dialects/sqlite/sqlite-master.test.js
Raw queries to the `sqlite_master` table were being special-cased and as such would return inconsistent values. For example, `SELECT * FROM sqlite_master` would simply return an array populated with just the value in the `name` column. This change allows you to query the `sqlite_master` just like any other table, and removes hardcoded SQL string checks in favor of using the `QueryTypes` enum.
This is related to #1612 and #8769. Previous workarounds were to shove the `sqlite_master` table into a view so that its table name wouldn't be caught by the `indexOf` check and query the view instead.
This changeset also fixes a DataTypes test that was failing due to timezone issues.
=> Adds support for querying sqlite_master table

lib/model.js, test/integration/model/bulk-create.test.js
=> fix(bulkCreate): dont map dataValue to fields for individualHooks:true

lib/associations/belongs-to-many.js, test/integration/associations/belongs-to-many.test.js
…es table
belongsToMany.add returns array of intermediate table instance, not nested array of array.
See issue: #8377
=> belongsToMany.add returns array of intermediate table instance

docs/raw-queries.md
I've been using sequelize for a while already. Thanks for a good work!
I've stumbled upon a confusion when using `sequelize.query()` with `model` option. Not sure what was the maintainers' decision when disabling fields mapping by default, but it is quite confusing to not have mapping when model is passed. Changing default behavior may break, that's why I've updated the docs to clearly indicate the library users that the `mapToModel` property controls whether table fields will be mapped to the model or not.
closes https://github.com/sequelize/sequelize/issues/9687
=> Update raw query docs on model mapping

lib/model.js, test/integration/include/findAll.test.js, test/integration/model/scope.test.js, test/unit/model/scope.test.js
Assigning Utils.Where instance to scope not plain Object.
See issue: #6440
=> fixing a bug with sequelize.where in model scope

lib/model.js, test/integration/associations/has-many.test.js
=> fix(hasMany): don't propagate group to separated queries

lib/model.js, test/integration/model.test.js, test/integration/model/bulk-create.test.js
- [NA] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
Closes #[9796]
=> fix(model): Fix edge case crash in bulkCreate ( #9796)

lib/model.js, test/integration/model/scope/count.test.js
=> Suggested fix #9787

lib/sequelize.js
The doc seems to be missing the schema option, which I verified works for PostgreSQL
=> doc(options): add missing schema option

lib/model.js
Fixed wrong function name of error in `Model.findCreateFind` method
=> style(Model): fix error message in findCreateFind

lib/dialects/abstract/connection-manager.js, lib/errors/index.js, lib/transaction.js, test/integration/pool.test.js, test/integration/transaction.test.js
Error described in issue #9218 happens when connection acquiring for auto-callback transaction times out: sequelize tries to automatically rollback transaction, but there is no connection to send rollback command.
Added check for inexistent connection, test and special erorr type.
=> fix(transaction): fixed unhandled rejection when connection acquiring times out (#9218)

lib/dialects/mssql/query-generator.js, lib/dialects/mysql/query-generator.js, lib/dialects/postgres/query-generator.js, test/integration/query-interface/changeColumn.test.js, test/unit/sql/change-column.test.js
=> fix(changeColumn): use engine defaults for foreign/unique key naming

lib/dialects/mssql/query-generator.js, lib/dialects/postgres/query-generator.js, test/integration/query-interface/createTable.test.js
Fixes #9149 
Added a space in `indexOf` check, enum with `COMMENT` is common but `COMMENT<space>` should be rare or invalid for most use cases, just enough to fix this bug
=> fix(postgres): enum with string COMMENT breaks query

docs/hooks.md
**Not applicable, this is a document only change**
I was very disappointed to realize today that if were to update or destroy a billion instances with individual hooks, Sequelize would try to fetch all billion of them into memory before running the individual hooks.  I had mistakenly assumed it would iterate through them in batches or using cursors of some kind...
I wish I had been warned about this before I decided to start using hooks, so I'm adding this warning to the docs.
=> docs(hooks.md, model.js): add warnings about memory limitations of individualHooks

docs/instances.md
Also added a note that creating a new instance with the same primary key as a soft-deleted instance will not work.
fix #9885
=> Add section for restore() to tutorial docs

docs/associations.md, lib/associations/belongs-to-many.js, lib/model.js, test/integration/associations/belongs-to-many.test.js, test/unit/associations/belongs-to-many.test.js
=> fix(associations): enable overwrite the name in unique constraint

lib/query-interface.js, package.json, test/integration/query-interface/createTable.test.js
=> fix(create-table): support for uniqueKeys

lib/associations/helpers.js, test/unit/associations/has-many.test.js
=> fix(model): check attribute overrides when defining assoc mixins (#9952)

lib/dialects/mysql/query.js, test/integration/dialects/mysql/warning.test.js, test/unit/dialects/mysql/query.test.js
fix #9919 
validate that warning row is iterable
=> fix(query): check valid warn message (#9919)

lib/dialects/abstract/connection-manager.js, lib/dialects/mssql/connection-manager.js, lib/dialects/mysql/connection-manager.js, lib/dialects/postgres/connection-manager.js, lib/dialects/sqlite/connection-manager.js, lib/sequelize.js, test/unit/dialect-module-configuration.test.js
Added support for new configuration option `dialectModule`. Sequelize instance will use that dialect library instance rather than requiring default dialect module
Fixes #9608
Fixes #7354
Closes #9609
=> feat(sequelize): dialectModule option

docs/models-usage.md, lib/model.js, test/integration/associations/belongs-to-many.test.js, test/integration/associations/belongs-to.test.js, test/integration/associations/has-many.test.js, test/integration/associations/has-one.test.js, test/integration/model/scope/find.test.js, test/integration/sequelize.transaction.test.js, test/unit/model/validation.test.js
Little addition to the previous PR https://github.com/sequelize/sequelize/pull/9933
Remove the .all() alias of .findAll()
=> refactor(Model): remove .all() alias of .findAll()

lib/associations/belongs-to.js, lib/associations/has-one.js, test/integration/associations/belongs-to.test.js
=> fix(belongs-to): create now returns target model

lib/dialects/postgres/data-types.js, test/unit/sql/data-types.test.js
Proposal to fix #9738.
Postgres don't have type TINYINT.
With this PR the mesage error is more clear when use `TINYINT.UNSIGNED`. It's same when use `TINYINT`
From:
`ERROR: syntax error at or near "UNSIGNED"`
To:
`type "tinyint" does not exist`
@sushantdhiman what do you think?
=> fix(tinyint): ignore params for TINYINT on postgres

lib/query-interface.js
Adds missing documentation on 'bulkUpdate' inline at query-interface.js. Addresses https://github.com/sequelize/sequelize/issues/8820
=> docs(query-interface): add inline 'bulkUpdate' docs

lib/model.js, lib/query-interface.js, test/integration/model/sum.test.js
=> fix(sum): returns 0 when is empty matching

lib/dialects/abstract/index.js, lib/dialects/abstract/query.js, lib/dialects/postgres/index.js, lib/dialects/sqlite/index.js, test/integration/model/create.test.js
Change to _AbstractQuery.getUniqueConstraintErrorMessage()_ to handle falsey _field_. This fixes the TypeError in #10016.
Closes #10016
=> Handle undefined field on unique constraint error (#10016)

lib/sequelize.js, test/unit/configuration.test.js
Added support for the ssl option to the Postgres URI. For example:
```
postgres://localhost/sequelize_test?ssl=true
```
The way I chose to support this was assigning any query parameters from the URI into `dialectOptions`. Then each dialects `ConnectionManager.connect()` can use the parameters the same as if they were used in the constructor with `options.dialectOptions`. 
Closes #10015 
Related #9712, #6932, #5891
=> Add ssl option to uri for postgres

lib/dialects/abstract/query-generator.js, lib/dialects/mssql/query-generator.js, lib/dialects/mysql/query-generator.js, lib/dialects/postgres/query-generator.js, lib/query-interface.js, test/unit/dialects/mssql/query-generator.test.js, test/unit/dialects/mysql/query-generator.test.js, test/unit/dialects/postgres/query-generator.test.js
Resolved #8821
Added two API on QueryInterface - createDatabase and dropDatabase. I just want to used for https://github.com/sequelize/cli/issues/590. But these two API doesn't have testing code yet. It's hard to implement create and drop database in docker. If somebody has interesting on that. Please help me to add testing code on that.
=> Implement createDatabase and dropDatabase on QueryInterface

lib/dialects/abstract/query-generator.js, test/integration/model/findAll/separate.test.js, test/unit/sql/select.test.js
fix #9813 
I wrapped a subquery to union.
Although it is a little tricky, no error occurs with this.
=> fix(syntax): correct parentheses around union (#9813)

lib/dialects/mysql/query-generator.js, lib/dialects/postgres/query-generator.js, lib/query-interface.js, test/unit/dialects/mysql/query-generator.test.js, test/unit/dialects/postgres/query-generator.test.js
Resolved #10030 
Postgresql doesn't support `CREATE DATABASE IF NOT EXISTS...`. So remove words `IF NOT EXISTS`.
Add more options on postgresql  `CREATE DATABASE`:
- template
- ctype
refs:
- https://www.postgresql.org/docs/9.5/static/sql-createdatabase.html
- https://www.postgresql.org/docs/9.5/static/sql-dropdatabase.html
=>  fix(postgres): remove if not exists and cascade on create/drop db

docs/models-definition.md, lib/data-types.js, lib/dialects/sqlite/data-types.js, lib/instance-validator.js, test/integration/data-types.test.js, test/integration/model/create.test.js, test/integration/model/findAll.test.js, test/integration/model/findOne.test.js
#10024 added CITETXT for Postgres.
This isn't a real data-type in SQLite but uses `COLLATE NOCASE` on the `TEXT` field. The behavior is the same as CITEXT for Postgres with the exception of SQLite only supporting ASCII characters.
=> Add support for sqlite citext data-type 

lib/dialects/abstract/query-generator.js, test/integration/model.test.js, test/integration/model/create.test.js, test/integration/model/findAll.test.js, test/unit/sql/delete.test.js, test/unit/sql/where.test.js
Follow up from https://github.com/sequelize/sequelize/pull/9548, Now Sequelize will throw for any `undefined` where keys
=> fix: throw on undefined where parameters

lib/dialects/abstract/query-generator.js, lib/dialects/mssql/query-generator.js, lib/dialects/mysql/query-generator.js, lib/dialects/postgres/query-generator.js, lib/dialects/sqlite/query-generator.js, lib/dialects/sqlite/query.js, lib/sequelize.js, test/integration/model/scope/destroy.test.js, test/integration/sequelize.test.js, test/unit/configuration.test.js, test/unit/dialects/mssql/query-generator.test.js, test/unit/dialects/mysql/query-generator.test.js, test/unit/dialects/postgres/query-generator.test.js, test/unit/dialects/sqlite/query-generator.test.js, test/unit/sql/update.test.js
**Waiting for integration tests to run in CI**
- Trying to cleanup lodash template usage and replacing it with faster template strings, also minor caching of some calls!
- I skipped one particulary hard _.template call as the logic was too convoluted for me to touch.
- Replaced constant regex matches with string matches.
- Fixed some linting
- Fixes some inconsitent query generation padding
=> refactor(query-generation): cleanup template usage

lib/dialects/abstract/query-generator.js
FIxes #9982 
Also tiny cleanup 😄 
Not familiar enough with the repo to find an error case but, better safe than sorry.
=> fix(query-generator): fix bad property access

docs/models-usage.md
The original example did not work throwing an error about `order` requiring an array.
=> Fixed example for `order` in docs/models-usage.md

docs/upgrade-to-v4.md
Just fixing a typo in the `upgrade-v4.md`. The original snippet throws the error below.  
```
ReferenceError: propogateRequired is not defined
```
I would be happy to make this documentation better! Thanks!
=> Fix documentation typo in the section about upgrade to v4
