sequelize/sequelize

- docs/docs/usage.md
- Added MSSQL information
- Fixed formatting errors
- Updated module version information
> Update usage doc

- lib/instance.js
- lib/model.js
This pull request restores the functionality originally added in this pull request: https://github.com/sequelize/sequelize/pull/1952
> Add ability to pass options back to the getTableName function

- test/dialects/postgres/dao.test.js
Sample testcase for https://github.com/sequelize/sequelize/issues/2764
> Test case for #2764

- lib/dialects/abstract/query-generator.js
> Sequelize ignoring field value inside a subquery.

- lib/model.js
Fix for issue [#2896](https://github.com/sequelize/sequelize/issues/2896)
> fieldname mapping for model.count added

- docs/articles/getting-started.md
Referencing Issue https://github.com/sequelize/sequelize/issues/2899
Changed "which ways of database setup approaches" to "which types of database setup approaches", and added an appropriate comma.
> Wording tweak- first paragraph

- docs/articles/getting-started.md
Referencing issue https://github.com/sequelize/sequelize/issues/2899
There were a number of typos and wording updates in the section on Managing Schema.
> Docs- Updated 'Managing Schema Of Your Database'

- docs/articles/getting-started.md
A number of small tweaks on the Defining A Model section, referencing issue https://github.com/sequelize/sequelize/issues/2899.
> Docs- Wording changes on 'Defining A Model'

- docs/docs/models.md
Updated line 502 to remove the apostrophe
> Altered Grammar

- CONTRIBUTING.DOCS.md
Added a colon prior to a code block as done previously in the document
> Small text edit - CONTRIBUTING.DOCS.md

- CONTRIBUTING.DOCS.md
Believe the following changes will help make the documentation more clear:
> Improve wording in CONTRIBUTING.DOCS.md

- lib/sequelize.js
- test/configuration.test.js
> Fixes authentication credentials not being passed in db connection string, and passing options

- docs/docs/models.md
`Projects`.`id` IN (1,2,3) OR `Projects`.`id` < 10
has no sense, second part should be enough.
That's why I replaced `lt` lookup with `gt` to generate following SQL
`Projects`.`id` IN (1,2,3) OR `Projects`.`id` > 10
which have much more sense.
Sorry for removing whitespaces, I have change few lines in Complex filtering section, starting from line 723.
> Give more meaning for operator 'or'

- docs/docs/associations.md
The rest of the changes are similar to below:
> Updated punctuation: associations.md

- docs/docs/models.md
These changes should make this more readable:
> Updated grammar on models.md

- docs/docs/models.md
Edited first paragraph because there were stray html character codes instead of the actual punctuation marks.
> Replace HTML character codes with punctuation marks in models.md

- lib/errors.js
Using node 0.11.14.
Before
After
> Fix error stack trace

- docs/docs/associations.md
Corrected the spelling of 'constriants' to 'constraints'.
> Fix type in Associations.md

- changelog.md
- lib/instance-validator.js
- lib/instance.js
- lib/model.js
- lib/utils.js
- test/integration/model/upsert.test.js
Closes https://github.com/sequelize/sequelize/issues/2946 and https://github.com/sequelize/sequelize/issues/2987
> Add field support to upsert

- docs/docs/getting-started.md
I've spent about 10 minutes googling for "Error: The dialect postgress is not supported." before I found a typo =)
> typo in connection url example

- changelog.md
- lib/dialects/abstract/index.js
- lib/dialects/postgres/index.js
- lib/dialects/postgres/query-generator.js
- test/unit/sql/json.test.js
Closes https://github.com/sequelize/sequelize/issues/3034
@mickhansen Do the unit tests look reasonable to you?
> Support for plain strings, ints and bools in JSON

- docs/docs/models.md
There were no concrete example of getters and setters in "Defining as part of a property" section, so I rewrite it.
> Clearify how to use Getters & Setters

- docs/readthedocs_theme/footer.html
- mkdocs.yml
As the content is still originally from me and somehow related to my
anyways, I think we’ll have to add this lovely imprint :-| Hooray!
> Add imprint to the docs

- docs/readthedocs_theme/base.html
> Add canonical tag to theme template

- README.md
Update link to corresponding URL @ Readthedocs.org
> Fix "Getting Started" link in Readme

- docs/docs/instances.md
As reflected in:
https://github.com/sequelize/sequelize/blob/master/lib/model.js#L1449
> Updating docs to reflect actual bulk delete

- lib/sequelize.js
just remove a comma.for some IDE alerts
> No functional change,remove a comma

- Makefile
- lib/query-interface.js
- lib/sequelize.js
- test/integration/hooks.test.js
- test/integration/include/findAll.test.js
- test/integration/include/schema.test.js
- test/integration/model.test.js
- test/integration/sequelize.test.js
- test/integration/sequelize.transaction.test.js
- test/integration/support.js
- test/integration/transaction.test.js
Should help in identifying leaks, lets see.
> feat(test/misc): utils for verifying sequelize has no running/pending queries

- lib/sequelize.js
Remove extra "you":
"The dialect you of the database you" --> "The dialect of the database you"
> Fix grammar error in code comment

- index.js
- lib/emitters/custom-event-emitter.js
- lib/model-manager.js
- lib/plugins/counter-cache.js
- package.json
- test/integration/associations/belongs-to-many.test.js
- test/integration/dialects/postgres/associations.test.js
- test/integration/dialects/postgres/dao.test.js
- test/integration/include.test.js
- test/integration/include/findAll.test.js
- test/integration/include/schema.test.js
- test/integration/instance.test.js
- test/integration/model.test.js
- test/integration/model/create.test.js
- test/integration/model/find.test.js
- test/integration/promise.test.js
- test/integration/query-chainer.test.js
- test/integration/sequelize.transaction.test.js
- test/support.js
> Refactor last tests to use promise style

- docs/docs/hooks.md
Fixes the wrong arguments in the example in the hooks documentation. Fixes https://github.com/sequelize/sequelize/issues/3505
> Updates hooks.md

- docs/docs/models.md
I might be wrong but I think this way it makes more sense.
> Fix condition in model wide validation

- changelog.md
- docs/docs/migrations.md
- lib/associations/belongs-to-many.js
- lib/dialects/sqlite/query-interface.js
- lib/instance.js
- lib/model.js
- lib/query-chainer.js
- lib/query-interface.js
- lib/sequelize.js
- lib/sql-string.js
- lib/utils.js
- test/integration/associations/belongs-to-many.test.js
- test/integration/associations/self.test.js
- test/integration/dialects/postgres/associations.test.js
- test/integration/dialects/postgres/dao.test.js
- test/integration/instance.test.js
- test/integration/model.test.js
- test/integration/model/and-or-where.test.js
- test/integration/model/attributes/types.test.js
- test/integration/model/create.test.js
- test/integration/model/find.test.js
- test/integration/promise.test.js
- test/integration/query-chainer.test.js
- test/integration/query-interface.test.js
- test/integration/sequelize.test.js
- test/integration/vectors.test.js
This has to be merged before #3265 is possible to be merged.
> Proper sql logging

- lib/sequelize.js
> use then instead of catch for promise returned from a callback

- package.json
Fixes petkaantonov/bluebird/issues/291
> Bump bluebird version

- lib/associations/belongs-to-many.js
I believe this might have been an oversight.
> Default target reference in belongsToMany association to CASCADE

- docs/docs-generator.js
- docs/docs/models.md
- docs/docs/querying.md
> JSONB (and more) documentation

- docs/api/sequelize.md
- lib/sequelize.js
This PR fixes 3 small typos within the docs.
> Fix typo for sequelize within docs

- lib/migrator.js
- lib/query-chainer.js
- lib/query-interface.js
- lib/utils.js
> Fixed paths.

- lib/dialects/abstract/query-generator.js
- test/unit/sql/where.test.js
> Add support for WHERE LIKE ANY queries

- test/integration/dialects/postgres/dao.test.js
> Add test for an empty integer array as default value

- lib/utils/parameter-validator.js
> Fix a node-webkit issue

- CONTRIBUTING.md
- lib/sequelize.js
- lib/transaction.js
Added option for default global transaction isolation level.
Updated doc about contributing.
> Added option for default global transaction isolation level.

- changelog.md
- lib/dialects/abstract/query-generator.js
- test/unit/sql/index.test.js
> fix addIndexQuery when an object is provided as the tableName

- lib/model.js
> Use primaryKeyField in Model#count

- lib/errors.js
Use the parent error message if it's missing. I'm to lazy to write a test for this right now...
> Add parent error messages

- docs/docs/models-usage.md
Infos on the `required` option when doing nested eager loading.
> add doc on required for nested eager loading

- lib/dialects/mssql/query-generator.js
- test/integration/model/findAll.test.js
> [MSSQL] Eliminate duplicate ORDER BY statements in select queries

- lib/model.js
Fixed JSDOC to have all possible where options for http://docs.sequelizejs.com/en/latest/api/model/#findalloptions-promisearrayinstance
> DOC: findAll WHERE options list compiled based on guery-generator.js aliasMap

- lib/model.js
- test/unit/model/scope.test.js
Refs [Model scopes and `complexFunctions`](https://github.com/sequelize/sequelize/issues/3724) issue.
> Add hability to use raw queries in Model scopes

- changelog.md
- docs/docs/transactions.md
- lib/transaction.js
@calvintwr asked for  some help here. If you get to many conflicts while rebasing you should just rebase smaller steps at a time. That way it's easier.
Besides the docs this is also going to fix the changelog (one entry is misplaced).
> Transaction docs

- changelog.md
- lib/model.js
- lib/sequelize.js
- test/integration/associations/has-many.test.js
- test/integration/model.test.js
- test/integration/sequelize.test.js
You originally closed this since the author did not respond anymore.
> Add sequelize.truncate function

- test/integration/support.js
- test/integration/timezone.test.js
- test/integration/transaction.test.js
Just to make sure there are less failures. 
Edit: I had a look at broken CI runs and found at three issues that should be fixed with this PR.
> Fix racy tests

- lib/associations/base.js
- lib/associations/belongs-to-many.js
- lib/associations/belongs-to.js
- lib/associations/has-many-single-linked.js
- lib/associations/has-many.js
- lib/associations/has-one.js
- lib/associations/helpers.js
- lib/dialects/abstract/query-generator.js
- lib/dialects/abstract/query.js
- lib/dialects/mssql/query-generator.js
- lib/dialects/mssql/query.js
- lib/dialects/mysql/query-generator.js
- lib/dialects/mysql/query.js
- lib/dialects/postgres/hstore.js
- lib/dialects/postgres/query-generator.js
- lib/dialects/postgres/query.js
- lib/dialects/postgres/range.js
- lib/dialects/sqlite/query-generator.js
- lib/dialects/sqlite/query-interface.js
- lib/dialects/sqlite/query.js
- lib/instance.js
- lib/model-manager.js
- lib/model.js
- lib/model/attribute.js
- lib/plugins/counter-cache.js
- lib/query-interface.js
- lib/sequelize.js
- lib/utils.js
- lib/utils/parameter-validator.js
I thought it's nicer to extract my indentation changes so the `small-stuff` PR will be better to read.
There's one very tiny change that has nothing to do with indentation: In `lib/utils` I changed `validateParameter` to use the parameterValidator directly.
> Remove unnecessary indentation

- lib/query-interface.js
Just a small tidy up of code which I found to be convoluted. No functional changes.
> Tidy code for QueryInterface#addIndex

- docs/docs/associations.md
> fix mistype

- lib/utils.js
- test/integration/model/upsert.test.js
Fixes #3406 + adds tests
/cc @janmeier
> Fix issue where upsert fails for database function values

- lib/query-interface.js
issue https://github.com/sequelize/sequelize/issues/3782 .probably need to add some tests.
> pass transaction dealing with pg enums

- lib/dialects/abstract/query-generator.js
- test/unit/sql/where.test.js
issue https://github.com/sequelize/sequelize/issues/3767
> fix fields and-or logic

- docs/api/model.md
- lib/model.js
WAS: "refererred"
NOW: "referred"
> Fix spelling error in model.js

- docs/api/hooks.md
- docs/docs/hooks.md
- lib/hooks.js
Keep on forgetting writing docs)
> add removing hooks docs

- lib/instance.js
Instance::get() recursively calls itself if getting an array.
```
$ make test
1387 passing (2m)
2 pending
```
> Refactored away duplicate code in Instance::get()

- .travis.yml
- lib/data-types.js
- lib/dialects/abstract/query-generator.js
- lib/dialects/postgres/data-types.js
- lib/dialects/postgres/query-generator.js
- lib/dialects/postgres/query.js
- lib/instance.js
- lib/model.js
- package.json
- test/integration/dialects/postgres/dao.test.js
- test/unit/sql/data-types.test.js
This is to replace PR https://github.com/sequelize/sequelize/pull/3828. Same code added to the latest in master.
> Adding GEOMETRY Support

- docs/docs/models-usage.md
Affects 97d355aa80cad217a8bd7190a6c00433a73f367f
> Fix typo introduced in recent commit

- changelog.md
- lib/dialects/abstract/query.js
- lib/dialects/mssql/query.js
- test/integration/error.test.js
This is just a travis runner, because mssql takes forever to run for me. I'll merge it myself once everything looks green
Closes #4017 and #4012
> :bug: Check for model and unique keys being defined in unique constraint parsing

- changelog.md
- lib/dialects/postgres/query.js
I just ran into this and thought I'll fix it right quick.
> Fix path variable being surrounded by quotes. Fixes #3464

- docs/docs/models-usage.md
> Typo fix in Raw Queries

- lib/model.js
- test/unit/model/find-or-create.test.js
https://github.com/sequelize/sequelize/issues/4039
> FindOrCreate with CLS not using stored transaction

- Makefile
- lib/associations/mixin.js
- lib/instance.js
- lib/model.js
- lib/query-interface.js
- lib/sequelize.js
- package.json
- test/support.js
- test/supportShim.js
Please see issue https://github.com/sequelize/sequelize/issues/3834
> Test logging option passing

- changelog.md
- docs/docs/hooks.md
- lib/hooks.js
- test/integration/hooks.test.js
issue https://github.com/sequelize/sequelize/issues/3901
> add optional name arg to .hook function

- lib/dialects/abstract/query-generator.js
I sort of assume that it should be this way.
> Check for `and` or `or`

- lib/instance.js
- test/unit/instance/changed.test.js
As discussed in the issue #4007. This PR looks to fix the way that dates are compared.
> Sequelize doesn't compare dates correctly

- docs/docs/models-usage.md
- docs/docs/querying.md
Documenting the $notIn query operator.
> doc(querying) Add documentation for the $notIn query operator.

- lib/model.js
- test/integration/trigger.test.js
- adds hasTrigger option in model.js that is then passed to
querygenerator.update
- adds integration test for Model.update
> adds support for for table triggers in mssql dialect for Model.update

- test/integration/model/scope/associations.test.js
There seem to be some issues preventing use of includes inside scope definitions. These tests should reproduce the problems.
WIP, I'll be abusing the PR system for travis-ci checking.
> Add test case for scope with includes

- lib/transaction.js
transaction.commit() and .rollback() return Promise object
> Transaction document fix

- docs/docs/getting-started.md
So that no one asks #4432 again :)
> make it clear that there should be one sequelize instance per database

- changelog.md
- lib/hooks.js
- lib/model.js
- test/integration/hooks.test.js
For this issue [#4371](https://github.com/sequelize/sequelize/issues/4371)
> add beforeRestore/afterRestore hooks

- docs/docs/models-usage.md
In my opinion the introduction to finder methods reads a bit funny. This is my attempt to improve it. 
I am not at all hell-bent on this. *Please* feel free to amend or reject!
> updated models-usage.md

- lib/sequelize.js
I couldn't run the tests, I would appreciate it if someone does it.
> static dialect requires. Fixes #4517

- changelog.md
- lib/associations/belongs-to.js
- lib/associations/has-many.js
- lib/associations/has-one.js
- lib/associations/mixin.js
- test/integration/associations/belongs-to.test.js
- test/integration/associations/has-many.test.js
- test/integration/associations/has-one.test.js
* CASCADE on hasOne/hasMany
* NO ACTION on belongsTo
Fixes #2831
> Foreign keys with allowNull: false with new default values

- lib/associations/belongs-to.js
> Corrected API doc for BelongsTo association, Fixes #4580

- changelog.md
- lib/transaction.js
This addresses https://github.com/sequelize/sequelize/issues/4245.
> Fixes transaction not getting cleaned up with sqlite Closes #4245

- lib/associations/belongs-to-many.js
- lib/associations/belongs-to.js
- lib/associations/has-many.js
- lib/associations/has-one.js
- lib/associations/mixin.js
~~Don't merge this just yet. i wanna know if all is ok, then fix the Overview section. So wait until then before merging :D~~
Addressing #4591
> Doc association api improvements. Fixes #4591

- lib/associations/belongs-to-many.js
- lib/associations/belongs-to.js
- lib/associations/has-many.js
- lib/associations/has-one.js
- lib/associations/helpers.js
- lib/dialects/abstract/query-generator.js
- lib/dialects/sqlite/query-generator.js
- lib/instance.js
- lib/model.js
- lib/query-interface.js
- test/integration/associations/belongs-to-many.test.js
- test/integration/associations/belongs-to.test.js
- test/integration/model/schema.test.js
- test/unit/model/schema.test.js
- test/unit/sql/index.test.js
This PR is to address https://github.com/sequelize/sequelize/issues/4119.
I added some unit and integration tests to cover the behavior more thoroughly.
> make schema a property on the model independent of prototype

- docs/docs/getting-started.md
The previous code example did not work as it tried to use the result of findAll() as a single entity.
I changed the findAll() to a findOne(), such that the overall logic of the code is the same.
> Fixed the Getting Started Promise documentation

- docs/docs/models-definition.md
> Fix typo in models-definition

- docs/docs/querying.md
So that people know there is such feature :grin:
> [docs] Added example for sequelize.where

- docs/docs/querying.md
Noticed this while working on #4753
> [docs] Fixed a small typo in the docs

- docs/docs/hooks.md
* fix sequelize/sequelize#4777
> Doc update

- docs/docs/associations.md
> fix document for associations

- docs/index.md
The previous code was calling then on the promise returned by `sync()` which obviously doesn't resolve into a `jane` instance!
> fix the example at the docs home page

- docs/docs/querying.md
change value from 100 to 1000 to match comment
> Fix typo in querying.md

- changelog.md
- lib/dialects/postgres/range.js
- test/integration/dialects/postgres/range.test.js
I've merged @alekbarszczewski's pull request #4706 with master and resolved the conflicts The changes to the parse() method are greatly simplified with the recent master changes.
> Merge of pull request  #4706 - pg range handling improved to HEAD

- lib/dialects/mysql/connection-manager.js
A simple fix to maintain browserify-friendliness!
> Update MySQL connect manager (browserify fix).

- lib/model.js
Exposed Model.$conformOptions and Model.$conformInclude.
> conformInclude/conformOptions exposed by Model

- lib/dialects/postgres/query-generator.js
- test/unit/sql/create-table.test.js
> bug(5015) pg doesn't support create table if not exists for 9.0 and below

- lib/data-types.js
Updated documentation to include mention of returning values from a function for primary keys.
> Doc change - custom auto-generated values

- test/integration/instance.test.js
> Changed assertion for silent=true test in instance integration

- changelog.md
- lib/dialects/postgres/connection-manager.js
- test/integration/dialects/postgres/connection-manager.test.js
> Postgres named timezone issue

- lib/dialects/abstract/index.js
- lib/dialects/sqlite/index.js
- lib/dialects/sqlite/query-generator.js
- lib/sequelize.js
- lib/transaction.js
- test/integration/transaction.test.js
Pull request for https://github.com/sequelize/sequelize/issues/4901
> Added Transaction Type

- lib/dialects/sqlite/query.js
- test/integration/dialects/sqlite/query-generator.test.js
- test/integration/query-interface.test.js
> 5051 fix sqlite default value

- lib/instance.js
Fixes: https://github.com/sequelize/sequelize/issues/5060
> Fix options being written to instead of cloning on instance.update

- lib/model.js
The key 'titleAttributes' on line 2590 seems to be incorrect. Should be 'attributes', causes a crash when excluding attributes with a scope.
var Account = sequelize.define('accounts', {
....
},{
freezeTableName: true,
paranoid: true,
defaultScope: {
where: { type: 'partner' },
attributes: { exclude: ['password'] }
},
indexes: [
{
name: 'accounts_uuid_key',
unique: true,
fields: ['uuid']
},
{
name: 'accounts_email_key',
unique: true,
fields: ['email']
}
],
scopes: {
auth: { attributes: ['id', 'uuid', 'email', 'password']}
}
});
----
/Users/username/Documents/project_name/node_modules/sequelize/lib/model.js:2590
var attributes = Object.keys(this.tableAttributes);
^
TypeError: Cannot convert undefined or null to object
at Function.keys (native)
at Model.$expandAttributes …
> Excluding attributes with scope.

- changelog.md
- lib/instance.js
> Fix(#4702): instance returns this on all paths

- changelog.md
- lib/sql-string.js
- test/integration/model/create.test.js
- test/integration/model/find.test.js
- test/unit/sql/create-table.test.js
- test/unit/sql/insert.js
- test/unit/sql/join-include-query.test.js
- test/unit/sql/select.test.js
- test/unit/sql/update.js
- test/unit/sql/where.test.js
> Prefix string literals with N in mssql

- changelog.md
- lib/model.js
- test/integration/model/scope.test.js
> Fix #4856 : Attributes from multiple scopes doesn't merge

- test/unit/model/findall.test.js
- test/unit/model/findone.test.js
Fixes #1150
Its a really old bug that has already been fixed at some point. I am adding tests to verify that `options` are properly cloned.
> Fix(#1150) : Test to verify findAll / find properly clone options

- changelog.md
- lib/dialects/abstract/query.js
- lib/dialects/mysql/data-types.js
- test/integration/data-types.test.js
> MySQL Geometry throw unhandled exception when buffer is null

- docs/docs/migrations.md
- docs/docs/usage.md
- lib/instance.js
- lib/model.js
- lib/sequelize.js
Closes #2912
Closes #1220
Closes #4648
Closes #4674
Closes #5139
> Fixed various docs issues

- docs/docs/migrations.md
> Typo in options

- docs/articles/getting-started.md
- docs/docs/associations.md
- docs/docs/hooks.md
- docs/docs/instances.md
- docs/docs/legacy.md
- docs/docs/models-definition.md
- docs/docs/models-usage.md
- docs/index.md
Closes #2797
Closes #2846
Closes #3348
> Few more documents updates

- changelog.md
- lib/dialects/postgres/query-generator.js
- lib/query-interface.js
- test/integration/dialects/postgres/dao.test.js
- test/unit/sql/enum.test.js
Re-roll of #4464 
Just gonna let travis do its thing to make sure the merge went well :D
> Merge PR #4464 and add tests

- lib/model.js
- test/integration/model.test.js
Fixed https://github.com/sequelize/sequelize/issues/5275
> Fix model update with individualHooks

- lib/utils.js
- test/unit/utils.test.js
Fixes https://github.com/sequelize/sequelize/issues/4167. Should respect parent model as well as sub model fields. If I missed something, let me know
> Fixed field alias in order clause

- lib/dialects/abstract/query-generator.js
- test/unit/sql/json.test.js
> Properly escape number 0 in query generator

- docs/docs/hooks.md
Added notes to documentation about this caveat when using updateOnDuplicate with a hook.
https://github.com/sequelize/sequelize/issues/5310
> Added documentation note about bulkCreate hook and updatesOnDuplicate option

- docs/docs/associations.md
- docs/docs/models-usage.md
Closes #2975, Closes #3416, Closes #3582
> Updated Documentation

- lib/data-types.js
- test/integration/sequelize.test.js
#5390 dialect mariaDB throw errors when submitting raw queries
> Fixes #5390 - dialect mariaDB missing data-types

- test/integration/associations/belongs-to-many.test.js
Added tests which confirm self reference works for same model.
Closes #3295
> (issue #3295) self reference tests for BelongsToMany

- docs/docs/models-definition.md
> Added Sequelize.DATEONLY to docs

- lib/associations/belongs-to-many.js
- test/integration/associations/belongs-to-many.test.js
The pull request  #4739 has been inactive for a while. Querying the through model is a crucial feature for us, so I'd like to move this forward.
#4739 works very well. I wrote a test for it and the original commits are still included.
> Support querying the through model

- lib/model.js
- test/unit/model/destroy.test.js
- test/unit/model/update.test.js
> Fix DELETE WHERE 1=1 when complex objects passed in options.where to destroy or update

- lib/dialects/mssql/query-generator.js
- lib/dialects/mssql/query-interface.js
- lib/dialects/mysql/query-generator.js
- lib/dialects/mysql/query-interface.js
- lib/query-interface.js
- test/integration/query-interface.test.js
This is failing for me on MS SQL Server 2k8 R2. It might not be an issue on other database types, or newer versions of MSSQL.
Just adding failing tests for now, and will look into implementing a fix soon.
> removeColumn for column with foreign key constraint

- docs/docs/querying.md
- test/integration/instance.test.js
- test/unit/dialects/mysql/query-generator.test.js
- test/unit/dialects/postgres/query-generator.test.js
- test/unit/dialects/sqlite/query-generator.test.js
Open issues tested in this commit:
[#5301](https://github.com/sequelize/sequelize/issues/5301)
* Solved by commit [46b58d76](https://github.com/sequelize/sequelize/commit/46b58d76027aff7c140236233e7f3a946db424fb)
* Test in [test/integration/instance.test.js]()
[#5489](https://github.com/sequelize/sequelize/issues/5489)
* Solved by commit [251648a1](https://github.com/sequelize/sequelize/commit/251648a1865ae43f4fd513d13a5866ed51976047)
* Test in [test/unit/sql/where.test.js](https://github.com/sequelize/sequelize/blob/master/test/unit/sql/where.test.js#L132), and query-generator for [MySQL](https://github.com/sequelize/sequelize/compare/master...krmannix:master#diff-32faf0d7550b4218a1b97438c7caeb1fR372), [Postgres](https://github.com/sequelize/sequelize/compare/master...krmannix:master#diff …
> updated docs and tests for issues #5031 and #5489

- lib/dialects/postgres/query-generator.js
No method from the link is actually implemented here.
> Removed misleading comment

- changelog.md
- lib/dialects/mysql/query-generator.js
- test/unit/sql/add-column.test.js
- solve issue: [queryInterface.addColumn with references not add reference in mysql](https://github.com/sequelize/sequelize/issues/5592)
- all existing tests pass
- add queryInterface.addColumn test for mysql
> fix `addColumn` with reference not add reference in mysql

- lib/dialects/sqlite/query-interface.js
#5626 Made SQLite query-interface use the full options-object (including transactions).
> Added missing transaction in SQLite query interface

- docs/docs/models-usage.md
> `limit: 3` typo in examples

- docs/docs/models-usage.md
It is a way to know how you can order data by DESC or ASC with model attributes and alias.
> Docs: Added Ordering Eager Loaded Associations option.

- lib/dialects/mssql/query-generator.js
- lib/dialects/mysql/query-generator.js
- lib/dialects/postgres/query-generator.js
- lib/dialects/sqlite/query-generator.js
- lib/model-manager.js
- lib/model.js
- lib/utils.js
- test/integration/include/schema.test.js
- test/integration/model.test.js
- test/unit/dialects/mysql/query-generator.test.js
- test/unit/dialects/postgres/query-generator.test.js
- test/unit/dialects/sqlite/query-generator.test.js
- test/unit/utils.test.js
Closes #5234
- Removed use of the old referenceKey code
- Removed test cases that use old reference code
> Task #5234 - remove old referenceKey code

- docs/api/datatypes.md
- lib/data-types.js
Noticed that this was a little out of order when reading the docs. Changed the source comment and the documentation as well
> Minor Docs fix

- .jshintrc
- lib/dialects/abstract/query-generator.js
- lib/dialects/postgres/query-generator.js
- test/unit/dialects/mysql/query-generator.test.js
- test/unit/dialects/postgres/query-generator.test.js
Reopen https://github.com/sequelize/sequelize/pull/5631
> fix limit=0 issue

- changelog.md
- test/integration/hooks/validate.test.js
Closes #3534 
Added a test which verify that values changed in the validation hooks are preserved.
> Tests for #3534, values modified in validate hooks are saved

- changelog.md
- lib/data-types.js
- package.json
[terraformer-wkt-parser](https://github.com/Esri/terraformer-wkt-parser) seems like a much better choice to [wellknown](https://github.com/mapbox/wellknown) for WKT parsing, here are a few reasons:
- faster
- better documentation
- fewer dependencies
- less unnecessary features such as a cli
These alternatives were turned down:
- [OpenLayers WKT](https://github.com/openlayers/openlayers/blob/master/lib/OpenLayers/Format/WKT.js) -- needs to be put in it's own module
- [Wicket](https://github.com/arthur-e/Wicket) -- more unnecessary features, needs an instance to be created on each convert (so likely slower)
```
Benchmarks for: polygon...
o wellknown x 108,678 ops/sec ±1.53% (135 runs sampled)
o terraformer x 124,363 ops/sec ±2.61% (133 runs sampled)
Fastest: terraformer
Slowest: wellknown …
```
> remove dependency on wellknown in favor of terraformer-wkt-parser

- lib/instance-validator.js
- test/integration/instance.validations.test.js
- test/unit/instance/build.test.js
- test/unit/model/validation.test.js
Clarify validate documentation as validate emits undefined if there are no errors not null.
> Update validation to return null

- test/unit/model/validation.test.js
The new test ensures that promises can be returned by custom model
validation functions (there is already a test which does the same tests
for field-based custom validation functions).
> Add custom validation function testcases

- docs/api/datatypes.md
- lib/data-types.js
This helps users to understand the reason to this conversion and avoid more open issues to Sequelize like these:
- https://github.com/sequelize/sequelize/issues/1774
- https://github.com/sequelize/sequelize/issues/4550
> docs(datatype): add a note about BIGINT datatype conversion to string

- docs/docs/raw-queries.md
plus minor edit
nice work team!
> fix none/non typo

- changelog.md
- lib/dialects/mysql/query-generator.js
- test/integration/query-interface.test.js
attempt to fix issue #5808 
had a previous pull request with a passing build on the actual code [#5830](https://github.com/sequelize/sequelize/pull/5830)
needed integration tests and merged my changes into a single commit so I made I new pull request for it
I also ran this in a successful build in travis on my [fork](https://travis-ci.org/paolord/sequelize/builds/127562142)
> fixes issue #5808 removeColumn tries to delete nonexistent foreign keys

- changelog.md
- lib/query-interface.js
- lib/sequelize.js
> Remove default isolation level

- docs/docs/associations.md
> projectId formatting

- lib/dialects/sqlite/query.js
Added default value for tableTypes. This seems to fix #5755.
> add default value for tableTypes in sqlite (#5755)

- lib/instance.js
- test/integration/instance.test.js
May need to check if it works with Mongo and Postgres, will wait for Travis CI result.
> Prove that Instance.equals() still doesn't work and fix it

- docs/docs/associations.md
This PR only contains changes to documentation.
> highlight missing method names

- docs/docs/getting-started.md
I thought that you should show that Sequelize does not automaticly test the connection and I simply took the example from the old docs :)
> Docs: Update getting started with how to test connection

- lib/sequelize.js
> ES6 refactor: sequelize.js

- lib/model.js
- lib/model/attribute.js
> ES6 refactor: Model

- lib/query-interface.js
> ES6 refactor: QueryInterface

- lib/transaction.js
> ES6 refactor: Transaction

- lib/model-manager.js
> ES6 refactor: ModelManager

- lib/errors.js
- test/unit/errors.test.js
> ES6 refactor: errors

- lib/dialects/mysql/connection-manager.js
- lib/dialects/mysql/query-generator.js
- lib/dialects/mysql/query-interface.js
- lib/dialects/mysql/query.js
> ES6 Refactor: dialects / MySQL

- lib/dialects/mssql/connection-manager.js
- lib/dialects/mssql/query.js
> ES6 refactor: dialects / MSSQL

- lib/dialects/postgres/connection-manager.js
- lib/dialects/postgres/hstore.js
- lib/dialects/postgres/index.js
- lib/dialects/postgres/query-generator.js
- lib/dialects/postgres/query.js
- lib/dialects/postgres/range.js
> ES6 refactor: dialects / PostgreSQL

- lib/dialects/sqlite/connection-manager.js
- lib/dialects/sqlite/index.js
- lib/dialects/sqlite/query-generator.js
- lib/dialects/sqlite/query-interface.js
- lib/dialects/sqlite/query.js
See #6009 
Need help on this one, don't know why tests fail. Other PRs depend on this unfortunately.
> ES6 refactor: dialects / SQLite

- lib/dialects/abstract/connection-manager.js
- lib/dialects/abstract/index.js
- lib/dialects/abstract/query-generator.js
- lib/dialects/abstract/query.js
> ES6 Refactor: dialects / abstract

- lib/dialects/abstract/query-generator.js
- lib/dialects/postgres/query-generator.js
- lib/sequelize.js
- lib/utils.js
- test/integration/instance/values.test.js
- test/integration/utils.test.js
> ES6 refactor: utils

- lib/data-types.js
- lib/dialects/mssql/data-types.js
- lib/dialects/mysql/data-types.js
- lib/dialects/postgres/data-types.js
- lib/dialects/sqlite/data-types.js
- lib/utils/inherits.js
> ES6 refactor: data types

- lib/promise.js
> ES6 refactor of promise.js

- lib/utils/parameter-validator.js
> ES6 refactor of parameter-validator.js

- lib/dialects/parserStore.js
> ES6 refactor of parserStore.js

- lib/sql-string.js
> ES6 refactor of sql-string.js

- test/integration/include/findAndCountAll.test.js
Closes #3253
Just proved that `sequelize.or` will work perfectly with `findAndCountAll`. If there was any bug in past, it has already been resolved.
cc @janmeier @mickhansen
> (test) findAndCountAll regression with sequelize.or

- lib/utils/validator-extras.js
See #6009 
One thing I would like to discuss is if we can somehow avoid patching the global validator.
> ES6 refactor of validator-extras.js

- test/integration/model/count.test.js
Closes #3019, Issue seems to be fixed already. Test case to prevent regression.
> Closes #3019, Model.count should not return NaN

- docs/docs/models-definition.md
The 'someUnique' code is duplicated, as the right block is after few lines.
> SomeUnique example duplicate removed

- docs/api/instance.md
- docs/api/model.md
- lib/model.js
- lib/sequelize.js
Add missing option description for returning and silent
> Add missing option description for returning and silent

- lib/associations/belongs-to.js
> Fixed typo.

- changelog.md
- docs/docs/associations.md
- docs/docs/models-definition.md
- docs/docs/usage.md
- lib/model.js
- lib/sequelize.js
- test/integration/associations/scope.test.js
- test/integration/model.test.js
- test/integration/sequelize.test.js
> (cleanup) removing classMethods / instanceMethods support

- test/integration/associations/belongs-to.test.js
This is a backport of a fix against a race condition.
> Fix intermittently failing test on MSSQL (#6090)

- changelog.md
- lib/model.js
- test/unit/model/upsert.test.js
> Fix upsert failing on not null checks

- changelog.md
- lib/model.js
- test/integration/include/findAndCountAll.test.js
- test/integration/model.test.js
- test/integration/model/count.test.js
- test/unit/model/count.test.js
See #6190 for more details (same fix applied against v.3)
> Fix includes being removed from count queries

- docs/docs/models-definition.md
fix typo in docs: change touple to tuple
> change touple to tuple

- lib/transaction.js
Returns a rejected promise on errors during inside of transaction commit & rollback.
Allows for more graceful catching of errors.
> return a rejected promise on commit or rollback errors

- lib/hooks.js
- lib/sequelize.js
> ES6 refactor of hooks.js

- test/integration/include/schema.test.js
This adds a failing test for the issue #6131 . The error reported is:
```
SequelizeDatabaseError: relation "account.Tasks" does not exist
```
I tried to copy the surrounding tests in their style & naming, but I'm not quite sure if I got it right. Happy to update the test with feedback.
> Add postgres failing test for postgres grouped limits with schemas

- lib/data-types.js
- lib/dialects/postgres/data-types.js
- test/integration/model/geometry.test.js
> MySQL case for GEOGRAPHY/GEOMETRY sql injection

- lib/model.js
Expose model for use in global hooks.
> feat(model): expose model to global hooks

- changelog.md
- lib/dialects/postgres/query-generator.js
- test/integration/dialects/postgres/dao.test.js
- test/integration/utils.test.js
add uppercase name JSON field test
> add uppercase name JSON field test

- lib/sequelize.js
- test/integration/sequelize.test.js
> [BACKPORT] Use typeof instead of _.isPlainObject

- changelog.md
- docs/api/model.md
- lib/dialects/postgres/query-generator.js
- lib/model.js
- test/unit/sql/delete.test.js
> [BACKPORT] Restart identity truncate

- changelog.md
- lib/dialects/postgres/query-generator.js
- test/unit/dialects/postgres/query-generator.test.js
This is a port of my fix for #6203 in PR #6204 to the v4 branch.
> Port #6204 to v4 (fix #6203)

- changelog.md
- lib/data-types.js
- test/unit/model/validation.test.js
> Fix type validations being to strict for dates

- docs/docs/models-usage.md
- lib/model.js
- test/unit/model/include.test.js
Expand string or `{association: <string>}` in `include` option into the association
(Closes #970)
> include: expand alias into association (update 2)

- lib/dialects/postgres/query-generator.js
- test/unit/sql/delete.test.js
> Fix RESTART IDENTITY CASCADE v3

- lib/dialects/postgres/query-generator.js
- test/unit/sql/delete.test.js
> Fix RESTART IDENTITY CASCADE

- test/integration/model/create.test.js
add test for "should return autoIncrement primary key"
> add test for "should return autoIncrement primary key"

- lib/dialects/mysql/query.js
- lib/dialects/sqlite/query.js
- lib/model.js
- test/integration/model.test.js
- test/integration/model/create.test.js
[mySQL]  fix issue for null id of AI index bulkCreate
> Fix issue for null id of AI index bulkCreate

- lib/associations/belongs-to-many.js
https://github.com/sequelize/sequelize/pull/6551 for master
> fix(btm): Expose belongs to many getter similar to other associations

- .travis.yml
- lib/dialects/abstract/query-generator.js
- test/integration/model/findAll/groupedLimit.test.js
- test/unit/sql/select.test.js
Direct backport, no changes needed, other than es5-ification
> Grouped limit include for v3

- appveyor.yml
https://nodejs.org/en/blog/release/v6.6.0/
> Remove Node 6.3 version pin for MSSQL

- lib/instance-validator.js
- test/integration/instance.test.js
- test/integration/instance.validations.test.js
- test/integration/model/create.test.js
`Validation len failed` --> `Validation len on name failed`
> Include field name for built-in validation error messages

- docs/api/sequelize.md
- docs/docs/getting-started.md
I thought a couple of sections' documentation on connection pooling was lacking so I improved it.
> Improved documentation on connection pools

- .gitignore
- lib/dialects/abstract/query-generator.js
This is already done for update queries but was missing for inserts.
> Mix in default options for insert queries.

- changelog.md
- lib/dialects/abstract/query.js
- test/integration/model/findAll.test.js
Fixes #6472, #6349, #6316. Turns out this had been fixed in v4, so I back-ported that fix and its tests (#6297).
> Check that parent exists before appending attributes.

- .travis.yml
- docker-compose.yml
Fixes the broken builds on CI. But I still haven't used Alpine images as I didn't find enough time for building new docker images.
Please merge this PR so CI works again. We can use Alpine Images later on.
Closes #6733
> Using Takis

- lib/model.js
> Add rejectOnEmpty param to API docs

- changelog.md
- lib/data-types.js
- lib/dialects/mssql/data-types.js
- lib/dialects/mysql/data-types.js
- lib/dialects/mysql/query.js
- lib/dialects/postgres/data-types.js
- lib/dialects/sqlite/data-types.js
- lib/dialects/sqlite/query.js
- lib/model.js
- test/integration/data-types.test.js
> (fix) DATEONLY parsed as Date

- docs/docs/associations.md
Please review the code samples to be sure I followed the conventional naming behavior correctly. Thanks!
> Document creating with deep nesting

- lib/model.js
- test/integration/model/paranoid.test.js
> Tests for paranoid with only deletedAt

- changelog.md
- lib/model.js
- test/integration/model/paranoid.test.js
> restore ignore field from deletedAt attribute

- docs/docs/models-definition.md
Not a valid built-in validator, throws an error when you try to use it
> Remove isArray from docs

- lib/model.js
- test/unit/instance/set.test.js
> fix instance.set '1970-01-01' to null field

- changelog.md
- lib/model.js
- test/integration/model/attributes/field.test.js
Fixes https://github.com/sequelize/sequelize/issues/6296
> #6296 increment/decrement don't map updatedAt field

- .gitignore
- changelog.md
- lib/dialects/mssql/index.js
- lib/dialects/mssql/query-generator.js
- lib/dialects/mssql/query.js
- lib/model.js
- test/config/config.js
- test/integration/model/upsert.test.js
> MSSQL upsert implementation - V3 backport

- lib/dialects/abstract/query-generator.js
- test/integration/include/findAll.test.js
Added Failing test case & patch for #6052
> Fix for generateThroughJoin

- changelog.md
- lib/dialects/postgres/index.js
- lib/utils.js
- test/integration/dialects/postgres/dao.test.js
- test/unit/sql/data-types.test.js
fixes #6752 
also fixes a small omission that prevented a few HSTORE tests from running.
> Hstore & JSON fixes

- lib/dialects/mysql/connection-manager.js
- test/integration/model/upsert.test.js
Fixed #6310 : added flags: '-FOUND_ROWS' at createConnection in mysql dialect.
This is the PR for v3 that I currently use.
Thanks
> Fix getting true when upsert a row to its current value with mysql for Sequelize v3

- lib/sequelize.js
- test/integration/sequelize.test.js
sequelize not rejects promise if 'formatNamedParameters' throws an error
> try catch block added for formatting parameters process

- changelog.md
- docs/docs/migrations.md
- lib/dialects/mssql/index.js
- test/unit/sql/index.test.js
> Filtered indexes for SQL Server

- changelog.md
- lib/dialects/mssql/query-generator.js
- lib/dialects/mssql/query-interface.js
- lib/dialects/mysql/query-interface.js
- test/integration/query-interface.test.js
- test/unit/dialects/mssql/query-generator.test.js
> V3 Port -  MSSQL removeColumn method fix for primaryKey column

- docs/docs/models-definition.md
> Missing comma

- changelog.md
- lib/dialects/abstract/connection-manager.js
- lib/dialects/mssql/connection-manager.js
- lib/dialects/mssql/index.js
- lib/dialects/mysql/index.js
- lib/dialects/postgres/connection-manager.js
- lib/dialects/postgres/index.js
- lib/sequelize.js
- package.json
- test/integration/associations/multiple-level-filters.test.js
- test/integration/dialects/abstract/connection-manager.test.js
- test/integration/dialects/mssql/connection-manager.test.js
- test/integration/dialects/mysql/connector-manager.test.js
- test/integration/pool.test.js
- test/integration/replication.test.js
- test/unit/transaction.test.js
- Bump to latest version of generic pool
- Fix issue where replication priorities were not used properly
Fix #7068, #4711
Close #5776
> Generic Pool Update

- changelog.md
- lib/dialects/mssql/connection-manager.js
> Tedious debug undefined dialectOptions regression fix

- changelog.md
- lib/model.js
- test/integration/instance.test.js
Closes: #6356
Backport: #7164 
Fix ER_EMPTY_QUERY reject on update only virtual fields and add test. For master branch
> Fix issues #6356 on master

- docs/docs/associations.md
I fixed a grammar error and two punctuation errors in the docs/docs/associations.md file.
> Punctuation and grammar correction in docs/docs/associations.md. 

- lib/associations/belongs-to-many.js
- test/integration/associations/belongs-to-many.test.js
fixing: https://github.com/sequelize/sequelize/issues/7153
> Fixes setAssociation with scope

- docs/docs/models-definition.md
> Update models-definition.md - Spelling correction

- changelog.md
- docs/api/sequelize.md
- lib/dialects/postgres/connection-manager.js
fix error when connect to Postgres 8.2.0
issue: #5254
> fix error when connect to Postgres 8.2.0(fix #5254)

- package.json
> chore(package): update mysql2 to version 1.2.0

- lib/instance.js
- test/unit/instance/previous.test.js
This is port of https://github.com/sequelize/sequelize/pull/7328
@sushantdhiman, here it is :)
> port of 791b4c04fd383bdf721e72f617f8d3270f3c789e

- changelog.md
- lib/transaction.js
- test/integration/replication.test.js
> read-only transactions for read replicas (v3)

- changelog.md
- lib/instance.js
- test/integration/instance/values.test.js
Backport of https://github.com/sequelize/sequelize/pull/7435 to v3
> V3 #7404 make it possible to pass parameters to getter functions (#7435)

- docs/models-definition.md
just a <small>small thing</small>
> fix typo in validations documentation

- docs/models-usage.md
Fixed type in generated code example.
> Fix typo in generated code in documentation

- CONTRIBUTING.md
Update OSX to macOS in `CONTRIBUTING.md` documentation.
This is a documentation-only change so not sure how to fill out the above checklist. Please let me know. 😁
> Update OSX to macOS in `CONTRIBUTING.md` documentation

- README.md
> Fixed the Getting Started link in README

- lib/sequelize.js
- test/integration/sequelize/log.test.js
> slice the options argument if the logging is set to console.log

- docs/models-usage.md
> Document $nested.column$ syntax

- lib/model.js
Better wording for [this](https://github.com/sequelize/sequelize/issues/7506) problem
> extend model options documentation for properties 'underscored' and 'underscoredAll'

- lib/instance.js
Small change in documentation as discussed on slack with @janmeier.
> Adding description of 'fields' option for 'validate'

- .editorconfig
- docs/associations.md
- docs/getting-started.md
- docs/hooks.md
- docs/index.md
- docs/instances.md
- docs/migrations.md
- docs/models-definition.md
- docs/models-usage.md
- docs/raw-queries.md
- docs/scopes.md
- docs/transactions.md
- docs/usage.md
- Use ES6 in docs, as supported by our minimal version (Node 4). That means arrow functions and `const`.
- Make model names PascalCase. Models are classes in v4 and the name becomes the class name, PascalCase is the convention for that.
- Make indentation consistently 2 spaces.
> Polish docs

- changelog.md
- lib/dialects/mssql/query.js
- lib/utils.js
- test/unit/dialects/mssql/query.js
- test/unit/utils.test.js
> [MSSQL] Format isolation level as tedious isolation level

- docs/getting-started.md
Hello everyone, I was reading through the getting started and found this small mistake.
I'll understand if you don't merge it
Thanks
> Remove unused `err` variable on getting started

- docs/models-definition.md
Signed-off-by: Martin H. Bramwell <martinhbramwell@gmail.com>
> Amplify docs for "import" instruction

- .esdoc.json
- docs/css/style.css
- docs/upgrade-to-v4.md
v3 to v4 migration guide along with newer features section.
> Docs: Added v3 to v4 migration guide

- docs/upgrade-to-v4.md
> Add note on Model.Instance and instance.Model to migration guide

- docs/models-usage.md
Small change in the docs in order to fix an incorrect ES6 arrow function.
> Minor fix to count docs

- lib/query-interface.js
> Orthographic fix in comments

- docs/associations.md
[Issue](https://github.com/sequelize/sequelize/issues/7849)
> fix link in Associations documentation

- lib/dialects/mssql/query-generator.js
- lib/dialects/mysql/query-generator.js
- lib/dialects/postgres/query-generator.js
- lib/dialects/sqlite/query-generator.js
- lib/model.js
- lib/query-interface.js
- test/integration/model/sync.test.js
- test/unit/model/indexes.test.js
Fixes regression introduced by #7196 as described in: #7771
I've also inverted the unit tests to make sure no one else breaks this by mistake.
Closes #7771
> fix(indexes): Fix composite index issue

- lib/query-interface.js
- test/integration/instance.test.js
Basically just follow what query interface `increment` does
Closes #7810
> fix(queryinterface): decrement regression

- docs/transactions.md
> Correct reference to isolation level default

- docs/migrations.md
I think adding a name to the constraint makes it easier to understand, since removing constraints requires the constraint name.
> Adding name to FK constraint

- lib/model.js
- test/integration/model/schema.test.js
Assign schema value to model to fix the following issues:
#7624 #7085 #6832 #6336 #5901 #5864 #5233
> Fix non public schema for PostgreSQL

- lib/dialects/mysql/connection-manager.js
fixing #8111 
cc @sushantdhiman
> fix(validate): Disallow using destroyed sockets

- docs/models-definition.md
Fix url related to configuration section in models-definitions.md returning a 404.
> docs(models-definitions): Fix wrong url for configuration section

- docs/hooks.md
- docs/upgrade-to-v4.md
> Update documentation for hooks

- docs/legacy.md
> docs(guide): Fixed case of object key.

- docs/hooks.md
https://github.com/sequelize/sequelize/issues/8215
> docs(hooks): fix controversial in method hooks (#8215)

- lib/model.js
> No necessary check because count is zero

- lib/associations/belongs-to-many.js
- test/integration/model/attributes/field.test.js
> fix(association): use `field` value in `count`

- lib/dialects/abstract/query-generator.js
- test/integration/instance.test.js
- test/unit/dialects/mssql/query-generator.test.js
- test/unit/dialects/mysql/query-generator.test.js
- test/unit/dialects/postgres/query-generator.test.js
- test/unit/dialects/sqlite/query-generator.test.js
> fix(decrement/negativeValue): Instance.decrement doesn't work with negative value (#8253)

- lib/model.js
- test/integration/associations/has-many.test.js
Check for sourceKey value first at save with nested assotiated model.
#8092
Closes #8092
> fix(model): Creating with associations and custom sourceKey (#8092)

- lib/model.js
Fix missing comma in the example in Model.js
> docs(Model): fix missing comma

- package.json
It shoud be fixed: https://github.com/coopernurse/node-pool/issues/174
Upgrade a deps
> chore(package): Upgrade generic-pool to version 3.1.8, fix connection bug

- package.json
> chore(package): update retry-as-promised to version 2.3.1

- lib/model.js
- test/integration/model.test.js
Fixes #8362
Use correct columns names in `Model.increment` for WHERE predicates.
> fix(model): use correct column names in `increment`

- test/integration/model/findAll.test.js
Added a test to prove that https://github.com/sequelize/sequelize/issues/8321 is a real problem. Not sure if this is the right spot to add a test like this, but this is more just for proof than anything else.
This test passes on sequelize v4.8.3 and fails on sequelize v4.8.4.
> test(integration/model/findAll): Add test for findAll with limit and mixed association results

- lib/associations/belongs-to-many.js
- lib/associations/helpers.js
- lib/dialects/abstract/query-generator.js
- lib/dialects/abstract/query.js
- lib/dialects/mssql/query-generator.js
- lib/dialects/mssql/query.js
- lib/dialects/mysql/connection-manager.js
- lib/dialects/mysql/query-generator.js
- lib/dialects/mysql/query.js
- lib/dialects/postgres/connection-manager.js
- lib/dialects/postgres/query-generator.js
- lib/dialects/postgres/query.js
- lib/dialects/sqlite/query-generator.js
- lib/dialects/sqlite/query-interface.js
- lib/hooks.js
- lib/instance-validator.js
- lib/model.js
- lib/query-interface.js
- lib/sequelize.js
- lib/transaction.js
- lib/utils.js
- test/support.js
- test/unit/associations/belongs-to-many.test.js
- test/unit/associations/belongs-to.test.js
- test/unit/associations/has-many.test.js
- test/unit/associations/has-one.test.js
- test/unit/sql/create-table.test.js
> 8365 refactor lodash

- CONTRIBUTING.md
Fixed name and reference of .eslintrc.json file in CONTRIBUTING.md file.
> docs(contributing): fixed name and reference to .eslintrc.json file

- docs/hooks.md
Fix typo in hooks bulk update example.
> docs(hooks): fix typo in bulk update example.

- lib/sql-string.js
- test/unit/dialects/abstract/query-generator.test.js
Closes https://github.com/sequelize/sequelize/pull/8425/
> fix: show inspected value for incorrect where query

- lib/model.js
- lib/utils.js
- test/integration/instance.test.js
- test/integration/instance/update.test.js
Fixes #8202
Fixes #8006
Closes #8204
Closes #7787
> fix(paranoid): use Utils.now to query for paranoid records

- lib/dialects/sqlite/index.js
- test/unit/sql/index.test.js
added support to create index where clause in sqlite
#8407
> fix(lib/dialects/sqlite/index.js): sqlite add index supporting where

- lib/data-types.js
- lib/dialects/mssql/data-types.js
- lib/dialects/mysql/data-types.js
- lib/dialects/postgres/data-types.js
- lib/dialects/sqlite/data-types.js
- test/unit/sql/data-types.test.js
only pass `npm run test-unit`
ref: #4412
> feat(lib/data-types.js): add TINYINT, SMALLINT, MEDIUMINT types.

- lib/dialects/abstract/connection-manager.js
> ensure to return connection info after destroy

- docs/upgrade-to-v4.md
~### Pull Request check-list~
~_Please make sure to review and check all of these items:_~
~- [ ] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?~
~- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?~
~- [ ] Have you added new tests to prevent regressions?~
~- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?~
~- [ ] Did you follow the commit message conventions explained in CONTRIBUTING.md?~
~### Description of change~
> Fix spelling

- docs/scopes.md
- lib/model.js
- test/integration/model.test.js
Closes #8539
Closes #8537 
Make `Model.increment` respect scopes.
> fix(increment): support scopes

- docs/querying.md
Change "your" to "you're" in querying.md, line 256
> docs: grammar fix

- docs/transactions.md
Fix example code in http://docs.sequelizejs.com/manual/tutorial/transactions.html#unmanaged-transaction-then-callback-
Homer and Lisa Simpson are not siblings.
> Update unmanaged transaction example

- lib/model.js
- test/integration/model/optimistic_locking.test.js
- [y] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [y] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [y] Have you added new tests to prevent regressions?
- [n] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [y] Did you follow the commit message conventions explained in CONTRIBUTING.md?
Using decrement on model should increment the version instead of decrementing it
**Note**: _Some unrelated tests were failing locally before the changes_
> fix(optimistic_locking): fix version update on model decrement

- docs/querying.md
Adding a few basic examples for the usage of Symbolic Operators, since they were not clear to me, and the examples under 'Combinations' were quite confusing.
[Issue link](https://github.com/sequelize/sequelize/issues/8417)
> docs(querying): Added examples for symbolic operator queries with [Op.or]

- package.json
> chore(package): update mysql2 to version 1.5.0

- lib/model.js
- test/unit/model/define.test.js
Closes: #8620
Explicitly passing a `null` or `undefined` `attributes.column.unique` value in `sequelize.define()` was causing an ambiguous error. Updated the code to ignore `null` or `underfined` `attributes.column.unique` values.
> ignore null or undefined attributes.column.unique

- LICENSE
update the deadline and format of LICENSE
> update license deadline and format

- lib/hooks.js
- lib/model.js
- lib/sequelize.js
- test/integration/hooks/hooks.test.js
- test/unit/hooks.test.js
Fix https://github.com/sequelize/sequelize/issues/8596
> fix: hook proxies are not added when defined with hooks options

- README.md
For more Chinese developer easy to learn sequelize.
> Add Chinese Doc v4 address

- lib/dialects/mysql/data-types.js
- package.json
- test/integration/data-types.test.js
https://github.com/sequelize/sequelize/pull/8661
> fix: breaking changes in mysql2, handle null buffer

- docs/migrations.md
> docs: update production example

- docs/models-usage.md
Add some clarification to docs.
> Clarify findAndCountAll filters

- docs/associations.md
- other commands (hasOne, belongs-to-many) are referenced in heading so hasMany should also be in heading.
- I think the model is singular, so trainer, ...or not?
> two 'improvements'

- .travis.yml
- CONTRIBUTING.md
- Dockerfile
- docker-compose.yml
- package.json
Just cleaning up testing and contribution setup and docs
> chores: contribution guidelines and local testing/sscce setup

- docs/associations.md
> Some corrections/ improvements.

- lib/dialects/sqlite/query.js
- lib/model.js
- test/integration/model/attributes.test.js
Closes https://github.com/sequelize/sequelize/issues/8719
> fix(model): attributetoString attribute testcase and fix (#8719)

- .github/ISSUE_TEMPLATE.md
If someone encounters an issue with Sequelize on an existing project, it’s convenient to quickly install Sequelize from GitHub (instead of npm) to test the issue with the master branch.
This PR modifies the issue template to include the command that does it.
> docs(github): Add a command to test with Sequelize’s master branch

- docs/models-definition.md
> removes confusing poem descriptor

- docs/models-usage.md
> docs(model-usage): Fix typo in order/group recap

- test/integration/model/findAll.test.js
> test: assert that where conditions are not ignored with empty include

- docs/migrations.md
Just fixing a few simple typos and cleaning up wording in a few places that I noticed while reading the docs. Thanks!
> docs(migrations): fix typos and clean up wording

- docs/upgrade-to-v4.md
Today I updated one project from 3.24.8 to 4.25.2 and noted that couple of major breaking changes are not in the migrating guide, they are
- `include` always an array
- `where` does not make `include` `required`
see changed files for verbose explanation.
fixes #8681
> Migration to v4 guide updated

- lib/model.js
- test/integration/model/scope.test.js
> fix: scope ignores symbol operators

- lib/model.js
- test/integration/model/scope/destroy.test.js
- test/integration/model/scope/update.test.js
> fix(scopes): scope is injected after checking for options.where

- lib/model.js
- test/unit/model/find-and-count-all.test.js
> fix(findAndCount): throws unhandled rejection from findAll

- package.json
> chore(package): update sinon to version 4.1.5

- docs/associations.md
Minor change to the 'Associating objects' section of the Associations docs. As it stands, the sample code generates a circular reference.
> docs(associations): Fix project / tasks example cardinality

- package.json
> chore(package): update uuid to version 3.2.1

- package.json
> chore(package): update semver to version 5.5.0

- test/integration/model/scope.test.js
Concerns from https://github.com/sequelize/sequelize/issues/8473
> test: scopes with operators work for findAll

- package.json
> chore(package): update sinon to version 4.2.0

- test/integration/model/scope.test.js
https://github.com/sequelize/sequelize/issues/8473#issuecomment-359260447
> test: scope with or operator

- package.json
> chore(package): update validator to version 9.4.0

- lib/model.js
- test/integration/model/findOrBuild.test.js
Bug Fix: Modified model.js for findOrBuild, so instance is built with values and options.
address #[8919]
> fix(<model>): fix findOrBuild bug

- docs/getting-started.md
> docs(Getting Started): Update npm install for latest pg

- lib/dialects/postgres/connection-manager.js
- test/integration/data-types.test.js
> fix(postgres/conectionmanager): Don't leak OIDs between instances

- lib/dialects/mssql/connection-manager.js
- test/unit/dialects/mssql/connection-manager.test.js
Fixes https://github.com/sequelize/sequelize/issues/8014
Fixes https://github.com/sequelize/sequelize/issues/8833
> fix(mssql/connection-manager): reconnect always timeouts

- docs/upgrade-to-v4.md
> docs(upgrade-v4): Fix instructions for include and required

- package.json
The current validator dependency has a security vulnerability: https://snyk.io/vuln/npm:validator:20180218
This is a simple PR to upgrade validator to 9.4.1
> chore: Upgrade validator to 9.4.1

- docs/instances.md
I just deleted a comma that is causing the sample code crash.
I just deleted a comma that is causing the 'several rows update' sample code crash.
> Comma (',') fix on 'several rows update' sample code

- docs/querying.md
2f7ac2d833b3e186fa4e708602ce7d416da84a8e changed the value in an example, which makes the comment outdated. This change updates the comment to reflect the example code.
> docs(querying): Update comment after example value was changed

- lib/dialects/abstract/query-generator.js
- lib/model.js
- lib/query-interface.js
- test/integration/model/bulk-create.test.js
- test/unit/sql/insert.test.js
> Fix field name mapping issue for bulk create queries with ON DUPLICATE UPDATE

- lib/dialects/abstract/query-generator.js
Fixed a typo in the error message.
> Fixed a typo

- lib/dialects/abstract/query-generator/helpers/quote.js
- test/unit/sql/select.test.js
Port https://github.com/sequelize/sequelize/pull/8935 to v5
> fix(postgres): reserved word

- lib/query-interface.js
I think there must be an example of using for each method...
small code example was added
> addColumn example code

- lib/dialects/mssql/query-generator.js
- lib/dialects/mysql/query-generator.js
- lib/dialects/postgres/query-generator.js
- lib/dialects/sqlite/query-generator.js
- lib/query-interface.js
- test/unit/sql/delete.test.js
Closes https://github.com/sequelize/sequelize/issues/8522
> fix(query-generator/deleteQuery): remove auto limit

- lib/model.js
Although the option restartIdentity is mentioned with destroy method, it is not mentioned with truncate, hence added in documentation.
> docs(model): postgres Model truncate method with restartIdentity option

- lib/associations/base.js
- lib/associations/belongs-to-many.js
- lib/associations/belongs-to.js
- lib/associations/has-many.js
- lib/associations/has-one.js
- lib/associations/mixin.js
- lib/deferrable.js
- lib/sequelize.js
- lib/utils.js
- test/integration/include/find.test.js
- test/integration/include/findAll.test.js
- test/integration/include/schema.test.js
- test/integration/utils.test.js
> refactor: remove old code, clean up

- lib/dialects/postgres/query-generator.js
- test/unit/dialects/postgres/query-generator.test.js
> fix(query-generator): syntax error in Postgres with SMALLINT and autoIncrement

- lib/dialects/mssql/query.js
- test/integration/error.test.js
> fix(mssql): inconsistent unique error handling

- docs/associations.md
I updated some documentation formatting and fixed some code examples.
> Update some documentation examples

- docs/models-usage.md
> Docs: Fix typo

- package.json
> chore(package): update cross-env to version 5.2.0

- lib/dialects/abstract/query.js
- lib/dialects/mssql/query.js
- lib/dialects/mysql/query-interface.js
- lib/dialects/postgres/query.js
- lib/dialects/sqlite/query-interface.js
- lib/errors/index.js
- test/integration/query-interface.test.js
- test/unit/errors.test.js
> fix(UnknownConstraintError): improper handling of error options

- docs/upgrade-to-v5.md
- lib/dialects/mssql/connection-manager.js
- lib/dialects/mysql/connection-manager.js
- lib/dialects/postgres/connection-manager.js
- lib/query-interface.js
- test/integration/instance/to-json.test.js
- test/unit/model/scope.test.js
Don't is the more commonly used spelling for English speakers.
Fix some typos.
> chore(grammar): dont -> don't

- lib/dialects/abstract/query.js
- lib/model.js
- lib/utils.js
- test/integration/model/attributes/types.test.js
> fix(model): ignore VIRTUAL/getters with attributes.exclude

- docs/models-definition.md
- lib/data-types.js
- lib/dialects/postgres/data-types.js
- package.json
- test/integration/data-types.test.js
> Backport Postgres network types to v4

- docs/hooks.md
Fix in the docs `updatesOnDuplicate`  to `updateOnDuplicate`
> docs(hooks): fix updatesOnDuplicate -> updateOnDuplicate

- lib/query-interface.js
Minor typo, should be a simple fix. I don't have the full test environment setup, but I think this fix is clear. I found it while reading the docs and thought I should help.
> docs(query-interface): fix typo in dropSchema doc

- lib/model.js
- test/integration/model/find.test.js
- test/integration/model/findAll.test.js
> fix(model): unable to override rejectOnEmpty

- lib/associations/has-many.js
- lib/associations/has-one.js
- package.json
- test/integration/associations/has-one.test.js
Fixes https://github.com/sequelize/sequelize/issues/9656
> fix(hasOne.sourceKey): setup sourceKeyAttribute for joins

- docs/usage.md
> docs(usage): fix typo in define doc

- package.json
> chore(package): update sqlite3 to version 4.0.2

- package.json
> chore(package): update semantic-release to version 15.8.0

- lib/transaction.js
- test/integration/dialects/postgres/error.test.js
> ci(postgres): remove extra beforeEach

- lib/dialects/mysql/query.js
> fix:improve robustness

- docs/usage.md
> Fix missing word in usage.md

- lib/dialects/sqlite/connection-manager.js
- test/integration/dialects/sqlite/connection-manager.test.js
> fix(sqlite): close connection properly and cleanup files

- lib/dialects/mssql/query.js
- test/integration/query-interface/describeTable.test.js
> feat(describeTable): support string length for mssql

- lib/query-interface.js
- test/integration/query-interface/changeColumn.test.js
> fix(changeColumn): normalize attribute

- lib/dialects/abstract/index.js
- lib/dialects/abstract/query-generator.js
- lib/dialects/postgres/index.js
- lib/model.js
- test/integration/model/bulk-create.test.js
- test/unit/dialects/postgres/query-generator.test.js
> feat: support ignoreDuplicates in Postgres >= 9.5

- .travis.yml
- docker-compose.yml
- test/config/.docker.env
- test/integration/model/findAll/group.test.js
Postgres 10 (Image from https://github.com/sushantdhiman/sequelize-postgres)
> chores: postgres-10

- .travis.yml
- codecov.yml
- package.json
> chores: use yarn in CI

- lib/model.js
- test/integration/model/scope/count.test.js
Porting scope fix for #9787 from `master` to `v4` branch.
> fix(scope): fix issue on count w/scope merging where and added a regression test

- package.json
> chore(package): update lodash to version 4.17.11

- .travis.yml
- package.json
> ci: install pg-native on demand

- lib/sequelize.js
- test/integration/sequelize.test.js
https://github.com/sequelize/sequelize/issues/9924
> feat(sequelize): add getDatabaseName method on sequelize instance

- lib/dialects/abstract/index.js
- lib/dialects/abstract/query-generator.js
- lib/dialects/postgres/index.js
- lib/model.js
- test/integration/model/bulk-create.test.js
- test/unit/dialects/postgres/query-generator.test.js
Backporting #9883 to v4. Cherry-picked 3a56cf74 with conflicts resolved.
> feat(postgres): Backport #9883 to v4

- package.json
> chore(package): update pg to version 7.5.0

- lib/dialects/abstract/query-generator.js
Closes: https://github.com/sequelize/sequelize/issues/10011
> docs(query-generator): remove doc about where raw query

- lib/data-types.js
- lib/dialects/mssql/data-types.js
- lib/dialects/postgres/data-types.js
- lib/dialects/sqlite/data-types.js
- test/unit/dialects/mysql/query.test.js
- test/unit/model/define.test.js
Follow up on https://github.com/sequelize/sequelize/pull/10001
>  refactor: cleanup integer option removal

- lib/instance-validator.js
- lib/utils/validator-extras.js
Issue: https://github.com/sequelize/sequelize/pull/9973
cherry-picked commit: https://github.com/sequelize/sequelize/commit/f7585ac08cf8a44a535ae3b9c42776f9fd4bc22e
> fix: cherry-pick memory leak perf commit (#9973)

- docs/associations.md
- lib/associations/belongs-to-many.js
- lib/model.js
- test/integration/associations/belongs-to-many.test.js
- test/integration/model/upsert.test.js
- test/unit/associations/belongs-to-many.test.js
Allow overwriting the unique key constraint for v4
> fix(associations): enable overwrite the name in unique constraint

- lib/associations/belongs-to.js
- lib/hooks.js
- lib/model.js
- lib/sequelize.js
Deprecation warning for public API removed in v5-beta https://github.com/sequelize/sequelize/pull/9933
> chore: deprecate public apis removed from v5.beta

- package.json
> chore(package): update retry-as-promised to version 3.1.0

- lib/dialects/abstract/query-generator.js
- test/integration/model/findAll/separate.test.js
- test/unit/sql/select.test.js
Hello!
This is a cherry-pick of https://github.com/sequelize/sequelize/commit/55e5734ecda7cb63e87480a09a350147353eea51 to the `v4` branch, as suggested by @sushantdhiman in https://github.com/sequelize/sequelize/pull/10003.
Thanks!
> fix(syntax): correct parentheses around union (#9813) (#10003)

- docs/plugins/esdoc-sequelize.js
- package.json
> docs: fix favicon

- package.json
> chore(package): update wkx to version 0.4.6

- docs/raw-queries.md
Cherry picking doc change from master into v4.
> docs(querying): model mapping for custom fields (#9688)

- docs/api/associations.md
- docs/api/datatypes.md
- docs/api/errors.md
- docs/api/hooks.md
- docs/api/instance.md
- docs/api/model.md
- docs/api/sequelize.md
- docs/api/transaction.md
The changed links did not resolve. Replaced **blog/716cb2d2aae3a4cd7fdaace13411cf4161e6deb6** with **tree/2.0**.
> Fixed some links in 2.0 docs

- package.json
> update mariadb dependency

- .eslintrc.json
- lib/data-types.js
- package.json
- test/integration/data-types.test.js
Backports #10492 to v4
Backports #10492 to v4
> Backport Number serialization to v4

- lib/model.js
- package.json
- test/unit/model/include.test.js
> fix(model): throw for invalid include type

- lib/query-interface.js
- test/integration/query-interface/describeTable.test.js
> fix(query-interface): reject with error for describeTable

- CONTRIBUTING.DOCS.md
- CONTRIBUTING.md
Some minor updates to the contributing guidelines (about docs) that I believe to be useful.
> docs: update contributing guidelines

- test/integration/dialects/abstract/connection-manager.test.js
- test/integration/dialects/postgres/range.test.js
- test/integration/sequelize.transaction.test.js
- test/support.js
- test/unit/associations/belongs-to-many.test.js
- test/unit/associations/has-many.test.js
- test/unit/connection-manager.test.js
- test/unit/dialects/mssql/query.test.js
- test/unit/hooks.test.js
- test/unit/instance-validator.test.js
- test/unit/instance/decrement.test.js
- test/unit/instance/destroy.test.js
- test/unit/instance/increment.test.js
- test/unit/instance/reload.test.js
- test/unit/instance/restore.test.js
- test/unit/instance/save.test.js
- test/unit/model/bulkcreate.test.js
- test/unit/model/count.test.js
- test/unit/model/destroy.test.js
- test/unit/model/find-and-count-all.test.js
- test/unit/model/find-create-find.test.js
- test/unit/model/find-or-create.test.js
- test/unit/model/findall.test.js
- test/unit/model/findone.test.js
- test/unit/model/update.test.js
- test/unit/model/upsert.test.js
- test/unit/model/validation.test.js
- test/unit/sql/change-column.test.js
- test/unit/transaction.test.js
Side product of some other changes, ensures we only use bluebird and reduces code a bit.
> chore(tests): use sinon resolves

- lib/data-types.js
- lib/transaction.js
- lib/utils/classToInvokable.js
> docs(data-types): fix param locations

- types/lib/transaction.d.ts
Fixes #10579
This really shouldn't impact performance at all.
> fix(typescript): do not use const enums

- lib/dialects/abstract/query-generator.js
- lib/model.js
- test/integration/model/scope/find.test.js
Fixes #10399
@u9r52sld please look at this too as your change caused this issue.
> fix(query-generator): correctly treat projection inversion in include default scope

- types/lib/data-types.d.ts
- types/test/data-types.ts
> fix(typescript): add missing data types

- lib/model.js
- test/integration/model/scope/associations.test.js
- test/unit/model/include.test.js
- test/unit/sql/generateJoin.test.js
fixing `_uniqIncludes` function with `include.association`.
See issue: #10123
> fix(uniq-includes-with-association): modify uniqIncludes

- lib/dialects/abstract/query-generator.js
- lib/dialects/mariadb/data-types.js
- lib/dialects/mysql/data-types.js
- test/integration/operators.test.js
Reverts sequelize/sequelize#10615
> Revert "fix(query-interface): incorrect regex escape with json querying"

- lib/dialects/postgres/query-generator.js
- test/unit/dialects/postgres/query-generator.test.js
> fix(postgres): quote trigger query identifiers

- types/lib/model.d.ts
Field `modelName` is missing in types.
> fix(typings): add modelName to InitOptions

- test/integration/model.test.js
Fix typos in model.test.js test names.
> chore(tests): typos in model test names

- lib/model.js
- test/integration/model.test.js
> fix(model): mapping fields twice on saving instance

- docs/upgrade-to-v5.md
- lib/dialects/mysql/connection-manager.js
- lib/model.js
- lib/query-interface.js
- lib/sequelize.js
- test/integration/associations/belongs-to-many.test.js
- test/integration/model/bulk-create.test.js
- test/integration/model/create.test.js
- test/integration/transaction.test.js
- types/lib/sequelize.d.ts
> docs: fixed many typos

- .github/PULL_REQUEST_TEMPLATE.md
This phrase is arguably racist and sexist.
> Remove ... "joke"? ... in pull request template

- types/lib/model.d.ts
- types/test/models/User.ts
> fix(types): add version property to init options

- lib/model.js
- test/integration/model/scope/merge.test.js
> fix(scope): conform includes correctly

- lib/data-types.js
- lib/dialects/abstract/connection-manager.js
- lib/dialects/abstract/query.js
- lib/dialects/mariadb/connection-manager.js
- lib/dialects/mariadb/query.js
- lib/dialects/mssql/connection-manager.js
- lib/dialects/mssql/query.js
- lib/dialects/mysql/connection-manager.js
- lib/dialects/mysql/query.js
- lib/dialects/postgres/connection-manager.js
- lib/dialects/postgres/query.js
- lib/dialects/sqlite/connection-manager.js
- lib/dialects/sqlite/query.js
- lib/hooks.js
- lib/model.js
- lib/sequelize.js
- lib/utils/logger.js
- package.json
- test/integration/sequelize.test.js
- test/integration/sequelize/log.test.js
- test/unit/dialects/abstract/query.test.js
- test/unit/model/findall.test.js
- test/unit/utils.test.js
- types/lib/utils/logger.d.ts
Replaces `debug` package with `debuglog` native and acts as a foundation for https://github.com/sequelize/sequelize/pull/10284#discussion_r269296280
cc @javiertury 
~~#Fixes 10661~~
> chore(logger): streamline logging

- types/lib/sequelize.d.ts
- types/test/sequelize.ts
> fix(types): add missing useCLS static

- .markdownlint.json
- .travis.yml
- docs/index.md
- docs/typescript.md
- package.json
Now we write manuals through markdown, which are irregular and make it difficult to read. So I suggest introduce [markdownlint](https://github.com/igorshubovych/markdownlint-cli) to rule out markdown style. And I try to pick loose rules.
If everybody has questions or opinions, please feel free to comment.
> Introduce markdownlint

- README.md
- package.json
> docs(typescript): improve typescript docs and add peer deps

- lib/query-interface.js
The method descriptions in the docstrings of QueryInterface were inconsistent in terms of verbal tense, usage of articles, punctuation, etc. This change harmonizes the method descriptions in that file, and also adds the missing description for `removeConstraint()`.
> docs: edit docstring descriptions for consistency

- types/lib/sequelize.d.ts
- types/lib/transaction.d.ts
- types/test/transaction.ts
- types/test/where.ts
> fix(types): add parent transaction and enhance `where` parameters

- types/lib/sequelize.d.ts
The nodes, as per the docs, need to be an array, and both write and read are mandatory if set
> fix(types): correct replicationOptions interface

- lib/dialects/postgres/query.js
Rename postgresql query debug namespace (mistake in #10630)
> fix(postgres): rename debug context

- docs/querying.md
- lib/dialects/abstract/query-generator.js
- test/unit/sql/where.test.js
> fix(querying): swap startWith and endsWith operators

- docs/migrations.md
Simple typos in docs for Migrations.
> fix typo in migrations docs

- lib/dialects/mssql/connection-manager.js
> fix(mssql): unexpected error event when connect fails, crashing node process

- types/lib/model.d.ts
- types/test/count.ts
Solves #10757 hopefully :)
I'm not well versed in typescript but if there are changes to make I'm up for it. As always if it's not useful please ignore.
> feat(typings): model.count with group by

- types/lib/errors.d.ts
- types/test/errors.ts
Solves #10775 
Adding type of OptimisticLockError and a test.
> feat(types): adding OptimisticLockError type

- types/lib/model.d.ts
- types/test/models/User.ts
When we use an array of string and methods
We can mix scope names and method objects in the scope function
> fix(types): fix scope typing

- types/lib/query-interface.d.ts
- types/test/query-interface.ts
So there's some undocumented breaking changes in https://github.com/sequelize/sequelize/commit/9b46f91301f40d7a973becb99d062da81e9f6164
this at least makes them visible.
> fix(typings): types for addIndex

- types/lib/model.d.ts
- types/lib/operators.d.ts
- types/test/where.ts
Fixes #10838
@sushantdhiman @eseliger we really need to beef up docs for operators, some are not documented all all...
> feat(typings): add some missing operators

- docs/associations.md
- docs/models-definition.md
- docs/typescript.md
- docs/upgrade-to-v5.md
- types/test/e2e/docs-example.ts
- types/test/model.ts
- types/test/models/User.ts
- types/test/models/UserGroup.ts
- types/test/tsconfig.json
- types/test/where.ts
Drop in the sea but it's something!
Fixes #10831
> docs(typescript): misc improvements for TS, best practises and changelog

- types/lib/model.d.ts
- types/test/models/User.ts
Adds the overloaded signature for `Model#addScope`, and some JSDocs for
the method
n/a
> fix(types): add Model#addScope overload

- lib/model.js
- test/integration/sequelize.test.js
> fix(sync): handle alter correctly with underscored/aliased columns

- types/lib/sequelize.d.ts
- types/test/sequelize.ts
> fix(types): add dialectModule types

- lib/model.js
- types/lib/model.d.ts
- types/test/include.ts
> fix(types): add duplicating option

- types/lib/sequelize.d.ts
- types/test/sequelize.ts
> fix(types): add random function to sequelize

- test/support.js
Is not in use anymore, removed it to cleanup code a bit.
> refactor: remove old unused callback parameter

- lib/dialects/abstract/connection-manager.js
- lib/dialects/postgres/connection-manager.js
- lib/sequelize.js
> Backport security patches

- lib/dialects/sqlite/connection-manager.js
> chore: modernize connections handling in sqlite

- docs/getting-started.md
The "Getting Started" tutorial contained (and still does contain) many grammatical errors, thus I've decided to improve the grammar in the documentation.
These are just a few of the changes I'm planning to make, I haven't even fully examined the docs yet, but making these small adjustments and documenting them in my commit messages involves much effort.
> Lingual improvements to "Getting Started"

- types/lib/model.d.ts
- types/lib/query-interface.d.ts
- types/test/count.ts
The `useMaster: false` option was missing for model.count
> fix(types): add poolable to count options

- docs/hooks.md
- lib/model.js
- types/lib/hooks.d.ts
- types/lib/model.d.ts
- types/lib/sequelize.d.ts
- types/test/hooks.ts
Added beforeSave and afterSave hooks typings.
Superceedes #10833
> fix(types): add beforeSave and afterSave typings

- lib/model.js
> fix grammar

- docs/raw-queries.md
> docs(raw-queries): fix broken link

- types/lib/model.d.ts
- types/test/index-hints.ts
Fix incorrect IndexHint.value typing name to IndexHint.values 
Closes #11008
> fix(types): update IndexHint.value to IndexHint.values (#11008)

- README.md
Update Chinese docs translations link to v5
> Update Chinese docs translations link to v5

- lib/dialects/abstract/connection-manager.js
- package.json
- test/integration/sequelize.test.js
Fixes #10902 
Updates pool library to fix a bug with double destroy https://github.com/sequelize/sequelize-pool/pull/6
> fix: update sequelize-pool

- lib/dialects/abstract/query-generator.js
Fixing unescaped json path key for v3
> fix(postgres): json path key quoting

- docs/migrations.md
Added docs for migrations with foreign key in another Schema
Issue #2701
> docs: update v5 docs (#2701)

- types/lib/model.d.ts
- types/test/usage.ts
> fix(types): Add missing silent option

- .gitignore
- lib/dialects/abstract/connection-manager.js
> fix(pool): Fixes pooling when replication is being utilized.

- test/unit/sql/create-table.test.js
These are now redundant after #11122
> test: remove redundant test

- lib/dialects/postgres/query-generator.js
- lib/query-interface.js
- test/integration/dialects/postgres/query-interface.test.js
- types/lib/query-interface.d.ts
This adds an option to enable function replacement as described in #11165.
> Add option for forcing function creation (fixes #11165)

- .github/PULL_REQUEST_TEMPLATE.md
Update PR template adding reminder for TS typings
> chore(github): update PR template

- docs/migrations.md
when using Date.now(), it throws type error : Incorrect datetime value: '156320710...'
> fix a seeder file example

- docs/migrations.md
add an explanation for editing `config/config.json`.
> add explanation of  'config/config.json'

- lib/dialects/sqlite/query-generator.js
- lib/dialects/sqlite/query-interface.js
- test/integration/query-interface.test.js
This PR just shows an error. I'm not sure how to solve it. It's related to #11066
> fix(sqlite): don't break when adding a 2nd constraint to a table

- docs/migrations.md
Only additions to the documentation.
> Adding async/await example to documentation

- lib/model.js
- test/integration/instance.test.js
- test/integration/instance/destroy.test.js
- test/unit/model/destroy.test.js
> fix(model): destroying paranoid models with custom deletedAt

- lib/sequelize.js
Documentation-only changes. Verified on sequelize@5.12.2.
Closes #10206.
> docs(sequelize): add select to typeValidation list

- .eslintrc.json
- lib/dialects/abstract/query-generator.js
- lib/dialects/mysql/query.js
- lib/dialects/postgres/query.js
- lib/dialects/sqlite/query.js
- lib/model.js
- lib/sequelize.js
- test/integration/instance/update.test.js
- test/integration/sequelize.test.js
- test/integration/utils.test.js
- test/unit/associations/belongs-to-many.test.js
- test/unit/associations/has-many.test.js
- test/unit/sql/select.test.js
- test/unit/sql/where.test.js
infix operators rules in eslint
**Good**
```js
const a = 1;
a + b
a ? b : c
var {a = 0} = bar;
function foo(a = 0) { }
```
**Bad**
```js
const a=1;
a +b
a?b:c
var {a=0}=bar;
function foo(a=0) { }
```
> style(spacing): add spacing around infix operators rules in eslint

- lib/data-types.js
> docs(data-types): fix typo

- lib/transaction.js
Logic appears in the if statement below.
> Remove duplicate code

- lib/query-interface.js
"Columns" was improperly pluralized.
> QueryInterface.removeColumn(): fix parameter desc

- types/lib/sequelize.d.ts
- types/test/sequelize.ts
Fixes https://github.com/sequelize/sequelize/issues/11356
> fix(types): change raw query return type to [unknown[],unknown]

- docs/instances.md
Correcting a code error that I spotted in the docs.
> docs: fixed undefined variable error in sample code

- types/lib/sequelize.d.ts
- types/test/sequelize.ts
- [] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
Add typings : PoolOption.evict
> fix(types): add PoolOptions.evict (#11378)

- lib/dialects/abstract/query-generator.js
- lib/dialects/postgres/query-generator.js
- test/integration/dialects/postgres/associations.test.js
- test/integration/model/schema.test.js
Fixes https://github.com/sequelize/sequelize/issues/11382
> fix(postgres): syncing indexes with schema

- lib/dialects/postgres/query-generator.js
- test/integration/dialects/postgres/dao.test.js
Enum doesn't escape values on "Create Table"
> fix(enum): escape values

- lib/dialects/abstract/query-generator.js
- test/integration/include/findAll.test.js
Continued from https://github.com/sequelize/sequelize/pull/11385
Fixes #9035
> fix: unknown column with subquery joins

- docs/data-types.md
Just typos, sorry for missing template
> Fixed typo in documentation

- docs/manual/migrations.md
Remove misleading usage of removeColumn, just wasted lot of time because I copied a version for that command that doesn't work
> docs: remove usage of removeColumn

- .travis.yml
- docker-compose.yml
- lib/dialects/mariadb/query-generator.js
- lib/dialects/mysql/query-generator.js
- lib/query-interface.js
- test/config/mysql/mysql.sql
- test/integration/query-interface.test.js
Fixes https://github.com/sequelize/sequelize/pull/11439#pullrequestreview-290558915
Fixes #10629
> Fix mysql showAllTables listing all tables for all databases

- docs/manual/querying.md
Op.and documentation improvement
Closes #11505
see #11506
> docs: clarifyied usage of Op.and

- docs/manual/migrations.md
Document that we can generate a skeleton migration from CLI.
> Document migration:generate

- lib/query-interface.js
Closes (#10625)
Set `type` on `options` in query-interface `bulkUpdate` method.
> fix(bulkupdate): pass correct type in options

- docs/manual/hooks.md
Closes #11126
add a note that states hooks don't work on instances explicitly.
> State hooks don't work on instances explicitly

- lib/model.js
removed an always true conditional and changed childOptions to const since its first attribution was inside of the removed conditional.
> fix(model): remove useless conditional

- docs/manual/migrations.md
The .sequelizerc has several configuration options which are defined and described in the source code (cli/src/core/yargs.js) but not included in the documentation.
> Document .sequelizerc configuration options

- lib/dialects/mariadb/index.js
- test/unit/dialects/mariadb/query-generator.test.js
Supports `indexHints` option on the `mariadb` dialect.
#11570
> feat(mariadb): support indexHints on mariadb dialect

- lib/associations/belongs-to-many.js
- test/integration/associations/belongs-to-many.test.js
PR for v5 branch with the same modification as #11578
> fix(associations): allow binary key for belongs-to-many

- lib/model.js
- test/integration/model/bulk-create.test.js
---
As per comments in https://github.com/sequelize/sequelize/pull/11666 ports the change to V5 branch so a patch can be released.
> fix(model): generate ON CONFLICT ... DO UPDATE correctly, v5 branch port

- test/integration/associations/belongs-to-many.test.js
- test/integration/associations/belongs-to.test.js
- test/integration/cls.test.js
- test/integration/model.test.js
See #11859
Since refactoring our code to use async/await is obviously a huge task, I think it should be separated over various PRs.
I plan on do a series of PRs for this, this PR being the first of the series.
> refactor(*): use async/await

- test/integration/query-interface.test.js
See #11859
This is my second PR on the series started at #11864
> refactor(tests): use async/await

- lib/model.js
- types/lib/model.d.ts
> docs(model): fix findOne docs

- types/lib/sequelize.d.ts
- types/test/sequelize.ts
Closes #11595
- https://github.com/sequelize/sequelize/pull/11596
> Support `{ plain: true }` in typescript typings for sequelize.query

- lib/dialects/abstract/connection-manager.js
Bundlers (like webpack) have a hard time to include libraries over variable names (as described [here](https://github.com/facebook/react-native/issues/6391#issuecomment-194568185)). This pull-request gives webpack a way to know which libraries are used by this library. This can potentially close #6907 and #7509.
> Fix requires for bundlers like webpack

- lib/dialects/abstract/connection-manager.js
> fix: eliminate usage of Promise.join

- lib/dialects/abstract/connection-manager.js
- lib/instance-validator.js
- lib/model.js
- lib/sequelize.js
- test/integration/dialects/postgres/query-interface.test.js
> refactor: remove bluebird Promise.try and Promise.prototype.reflect usage

- lib/dialects/abstract/connection-manager.js
- lib/dialects/mysql/connection-manager.js
- lib/dialects/postgres/connection-manager.js
- lib/dialects/postgres/query-interface.js
- lib/dialects/sqlite/connection-manager.js
- lib/model.js
- lib/sequelize.js
- lib/transaction.js
- test/integration/dialects/postgres/dao.test.js
- test/integration/include/findAndCountAll.test.js
- test/integration/instance/destroy.test.js
- test/integration/instance/reload.test.js
> refactor: replace bluebird .tap

- lib/dialects/sqlite/query-interface.js
- lib/hooks.js
- lib/model.js
- lib/query-interface.js
- lib/sequelize.js
- lib/transaction.js
- test/integration/associations/has-many.test.js
- test/integration/associations/scope.test.js
- test/integration/error.test.js
- test/integration/include/findAll.test.js
- test/integration/include/schema.test.js
- test/integration/model.test.js
- test/integration/model/create.test.js
- test/unit/model/find-or-create.test.js
#11859 
Many uses of .each were deep within nasty pyramids of doom, in those cases I went ahead and
modernized the entire function to async/await.
> refactor: replace bluebird .each

- lib/dialects/abstract/connection-manager.js
> fix: add missing [] to Promise.all calls

- README.md
> Improved readability 

- lib/model.js
- test/integration/instance.test.js
- test/integration/model.test.js
- test/unit/increment.test.js
- test/unit/instance/save.test.js
- test/unit/model/destroy.test.js
- test/unit/model/findall.test.js
- test/unit/model/update.test.js
> refactor(model): asyncify methods

- test/integration/dialects/sqlite/dao-factory.test.js
- test/integration/transaction.test.js
> test: replace bluebird .throw calls

- lib/associations/belongs-to-many.js
- lib/associations/belongs-to.js
- lib/associations/has-many.js
- lib/associations/has-one.js
- test/integration/associations/belongs-to.test.js
> refactor(associations): asyncify methods

- lib/query-interface.js
- test/integration/dialects/postgres/query-interface.test.js
- test/integration/query-interface.test.js
> refactor(query-interface): asyncify methods

- lib/sequelize.js
- test/integration/sequelize.test.js
> refactor(sequelize): asyncify methods

- lib/instance-validator.js
> refactor(instance-validator): asyncify methods

- lib/dialects/abstract/connection-manager.js
> refactor(dialects/abstract): asyncify methods

- lib/dialects/postgres/connection-manager.js
- lib/dialects/postgres/query-interface.js
- lib/dialects/postgres/query.js
> refactor(dialects/postgres): asyncify methods

- lib/dialects/mysql/connection-manager.js
- lib/dialects/mysql/query-interface.js
- lib/dialects/mysql/query.js
> refactor(dialects/mysql): asyncify methods

- lib/dialects/mariadb/connection-manager.js
- lib/dialects/mariadb/query.js
> refactor(dialects/mariadb): asyncify methods

- test/integration/associations/belongs-to-many.test.js
- test/integration/associations/belongs-to.test.js
- test/integration/associations/has-many.test.js
- test/integration/associations/has-one.test.js
- test/integration/associations/scope.test.js
- test/integration/dialects/sqlite/dao-factory.test.js
- test/integration/include.test.js
- test/integration/include/findAll.test.js
- test/integration/include/findAndCountAll.test.js
- test/integration/include/findOne.test.js
- test/integration/include/limit.test.js
- test/integration/include/schema.test.js
- test/integration/include/separate.test.js
- test/integration/model/attributes.test.js
- test/integration/model/attributes/field.test.js
- test/integration/model/create.test.js
- test/integration/model/findAll/groupedLimit.test.js
- test/integration/model/json.test.js
- test/integration/transaction.test.js
- test/unit/model/validation.test.js
> test: replace all Promise.join calls with Promise.all

- test/integration/support.js
This thing just keeps on giving, this should make these errors more useful at least :)
Should help with https://github.com/sequelize/sequelize/pull/12140
> test: show additional information for queries that did not complete

- lib/transaction.js
> refactor(transaction): asyncify methods

- lib/dialects/sqlite/query.js
> refactor(sqlite/query): simplify promise usage, for what it's worth in debugging these test failures

- lib/hooks.js
- lib/sequelize.js
- lib/transaction.js
- test/integration/support.js
- test/integration/transaction.test.js
Dummy PR to trigger CI, please ignore
> test: debug transaction leak

- lib/hooks.js
- lib/sequelize.js
- test/integration/cls.test.js
- test/integration/support.js
Fixes #7773
See failed build failure for trace https://travis-ci.org/github/sequelize/sequelize/jobs/678904686
> test(cls): fix flaky test and remove relevant tracing code

- docs/manual/core-concepts/assocs.md
- package.json
> docs(association): document uniqueKey

- ENGINE.md
Adding support information related to database versions as starter.
> docs: database version support info

- lib/associations/belongs-to-many.js
- lib/dialects/mssql/connection-manager.js
- lib/dialects/mssql/query-interface.js
- lib/dialects/sqlite/connection-manager.js
- lib/dialects/sqlite/query-interface.js
- lib/dialects/sqlite/query.js
> refactor(lib): asyncify remaining methods in lib

- lib/dialects/abstract/query-generator.js
- test/unit/sql/where.test.js
Fixes https://github.com/sequelize/sequelize/issues/12073
> Handle literal substring starts ends with

- test/support.js
- test/unit/associations/belongs-to-many.test.js
- test/unit/associations/has-many.test.js
- test/unit/connection-manager.test.js
- test/unit/dialects/mssql/connection-manager.test.js
- test/unit/dialects/mssql/query.test.js
- test/unit/dialects/mysql/query.test.js
- test/unit/hooks.test.js
- test/unit/instance-validator.test.js
- test/unit/instance/build.test.js
- test/unit/instance/set.test.js
- test/unit/model/bulkcreate.test.js
- test/unit/model/count.test.js
- test/unit/model/find-and-count-all.test.js
- test/unit/model/find-create-find.test.js
- test/unit/model/find-or-create.test.js
- test/unit/model/findall.test.js
- test/unit/model/findone.test.js
- test/unit/model/update.test.js
- test/unit/model/upsert.test.js
- test/unit/model/validation.test.js
- test/unit/transaction.test.js
> asyncify test/unit

- test/integration/associations/alias.test.js
- test/integration/associations/belongs-to-many.test.js
- test/integration/associations/belongs-to.test.js
- test/integration/associations/has-many.test.js
- test/integration/associations/has-one.test.js
- test/integration/associations/multiple-level-filters.test.js
- test/integration/associations/scope.test.js
- test/integration/associations/self.test.js
> test: asyncify integration/associations

- lib/dialects/sqlite/query-generator.js
- test/unit/dialects/sqlite/query-generator.test.js
Closes #12194
Same as https://github.com/sequelize/sequelize/pull/12237
> fix(sqlite): multiple primary keys results in syntax error

- test/integration/dialects/abstract/connection-manager.test.js
- test/integration/dialects/mariadb/associations.test.js
- test/integration/dialects/mariadb/connector-manager.test.js
- test/integration/dialects/mariadb/dao.test.js
- test/integration/dialects/mariadb/errors.test.js
- test/integration/dialects/mariadb/query-interface.test.js
- test/integration/dialects/mssql/connection-manager.test.js
- test/integration/dialects/mssql/query-queue.test.js
- test/integration/dialects/mssql/regressions.test.js
- test/integration/dialects/mysql/associations.test.js
- test/integration/dialects/mysql/connector-manager.test.js
- test/integration/dialects/mysql/errors.test.js
- test/integration/dialects/mysql/warning.test.js
- test/integration/dialects/postgres/associations.test.js
- test/integration/dialects/postgres/connection-manager.test.js
- test/integration/dialects/postgres/dao.test.js
- test/integration/dialects/postgres/data-types.test.js
- test/integration/dialects/postgres/error.test.js
- test/integration/dialects/postgres/query-interface.test.js
- test/integration/dialects/postgres/query.test.js
- test/integration/dialects/postgres/range.test.js
- test/integration/dialects/postgres/regressions.test.js
- test/integration/dialects/sqlite/connection-manager.test.js
- test/integration/dialects/sqlite/dao-factory.test.js
- test/integration/dialects/sqlite/dao.test.js
- test/integration/dialects/sqlite/sqlite-master.test.js
> test(integration/dialects): asyncify

- test/integration/hooks/associations.test.js
- test/integration/hooks/bulkOperation.test.js
- test/integration/hooks/count.test.js
- test/integration/hooks/create.test.js
- test/integration/hooks/destroy.test.js
- test/integration/hooks/find.test.js
- test/integration/hooks/hooks.test.js
- test/integration/hooks/restore.test.js
- test/integration/hooks/updateAttributes.test.js
- test/integration/hooks/upsert.test.js
- test/integration/hooks/validate.test.js
> fix(test/integration/hooks): asyncify

- lib/dialects/mssql/connection-manager.js
- test/unit/dialects/mssql/connection-manager.test.js
> Fix tedious connect deprecation v5

- test/integration/instance/decrement.test.js
- test/integration/instance/destroy.test.js
- test/integration/instance/increment.test.js
- test/integration/instance/reload.test.js
- test/integration/instance/save.test.js
- test/integration/instance/to-json.test.js
- test/integration/instance/update.test.js
- test/integration/instance/values.test.js
I need to fix a bug I found in asyncify before I can convert `test/integration/include`
> test(integration/instance): asyncify

- test/integration/cls.test.js
- test/integration/configuration.test.js
- test/integration/data-types.test.js
- test/integration/error.test.js
- test/integration/include.test.js
- test/integration/instance.test.js
- test/integration/instance.validations.test.js
- test/integration/json.test.js
- test/integration/model.test.js
- test/integration/replication.test.js
- test/integration/schema.test.js
- test/integration/sequelize.test.js
- test/integration/sequelize.transaction.test.js
- test/integration/support.js
- test/integration/timezone.test.js
- test/integration/transaction.test.js
- test/integration/trigger.test.js
- test/integration/utils.test.js
- test/integration/vectors.test.js
> test: asyncify integration/*.js

- test/integration/query-interface/changeColumn.test.js
- test/integration/query-interface/createTable.test.js
- test/integration/query-interface/describeTable.test.js
- test/integration/query-interface/dropEnum.test.js
- test/integration/query-interface/removeColumn.test.js
> test(integration/query-interface): asyncify

- test/integration/include/findAll.test.js
- test/integration/include/findAndCountAll.test.js
- test/integration/include/findOne.test.js
- test/integration/include/limit.test.js
- test/integration/include/paranoid.test.js
- test/integration/include/schema.test.js
- test/integration/include/separate.test.js
> test(integration/include): asyncify

- test/integration/sequelize/deferrable.test.js
I think after this we're done asyncifying everything! 🎉
> test(integration/sequelize): asyncify

- CONTACT.md
- package-lock.json
- package.json
> build: update dependencies

- lib/model.js
- test/integration/instance/reload.test.js
Fixes https://github.com/sequelize/sequelize/issues/12387
> fix(reload): include default scope

- .travis.yml
- CONTRIBUTING.DOCS.md
- CONTRIBUTING.md
- Dockerfile
- README.md
- SECURITY.md
- docs/manual/other-topics/upgrade-to-v6.md
- package.json
> docs: prepare for v6 release

- .travis.yml
- package.json
Semantic release & other changes for v6 release in v5 branch
> build: changes for v6 release

- test/unit/hooks.test.js
- test/unit/model/update.test.js
> fix(typings): update strings in tests

- docs/manual/core-concepts/assocs.md
Add on the doc unique: false to prevent unique key generation with
For close this issue #12327
> docs: add unique: false to belongs_to_many

- src/custom-types/toposort-class/index.d.ts
- tsconfig.json
As this dependency has no types included, I bundled them here, so we can use them when migrating to TS.
> feat(ts): add bundled types for toposort-class

- CONTACT.md
> docs: add myself to CONTACT.md

- src/sql-string.ts
- src/utils.js
- src/utils/logger.ts
Needed to make the logger a module as well, so I can import it.
> feat(ts): convert sql-string to ts

- CONTRIBUTING.md
> doc: Add install tsc on configuration

- docs/manual/advanced-association-concepts/advanced-many-to-many.md
Added missing 'await' keywords in documentation
> feat(docs): add 'await' keywords to documentation

- src/sequelize.js
fix(truncate): fix missing await in truncate all model with cascade (#12660 with fix only)
> fix(truncate): fix missing await in truncate all model with cascade

- lib/sequelize.js
fix(truncate): fix missing await in truncate all model with cascade (#12660 with fix only for v6)
> fix(truncate): fix missing await in truncate all model with cascade (v6)

- docs/manual/core-concepts/model-basics.md
Minor typo fix
acceps -> accepts
> Docs: Typo fix in model basics

- docs/manual/core-concepts/model-querying-basics.md
This change is really tiny.
I just added the forgotten comma at `docs/manual/core-concepts/model-querying-basics.md`
Closes #12748
> docs: add forgotten comma

- types/lib/hooks.d.ts
- types/lib/model.d.ts
- types/test/hooks.ts
- types/test/type-helpers/deep-writable.ts
> fix(types): allow changing values on before hooks

- lib/sequelize.js
- types/lib/sequelize.d.ts
Just a small fix for a spelling mistake :)
> fix: typo in sequelize.js and sequelize.d.ts

- types/lib/model.d.ts
- types/test/transaction.ts
This PR is a backport of #13093 into v5.
> fix(types): Allow transaction to be null in Transactionable interface (#13092).

- lib/dialects/abstract/query-generator.js
- lib/dialects/abstract/query-generator/transaction.js
- lib/dialects/abstract/query.js
- lib/utils.js
- package.json
Update uuid in sequelize v5 to prevent [deprecation error](https://github.com/uuidjs/uuid#deep-requires-no-longer-supported).
fixes #13123
> fix: update uuid

- types/lib/model.d.ts
Added type Col to type ProjectionAlias so that we can use method sequelize.col in attributes option.
Closes #13104
> fix(types): add type Col to type ProjectionAlias

- types/lib/model.d.ts
- N/A Have you added new tests to prevent regressions?
- N/A Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
Let's look at the following example code:
```js
// Instrument is a model
const instrument = Instrument.build({
orchestraId: 1,
purchaseDate: new Date(),
type: "violin",
});
instrument.set("orchestraId", 3);
instrument.previous("orchestraId"); // => 1
```
In JavaScript, this works just fine, in TypeScript however, we get the following error: `Argument of type '"orchestraId"' is not assignable to parameter of type 'keyof Model<InstrumentAttributes, InstrumentCreationAttributes>'`, since currently the used type `keyof this` refers to the functions and properties of the Model instance, not the creation attributes. This is fixed with …
> fix(types): Model.prototype.previous() parameters and return value now properly typed

- lib/errors/validation-error.js
- types/lib/errors.d.ts
Changed typescript interface of ValidationErrorItem
Closes #13107
> Fix missing property in ValidationErrorItem

- package.json
version 1.13.0 of that dependency introduced fixes for the plural form of a few words: 
https://github.com/dreamerslab/node.inflection/releases/tag/v1.13.0
Closes https://github.com/sequelize/sequelize/issues/7562
> bump inflection dependency

- docs/manual/other-topics/migrations.md
Corrected several grammatical issues in order to improve the section's clarity. These changes primarily consisted of few additional "the"s and tense corrections.
> Updated Grammar in migrations.md

- docs/manual/other-topics/read-replication.md
> fix(docs): fix read-replication.md,here miss ',' between 'port' and 'replication'

- package.json
The current validator dependency has 4 security vulnerabilities : 
- https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090599
- https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090600
- https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090601
- https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090602
> fix(dependency): upgrade validator

- CONTRIBUTING.md
- dev/mariadb/10.3/start.sh
Update of docker usage documentation
> Update collaboration related scripts + docs

- types/test/model.ts
Add test for the nested column in where clause.
Closes #13288
> feat(test): add test for nested column in where query

- lib/model.js
- types/lib/model.d.ts
- types/test/model.ts
add overload type for findAndCountAll:
- add overload type for findAndCountAll with the group.
- add test for checking return type of findAndCountAll with and without group
- update return type of findAndCountAll in model.js docs comment
Closes #13302
> Issue 13302

- lib/model.js
- test/integration/associations/has-many.test.js
- test/integration/model.test.js
> Add tests and fix for usage of count with grouping

- docs/manual/core-concepts/getting-started.md
> Fix typo on getting-started

- docs/manual/core-concepts/model-querying-basics.md
> added semicolons on docs

- docs/index.md
Add sponsoring options to the documentation
> Add note about sponsoring options.

- ENGINE.md
> feat(mysql): add support for MySQL v8

- CONTACT.md
since the departure of jan and papb for awhile
> docs(contact): update contributors emails

- docs/manual/other-topics/resources.md
Add sequelize-bcrypt plugin in docs
> Add sequelize-bcrypt plugin

- docs/manual/other-topics/resources.md
`sequelize-joi` ownership change
> sequelize-joi ownership change

- .github/workflows/stale.yml
Increase stale marking and closing to 14 days each to give people more time to react
> ci(stale): update stale timing to 14 days each

- types/lib/model.d.ts
> test(type): cover Op.match with test

- types/lib/operators.d.ts
#13481 provided a wrong documentation for `Op.ne`
> fix(types): ne op documentation

- .github/workflows/ci.yml
We are now on TS version 4.5! But our tests were only up to 4.1 😅 . This adds additional versions. My recommendation is to consider dropping version 3.9?
> ci: add other ts versions to ci

- types/lib/associations/belongs-to-many.d.ts
- types/lib/associations/has-many.d.ts
- types/test/typescriptDocs/ModelInit.ts
Fixes a typo from here: https://github.com/sequelize/sequelize/pull/13678
> fix: wrong interface used within mixin

- README.md
- docs/css/style.css
- docs/index.md
Add in `README.md` and fix logo in current manual `index.md`
> docs: add logo

- build.js
- lib/dialects/abstract/query-generator.js
- lib/dialects/mssql/query-generator.js
- lib/dialects/mssql/query.js
- lib/dialects/mysql/query-interface.js
- lib/dialects/postgres/query.js
- lib/model.js
- test/integration/model/upsert.test.js
Removes esbuild minification which was causing tests to fail and some changed behavior.
Reverts #13594 & disables minification from esbuild which was causing some tests to fail.
> test: fix failing tests 

- CONTRIBUTING.md
Fixes #13714
@soryy708 Would something like this be good?
> docs(contributing): add section on adding/updating deps

- lib/dialects/postgres/connection-manager.js
- test/integration/associations/scope.test.js
- test/integration/model/create.test.js
- test/integration/model/findAll/groupedLimit.test.js
- test/integration/pool.test.js
- Mark all flaky tests with `Flaky test` in comments.
- Refactor some flaky test assertions to print more clear details.
- Fix one flaky test.
> test(integration): mark and fix flaky test

- docs/index.md
- docs/manual/other-topics/dialect-specific-things.md
- package.json
Add documentation for snowflake
Link to https://github.com/sequelize/sequelize/issues/11979
> docs(snowflake): add snowflake description

- lib/utils/class-to-invokable.ts
refactor(class-to-invokable): make typing a little more accurate
Updates types for the util `classToInvokable` function to be a bit more accurate.   Also removes the `get` trap since the handler was redundant.
> refactor(class-to-invokable): make typing a little more accurate

- index.js
@module sequelize represent how we import the module, the description is what the module used for.
since we use `require('sequelize')`, the `@module Sequelize` should be in lowercase `@module sequelize`.
> docs(jsdoc): update entry point descriptions.

- package.json
- test/integration/sequelize.test.js
This PR is updating validator to the most recent version to cater for anyone who is still on v5 and who wants to get rid of [CVE-2021-3765](https://github.com/advisories/GHSA-qgmg-gppg-76g5).
> fix(dependencies): update validator dependency to latest version

- .github/workflows/ci.yml
Tweak of the CI script to post newly created release on Twitter. Looks like this:
> ci(twitter): automatically post releases on twitter

- lib/model.js
At that line variable "options" cannot be falsy.
> refactor(model): remove unnecessary option fallback

- README.md
- docs/manual-groups.json
- docs/manual/other-topics/upgrade-to-v7.md
First steps towards an upgrade guide from v6 to v7.
> docs(v7): add upgrade guide to v7

- package.json
> ci(semantic-release): disable fail on major bump rule

- package.json
- test/integration/model/scope/merge.test.js
- yarn.lock
Closes #13852 
We just used the dependency in one file so I just replaced the feature with the result array
> meta(deps): remove js-combinatorics

- docs/manual/moved/models-definition.md
> docs: document sequelize.import & esm

- docs/manual/other-topics/dialect-specific-things.md
Copy of #12597 
---
Possibility to continue the work of #12636 #12621
Lets see if we have dialectOptions which is still not exposed
cc active maintainers @jesse23 @sdepold @WikiRik @ephys
> docs(dialect-specific): add details about dialectOptions

- package.json
Try to release new versions as alpha
> ci: tag releases as alpha

- test/integration/associations/scope.test.js
The test itself is not a problem, but for some reason it just fails for MySQL 8. But it's not really reproducible so I think it's better to just disable it for now
> test(mysql8): disable flaky mysql8 test

- types/lib/sequelize.d.ts
- types/test/sequelize.ts
Add null to returned Promise when querying with {plain: true}
> fix: fix typings for queries with  {plain: true} option

- lib/dialects/abstract/query-generator.js
- lib/dialects/mariadb/query-generator.js
- lib/dialects/mysql/query-generator.js
- lib/dialects/postgres/query-generator.js
- lib/dialects/sqlite/query-generator.js
- test/integration/model/scope/merge.test.js
- test/unit/dialects/abstract/query-generator.test.js
- test/unit/dialects/db2/query-json-path-extraction.test.js
- test/unit/dialects/mariadb/query-json-path-extraction.test.js
- test/unit/dialects/mssql/query-json-path-extraction.test.js
- test/unit/dialects/mysql/query-json-path-extraction.test.js
- test/unit/dialects/postgres/query-json-path-extraction.test.js
- test/unit/dialects/snowflake/query-json-path-extraction.test.js
- test/unit/dialects/sqlite/query-json-path-extraction.test.js
Refactor `jsonPathExtractionQuery` to decouple with dialect.
Extract from https://github.com/sequelize/sequelize/pull/13798
- sequelize.random needs more refactor
- data-types needs to be refactored to decouple from its own arch, into sequelize.js
> refactor(dialect): clean up jsonPathExtractionQuery

- test/integration/associations/scope.test.js
So the `current.options.databaseVersion` is not filled until the beforeEach so can only be found inside a test. So this would be a proper fix to #13870
> test(mysql8): actually disable flaky mysql8 test

- types/lib/data-types.d.ts
Replacement PR for https://github.com/sequelize/sequelize/pull/13444
Closes https://github.com/sequelize/sequelize/pull/13444
Closes https://github.com/sequelize/sequelize/issues/13316
Only adds the missing typings for TSVECTOR, as everything else was already there
> feat(types): add typings for DataTypes.TSVECTOR

- README.md
Introduce new version of Sequelize README.
> docs: introduce new version of sequelize README

- docs/manual/other-topics/dialect-specific-things.md
- docs/manual/other-topics/upgrade-to-v7.md
- lib/dialects/mssql/index.js
> docs(mssql): clarify in comments and docs supports MS SQL versions

- lib/model.js
Fixes #14025
Thanks to @bartdorsey for the suggested solution
> docs(model): improve findByPk return type

- docs/ROUTER.txt
- docs/css/style.css
- docs/esdoc-config.js
- docs/manual/core-concepts/assocs.md
- docs/manual/core-concepts/getting-started.md
- docs/manual/core-concepts/model-basics.md
- docs/manual/core-concepts/model-instances.md
- docs/manual/core-concepts/model-querying-basics.md
- docs/manual/core-concepts/raw-queries.md
- docs/manual/other-topics/aws-lambda.md
- docs/manual/other-topics/connection-pool.md
- docs/manual/other-topics/hooks.md
- docs/manual/other-topics/indexes.md
- docs/manual/other-topics/query-interface.md
- docs/manual/other-topics/scopes.md
- docs/transforms/group-data-types.js
Fixes https://github.com/sequelize/sequelize/issues/14083
> build: generate jsdoc from src instead of lib

- test/unit/utils.test.js
- test/unit/utils/check.test.ts
Adding some more tests for the utils' check file. Inspired by #13992 .
> test: cover utils/check with tests

- src/sequelize.d.ts
Missing snowflake and db2 dialects types, causing casting with any
> fix(types): missing snowflake and db2 dialects

- .github/ISSUE_TEMPLATE/bug_report.md
The inline comment () does not like it when there are two dashes which caused the comment to be rendered as normal text. This fixes that but unfortunately does space out the three points as separate paragraphs. So it's the lesser of two evils in my view
> meta: update comment in bug report template

- CONTRIBUTING.md
Closes #14204
Changed link to point from eslintrc.json ( doesn't exist anymore ) to eslintrc.js in section coding guidelines.
> docs(contributing.md): changed link from .eslintrc.json to .js

- src/dialects/abstract/query-interface.d.ts
- test/types/query-interface.ts
> fix(types): remove non-exist types in query interface

- test/integration/transaction.test.js
See https://github.com/sequelize/sequelize/issues/14174
> test: disable deadlock test for mariadb 10.5.15 (v6)

- src/model.d.ts
- src/operators.ts
Fixes the other examples that were not tackled in https://github.com/sequelize/sequelize/pull/14123 (or https://github.com/sequelize/website/pull/66 )
See those PRs for more information
> docs(op): fix queries example for [Op.any]

- dev/update-authors.js
> ci(update-authors): exclude sequelize email

- src/sequelize.d.ts
Related to https://github.com/sequelize/sequelize/issues/14193
> fix(types): accept `ibmi` as dialect name

- package.json
- yarn.lock
[sqlite3](https://github.com/TryGhost/node-sqlite3) has been transferred to another organization and has a new released version. This means we do not need to use the fork anymore.
> build(sqlite): use regular package instead of vscode fork

- package.json
- yarn.lock
> build(deps): remove acorn

- CONTACT.md
Move my email to Gmail for security reports and accept specific mail only.
> docs: update CONTACT.md email

- src/model.js
This is the documentation changes
> docs: added nest option inside findAll query

- README.md
See https://github.com/sequelize/sequelize/pull/14744
> meta: fix alignment logo (v6)

- src/model.js
> meta: update updated_at on upsert

- test/integration/model.test.js
- test/integration/model/findAll.test.js
- test/integration/pool.test.ts
I noticed that some tests were logging without needing them. So I removed them.
> meta: remove unneeded logging in tests

- package.json
> meta: update types property package.json (v6)

- package.json
This should fix #14897 in main
cc @alecrobertson1 @xadamxk
People can test this by using the following in their package.json
`"sequelize": "sequelize/sequelize#83ac809",`
> meta: update types property package.json

- src/utils/index.ts
Targetting the v7 alpha release, for the #14963 unit testing.
> fix: expose url utility in utils

- src/model.d.ts
- test/types/model.ts
Close https://github.com/sequelize/sequelize/issues/14957
> fix(types): backport #14704 for v6

- .github/PULL_REQUEST_TEMPLATE.md
Parts of our PR template are outdated. This is a small update to align it to our latest conventions
> meta: update PR template again

- renovate.json
It would be great if Renovate would just check this before merging. Closes #15025
> meta: fix typo ignorePaths renovate

- .github/workflows/pr-title.yml
Adds the Oracle scope to the possible options since support for it has landed in v6.
> meta(oracle): add oracle PR scope

- src/dialects/db2/query-generator.d.ts
- src/dialects/db2/query-interface.d.ts
- src/dialects/db2/query.d.ts
- src/dialects/ibmi/query-generator.d.ts
- src/dialects/ibmi/query-interface.d.ts
- src/dialects/ibmi/query.d.ts
- src/dialects/mariadb/query-generator.d.ts
- src/dialects/mariadb/query.d.ts
- src/dialects/mssql/query-generator.d.ts
- src/dialects/mssql/query-interface.d.ts
- src/dialects/mssql/query.d.ts
- src/dialects/mysql/query-generator.d.ts
- src/dialects/mysql/query-interface.d.ts
- src/dialects/mysql/query.d.ts
- src/dialects/postgres/query-generator.d.ts
- src/dialects/postgres/query-interface.d.ts
- src/dialects/postgres/query.d.ts
- src/dialects/snowflake/query-generator.d.ts
- src/dialects/snowflake/query-interface.d.ts
- src/dialects/snowflake/query.d.ts
- src/dialects/sqlite/query-generator.d.ts
- src/dialects/sqlite/query-interface.d.ts
- src/dialects/sqlite/query.d.ts
Part of the PRs split from #14505
> meta(types): add dialect typing stubs

- src/dialects/abstract/index.ts
- src/dialects/mariadb/index.js
- src/dialects/mssql/index.js
- src/dialects/mysql/index.js
- src/dialects/postgres/index.js
- src/dialects/sqlite/index.js
- test/integration/model/json.test.js
- test/integration/model/paranoid.test.js
- test/unit/sql/json.test.js
- test/unit/sql/where.test.ts
> meta: add jsonOperations to DialectSupports

- renovate.json
Allows renovate to auto-merge the lockfile maintenance PR (as is done on our website repo)
> meta: auto-merge lock file maintenance PR

- src/model.d.ts
same as this PR but on v6
https://github.com/sequelize/sequelize/pull/15208
> fix(types): add instance.dataValues property to model.d.ts

- package.json
- src/sequelize.d.ts
- src/sequelize.js
- yarn.lock
> feat(types): backport retry-as-promised types to v6

- lerna.json
- package.json
- packages/core/package.json
- packages/validator-js/package.json
- yarn.lock
This PR replaces our semantic-release setup with lerna in `--conventional-commits` mode
> meta: use lerna for monorepo releases

- test/unit/sql/get-where-conditions.test.js
> meta: fix null test getWhereConditions

- .github/workflows/ci.yml
- package.json
This PR imports the publish script changes made while testing the release on the v7 branch into main
> meta: update publish script

- src/utils/sql.ts
- test/unit/utils/sql.test.js
Backports https://github.com/sequelize/sequelize/pull/15758 to v6
Closes #15301
> fix: fix unnamed dollar string detection (v6)

- packages/core/src/dialects/mssql/async-queue.ts
Unblocks #15771 and is auto fixed by eslint
> fix(mssql): make inner enqueue function async

- CONTRIBUTING.md
- README.md
> fix: update Slack invitation link

- src/dialects/abstract/connection-manager.js
- src/hooks.d.ts
- src/hooks.js
- src/sequelize.d.ts
- test/integration/hooks/hooks.test.js
- test/types/hooks.ts
- test/unit/esm-named-exports.test.js
Link to issue: https://github.com/sequelize/sequelize/issues/15724
> feat: add beforePoolAcquire and afterPoolAcquire hooks

- .github/workflows/ci.yml
> meta: use Node 18 in CI

- packages/core/package.json
- packages/core/src/dialects/postgres/connection-manager.ts
- yarn.lock
This PR is a replacement for https://github.com/sequelize/sequelize/pull/16048
> meta: update dependency @types/pg to v8.10.2

- .github/workflows/ci.yml
- .prettierrc.json
- package.json
- src/transaction.d.ts
- yarn.lock
Introduce fixes for typescript 5.2 compatibility in v6. Fixes #16414
> feat(types): add TypeScript 5.2 support

- dev/mssql/latest/docker-compose.yml
- dev/mssql/oldest/docker-compose.yml
Updated the docker envs for mssql as per [Microsoft docs](https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-configure-environment-variables?view=sql-server-ver16)
> meta: update mssql docker envs

- .github/workflows/ci.yml
Adds node-gyp globally so it can be executed on Node 18 by ibm_db
> meta: add node-gyp globally

- package.json
- packages/core/src/decorators/shared/model.ts
- packages/core/src/model-definition.ts
- yarn.lock
> feat(types): support TypeScript 5.3.3

- packages/core/test/integration/support.ts
This PR fixes potential deadlocks when drop test databases for db2.
> fix: use loop to drop db2 test databases to prevent deadlocks

- src/dialects/postgres/connection-manager.js
Backport https://github.com/sequelize/sequelize/pull/16056
Backports https://github.com/sequelize/sequelize/pull/16056 to v6
Linked issue: https://github.com/sequelize/sequelize/issues/16870
> feat(postgres): backport stream dialectOption to v6

- packages/core/test/integration/query-interface.test.js
- packages/core/test/support.ts
- packages/core/test/unit/sql/select.test.js
> meta: remove unused test support functions

- nx.json
As per PR #17181 the `lib` and `types` folders have been merged. 
This PR removes the `types` folder from the nx config.
> meta: update build outputs in nx config

- packages/core/package.json
- packages/db2/package.json
- packages/ibmi/package.json
- packages/mariadb/package.json
- packages/mssql/package.json
- packages/mysql/package.json
- packages/postgres/package.json
- packages/snowflake/package.json
- packages/sqlite/package.json
- packages/utils/package.json
- packages/validator-js/package.json
This PR updates the files and export for each of the packages to only include the code from the `lib` directory.
> meta: update `package.json` files and exports

- AUTHORS
- dev/update-authors.js
Adding a few additional email addresses of bots to the list of emails to exclude from the AUTHORS file.
> meta: add additional ignored AUTHORS

- packages/mysql/package.json
- packages/mysql/src/_internal/connection-options.ts
- yarn.lock
Update mysql2 to ^3.11.2 and add jsonStrings to connection-options.ts
> fix(mysql): update mysql2 to ^3.11.2

- package.json
- packages/core/src/transaction.ts
- packages/sqlite3/src/query-interface.ts
- yarn.lock
- Update `prettier` to v3.3.3
- Format files with new prettier version
- Fixes failing tests in #17267
> fix: update prettier to v3.3.3

- packages/cli/package.json
- packages/cli/src/_internal/sequelize-command.ts
- yarn.lock
Updates `@sequelize/cli` to use the new [`inquirer`](https://github.com/SBoudrias/Inquirer.js) packages.
Closes #17539
> fix: update inquirer

- packages/core/src/abstract-dialect/query-generator.js
- packages/core/test/unit/sql/select.test.js
https://github.com/sequelize/sequelize/issues/17344
N/A
> feat: replace correlated subquery with EXISTS

- README.md
> fix: add call for new maintainers to README
